//! Discovers the per-module oracle files in `src/oracles/` and generates the module list and the
//! registration function, so that adding a module never touches a shared Rust file.

use std::{env, fs, path::Path};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let dir = Path::new(&manifest_dir).join("src").join("oracles");
    println!("cargo:rerun-if-changed=src/oracles");
    println!("cargo:rerun-if-changed=build.rs");

    let mut modules: Vec<String> = fs::read_dir(&dir)
        .expect("src/oracles must exist")
        .filter_map(|entry| {
            let path = entry.expect("readable dir entry").path();
            let is_rs = path.extension().is_some_and(|e| e == "rs");
            let stem = path.file_stem()?.to_str()?.to_owned();
            (is_rs && stem != "mod").then_some(stem)
        })
        .collect();
    modules.sort();

    let mut out = String::from("// Generated by build.rs - one entry per file of src/oracles/.\n");
    for m in &modules {
        let path = dir.join(format!("{m}.rs"));
        out.push_str(&format!(
            "#[path = {:?}]\npub mod {m};\n",
            path.to_str().expect("utf-8 path")
        ));
    }
    out.push_str("\npub fn register_all(registries: &mut crate::registry::Registries) {\n");
    for m in &modules {
        out.push_str(&format!("    registries.module({m:?}, {m}::register);\n"));
    }
    out.push_str("}\n");

    let dest = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("oracles_gen.rs");
    fs::write(dest, out).expect("write oracles_gen.rs");
}
