// GENERATED by tools/codegen/intvec.py - do not edit by hand.
//! Port of glam-rs `i32/ivec4.rs` @ 0.33.8: a 4-dimensional `i32` vector.
//!
//! The six integer vector modules are generated from one template (`tools/codegen/intvec.py`),
//! as in glam-rs. Every formulation is the cheapest of the candidates measured in
//! `gas/ivec4.snap`; the losing candidates live in `benches::alt::ivec4`.
//!
//! Overflow: the operators and the plain methods panic (corelib messages, or `'IVec4: overflow'`
//! for the fused kernels); the `checked_*` / `wrapping_*` / `saturating_*` families never do. They
//! exist for their semantics: they are slower than the panicking operators.

use core::integer::i32_diff;
use core::num::traits::{
    CheckedAdd, CheckedSub, SaturatingAdd, SaturatingSub, WideMul, WrappingAdd, WrappingSub,
};
use core::ops::index::IndexView;
use core::ops::{AddAssign, DivAssign, MulAssign, RemAssign, SubAssign};
use core::traits::{BitAnd, BitNot, BitOr, BitXor, DivRem};
use crate::bvec4::{BVec4, BVec4Trait};
use crate::ivec2::IVec2;
use crate::ivec3::IVec3;
use crate::uvec4::UVec4;

/// A 4-dimensional `i32` vector.
///
/// Mirrors `glam::IVec4`.
/// #### Deviations
/// * `Debug` is the derived Cairo formatting; `Display` is not implemented.
/// * Not ported: `map` (a closure parameter cannot be force-inlined, E2143), `from_slice` /
///   `write_to_slice` (no `Span` in fixed-size math), `Sum` / `Product`, `IndexMut`, the
///   by-reference operator overloads, the scalar-on-the-left operators (`2 * v`), the scalar
///   bit operators (use `v & IVec4Trait::splat(s)`), shifts by a vector or by another integer
///   width, and the casts to types that do not exist in glam.cairo (`as_i64vec4`, ...).
/// * `as_vec4` (and `as_dvec4`) will land with the `Vec4` port.
#[derive(Copy, Drop, Serde, PartialEq, Debug, Default, Hash)]
pub struct IVec4 {
    pub x: i32,
    pub y: i32,
    pub z: i32,
    pub w: i32,
}

/// Creates a 4-dimensional `i32` vector.
///
/// Mirrors `glam::ivec4`.
/// #### Panics
/// * Never.
/// #### Deviations
/// * None.
#[inline(always)]
pub fn ivec4(x: i32, y: i32, z: i32, w: i32) -> IVec4 {
    IVec4 { x, y, z, w }
}

pub trait IVec4Trait {
    /// All zeroes.
    ///
    /// Mirrors `glam::IVec4::ZERO`.
    const ZERO: IVec4;
    /// All ones.
    ///
    /// Mirrors `glam::IVec4::ONE`.
    const ONE: IVec4;
    /// All negative ones.
    ///
    /// Mirrors `glam::IVec4::NEG_ONE`.
    const NEG_ONE: IVec4;
    /// All `i32::MIN`.
    ///
    /// Mirrors `glam::IVec4::MIN`.
    const MIN: IVec4;
    /// All `i32::MAX`.
    ///
    /// Mirrors `glam::IVec4::MAX`.
    const MAX: IVec4;
    /// A unit vector pointing along the positive X axis.
    ///
    /// Mirrors `glam::IVec4::X`.
    const X: IVec4;
    /// A unit vector pointing along the positive Y axis.
    ///
    /// Mirrors `glam::IVec4::Y`.
    const Y: IVec4;
    /// A unit vector pointing along the positive Z axis.
    ///
    /// Mirrors `glam::IVec4::Z`.
    const Z: IVec4;
    /// A unit vector pointing along the positive W axis.
    ///
    /// Mirrors `glam::IVec4::W`.
    const W: IVec4;
    /// A unit vector pointing along the negative X axis.
    ///
    /// Mirrors `glam::IVec4::NEG_X`.
    const NEG_X: IVec4;
    /// A unit vector pointing along the negative Y axis.
    ///
    /// Mirrors `glam::IVec4::NEG_Y`.
    const NEG_Y: IVec4;
    /// A unit vector pointing along the negative Z axis.
    ///
    /// Mirrors `glam::IVec4::NEG_Z`.
    const NEG_Z: IVec4;
    /// A unit vector pointing along the negative W axis.
    ///
    /// Mirrors `glam::IVec4::NEG_W`.
    const NEG_W: IVec4;
    /// The unit axes.
    ///
    /// Mirrors `glam::IVec4::AXES`.
    const AXES: [IVec4; 4];
    /// Creates a new vector.
    ///
    /// Mirrors `glam::IVec4::new`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn new(x: i32, y: i32, z: i32, w: i32) -> IVec4;
    /// Creates a vector with all elements set to `v`.
    ///
    /// Mirrors `glam::IVec4::splat`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn splat(v: i32) -> IVec4;
    /// Creates a vector from the elements in `if_true` and `if_false`, selecting which to
    /// use for each element of `self`.
    ///
    /// A true element in the mask uses the corresponding element from `if_true`, and false
    /// uses the element from `if_false`.
    ///
    /// Mirrors `glam::IVec4::select`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn select(mask: BVec4, if_true: IVec4, if_false: IVec4) -> IVec4;
    /// Creates a new vector from an array.
    ///
    /// Mirrors `glam::IVec4::from_array`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn from_array(a: [i32; 4]) -> IVec4;
    /// Converts `self` to `[x, y, z, w]`.
    ///
    /// Mirrors `glam::IVec4::to_array`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn to_array(self: IVec4) -> [i32; 4];
    /// Creates a 3D vector from the `x`, `y`, `z` elements of `self`, discarding `w`.
    ///
    /// Mirrors `glam::IVec4::truncate`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn truncate(self: IVec4) -> IVec3;
    /// Creates a 4D vector from `self` with the given value of `x`.
    ///
    /// Mirrors `glam::IVec4::with_x`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn with_x(self: IVec4, x: i32) -> IVec4;
    /// Creates a 4D vector from `self` with the given value of `y`.
    ///
    /// Mirrors `glam::IVec4::with_y`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn with_y(self: IVec4, y: i32) -> IVec4;
    /// Creates a 4D vector from `self` with the given value of `z`.
    ///
    /// Mirrors `glam::IVec4::with_z`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn with_z(self: IVec4, z: i32) -> IVec4;
    /// Creates a 4D vector from `self` with the given value of `w`.
    ///
    /// Mirrors `glam::IVec4::with_w`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn with_w(self: IVec4, w: i32) -> IVec4;
    /// Computes the dot product of `self` and `rhs`.
    ///
    /// Mirrors `glam::IVec4::dot`.
    /// #### Panics
    /// * `'IVec4: overflow'` if the result does not fit `i32`.
    /// #### Deviations
    /// * Only the final result is range-checked: an intermediate product or sum that
    ///   leaves the `i32` range does not panic when the result fits (glam-rs panics in
    ///   debug builds and wraps in release builds).
    fn dot(self: IVec4, rhs: IVec4) -> i32;
    /// Returns a vector where every component is the dot product of `self` and `rhs`.
    ///
    /// Mirrors `glam::IVec4::dot_into_vec`.
    /// #### Panics
    /// * `'IVec4: overflow'` if the result does not fit `i32`.
    /// #### Deviations
    /// * Only the final result is range-checked: an intermediate product or sum that
    ///   leaves the `i32` range does not panic when the result fits (glam-rs panics in
    ///   debug builds and wraps in release builds).
    fn dot_into_vec(self: IVec4, rhs: IVec4) -> IVec4;
    /// Returns a vector containing the minimum values for each element of `self` and
    /// `rhs`.
    ///
    /// In other words this computes `[min(x, rhs.x), min(self.y, rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::min`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn min(self: IVec4, rhs: IVec4) -> IVec4;
    /// Returns a vector containing the maximum values for each element of `self` and
    /// `rhs`.
    ///
    /// In other words this computes `[max(self.x, rhs.x), max(self.y, rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::max`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn max(self: IVec4, rhs: IVec4) -> IVec4;
    /// Component-wise clamping of values, similar to `i32::clamp`.
    ///
    /// Each element in `min` must be less-or-equal to the corresponding element in `max`.
    ///
    /// Mirrors `glam::IVec4::clamp`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * The `glam_assert!(min <= max)` precondition is not checked. When it is violated
    ///   the result differs from the `self.max(min).min(max)` of glam-rs: an element below
    ///   `min` clamps to `min` (glam-rs: to `max`). The if-chain is 10 to 30 % cheaper.
    fn clamp(self: IVec4, min: IVec4, max: IVec4) -> IVec4;
    /// Returns the horizontal minimum of `self`.
    ///
    /// In other words this computes `min(x, y, ..)`.
    ///
    /// Mirrors `glam::IVec4::min_element`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn min_element(self: IVec4) -> i32;
    /// Returns the horizontal maximum of `self`.
    ///
    /// In other words this computes `max(x, y, ..)`.
    ///
    /// Mirrors `glam::IVec4::max_element`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn max_element(self: IVec4) -> i32;
    /// Returns the index of the first minimum element of `self`.
    ///
    /// Mirrors `glam::IVec4::min_position`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn min_position(self: IVec4) -> usize;
    /// Returns the index of the first maximum element of `self`.
    ///
    /// Mirrors `glam::IVec4::max_position`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn max_position(self: IVec4) -> usize;
    /// Returns the sum of all elements of `self`.
    ///
    /// In other words, this computes `self.x + self.y + ..`.
    ///
    /// Mirrors `glam::IVec4::element_sum`.
    /// #### Panics
    /// * `'IVec4: overflow'` if the result does not fit `i32`.
    /// #### Deviations
    /// * Only the final result is range-checked: an intermediate product or sum that
    ///   leaves the `i32` range does not panic when the result fits (glam-rs panics in
    ///   debug builds and wraps in release builds).
    fn element_sum(self: IVec4) -> i32;
    /// Returns the product of all elements of `self`.
    ///
    /// In other words, this computes `self.x * self.y * ..`.
    ///
    /// Mirrors `glam::IVec4::element_product`.
    /// #### Panics
    /// * `'IVec4: overflow'` if the result does not fit `i32`.
    /// #### Deviations
    /// * Only the final result is range-checked: an intermediate product or sum that
    ///   leaves the `i32` range does not panic when the result fits (glam-rs panics in
    ///   debug builds and wraps in release builds).
    fn element_product(self: IVec4) -> i32;
    /// Returns a vector mask containing the result of a `==` comparison for each element
    /// of `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x == rhs.x, self.y == rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::IVec4::cmpeq`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmpeq(self: IVec4, rhs: IVec4) -> BVec4;
    /// Returns a vector mask containing the result of a `!=` comparison for each element
    /// of `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x != rhs.x, self.y != rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::IVec4::cmpne`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmpne(self: IVec4, rhs: IVec4) -> BVec4;
    /// Returns a vector mask containing the result of a `>=` comparison for each element
    /// of `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x >= rhs.x, self.y >= rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::IVec4::cmpge`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmpge(self: IVec4, rhs: IVec4) -> BVec4;
    /// Returns a vector mask containing the result of a `>` comparison for each element of
    /// `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x > rhs.x, self.y > rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::IVec4::cmpgt`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmpgt(self: IVec4, rhs: IVec4) -> BVec4;
    /// Returns a vector mask containing the result of a `<=` comparison for each element
    /// of `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x <= rhs.x, self.y <= rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::IVec4::cmple`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmple(self: IVec4, rhs: IVec4) -> BVec4;
    /// Returns a vector mask containing the result of a `<` comparison for each element of
    /// `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x < rhs.x, self.y < rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::IVec4::cmplt`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmplt(self: IVec4, rhs: IVec4) -> BVec4;
    /// Returns a vector containing the absolute value of each element of `self`.
    ///
    /// Mirrors `glam::IVec4::abs`.
    /// #### Panics
    /// * `'i32_neg Underflow'` if an element is `i32::MIN`.
    /// #### Deviations
    /// * None.
    fn abs(self: IVec4) -> IVec4;
    /// Returns a vector with elements representing the sign of `self`.
    ///
    /// - `0` if the number is zero
    /// - `1` if the number is positive
    /// - `-1` if the number is negative
    ///
    /// Mirrors `glam::IVec4::signum`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn signum(self: IVec4) -> IVec4;
    /// Returns a bitmask with the lowest 4 bits set to the sign bits from the elements of
    /// `self`.
    ///
    /// A negative element results in a `1` bit and a positive element in a `0` bit.
    /// Element `x` goes into the first lowest bit, element `y` into the second, etc.
    ///
    /// Mirrors `glam::IVec4::is_negative_bitmask`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn is_negative_bitmask(self: IVec4) -> u32;
    /// Returns a mask indicating which components are negative.
    ///
    /// Mirrors `glam::IVec4::is_negative_mask`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn is_negative_mask(self: IVec4) -> BVec4;
    /// Computes the squared length of `self`.
    ///
    /// Mirrors `glam::IVec4::length_squared`.
    /// #### Panics
    /// * `'IVec4: overflow'` if the result does not fit `i32`.
    /// #### Deviations
    /// * Only the final result is range-checked: an intermediate product or sum that
    ///   leaves the `i32` range does not panic when the result fits (glam-rs panics in
    ///   debug builds and wraps in release builds).
    fn length_squared(self: IVec4) -> i32;
    /// Compute the squared euclidean distance between two points in space.
    ///
    /// Mirrors `glam::IVec4::distance_squared`.
    /// #### Panics
    /// * `'IVec4: overflow'` if the result does not fit `i32`.
    /// #### Deviations
    /// * Only the final result is range-checked: an intermediate product or sum that
    ///   leaves the `i32` range does not panic when the result fits (glam-rs panics in
    ///   debug builds and wraps in release builds).
    fn distance_squared(self: IVec4, rhs: IVec4) -> i32;
    /// Returns the element-wise quotient of Euclidean division of `self` by `rhs`.
    ///
    /// Mirrors `glam::IVec4::div_euclid`.
    /// #### Panics
    /// * `'Division by 0'` if any `rhs` element is 0.
    /// * `'attempt to divide with overflow'` for `i32::MIN / -1`.
    /// #### Deviations
    /// * None.
    fn div_euclid(self: IVec4, rhs: IVec4) -> IVec4;
    /// Returns the element-wise remainder of Euclidean division of `self` by `rhs`.
    ///
    /// Mirrors `glam::IVec4::rem_euclid`.
    /// #### Panics
    /// * `'Division by 0'` if any `rhs` element is 0.
    /// #### Deviations
    /// * `i32::MIN.rem_euclid(-1)` is 0, the mathematical result: `i32::rem_euclid` of
    ///   Rust panics with an overflow there (it computes `MIN % -1`).
    fn rem_euclid(self: IVec4, rhs: IVec4) -> IVec4;
    /// Computes the manhattan distance between two points.
    ///
    /// See also `checked_manhattan_distance`.
    ///
    /// Mirrors `glam::IVec4::manhattan_distance`.
    /// #### Panics
    /// * `'IVec4: overflow'` if the result does not fit `i32`.
    /// #### Deviations
    /// * None.
    fn manhattan_distance(self: IVec4, rhs: IVec4) -> u32;
    /// Computes the manhattan distance between two points.
    ///
    /// This will return `None` if the result is greater than `u32::MAX`.
    ///
    /// Mirrors `glam::IVec4::checked_manhattan_distance`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_manhattan_distance(self: IVec4, rhs: IVec4) -> Option<u32>;
    /// Computes the chebyshev distance between two points.
    ///
    /// Mirrors `glam::IVec4::chebyshev_distance`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn chebyshev_distance(self: IVec4, rhs: IVec4) -> u32;
    /// Casts all elements of `self` to `u32`.
    ///
    /// Like the Rust `as` cast this is the two's complement reinterpretation: `-1` becomes
    /// `u32::MAX`. The checked conversion is `TryInto<IVec4, UVec4>`.
    ///
    /// Mirrors `glam::IVec4::as_uvec4`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn as_uvec4(self: IVec4) -> UVec4;
    /// Returns a vector containing the checked addition of `self` and `rhs`.
    ///
    /// In other words this computes `Some([self.x + rhs.x, self.y + rhs.y, ..])` but
    /// returns `None` on any overflow.
    ///
    /// Mirrors `glam::IVec4::checked_add`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_add(self: IVec4, rhs: IVec4) -> Option<IVec4>;
    /// Returns a vector containing the checked subtraction of `self` and `rhs`.
    ///
    /// In other words this computes `Some([self.x - rhs.x, self.y - rhs.y, ..])` but
    /// returns `None` on any overflow.
    ///
    /// Mirrors `glam::IVec4::checked_sub`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_sub(self: IVec4, rhs: IVec4) -> Option<IVec4>;
    /// Returns a vector containing the checked multiplication of `self` and `rhs`.
    ///
    /// In other words this computes `Some([self.x * rhs.x, self.y * rhs.y, ..])` but
    /// returns `None` on any overflow.
    ///
    /// Mirrors `glam::IVec4::checked_mul`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_mul(self: IVec4, rhs: IVec4) -> Option<IVec4>;
    /// Returns a vector containing the checked division of `self` and `rhs`.
    ///
    /// In other words this computes `Some([self.x / rhs.x, self.y / rhs.y, ..])` but
    /// returns `None` on any division by zero or overflow.
    ///
    /// Mirrors `glam::IVec4::checked_div`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_div(self: IVec4, rhs: IVec4) -> Option<IVec4>;
    /// Returns a vector containing the wrapping addition of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.wrapping_add(rhs.x),
    /// self.y.wrapping_add(rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::wrapping_add`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn wrapping_add(self: IVec4, rhs: IVec4) -> IVec4;
    /// Returns a vector containing the wrapping subtraction of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.wrapping_sub(rhs.x),
    /// self.y.wrapping_sub(rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::wrapping_sub`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn wrapping_sub(self: IVec4, rhs: IVec4) -> IVec4;
    /// Returns a vector containing the wrapping multiplication of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.wrapping_mul(rhs.x),
    /// self.y.wrapping_mul(rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::wrapping_mul`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn wrapping_mul(self: IVec4, rhs: IVec4) -> IVec4;
    /// Returns a vector containing the wrapping division of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.wrapping_div(rhs.x),
    /// self.y.wrapping_div(rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::wrapping_div`.
    /// #### Panics
    /// * `'Division by 0'` if any `rhs` element is 0.
    /// #### Deviations
    /// * None.
    fn wrapping_div(self: IVec4, rhs: IVec4) -> IVec4;
    /// Returns a vector containing the saturating addition of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.saturating_add(rhs.x),
    /// self.y.saturating_add(rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::saturating_add`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn saturating_add(self: IVec4, rhs: IVec4) -> IVec4;
    /// Returns a vector containing the saturating subtraction of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.saturating_sub(rhs.x),
    /// self.y.saturating_sub(rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::saturating_sub`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn saturating_sub(self: IVec4, rhs: IVec4) -> IVec4;
    /// Returns a vector containing the saturating multiplication of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.saturating_mul(rhs.x),
    /// self.y.saturating_mul(rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::saturating_mul`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn saturating_mul(self: IVec4, rhs: IVec4) -> IVec4;
    /// Returns a vector containing the saturating division of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.saturating_div(rhs.x),
    /// self.y.saturating_div(rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::saturating_div`.
    /// #### Panics
    /// * `'Division by 0'` if any `rhs` element is 0.
    /// #### Deviations
    /// * None.
    fn saturating_div(self: IVec4, rhs: IVec4) -> IVec4;
    /// Returns a vector containing the checked addition of `self` and unsigned vector
    /// `rhs`.
    ///
    /// In other words this computes `Some([self.x + rhs.x, self.y + rhs.y, ..])` but
    /// returns `None` on any overflow.
    ///
    /// Mirrors `glam::IVec4::checked_add_unsigned`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_add_unsigned(self: IVec4, rhs: UVec4) -> Option<IVec4>;
    /// Returns a vector containing the wrapping addition of `self` and unsigned vector
    /// `rhs`.
    ///
    /// In other words this computes `[self.x.wrapping_add_unsigned(rhs.x),
    /// self.y.wrapping_add_unsigned(rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::wrapping_add_unsigned`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn wrapping_add_unsigned(self: IVec4, rhs: UVec4) -> IVec4;
    /// Returns a vector containing the saturating addition of `self` and unsigned vector
    /// `rhs`.
    ///
    /// In other words this computes `[self.x.saturating_add_unsigned(rhs.x),
    /// self.y.saturating_add_unsigned(rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::saturating_add_unsigned`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn saturating_add_unsigned(self: IVec4, rhs: UVec4) -> IVec4;
    /// Returns a vector containing the checked subtraction of `self` and unsigned vector
    /// `rhs`.
    ///
    /// In other words this computes `Some([self.x - rhs.x, self.y - rhs.y, ..])` but
    /// returns `None` on any overflow.
    ///
    /// Mirrors `glam::IVec4::checked_sub_unsigned`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_sub_unsigned(self: IVec4, rhs: UVec4) -> Option<IVec4>;
    /// Returns a vector containing the wrapping subtraction of `self` and unsigned vector
    /// `rhs`.
    ///
    /// In other words this computes `[self.x.wrapping_sub_unsigned(rhs.x),
    /// self.y.wrapping_sub_unsigned(rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::wrapping_sub_unsigned`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn wrapping_sub_unsigned(self: IVec4, rhs: UVec4) -> IVec4;
    /// Returns a vector containing the saturating subtraction of `self` and unsigned
    /// vector `rhs`.
    ///
    /// In other words this computes `[self.x.saturating_sub_unsigned(rhs.x),
    /// self.y.saturating_sub_unsigned(rhs.y), ..]`.
    ///
    /// Mirrors `glam::IVec4::saturating_sub_unsigned`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn saturating_sub_unsigned(self: IVec4, rhs: UVec4) -> IVec4;
    /// Returns `[self.x + rhs, self.y + rhs, ..]`.
    ///
    /// Mirrors `impl Add<i32> for glam::IVec4`.
    /// #### Panics
    /// * `'i32_add Overflow'` / `'i32_add Underflow'` on overflow.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Add<i32> for IVec4`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    fn add_scalar(self: IVec4, rhs: i32) -> IVec4;
    /// Returns `[self.x - rhs, self.y - rhs, ..]`.
    ///
    /// Mirrors `impl Sub<i32> for glam::IVec4`.
    /// #### Panics
    /// * `'i32_sub Overflow'` / `'i32_sub Underflow'` on overflow.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Sub<i32> for IVec4`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    fn sub_scalar(self: IVec4, rhs: i32) -> IVec4;
    /// Returns `[self.x * rhs, self.y * rhs, ..]`.
    ///
    /// Mirrors `impl Mul<i32> for glam::IVec4`.
    /// #### Panics
    /// * `'i32_mul Overflow'` on overflow.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Mul<i32> for IVec4`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    fn mul_scalar(self: IVec4, rhs: i32) -> IVec4;
    /// Returns `[self.x / rhs, self.y / rhs, ..]` (truncated division).
    ///
    /// Mirrors `impl Div<i32> for glam::IVec4`.
    /// #### Panics
    /// * `'Division by 0'` if `rhs` is 0.
    /// * `'attempt to divide with overflow'` for `i32::MIN / -1`.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Div<i32> for IVec4`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    fn div_scalar(self: IVec4, rhs: i32) -> IVec4;
    /// Returns `[self.x % rhs, self.y % rhs, ..]` (the remainder has the sign of `self`).
    ///
    /// Mirrors `impl Rem<i32> for glam::IVec4`.
    /// #### Panics
    /// * `'Division by 0'` if `rhs` is 0.
    /// * `'attempt to divide with overflow'` for `i32::MIN / -1`.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Rem<i32> for IVec4`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    /// * `i32::MIN % -1` panics (the quotient overflows); Rust returns 0 in release
    ///   builds.
    fn rem_scalar(self: IVec4, rhs: i32) -> IVec4;
    /// Shifts every element left by `rhs` bits: the bits shifted out are lost, as with the
    /// Rust `<<` (the result is the two's complement reinterpretation).
    ///
    /// Mirrors `impl Shl<u32> for glam::IVec4`.
    /// #### Panics
    /// * `'IVec4: shift overflow'` if `rhs >= 32` (Rust: overflow panic in debug builds,
    ///   masked shift amount in release builds).
    /// #### Deviations
    /// * glam-rs spells this with an operator; Cairo has no shift operator nor trait. Only
    ///   the `u32` shift amount is ported (not the 8 integer widths nor the per-component
    ///   vector amounts).
    fn shl(self: IVec4, rhs: u32) -> IVec4;
    /// Shifts every element right by `rhs` bits: an arithmetic shift, i.e. a division by
    /// `2^rhs` rounded toward negative infinity, as with the Rust `>>`.
    ///
    /// Mirrors `impl Shr<u32> for glam::IVec4`.
    /// #### Panics
    /// * `'IVec4: shift overflow'` if `rhs >= 32` (Rust: overflow panic in debug builds,
    ///   masked shift amount in release builds).
    /// #### Deviations
    /// * glam-rs spells this with an operator; Cairo has no shift operator nor trait. Only
    ///   the `u32` shift amount is ported (not the 8 integer widths nor the per-component
    ///   vector amounts).
    fn shr(self: IVec4, rhs: u32) -> IVec4;
}

pub impl IVec4Impl of IVec4Trait {
    const ZERO: IVec4 = IVec4 { x: 0, y: 0, z: 0, w: 0 };
    const ONE: IVec4 = IVec4 { x: 1, y: 1, z: 1, w: 1 };
    const NEG_ONE: IVec4 = IVec4 { x: -1, y: -1, z: -1, w: -1 };
    const MIN: IVec4 = IVec4 { x: -0x80000000, y: -0x80000000, z: -0x80000000, w: -0x80000000 };
    const MAX: IVec4 = IVec4 { x: 0x7fffffff, y: 0x7fffffff, z: 0x7fffffff, w: 0x7fffffff };
    const X: IVec4 = IVec4 { x: 1, y: 0, z: 0, w: 0 };
    const Y: IVec4 = IVec4 { x: 0, y: 1, z: 0, w: 0 };
    const Z: IVec4 = IVec4 { x: 0, y: 0, z: 1, w: 0 };
    const W: IVec4 = IVec4 { x: 0, y: 0, z: 0, w: 1 };
    const NEG_X: IVec4 = IVec4 { x: -1, y: 0, z: 0, w: 0 };
    const NEG_Y: IVec4 = IVec4 { x: 0, y: -1, z: 0, w: 0 };
    const NEG_Z: IVec4 = IVec4 { x: 0, y: 0, z: -1, w: 0 };
    const NEG_W: IVec4 = IVec4 { x: 0, y: 0, z: 0, w: -1 };
    const AXES: [IVec4; 4] = [
        IVec4 { x: 1, y: 0, z: 0, w: 0 }, IVec4 { x: 0, y: 1, z: 0, w: 0 },
        IVec4 { x: 0, y: 0, z: 1, w: 0 }, IVec4 { x: 0, y: 0, z: 0, w: 1 },
    ];

    #[inline(always)]
    fn new(x: i32, y: i32, z: i32, w: i32) -> IVec4 {
        IVec4 { x, y, z, w }
    }

    #[inline(always)]
    fn splat(v: i32) -> IVec4 {
        IVec4 { x: v, y: v, z: v, w: v }
    }

    #[inline(always)]
    fn select(mask: BVec4, if_true: IVec4, if_false: IVec4) -> IVec4 {
        IVec4 {
            x: if mask.x {
                if_true.x
            } else {
                if_false.x
            },
            y: if mask.y {
                if_true.y
            } else {
                if_false.y
            },
            z: if mask.z {
                if_true.z
            } else {
                if_false.z
            },
            w: if mask.w {
                if_true.w
            } else {
                if_false.w
            },
        }
    }

    #[inline(always)]
    fn from_array(a: [i32; 4]) -> IVec4 {
        let [x, y, z, w] = a;
        IVec4 { x, y, z, w }
    }

    #[inline(always)]
    fn to_array(self: IVec4) -> [i32; 4] {
        [self.x, self.y, self.z, self.w]
    }

    #[inline(always)]
    fn truncate(self: IVec4) -> IVec3 {
        IVec3 { x: self.x, y: self.y, z: self.z }
    }

    #[inline(always)]
    fn with_x(self: IVec4, x: i32) -> IVec4 {
        IVec4 { x: x, y: self.y, z: self.z, w: self.w }
    }

    #[inline(always)]
    fn with_y(self: IVec4, y: i32) -> IVec4 {
        IVec4 { x: self.x, y: y, z: self.z, w: self.w }
    }

    #[inline(always)]
    fn with_z(self: IVec4, z: i32) -> IVec4 {
        IVec4 { x: self.x, y: self.y, z: z, w: self.w }
    }

    #[inline(always)]
    fn with_w(self: IVec4, w: i32) -> IVec4 {
        IVec4 { x: self.x, y: self.y, z: self.z, w: w }
    }

    #[inline(always)]
    fn dot(self: IVec4, rhs: IVec4) -> i32 {
        let d: felt252 = self.x.wide_mul(rhs.x).into()
            + self.y.wide_mul(rhs.y).into()
            + self.z.wide_mul(rhs.z).into()
            + self.w.wide_mul(rhs.w).into();
        d.try_into().expect('IVec4: overflow')
    }

    #[inline(always)]
    fn dot_into_vec(self: IVec4, rhs: IVec4) -> IVec4 {
        let d = Self::dot(self, rhs);
        IVec4 { x: d, y: d, z: d, w: d }
    }

    #[inline(always)]
    fn min(self: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: if self.x < rhs.x {
                self.x
            } else {
                rhs.x
            },
            y: if self.y < rhs.y {
                self.y
            } else {
                rhs.y
            },
            z: if self.z < rhs.z {
                self.z
            } else {
                rhs.z
            },
            w: if self.w < rhs.w {
                self.w
            } else {
                rhs.w
            },
        }
    }

    #[inline(always)]
    fn max(self: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: if self.x > rhs.x {
                self.x
            } else {
                rhs.x
            },
            y: if self.y > rhs.y {
                self.y
            } else {
                rhs.y
            },
            z: if self.z > rhs.z {
                self.z
            } else {
                rhs.z
            },
            w: if self.w > rhs.w {
                self.w
            } else {
                rhs.w
            },
        }
    }

    #[inline(always)]
    fn clamp(self: IVec4, min: IVec4, max: IVec4) -> IVec4 {
        IVec4 {
            x: if self.x < min.x {
                min.x
            } else if self.x > max.x {
                max.x
            } else {
                self.x
            },
            y: if self.y < min.y {
                min.y
            } else if self.y > max.y {
                max.y
            } else {
                self.y
            },
            z: if self.z < min.z {
                min.z
            } else if self.z > max.z {
                max.z
            } else {
                self.z
            },
            w: if self.w < min.w {
                min.w
            } else if self.w > max.w {
                max.w
            } else {
                self.w
            },
        }
    }

    #[inline(always)]
    fn min_element(self: IVec4) -> i32 {
        let m = if self.z < self.w {
            self.z
        } else {
            self.w
        };
        let m = if self.y < m {
            self.y
        } else {
            m
        };
        let m = if self.x < m {
            self.x
        } else {
            m
        };
        m
    }

    #[inline(always)]
    fn max_element(self: IVec4) -> i32 {
        let m = if self.z > self.w {
            self.z
        } else {
            self.w
        };
        let m = if self.y > m {
            self.y
        } else {
            m
        };
        let m = if self.x > m {
            self.x
        } else {
            m
        };
        m
    }

    #[inline(always)]
    fn min_position(self: IVec4) -> usize {
        let mut m = self.x;
        let mut index = 0;
        if self.y < m {
            m = self.y;
            index = 1;
        }
        if self.z < m {
            m = self.z;
            index = 2;
        }
        if self.w < m {
            index = 3;
        }
        index
    }

    #[inline(always)]
    fn max_position(self: IVec4) -> usize {
        let mut m = self.x;
        let mut index = 0;
        if self.y > m {
            m = self.y;
            index = 1;
        }
        if self.z > m {
            m = self.z;
            index = 2;
        }
        if self.w > m {
            index = 3;
        }
        index
    }

    #[inline(always)]
    fn element_sum(self: IVec4) -> i32 {
        let s: felt252 = self.x.into() + self.y.into() + self.z.into() + self.w.into();
        s.try_into().expect('IVec4: overflow')
    }

    #[inline(always)]
    fn element_product(self: IVec4) -> i32 {
        let p: felt252 = self.x.into() * self.y.into() * self.z.into() * self.w.into();
        p.try_into().expect('IVec4: overflow')
    }

    #[inline(always)]
    fn cmpeq(self: IVec4, rhs: IVec4) -> BVec4 {
        BVec4 { x: self.x == rhs.x, y: self.y == rhs.y, z: self.z == rhs.z, w: self.w == rhs.w }
    }

    #[inline(always)]
    fn cmpne(self: IVec4, rhs: IVec4) -> BVec4 {
        BVec4 { x: self.x != rhs.x, y: self.y != rhs.y, z: self.z != rhs.z, w: self.w != rhs.w }
    }

    #[inline(always)]
    fn cmpge(self: IVec4, rhs: IVec4) -> BVec4 {
        BVec4 { x: self.x >= rhs.x, y: self.y >= rhs.y, z: self.z >= rhs.z, w: self.w >= rhs.w }
    }

    #[inline(always)]
    fn cmpgt(self: IVec4, rhs: IVec4) -> BVec4 {
        BVec4 { x: self.x > rhs.x, y: self.y > rhs.y, z: self.z > rhs.z, w: self.w > rhs.w }
    }

    #[inline(always)]
    fn cmple(self: IVec4, rhs: IVec4) -> BVec4 {
        BVec4 { x: self.x <= rhs.x, y: self.y <= rhs.y, z: self.z <= rhs.z, w: self.w <= rhs.w }
    }

    #[inline(always)]
    fn cmplt(self: IVec4, rhs: IVec4) -> BVec4 {
        BVec4 { x: self.x < rhs.x, y: self.y < rhs.y, z: self.z < rhs.z, w: self.w < rhs.w }
    }

    #[inline(always)]
    fn abs(self: IVec4) -> IVec4 {
        IVec4 { x: abs_i32(self.x), y: abs_i32(self.y), z: abs_i32(self.z), w: abs_i32(self.w) }
    }

    #[inline(always)]
    fn signum(self: IVec4) -> IVec4 {
        IVec4 {
            x: signum_i32(self.x),
            y: signum_i32(self.y),
            z: signum_i32(self.z),
            w: signum_i32(self.w),
        }
    }

    #[inline(always)]
    fn is_negative_bitmask(self: IVec4) -> u32 {
        Self::is_negative_mask(self).bitmask()
    }

    #[inline(always)]
    fn is_negative_mask(self: IVec4) -> BVec4 {
        BVec4 { x: self.x < 0, y: self.y < 0, z: self.z < 0, w: self.w < 0 }
    }

    #[inline(always)]
    fn length_squared(self: IVec4) -> i32 {
        let d: felt252 = self.x.wide_mul(self.x).into()
            + self.y.wide_mul(self.y).into()
            + self.z.wide_mul(self.z).into()
            + self.w.wide_mul(self.w).into();
        d.try_into().expect('IVec4: overflow')
    }

    #[inline(always)]
    fn distance_squared(self: IVec4, rhs: IVec4) -> i32 {
        let dx: felt252 = self.x.into() - rhs.x.into();
        let dy: felt252 = self.y.into() - rhs.y.into();
        let dz: felt252 = self.z.into() - rhs.z.into();
        let dw: felt252 = self.w.into() - rhs.w.into();
        let d: felt252 = dx * dx + dy * dy + dz * dz + dw * dw;
        d.try_into().expect('IVec4: overflow')
    }

    #[inline(always)]
    fn div_euclid(self: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: div_euclid_i32(self.x, rhs.x),
            y: div_euclid_i32(self.y, rhs.y),
            z: div_euclid_i32(self.z, rhs.z),
            w: div_euclid_i32(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn rem_euclid(self: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: rem_euclid_i32(self.x, rhs.x),
            y: rem_euclid_i32(self.y, rhs.y),
            z: rem_euclid_i32(self.z, rhs.z),
            w: rem_euclid_i32(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn manhattan_distance(self: IVec4, rhs: IVec4) -> u32 {
        let d: felt252 = abs_diff_i32(self.x, rhs.x).into()
            + abs_diff_i32(self.y, rhs.y).into()
            + abs_diff_i32(self.z, rhs.z).into()
            + abs_diff_i32(self.w, rhs.w).into();
        d.try_into().expect('IVec4: overflow')
    }

    #[inline(always)]
    fn checked_manhattan_distance(self: IVec4, rhs: IVec4) -> Option<u32> {
        let d: felt252 = abs_diff_i32(self.x, rhs.x).into()
            + abs_diff_i32(self.y, rhs.y).into()
            + abs_diff_i32(self.z, rhs.z).into()
            + abs_diff_i32(self.w, rhs.w).into();
        d.try_into()
    }

    #[inline(always)]
    fn chebyshev_distance(self: IVec4, rhs: IVec4) -> u32 {
        let m = abs_diff_i32(self.x, rhs.x);
        let d = abs_diff_i32(self.y, rhs.y);
        let m = if d > m {
            d
        } else {
            m
        };
        let d = abs_diff_i32(self.z, rhs.z);
        let m = if d > m {
            d
        } else {
            m
        };
        let d = abs_diff_i32(self.w, rhs.w);
        let m = if d > m {
            d
        } else {
            m
        };
        m
    }

    #[inline(always)]
    fn as_uvec4(self: IVec4) -> UVec4 {
        UVec4 {
            x: i32_as_u32(self.x),
            y: i32_as_u32(self.y),
            z: i32_as_u32(self.z),
            w: i32_as_u32(self.w),
        }
    }

    #[inline(always)]
    fn checked_add(self: IVec4, rhs: IVec4) -> Option<IVec4> {
        Some(
            IVec4 {
                x: self.x.checked_add(rhs.x)?,
                y: self.y.checked_add(rhs.y)?,
                z: self.z.checked_add(rhs.z)?,
                w: self.w.checked_add(rhs.w)?,
            },
        )
    }

    #[inline(always)]
    fn checked_sub(self: IVec4, rhs: IVec4) -> Option<IVec4> {
        Some(
            IVec4 {
                x: self.x.checked_sub(rhs.x)?,
                y: self.y.checked_sub(rhs.y)?,
                z: self.z.checked_sub(rhs.z)?,
                w: self.w.checked_sub(rhs.w)?,
            },
        )
    }

    #[inline(always)]
    fn checked_mul(self: IVec4, rhs: IVec4) -> Option<IVec4> {
        Some(
            IVec4 {
                x: checked_mul_i32(self.x, rhs.x)?,
                y: checked_mul_i32(self.y, rhs.y)?,
                z: checked_mul_i32(self.z, rhs.z)?,
                w: checked_mul_i32(self.w, rhs.w)?,
            },
        )
    }

    #[inline(always)]
    fn checked_div(self: IVec4, rhs: IVec4) -> Option<IVec4> {
        Some(
            IVec4 {
                x: checked_div_i32(self.x, rhs.x)?,
                y: checked_div_i32(self.y, rhs.y)?,
                z: checked_div_i32(self.z, rhs.z)?,
                w: checked_div_i32(self.w, rhs.w)?,
            },
        )
    }

    #[inline(always)]
    fn wrapping_add(self: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: self.x.wrapping_add(rhs.x),
            y: self.y.wrapping_add(rhs.y),
            z: self.z.wrapping_add(rhs.z),
            w: self.w.wrapping_add(rhs.w),
        }
    }

    #[inline(always)]
    fn wrapping_sub(self: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: self.x.wrapping_sub(rhs.x),
            y: self.y.wrapping_sub(rhs.y),
            z: self.z.wrapping_sub(rhs.z),
            w: self.w.wrapping_sub(rhs.w),
        }
    }

    #[inline(always)]
    fn wrapping_mul(self: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: wrapping_mul_i32(self.x, rhs.x),
            y: wrapping_mul_i32(self.y, rhs.y),
            z: wrapping_mul_i32(self.z, rhs.z),
            w: wrapping_mul_i32(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn wrapping_div(self: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: wrapping_div_i32(self.x, rhs.x),
            y: wrapping_div_i32(self.y, rhs.y),
            z: wrapping_div_i32(self.z, rhs.z),
            w: wrapping_div_i32(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn saturating_add(self: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: self.x.saturating_add(rhs.x),
            y: self.y.saturating_add(rhs.y),
            z: self.z.saturating_add(rhs.z),
            w: self.w.saturating_add(rhs.w),
        }
    }

    #[inline(always)]
    fn saturating_sub(self: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: self.x.saturating_sub(rhs.x),
            y: self.y.saturating_sub(rhs.y),
            z: self.z.saturating_sub(rhs.z),
            w: self.w.saturating_sub(rhs.w),
        }
    }

    #[inline(always)]
    fn saturating_mul(self: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: saturating_mul_i32(self.x, rhs.x),
            y: saturating_mul_i32(self.y, rhs.y),
            z: saturating_mul_i32(self.z, rhs.z),
            w: saturating_mul_i32(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn saturating_div(self: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: saturating_div_i32(self.x, rhs.x),
            y: saturating_div_i32(self.y, rhs.y),
            z: saturating_div_i32(self.z, rhs.z),
            w: saturating_div_i32(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn checked_add_unsigned(self: IVec4, rhs: UVec4) -> Option<IVec4> {
        Some(
            IVec4 {
                x: checked_add_unsigned(self.x, rhs.x)?,
                y: checked_add_unsigned(self.y, rhs.y)?,
                z: checked_add_unsigned(self.z, rhs.z)?,
                w: checked_add_unsigned(self.w, rhs.w)?,
            },
        )
    }

    #[inline(always)]
    fn wrapping_add_unsigned(self: IVec4, rhs: UVec4) -> IVec4 {
        IVec4 {
            x: wrapping_add_unsigned(self.x, rhs.x),
            y: wrapping_add_unsigned(self.y, rhs.y),
            z: wrapping_add_unsigned(self.z, rhs.z),
            w: wrapping_add_unsigned(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn saturating_add_unsigned(self: IVec4, rhs: UVec4) -> IVec4 {
        IVec4 {
            x: saturating_add_unsigned(self.x, rhs.x),
            y: saturating_add_unsigned(self.y, rhs.y),
            z: saturating_add_unsigned(self.z, rhs.z),
            w: saturating_add_unsigned(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn checked_sub_unsigned(self: IVec4, rhs: UVec4) -> Option<IVec4> {
        Some(
            IVec4 {
                x: checked_sub_unsigned(self.x, rhs.x)?,
                y: checked_sub_unsigned(self.y, rhs.y)?,
                z: checked_sub_unsigned(self.z, rhs.z)?,
                w: checked_sub_unsigned(self.w, rhs.w)?,
            },
        )
    }

    #[inline(always)]
    fn wrapping_sub_unsigned(self: IVec4, rhs: UVec4) -> IVec4 {
        IVec4 {
            x: wrapping_sub_unsigned(self.x, rhs.x),
            y: wrapping_sub_unsigned(self.y, rhs.y),
            z: wrapping_sub_unsigned(self.z, rhs.z),
            w: wrapping_sub_unsigned(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn saturating_sub_unsigned(self: IVec4, rhs: UVec4) -> IVec4 {
        IVec4 {
            x: saturating_sub_unsigned(self.x, rhs.x),
            y: saturating_sub_unsigned(self.y, rhs.y),
            z: saturating_sub_unsigned(self.z, rhs.z),
            w: saturating_sub_unsigned(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn add_scalar(self: IVec4, rhs: i32) -> IVec4 {
        IVec4 { x: self.x + rhs, y: self.y + rhs, z: self.z + rhs, w: self.w + rhs }
    }

    #[inline(always)]
    fn sub_scalar(self: IVec4, rhs: i32) -> IVec4 {
        IVec4 { x: self.x - rhs, y: self.y - rhs, z: self.z - rhs, w: self.w - rhs }
    }

    #[inline(always)]
    fn mul_scalar(self: IVec4, rhs: i32) -> IVec4 {
        IVec4 { x: self.x * rhs, y: self.y * rhs, z: self.z * rhs, w: self.w * rhs }
    }

    #[inline(always)]
    fn div_scalar(self: IVec4, rhs: i32) -> IVec4 {
        let d: NonZero<i32> = rhs.try_into().expect('Division by 0');
        let (x, _) = DivRem::div_rem(self.x, d);
        let (y, _) = DivRem::div_rem(self.y, d);
        let (z, _) = DivRem::div_rem(self.z, d);
        let (w, _) = DivRem::div_rem(self.w, d);
        IVec4 { x, y, z, w }
    }

    #[inline(always)]
    fn rem_scalar(self: IVec4, rhs: i32) -> IVec4 {
        let d: NonZero<i32> = rhs.try_into().expect('Division by 0');
        let (_, x) = DivRem::div_rem(self.x, d);
        let (_, y) = DivRem::div_rem(self.y, d);
        let (_, z) = DivRem::div_rem(self.z, d);
        let (_, w) = DivRem::div_rem(self.w, d);
        IVec4 { x, y, z, w }
    }

    #[inline(always)]
    fn shl(self: IVec4, rhs: u32) -> IVec4 {
        let p = pow2(rhs);
        IVec4 {
            x: shl_i32(self.x, p),
            y: shl_i32(self.y, p),
            z: shl_i32(self.z, p),
            w: shl_i32(self.w, p),
        }
    }

    #[inline(always)]
    fn shr(self: IVec4, rhs: u32) -> IVec4 {
        let p: NonZero<u32> = pow2(rhs).try_into().unwrap();
        let (bias, _) = DivRem::div_rem(0x80000000_u32, p);
        let bias: felt252 = bias.into();
        IVec4 {
            x: shr_i32(self.x, p, bias),
            y: shr_i32(self.y, p, bias),
            z: shr_i32(self.z, p, bias),
            w: shr_i32(self.w, p, bias),
        }
    }
}

/// Component-wise `+`. Panics with the corelib `i32_add` overflow messages.
///
/// Mirrors `impl Add for glam::IVec4`.
pub impl IVec4Add of Add<IVec4> {
    #[inline(always)]
    fn add(lhs: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 { x: lhs.x + rhs.x, y: lhs.y + rhs.y, z: lhs.z + rhs.z, w: lhs.w + rhs.w }
    }
}

/// Component-wise `-`. Panics with the corelib `i32_sub` overflow messages.
///
/// Mirrors `impl Sub for glam::IVec4`.
pub impl IVec4Sub of Sub<IVec4> {
    #[inline(always)]
    fn sub(lhs: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 { x: lhs.x - rhs.x, y: lhs.y - rhs.y, z: lhs.z - rhs.z, w: lhs.w - rhs.w }
    }
}

/// Component-wise `*`. Panics with `'i32_mul Overflow'`.
///
/// Mirrors `impl Mul for glam::IVec4`.
pub impl IVec4Mul of Mul<IVec4> {
    #[inline(always)]
    fn mul(lhs: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 { x: lhs.x * rhs.x, y: lhs.y * rhs.y, z: lhs.z * rhs.z, w: lhs.w * rhs.w }
    }
}

/// Component-wise `/`. Truncated division. Panics with `'Division by 0'` and, for `i32::MIN / -1`,
/// `'attempt to divide with overflow'`.
///
/// Mirrors `impl Div for glam::IVec4`.
pub impl IVec4Div of Div<IVec4> {
    #[inline(always)]
    fn div(lhs: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 { x: lhs.x / rhs.x, y: lhs.y / rhs.y, z: lhs.z / rhs.z, w: lhs.w / rhs.w }
    }
}

/// Component-wise `%`. The remainder has the sign of `lhs`. Panics with `'Division by 0'` and, for
/// `i32::MIN % -1`, `'attempt to divide with overflow'`.
///
/// Mirrors `impl Rem for glam::IVec4`.
pub impl IVec4Rem of Rem<IVec4> {
    #[inline(always)]
    fn rem(lhs: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 { x: lhs.x % rhs.x, y: lhs.y % rhs.y, z: lhs.z % rhs.z, w: lhs.w % rhs.w }
    }
}

/// Component-wise negation. Panics with `'i32_neg Underflow'` on `i32::MIN`.
///
/// Mirrors `impl Neg for glam::IVec4`.
pub impl IVec4Neg of Neg<IVec4> {
    #[inline(always)]
    fn neg(a: IVec4) -> IVec4 {
        IVec4 { x: -a.x, y: -a.y, z: -a.z, w: -a.w }
    }
}

/// Mirrors `impl AddAssign for glam::IVec4`.
pub impl IVec4AddAssign of AddAssign<IVec4, IVec4> {
    #[inline(always)]
    fn add_assign(ref self: IVec4, rhs: IVec4) {
        self = self + rhs;
    }
}

/// Mirrors `impl SubAssign for glam::IVec4`.
pub impl IVec4SubAssign of SubAssign<IVec4, IVec4> {
    #[inline(always)]
    fn sub_assign(ref self: IVec4, rhs: IVec4) {
        self = self - rhs;
    }
}

/// Mirrors `impl MulAssign for glam::IVec4`.
pub impl IVec4MulAssign of MulAssign<IVec4, IVec4> {
    #[inline(always)]
    fn mul_assign(ref self: IVec4, rhs: IVec4) {
        self = self * rhs;
    }
}

/// Mirrors `impl DivAssign for glam::IVec4`.
pub impl IVec4DivAssign of DivAssign<IVec4, IVec4> {
    #[inline(always)]
    fn div_assign(ref self: IVec4, rhs: IVec4) {
        self = self / rhs;
    }
}

/// Mirrors `impl RemAssign for glam::IVec4`.
pub impl IVec4RemAssign of RemAssign<IVec4, IVec4> {
    #[inline(always)]
    fn rem_assign(ref self: IVec4, rhs: IVec4) {
        self = self % rhs;
    }
}

/// Mirrors `impl AddAssign<i32> for glam::IVec4` (see `IVec4Trait::add_scalar`).
pub impl IVec4AddAssignScalar of AddAssign<IVec4, i32> {
    #[inline(always)]
    fn add_assign(ref self: IVec4, rhs: i32) {
        self = IVec4Trait::add_scalar(self, rhs);
    }
}

/// Mirrors `impl SubAssign<i32> for glam::IVec4` (see `IVec4Trait::sub_scalar`).
pub impl IVec4SubAssignScalar of SubAssign<IVec4, i32> {
    #[inline(always)]
    fn sub_assign(ref self: IVec4, rhs: i32) {
        self = IVec4Trait::sub_scalar(self, rhs);
    }
}

/// Mirrors `impl MulAssign<i32> for glam::IVec4` (see `IVec4Trait::mul_scalar`).
pub impl IVec4MulAssignScalar of MulAssign<IVec4, i32> {
    #[inline(always)]
    fn mul_assign(ref self: IVec4, rhs: i32) {
        self = IVec4Trait::mul_scalar(self, rhs);
    }
}

/// Mirrors `impl DivAssign<i32> for glam::IVec4` (see `IVec4Trait::div_scalar`).
pub impl IVec4DivAssignScalar of DivAssign<IVec4, i32> {
    #[inline(always)]
    fn div_assign(ref self: IVec4, rhs: i32) {
        self = IVec4Trait::div_scalar(self, rhs);
    }
}

/// Mirrors `impl RemAssign<i32> for glam::IVec4` (see `IVec4Trait::rem_scalar`).
pub impl IVec4RemAssignScalar of RemAssign<IVec4, i32> {
    #[inline(always)]
    fn rem_assign(ref self: IVec4, rhs: i32) {
        self = IVec4Trait::rem_scalar(self, rhs);
    }
}

/// Component-wise bitwise `&` of the two's complement representations. One bitwise builtin cell per
/// component.
///
/// Mirrors `impl BitAnd for glam::IVec4`.
pub impl IVec4BitAnd of BitAnd<IVec4> {
    #[inline(always)]
    fn bitand(lhs: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: bitand_i32(lhs.x, rhs.x),
            y: bitand_i32(lhs.y, rhs.y),
            z: bitand_i32(lhs.z, rhs.z),
            w: bitand_i32(lhs.w, rhs.w),
        }
    }
}

/// Component-wise bitwise `|` of the two's complement representations. One bitwise builtin cell per
/// component.
///
/// Mirrors `impl BitOr for glam::IVec4`.
pub impl IVec4BitOr of BitOr<IVec4> {
    #[inline(always)]
    fn bitor(lhs: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: bitor_i32(lhs.x, rhs.x),
            y: bitor_i32(lhs.y, rhs.y),
            z: bitor_i32(lhs.z, rhs.z),
            w: bitor_i32(lhs.w, rhs.w),
        }
    }
}

/// Component-wise bitwise `^` of the two's complement representations. One bitwise builtin cell per
/// component.
///
/// Mirrors `impl BitXor for glam::IVec4`.
pub impl IVec4BitXor of BitXor<IVec4> {
    #[inline(always)]
    fn bitxor(lhs: IVec4, rhs: IVec4) -> IVec4 {
        IVec4 {
            x: bitxor_i32(lhs.x, rhs.x),
            y: bitxor_i32(lhs.y, rhs.y),
            z: bitxor_i32(lhs.z, rhs.z),
            w: bitxor_i32(lhs.w, rhs.w),
        }
    }
}

/// Component-wise bitwise NOT (`~v`): `-x - 1`, which never overflows. No bitwise builtin.
///
/// Mirrors `impl Not for glam::IVec4` (the Rust `!v`; Cairo spells the bitwise
/// complement of an integer `~`).
pub impl IVec4BitNot of BitNot<IVec4> {
    #[inline(always)]
    fn bitnot(a: IVec4) -> IVec4 {
        IVec4 { x: -1 - a.x, y: -1 - a.y, z: -1 - a.z, w: -1 - a.w }
    }
}

/// `v[i]`. Panics with `'IVec4: index out of bounds'` if `index >= 4`.
///
/// Mirrors `impl Index<usize> for glam::IVec4`.
pub impl IVec4IndexView of IndexView<IVec4, usize> {
    type Target = i32;
    #[inline(always)]
    fn index(self: @IVec4, index: usize) -> i32 {
        match index {
            0 => *self.x,
            1 => *self.y,
            2 => *self.z,
            3 => *self.w,
            _ => core::panic_with_felt252('IVec4: index out of bounds'),
        }
    }
}

/// Mirrors `impl From<[i32; 4]> for glam::IVec4`.
pub impl I32ArrayIntoIVec4 of Into<[i32; 4], IVec4> {
    #[inline(always)]
    fn into(self: [i32; 4]) -> IVec4 {
        IVec4Trait::from_array(self)
    }
}

/// Mirrors `impl From<glam::IVec4> for [i32; 4]`.
pub impl IVec4IntoI32Array of Into<IVec4, [i32; 4]> {
    #[inline(always)]
    fn into(self: IVec4) -> [i32; 4] {
        [self.x, self.y, self.z, self.w]
    }
}

/// Mirrors `impl From<(i32, i32, i32, i32)> for glam::IVec4`.
pub impl I32TupleIntoIVec4 of Into<(i32, i32, i32, i32), IVec4> {
    #[inline(always)]
    fn into(self: (i32, i32, i32, i32)) -> IVec4 {
        let (x, y, z, w) = self;
        IVec4 { x, y, z, w }
    }
}

/// Mirrors `impl From<glam::IVec4> for (i32, i32, i32, i32)`.
pub impl IVec4IntoI32Tuple of Into<IVec4, (i32, i32, i32, i32)> {
    #[inline(always)]
    fn into(self: IVec4) -> (i32, i32, i32, i32) {
        (self.x, self.y, self.z, self.w)
    }
}

/// Mirrors `impl From<(IVec3, i32)> for glam::IVec4`.
pub impl IVec3I32IntoIVec4 of Into<(IVec3, i32), IVec4> {
    #[inline(always)]
    fn into(self: (IVec3, i32)) -> IVec4 {
        let (v, w) = self;
        IVec4 { x: v.x, y: v.y, z: v.z, w }
    }
}

/// Mirrors `impl From<(i32, IVec3)> for glam::IVec4`.
pub impl I32IVec3IntoIVec4 of Into<(i32, IVec3), IVec4> {
    #[inline(always)]
    fn into(self: (i32, IVec3)) -> IVec4 {
        let (x, v) = self;
        IVec4 { x, y: v.x, z: v.y, w: v.z }
    }
}

/// Mirrors `impl From<(IVec2, i32, i32)> for glam::IVec4`.
pub impl IVec2I32I32IntoIVec4 of Into<(IVec2, i32, i32), IVec4> {
    #[inline(always)]
    fn into(self: (IVec2, i32, i32)) -> IVec4 {
        let (v, z, w) = self;
        IVec4 { x: v.x, y: v.y, z, w }
    }
}

/// Mirrors `impl From<(IVec2, IVec2)> for glam::IVec4`.
pub impl IVec2IVec2IntoIVec4 of Into<(IVec2, IVec2), IVec4> {
    #[inline(always)]
    fn into(self: (IVec2, IVec2)) -> IVec4 {
        let (v, u) = self;
        IVec4 { x: v.x, y: v.y, z: u.x, w: u.y }
    }
}

/// `true` maps to 1 and `false` to 0.
///
/// Mirrors `impl From<BVec4> for glam::IVec4`.
pub impl BVec4IntoIVec4 of Into<BVec4, IVec4> {
    #[inline(always)]
    fn into(self: BVec4) -> IVec4 {
        IVec4 {
            x: if self.x {
                1
            } else {
                0
            },
            y: if self.y {
                1
            } else {
                0
            },
            z: if self.z {
                1
            } else {
                0
            },
            w: if self.w {
                1
            } else {
                0
            },
        }
    }
}

/// Checked conversion: `None` if an element does not fit `i32`.
///
/// Mirrors `impl TryFrom<UVec4> for glam::IVec4`.
pub impl UVec4TryIntoIVec4 of TryInto<UVec4, IVec4> {
    #[inline(always)]
    fn try_into(self: UVec4) -> Option<IVec4> {
        Some(
            IVec4 {
                x: self.x.try_into()?,
                y: self.y.try_into()?,
                z: self.z.try_into()?,
                w: self.w.try_into()?,
            },
        )
    }
}

/// `2^n`. Shifts are a multiplication / division by a power of two taken from a jump table
/// (a runtime `pow(2, n)` costs ~10 000 gas more, a `const` array lookup ~200 more).
#[inline(always)]
fn pow2(n: u32) -> u32 {
    match n {
        0 => 0x1,
        1 => 0x2,
        2 => 0x4,
        3 => 0x8,
        4 => 0x10,
        5 => 0x20,
        6 => 0x40,
        7 => 0x80,
        8 => 0x100,
        9 => 0x200,
        10 => 0x400,
        11 => 0x800,
        12 => 0x1000,
        13 => 0x2000,
        14 => 0x4000,
        15 => 0x8000,
        16 => 0x10000,
        17 => 0x20000,
        18 => 0x40000,
        19 => 0x80000,
        20 => 0x100000,
        21 => 0x200000,
        22 => 0x400000,
        23 => 0x800000,
        24 => 0x1000000,
        25 => 0x2000000,
        26 => 0x4000000,
        27 => 0x8000000,
        28 => 0x10000000,
        29 => 0x20000000,
        30 => 0x40000000,
        31 => 0x80000000,
        _ => core::panic_with_felt252('IVec4: shift overflow'),
    }
}

/// `(a << n) mod 2^32` with `p = 2^n`: widening multiplication, then the low 32 bits.
#[inline(always)]
fn shl_u32(a: u32, p: u32) -> u32 {
    let (_, lo) = DivRem::div_rem(a.wide_mul(p), 0x100000000);
    lo.try_into().unwrap()
}

/// Two's complement reinterpretation. `i32_diff(a, 0)` is `Ok(a)` when `a >= 0` and
/// `Err(2^32 + a)` otherwise: exactly the wrapped value in both cases, in one libfunc.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn i32_as_u32(a: i32) -> u32 {
    match i32_diff(a, 0) {
        Ok(v) | Err(v) => v,
    }
}

/// Two's complement reinterpretation: `a - 2^32` when `a >= 2^31`.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn u32_as_i32(a: u32) -> i32 {
    match a.try_into() {
        Some(v) => v,
        None => {
            let f: felt252 = a.into();
            (f - 0x100000000).try_into().unwrap()
        },
    }
}

/// `|a - b|` as a `u32` (never overflows). `i32_diff` yields `a - b` directly when `a >= b`.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn abs_diff_i32(a: i32, b: i32) -> u32 {
    match i32_diff(a, b) {
        Ok(d) => d,
        Err(_) => match i32_diff(b, a) {
            Ok(d) | Err(d) => d,
        },
    }
}

/// The `i32 -> u32` downcast is the cheapest sign test (one range check, against a full
/// `i32_diff` for `a < 0`).
#[allow(manual_unwrap_or)]
#[inline(always)]
fn abs_i32(a: i32) -> i32 {
    match TryInto::<i32, u32>::try_into(a) {
        Some(_) => a,
        None => -a,
    }
}

/// Zero first (an equality costs no range check), then the downcast sign test of `abs_i32`.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn signum_i32(a: i32) -> i32 {
    if a == 0 {
        0
    } else {
        match TryInto::<i32, u32>::try_into(a) {
            Some(_) => 1,
            None => -1,
        }
    }
}

/// Euclidean quotient: `a = q * b + r` with `0 <= r < |b|`. Own sign / magnitude split
/// (`i32_diff`), one unsigned `DivRem` on `|a| = Q * |b| + R`, signed rebuild: cheaper than the
/// corelib signed `DivRem` followed by the fix-up of Rust's `i32::div_euclid`.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn div_euclid_i32(a: i32, b: i32) -> i32 {
    let (mb, nb) = match i32_diff(b, 0) {
        Ok(m) => (m, false),
        Err(_) => (abs_diff_i32(0, b), true),
    };
    let d: NonZero<u32> = mb.try_into().expect('Division by 0');
    match i32_diff(a, 0) {
        Ok(ma) => {
            let (q, _) = DivRem::div_rem(ma, d);
            let q: i32 = q.try_into().unwrap();
            if nb {
                -q
            } else {
                q
            }
        },
        Err(_) => {
            let (q, r) = DivRem::div_rem(abs_diff_i32(0, a), d);
            let q: felt252 = if r == 0 {
                q.into()
            } else {
                q.into() + 1
            };
            if nb {
                q.try_into().expect('attempt to divide with overflow')
            } else {
                (-q).try_into().unwrap()
            }
        },
    }
}

/// Euclidean remainder, `0 <= r < |b|`: `R` when `a >= 0`, else `|b| - R` (or 0), with
/// `|a| = Q * |b| + R` from one unsigned `DivRem`.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn rem_euclid_i32(a: i32, b: i32) -> i32 {
    let mb = abs_diff_i32(b, 0);
    let d: NonZero<u32> = mb.try_into().expect('Division by 0');
    match i32_diff(a, 0) {
        Ok(ma) => {
            let (_, r) = DivRem::div_rem(ma, d);
            r.try_into().unwrap()
        },
        Err(_) => {
            let (_, r) = DivRem::div_rem(abs_diff_i32(0, a), d);
            if r == 0 {
                0
            } else {
                (mb - r).try_into().unwrap()
            }
        },
    }
}

#[inline(always)]
fn checked_mul_i32(a: i32, b: i32) -> Option<i32> {
    a.wide_mul(b).try_into()
}

/// `None` for a zero divisor and for `i32::MIN / -1`.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn checked_div_i32(a: i32, b: i32) -> Option<i32> {
    match TryInto::<i32, NonZero<i32>>::try_into(b) {
        Some(d) => {
            if b == -1 && a == -0x80000000 {
                None
            } else {
                let (q, _) = DivRem::div_rem(a, d);
                Some(q)
            }
        },
        None => None,
    }
}

/// In range: one downcast. Otherwise the low 32 bits of the 64-bit product, reinterpreted as an
/// `i32`: adding `2^63` (a multiple of `2^32`) makes the product non-negative without changing
/// its low half.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn wrapping_mul_i32(a: i32, b: i32) -> i32 {
    let p = a.wide_mul(b);
    match p.try_into() {
        Some(v) => v,
        None => {
            let p: felt252 = p.into();
            let p: u64 = (p + 0x8000000000000000).try_into().unwrap();
            let (_, lo) = DivRem::div_rem(p, 0x100000000);
            u32_as_i32(lo.try_into().unwrap())
        },
    }
}

#[allow(manual_unwrap_or)]
#[inline(always)]
fn saturating_mul_i32(a: i32, b: i32) -> i32 {
    let p = a.wide_mul(b);
    match p.try_into() {
        Some(v) => v,
        None => if p < 0 {
            -0x80000000
        } else {
            0x7fffffff
        },
    }
}

/// `i32::MIN / -1` wraps to `i32::MIN`.
#[inline(always)]
fn wrapping_div_i32(a: i32, b: i32) -> i32 {
    if b == -1 && a == -0x80000000 {
        a
    } else {
        a / b
    }
}

/// `i32::MIN / -1` saturates to `i32::MAX`.
#[inline(always)]
fn saturating_div_i32(a: i32, b: i32) -> i32 {
    if b == -1 && a == -0x80000000 {
        0x7fffffff
    } else {
        a / b
    }
}

#[inline(always)]
fn checked_add_unsigned(a: i32, b: u32) -> Option<i32> {
    let s: felt252 = a.into() + b.into();
    s.try_into()
}

#[inline(always)]
fn checked_sub_unsigned(a: i32, b: u32) -> Option<i32> {
    let s: felt252 = a.into() - b.into();
    s.try_into()
}

/// `a + b < 2^31 + 2^32`: at most one wrap, downward.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn wrapping_add_unsigned(a: i32, b: u32) -> i32 {
    let s: felt252 = a.into() + b.into();
    match s.try_into() {
        Some(v) => v,
        None => (s - 0x100000000).try_into().unwrap(),
    }
}

/// `a - b >= -2^31 - 2^32 + 1`: at most one wrap, upward.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn wrapping_sub_unsigned(a: i32, b: u32) -> i32 {
    let s: felt252 = a.into() - b.into();
    match s.try_into() {
        Some(v) => v,
        None => (s + 0x100000000).try_into().unwrap(),
    }
}

#[allow(manual_unwrap_or)]
#[inline(always)]
fn saturating_add_unsigned(a: i32, b: u32) -> i32 {
    let s: felt252 = a.into() + b.into();
    match s.try_into() {
        Some(v) => v,
        None => 0x7fffffff,
    }
}

#[allow(manual_unwrap_or)]
#[inline(always)]
fn saturating_sub_unsigned(a: i32, b: u32) -> i32 {
    let s: felt252 = a.into() - b.into();
    match s.try_into() {
        Some(v) => v,
        None => -0x80000000,
    }
}

/// Two's complement left shift: reinterpret, shift the `u32`, reinterpret back.
#[inline(always)]
fn shl_i32(a: i32, p: u32) -> i32 {
    u32_as_i32(shl_u32(i32_as_u32(a), p))
}

/// Arithmetic right shift, `floor(a / p)`: bias `a` by `2^31` to make it unsigned
/// (`i32_diff(a, MIN)` is always `Ok(a + 2^31)`), divide, remove the bias `2^31 / p`.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn shr_i32(a: i32, p: NonZero<u32>, bias: felt252) -> i32 {
    let u = match i32_diff(a, -0x80000000) {
        Ok(v) | Err(v) => v,
    };
    let (q, _) = DivRem::div_rem(u, p);
    (q.into() - bias).try_into().unwrap()
}

/// Bitwise `&` of the two's complement representations (one bitwise builtin cell).
#[inline(always)]
fn bitand_i32(a: i32, b: i32) -> i32 {
    u32_as_i32(i32_as_u32(a) & i32_as_u32(b))
}

/// Bitwise `|` of the two's complement representations (one bitwise builtin cell).
#[inline(always)]
fn bitor_i32(a: i32, b: i32) -> i32 {
    u32_as_i32(i32_as_u32(a) | i32_as_u32(b))
}

/// Bitwise `^` of the two's complement representations (one bitwise builtin cell).
#[inline(always)]
fn bitxor_i32(a: i32, b: i32) -> i32 {
    u32_as_i32(i32_as_u32(a) ^ i32_as_u32(b))
}
