// GENERATED by tools/codegen/fmat.py - do not edit by hand.
//! Port of glam-rs `f32/mat4.rs` @ 0.33.8 on the Q32.32 scalar: a column major 4x4
//! `fixed::Fixed` matrix whose columns are `Vec4`.
//!
//! The three fixed-point matrix modules are generated from one template
//! (`tools/codegen/fmat.py`), as in glam-rs. Every product goes through a fused kernel of
//! `fixed::wide` (one rescale per output scalar, docs/DESIGN.md section 2.1) and every
//! formulation is the cheapest of the candidates measured in `gas/mat4.snap`; the losing
//! candidates live in `benches::alt::mat4`.
//!
//! There is no NaN and no infinity: overflow, division by zero and the inversion of a singular
//! matrix panic (docs/DESIGN.md section 3).

use core::ops::{AddAssign, DivAssign, MulAssign, SubAssign};
use fixed::fixed::{Fixed, FixedTrait};
use fixed::trig::TrigTrait;
use fixed::wide::{
    RecipTrait, WideAdd, WideLift, WideMul, WideNarrow, WideSub, dot3, dot3_add, dot4, mul_sub,
    wide_from, wide_mul,
};
use crate::affine3::Affine3;
use crate::mat3::{Mat3, Mat3Trait};
use crate::quat::{Quat, QuatTrait};
use crate::vec3::{Vec3, Vec3Trait};
use crate::vec4::{Vec4, Vec4Trait};

/// A column major 4x4 matrix of Q32.32 fixed-point scalars.
///
/// Mirrors `glam::Mat4`.
/// #### Deviations
/// * `Debug` is the derived Cairo formatting; `Display` is not implemented.
/// * No `NAN` const and no `is_nan` / `is_finite`: those values do not exist
///   (docs/DESIGN.md section 3).
/// * Not ported: `col_mut` / `set_row` (no `&mut`), `from_cols_slice` / `from_rows_slice` /
///   `write_cols_to_slice` (no `Span` in fixed-size math), `Sum` / `Product` (no iterator trait
///   to implement), the by-reference operator overloads, the scalar-on-the-left operators
///   (`2.0 * m`) and the casts to types that do not exist in glam.cairo (`as_dmat4`, `Mat3A`).
/// * `from_euler` / `to_euler` are the extension trait `glam::euler::Mat4EulerTrait`.
/// * The projection matrices (`perspective_*`, `orthographic_*`, `frustum_*`, deprecated in
///   glam-rs 0.33.1 in favour of `glam::camera`) are not ported yet: see
///   `docs/PORTING_STATUS.md`.
#[derive(Copy, Drop, Serde, PartialEq, Debug, Hash)]
pub struct Mat4 {
    pub x_axis: Vec4,
    pub y_axis: Vec4,
    pub z_axis: Vec4,
    pub w_axis: Vec4,
}

/// Creates a 4x4 matrix from 4 column vectors.
///
/// Mirrors `glam::mat4`.
/// #### Panics
/// * Never.
/// #### Deviations
/// * None.
#[inline(always)]
pub fn mat4(x_axis: Vec4, y_axis: Vec4, z_axis: Vec4, w_axis: Vec4) -> Mat4 {
    Mat4 { x_axis, y_axis, z_axis, w_axis }
}

pub trait Mat4Trait {
    /// A matrix with all elements set to `0`.
    ///
    /// Mirrors `glam::Mat4::ZERO`.
    const ZERO: Mat4;
    /// The identity matrix: all diagonal elements are `1` and all off-diagonal elements are `0`.
    ///
    /// Mirrors `glam::Mat4::IDENTITY`.
    const IDENTITY: Mat4;
    /// Creates a 4x4 matrix from 4 column vectors.
    ///
    /// Mirrors `glam::Mat4::from_cols`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn from_cols(x_axis: Vec4, y_axis: Vec4, z_axis: Vec4, w_axis: Vec4) -> Mat4;
    /// Creates a 4x4 matrix from 4 row vectors.
    ///
    /// Matrices are stored in column major order, so the given rows are permuted into the
    /// matrix layout. Use `from_cols` instead when the data is already in column major
    /// order.
    ///
    /// Mirrors `glam::Mat4::from_rows`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn from_rows(row0: Vec4, row1: Vec4, row2: Vec4, row3: Vec4) -> Mat4;
    /// Creates a 4x4 matrix from a `[Fixed; 16]` array stored in column major order.
    ///
    /// If the data is in row major order use `from_rows_array` instead.
    ///
    /// Mirrors `glam::Mat4::from_cols_array`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn from_cols_array(m: [Fixed; 16]) -> Mat4;
    /// Creates a `[Fixed; 16]` array storing data in column major order.
    ///
    /// If you require the data in row major order use `to_rows_array` instead.
    ///
    /// Mirrors `glam::Mat4::to_cols_array`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn to_cols_array(self: Mat4) -> [Fixed; 16];
    /// Creates a 4x4 matrix from a `[Fixed; 16]` array stored in row major order.
    ///
    /// Matrices are stored in column major order, so the array is permuted into the matrix
    /// layout.
    ///
    /// Mirrors `glam::Mat4::from_rows_array`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn from_rows_array(m: [Fixed; 16]) -> Mat4;
    /// Creates a `[Fixed; 16]` array storing data in row major order.
    ///
    /// Mirrors `glam::Mat4::to_rows_array`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn to_rows_array(self: Mat4) -> [Fixed; 16];
    /// Creates a 4x4 matrix from a `[[Fixed; 4]; 4]` 2D array stored in column major
    /// order.
    ///
    /// If the data is in row major order `transpose` the returned matrix.
    ///
    /// Mirrors `glam::Mat4::from_cols_array_2d`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn from_cols_array_2d(m: [[Fixed; 4]; 4]) -> Mat4;
    /// Creates a `[[Fixed; 4]; 4]` 2D array storing data in column major order.
    ///
    /// If you require row major order `transpose` the matrix first.
    ///
    /// Mirrors `glam::Mat4::to_cols_array_2d`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn to_cols_array_2d(self: Mat4) -> [[Fixed; 4]; 4];
    /// Creates a 4x4 matrix with its diagonal set to `diagonal` and all other entries set
    /// to 0.
    ///
    /// Mirrors `glam::Mat4::from_diagonal`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn from_diagonal(diagonal: Vec4) -> Mat4;
    /// Returns the diagonal of `self`.
    ///
    /// Mirrors `glam::Mat4::diagonal`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn diagonal(self: Mat4) -> Vec4;
    /// Returns the matrix column for the given `index`.
    ///
    /// Mirrors `glam::Mat4::col`.
    /// #### Panics
    /// * `'Mat4: index out of bounds'` if `index` is greater than 3.
    /// #### Deviations
    /// * `col_mut` is not ported: there is no `&mut` in Cairo.
    fn col(self: Mat4, index: usize) -> Vec4;
    /// Returns the matrix row for the given `index`.
    ///
    /// Mirrors `glam::Mat4::row`.
    /// #### Panics
    /// * `'Mat4: index out of bounds'` if `index` is greater than 3.
    /// #### Deviations
    /// * `set_row` is not ported: there is no `&mut` in Cairo.
    fn row(self: Mat4, index: usize) -> Vec4;
    /// Returns the transpose of `self`.
    ///
    /// Exact: a permutation of the elements.
    ///
    /// Mirrors `glam::Mat4::transpose`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn transpose(self: Mat4) -> Mat4;
    /// Returns the determinant of `self`.
    ///
    /// Mirrors `glam::Mat4::determinant`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * Laplace expansion on the six 2x2 minors of the last two columns (glam-rs `a2323`
    ///   .. `a0123`): each minor is one fused `mul_sub` (floored, at most 1 ULP below the
    ///   exact value), the four 3x3 cofactors stay exact at the Q64.64 scale and their
    ///   products with the first column are summed at the Q96.96 scale and rescaled once.
    ///   The error is therefore at most `sum |m0i * m1j| + 1` ULP.
    /// * Quadruple products do not fit a felt252 (docs/DESIGN.md section 2.1), so the 2x2
    ///   minors cannot stay wide: those six rescales are what makes a 4x4 determinant
    ///   expressible.
    fn determinant(self: Mat4) -> Fixed;
    /// Transforms a 4D vector.
    ///
    /// Mirrors `glam::Mat4::mul_vec4`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One `dot4` fused kernel per element of the result: the exact Q64.64 sum of the 4
    ///   products is rescaled once (floored), so no intermediate term can overflow and the
    ///   element is at most 1 ULP below the exact value.
    fn mul_vec4(self: Mat4, rhs: Vec4) -> Vec4;
    /// Transforms a 4D vector by the transpose of `self`.
    ///
    /// Mirrors `glam::Mat4::mul_transpose_vec4`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One `dot4` fused kernel per element of the result: the exact Q64.64 sum of the 4
    ///   products is rescaled once (floored), so no intermediate term can overflow and the
    ///   element is at most 1 ULP below the exact value.
    fn mul_transpose_vec4(self: Mat4, rhs: Vec4) -> Vec4;
    /// Multiplies two 4x4 matrices.
    ///
    /// Mirrors `glam::Mat4::mul_mat4`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One `dot4` fused kernel per element of the result: the exact Q64.64 sum of the 4
    ///   products is rescaled once (floored), so no intermediate term can overflow and the
    ///   element is at most 1 ULP below the exact value. The 16 elements are 16 kernels,
    ///   one rescale each.
    /// * glam-rs spells this `self * rhs`; the operator is also implemented (`impl
    ///   Mul<Mat4> for Mat4`).
    fn mul_mat4(self: Mat4, rhs: Mat4) -> Mat4;
    /// Adds two 4x4 matrices.
    ///
    /// Exact.
    ///
    /// Mirrors `glam::Mat4::add_mat4`.
    /// #### Panics
    /// * `'i64_add Overflow'` / `'i64_add Underflow'` if an element sum leaves the scalar
    ///   range.
    /// #### Deviations
    /// * Overflow panics where f32 returns infinity or a larger finite value:
    ///   docs/DESIGN.md section 3, "overflow".
    fn add_mat4(self: Mat4, rhs: Mat4) -> Mat4;
    /// Subtracts two 4x4 matrices.
    ///
    /// Exact.
    ///
    /// Mirrors `glam::Mat4::sub_mat4`.
    /// #### Panics
    /// * `'i64_sub Overflow'` / `'i64_sub Underflow'` if an element difference leaves the
    ///   scalar range.
    /// #### Deviations
    /// * Overflow panics where f32 returns infinity or a larger finite value:
    ///   docs/DESIGN.md section 3, "overflow".
    fn sub_mat4(self: Mat4, rhs: Mat4) -> Mat4;
    /// Multiplies a 4x4 matrix by a scalar.
    ///
    /// Mirrors `glam::Mat4::mul_scalar`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Mul<f32> for Mat4`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    /// * The product is floored (one rescale per element), not rounded to nearest: at most
    ///   1 ULP below the exact result.
    fn mul_scalar(self: Mat4, rhs: Fixed) -> Mat4;
    /// Divides a 4x4 matrix by a scalar.
    ///
    /// One division shared by the 16 elements (`Recip`) and one fused multiplication each,
    /// rounded to nearest: cheaper than, and up to 1 ULP away from, the element-wise
    /// correctly rounded `Fixed / Fixed` kept in `benches::alt`.
    ///
    /// Mirrors `glam::Mat4::div_scalar`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if `rhs` is zero.
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Div<f32> for Mat4`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    fn div_scalar(self: Mat4, rhs: Fixed) -> Mat4;
    /// Multiplies `self` by a scaling vector `scale`. This is faster than creating a whole
    /// diagonal scaling matrix and then multiplying that. This operation is commutative.
    ///
    /// Mirrors `glam::Mat4::mul_diagonal_scale`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * The product is floored (one rescale per element), not rounded to nearest: at most
    ///   1 ULP below the exact result.
    fn mul_diagonal_scale(self: Mat4, scale: Vec4) -> Mat4;
    /// Returns the inverse of `self`.
    ///
    /// If the matrix is not invertible this function panics.
    ///
    /// Mirrors `glam::Mat4::inverse`.
    /// #### Panics
    /// * `'Mat4: singular'` if the determinant of `self` is zero.
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * glam-rs returns an invalid matrix (`glam_assert!` only) when the determinant is
    ///   zero; there is no NaN here, so a singular matrix panics (docs/DESIGN.md section
    ///   3).
    /// * One division shared by the 16 elements of the adjugate (`Recip`, rounded to
    ///   nearest) instead of one per element: the exact `x / det` whenever it is
    ///   representable.
    /// * The adjugate is 18 fused 2x2 minors (one floor rescale each) and 16 exact Q64.64
    ///   cofactor sums (one rescale each); the determinant is the expansion of
    ///   `determinant` on the same minors, so `inverse` is singular exactly when
    ///   `determinant` is zero.
    fn inverse(self: Mat4) -> Mat4;
    /// Returns the inverse of `self` or `None` if the matrix is not invertible.
    ///
    /// Mirrors `glam::Mat4::try_inverse`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One division shared by the 16 elements of the adjugate (`Recip`, rounded to
    ///   nearest) instead of one per element: the exact `x / det` whenever it is
    ///   representable.
    /// * The adjugate is 18 fused 2x2 minors (one floor rescale each) and 16 exact Q64.64
    ///   cofactor sums (one rescale each); the determinant is the expansion of
    ///   `determinant` on the same minors, so `inverse` is singular exactly when
    ///   `determinant` is zero.
    fn try_inverse(self: Mat4) -> Option<Mat4>;
    /// Returns the inverse of `self` or `Mat4::ZERO` if the matrix is not invertible.
    ///
    /// Mirrors `glam::Mat4::inverse_or_zero`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One division shared by the 16 elements of the adjugate (`Recip`, rounded to
    ///   nearest) instead of one per element: the exact `x / det` whenever it is
    ///   representable.
    /// * The adjugate is 18 fused 2x2 minors (one floor rescale each) and 16 exact Q64.64
    ///   cofactor sums (one rescale each); the determinant is the expansion of
    ///   `determinant` on the same minors, so `inverse` is singular exactly when
    ///   `determinant` is zero.
    fn inverse_or_zero(self: Mat4) -> Mat4;
    /// Takes the absolute value of each element in `self`.
    ///
    /// Mirrors `glam::Mat4::abs`.
    /// #### Panics
    /// * `'Fixed: overflow'` if an element is `Fixed::MIN`.
    /// #### Deviations
    /// * Overflow panics where f32 returns the finite value `2^31`: docs/DESIGN.md section
    ///   3, "overflow".
    fn abs(self: Mat4) -> Mat4;
    /// Returns a matrix containing the reciprocal `1 / n` of each element of `self`.
    ///
    /// Mirrors `glam::Mat4::recip`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if an element is zero.
    /// * `'Fixed: overflow'` if an element is `1` or `2` raw (the reciprocal does not
    ///   fit).
    /// #### Deviations
    /// * There is no NaN nor infinity: the operation panics instead of producing one.
    fn recip(self: Mat4) -> Mat4;
    /// Returns true if the absolute difference of all elements between `self` and `rhs` is
    /// less than or equal to `max_abs_diff`.
    ///
    /// This can be used to compare if two matrices contain similar elements.
    ///
    /// Mirrors `glam::Mat4::abs_diff_eq`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * The differences are computed exactly on 65 bits: unlike `(self - rhs).abs()` it
    ///   never overflows.
    fn abs_diff_eq(self: Mat4, rhs: Mat4, max_abs_diff: Fixed) -> bool;
    /// Multiplies this matrix by a 3D affine transform.
    ///
    /// Mirrors `impl Mul<Affine3> for glam::Mat4`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * Cairo's core `Mul` is homogeneous, so the heterogeneous operator is named
    ///   `mul_affine3`.
    /// * The affine transform is embedded with the exact 4th row `(0, 0, 0, 1)`, then the
    ///   fused `Mat4` product is used.
    fn mul_affine3(self: Mat4, rhs: Affine3) -> Mat4;
    /// Creates an affine transformation matrix from the given 3x3 linear transformation
    /// matrix.
    ///
    /// The resulting matrix can be used to transform 3D points and vectors. See
    /// `transform_point3` and `transform_vector3`.
    ///
    /// Exact.
    ///
    /// Mirrors `glam::Mat4::from_mat3`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn from_mat3(m: Mat3) -> Mat4;
    /// Creates an affine transformation matrix from the given 3x3 linear transformation
    /// matrix and `translation` vector.
    ///
    /// The resulting matrix can be used to transform 3D points and vectors. See
    /// `transform_point3` and `transform_vector3`.
    ///
    /// Exact.
    ///
    /// Mirrors `glam::Mat4::from_mat3_translation`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn from_mat3_translation(mat3: Mat3, translation: Vec3) -> Mat4;
    /// Creates an affine transformation matrix from the given 3D `translation`.
    ///
    /// The resulting matrix can be used to transform 3D points and vectors. See
    /// `transform_point3` and `transform_vector3`.
    ///
    /// Exact.
    ///
    /// Mirrors `glam::Mat4::from_translation`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn from_translation(translation: Vec3) -> Mat4;
    /// Creates an affine transformation matrix containing the given 3D non-uniform
    /// `scale`.
    ///
    /// The resulting matrix can be used to transform 3D points and vectors. See
    /// `transform_point3` and `transform_vector3`.
    ///
    /// Exact.
    ///
    /// Mirrors `glam::Mat4::from_scale`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3). glam-
    ///   rs asserts that `scale` is not entirely zero.
    fn from_scale(scale: Vec3) -> Mat4;
    /// Creates an affine transformation matrix from the given `rotation` quaternion.
    ///
    /// The resulting matrix can be used to transform 3D points and vectors. See
    /// `transform_point3` and `transform_vector3`.
    ///
    /// Every element is one exact two-term sum of raw products rescaled once (floored): `1
    /// - 2 (b^2 + c^2)` on the diagonal, `2 (ab +- cd)` off it, with the doubling folded
    /// into the second factor. Nine rescales for the nine elements, at most 1 ULP below
    /// the exact value each. The literal glam-rs expression rescales the twelve products
    /// one by one and costs 2.1x as much (43 460 against 20 660 gas for `Mat3`): it is
    /// kept in `benches::alt`.
    ///
    /// Mirrors `glam::Mat4::from_quat`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// * `'i64_add Overflow'` / `'i64_add Underflow'` if an element sum leaves the scalar
    ///   range.
    /// #### Deviations
    /// * The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3).
    ///   `rotation` must be normalized: as in glam-rs the elements are the ones of the
    ///   rotation matrix of a unit quaternion, and a quaternion of length `l` scales the
    ///   matrix by `l^2`.
    fn from_quat(rotation: Quat) -> Mat4;
    /// Creates an affine transformation matrix from the given `rotation` quaternion and 3D
    /// `translation`.
    ///
    /// The resulting matrix can be used to transform 3D points and vectors. See
    /// `transform_point3` and `transform_vector3`.
    ///
    /// Every element is one exact two-term sum of raw products rescaled once (floored): `1
    /// - 2 (b^2 + c^2)` on the diagonal, `2 (ab +- cd)` off it, with the doubling folded
    /// into the second factor. Nine rescales for the nine elements, at most 1 ULP below
    /// the exact value each. The literal glam-rs expression rescales the twelve products
    /// one by one and costs 2.1x as much (43 460 against 20 660 gas for `Mat3`): it is
    /// kept in `benches::alt`.
    ///
    /// Mirrors `glam::Mat4::from_rotation_translation`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// * `'i64_add Overflow'` / `'i64_add Underflow'` if an element sum leaves the scalar
    ///   range.
    /// #### Deviations
    /// * The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3).
    ///   `rotation` must be normalized: as in glam-rs the elements are the ones of the
    ///   rotation matrix of a unit quaternion, and a quaternion of length `l` scales the
    ///   matrix by `l^2`.
    fn from_rotation_translation(rotation: Quat, translation: Vec3) -> Mat4;
    /// Creates an affine transformation matrix from the given 3D `scale`, `rotation` and
    /// `translation`.
    ///
    /// The resulting matrix can be used to transform 3D points and vectors. See
    /// `transform_point3` and `transform_vector3`.
    ///
    /// Every element is one exact two-term sum of raw products rescaled once (floored): `1
    /// - 2 (b^2 + c^2)` on the diagonal, `2 (ab +- cd)` off it, with the doubling folded
    /// into the second factor. Nine rescales for the nine elements, at most 1 ULP below
    /// the exact value each. The literal glam-rs expression rescales the twelve products
    /// one by one and costs 2.1x as much (43 460 against 20 660 gas for `Mat3`): it is
    /// kept in `benches::alt`. The scale of column `i` is applied inside the single
    /// rescale of each element (`W2 * Fixed -> T2`), not after it: the elements are still
    /// one floor rescale away from the exact product, where glam-rs rounds the rotation
    /// matrix first and the scaled one second. The nine multiplications are free (21 360
    /// gas, the cost of `from_quat`): a `WideMul` is one step and no range check.
    ///
    /// Mirrors `glam::Mat4::from_scale_rotation_translation`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// * `'i64_add Overflow'` / `'i64_add Underflow'` if an element sum leaves the scalar
    ///   range.
    /// #### Deviations
    /// * The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3).
    ///   `rotation` must be normalized: as in glam-rs the elements are the ones of the
    ///   rotation matrix of a unit quaternion, and a quaternion of length `l` scales the
    ///   matrix by `l^2`.
    fn from_scale_rotation_translation(scale: Vec3, rotation: Quat, translation: Vec3) -> Mat4;
    /// Extracts `scale`, `rotation` and `translation` from `self`.
    ///
    /// The input matrix is expected to be a 3D affine transformation matrix otherwise the
    /// output will be invalid.
    ///
    /// Mirrors `glam::Mat4::to_scale_rotation_translation`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if a column of the linear part is zero.
    /// * `'Fixed: overflow'` if a column length or an element of the determinant does not
    ///   fit the scalar range.
    /// #### Deviations
    /// * The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3). The
    ///   4th row of `self` must be `(0, 0, 0, 1)` and the determinant must not be zero;
    ///   the latter panics here instead (`'Fixed: division by zero'`).
    /// * Never for a negation: the only one is `-length(x_axis)`, never `MIN` (R1 panic-
    ///   coverage audit, escalation 1).
    /// * The sign of the determinant is applied to `scale.x` by negating the length
    ///   (exact) instead of multiplying it by `signum(det)`; `signum(0)` is `+1` as
    ///   everywhere else (docs/DESIGN.md section 3), but a zero determinant means a zero
    ///   column, which panics.
    /// * Each column is divided by its own shared `Recip` (rounded to nearest, one
    ///   division for three components) instead of the `scale.recip()` then `column *
    ///   inv_scale` of glam-rs, which rounds twice. Each length is the floor of the exact
    ///   one, so a normalized column is within `1 / scale` ULP per component.
    /// * The rotation is `Quat::from_rotation_axes` of the normalized columns: its own
    ///   error (a square root and a shared division) adds to the above. Measured over 20
    ///   000 random `(scale, rotation, translation)` triples of the Python mirror, the
    ///   round trip `to_scale_rotation_translation(from_scale_rotation_translation(..))`
    ///   recovers the translation exactly, the rotation within 13 raw ULP per component
    ///   and the scale within `5 |scale| + 2` ULP, the linear term being the drift of the
    ///   squared length of the quantized quaternion.
    fn to_scale_rotation_translation(self: Mat4) -> (Vec3, Quat, Vec3);
    /// Creates an affine transformation matrix containing a 3D rotation around a
    /// normalized rotation `axis` of `angle` (in radians).
    ///
    /// Mirrors `glam::Mat4::from_axis_angle`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3). `axis`
    ///   must be normalized.
    /// * `fixed::trig::sin_cos` is accurate to about 1 ULP over a turn (see its
    ///   documentation); the products that follow add one floor rescale each.
    /// * Every element is one exact triple product plus one exact term, rescaled once
    ///   (floored).
    fn from_axis_angle(axis: Vec3, angle: Fixed) -> Mat4;
    /// Creates an affine transformation matrix containing a 3D rotation around the x axis
    /// of `angle` (in radians).
    ///
    /// Mirrors `glam::Mat4::from_rotation_x`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * `fixed::trig::sin_cos` is accurate to about 1 ULP over a turn (see its
    ///   documentation); the products that follow add one floor rescale each.
    fn from_rotation_x(angle: Fixed) -> Mat4;
    /// Creates an affine transformation matrix containing a 3D rotation around the y axis
    /// of `angle` (in radians).
    ///
    /// Mirrors `glam::Mat4::from_rotation_y`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * `fixed::trig::sin_cos` is accurate to about 1 ULP over a turn (see its
    ///   documentation); the products that follow add one floor rescale each.
    fn from_rotation_y(angle: Fixed) -> Mat4;
    /// Creates an affine transformation matrix containing a 3D rotation around the z axis
    /// of `angle` (in radians).
    ///
    /// Mirrors `glam::Mat4::from_rotation_z`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * `fixed::trig::sin_cos` is accurate to about 1 ULP over a turn (see its
    ///   documentation); the products that follow add one floor rescale each.
    fn from_rotation_z(angle: Fixed) -> Mat4;
    /// Transforms the given 3D vector as a point.
    ///
    /// This is the equivalent of multiplying the 3D vector as a 4D vector where `w` is
    /// `1`.
    ///
    /// This method assumes that `self` contains a valid affine transform. It does not
    /// perform a perspective divide: use `project_point3` for a projective transform.
    ///
    /// Mirrors `glam::Mat4::transform_point3`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3). The
    ///   4th row of `self` must be `(0, 0, 0, 1)`.
    /// * One `dot3_add` fused kernel per element: the translation is added exactly inside
    ///   the single rescale, so the result is at most 1 ULP below the exact value.
    fn transform_point3(self: Mat4, rhs: Vec3) -> Vec3;
    /// Transforms the given 3D vector as a direction.
    ///
    /// This is the equivalent of multiplying the 3D vector as a 4D vector where `w` is
    /// `0`.
    ///
    /// This method assumes that `self` contains a valid affine transform.
    ///
    /// Mirrors `glam::Mat4::transform_vector3`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3). The
    ///   4th row of `self` must be `(0, 0, 0, 1)`.
    /// * One `dot3` fused kernel per element of the result: the exact Q64.64 sum of the 3
    ///   products is rescaled once (floored), so no intermediate term can overflow and the
    ///   element is at most 1 ULP below the exact value.
    fn transform_vector3(self: Mat4, rhs: Vec3) -> Vec3;
    /// Transforms the given 3D vector as a point, applying perspective correction.
    ///
    /// This is the equivalent of multiplying the 3D vector as a 4D vector where `w` is
    /// `1`. The perspective divide is performed, meaning the resulting 3D vector is
    /// divided by `w`.
    ///
    /// This method assumes that `self` contains a projective transform.
    ///
    /// Mirrors `glam::Mat4::project_point3`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if the projected `w` is zero.
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One division shared by the three components (`Recip`, rounded to nearest) instead
    ///   of the three of `res / res.w`.
    /// * Each numerator is one `dot3_add` fused kernel (one floor rescale), so the result
    ///   is within `1 / |w|` ULP of the exact projection plus the rounding of the shared
    ///   division.
    fn project_point3(self: Mat4, rhs: Vec3) -> Vec3;
    /// Creates a right-handed view matrix using a camera position, a facing direction and
    /// an up direction.
    ///
    /// For a view coordinate system with `+X=right`, `+Y=up` and `+Z=back`.
    ///
    /// Mirrors `glam::Mat4::look_to_rh`.
    /// #### Panics
    /// * `'Vec3: normalize zero'` if `dir` and `up` are parallel.
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// * `'i64_neg Underflow'` if an element is `MIN`.
    /// #### Deviations
    /// * The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3). `dir`
    ///   and `up` must be normalized.
    /// * Deprecated in glam-rs 0.33.1 in favour of `glam::camera`, which is not ported yet
    ///   (task C1 of `docs/PLAN.md`); the name and the layout are the ones of
    ///   `Mat4::look_to_rh`.
    /// * `s` is normalized (one square root, one shared division, rounded to nearest) and
    ///   every other element is exact or one floored `dot3`.
    fn look_to_rh(eye: Vec3, dir: Vec3, up: Vec3) -> Mat4;
    /// Creates a left-handed view matrix using a camera position, a facing direction and
    /// an up direction.
    ///
    /// For a view coordinate system with `+X=right`, `+Y=up` and `+Z=forward`.
    ///
    /// Mirrors `glam::Mat4::look_to_lh`.
    /// #### Panics
    /// * `'Vec3: normalize zero'` if `dir` and `up` are parallel.
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// * `'i64_neg Underflow'` if an element is `MIN`.
    /// #### Deviations
    /// * The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3). `dir`
    ///   and `up` must be normalized.
    /// * Deprecated in glam-rs 0.33.1 in favour of `glam::camera`, which is not ported yet
    ///   (task C1 of `docs/PLAN.md`); the name and the layout are the ones of
    ///   `Mat4::look_to_rh`.
    /// * `s` is normalized (one square root, one shared division, rounded to nearest) and
    ///   every other element is exact or one floored `dot3`.
    fn look_to_lh(eye: Vec3, dir: Vec3, up: Vec3) -> Mat4;
    /// Creates a right-handed view matrix using a camera position, a focal point and an up
    /// direction.
    ///
    /// For a view coordinate system with `+X=right`, `+Y=up` and `+Z=back`.
    ///
    /// Mirrors `glam::Mat4::look_at_rh`.
    /// #### Panics
    /// * `'Vec3: normalize zero'` if `center` is `eye`, or if the direction and `up` are
    ///   parallel.
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// * `'i64_neg Underflow'` if an element is `MIN`.
    /// * `'i64_sub Overflow'` / `'i64_sub Underflow'` if an element difference leaves the
    ///   scalar range.
    /// #### Deviations
    /// * The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3). `dir`
    ///   and `up` must be normalized.
    /// * Deprecated in glam-rs 0.33.1 in favour of `glam::camera`, which is not ported yet
    ///   (task C1 of `docs/PLAN.md`); the name and the layout are the ones of
    ///   `Mat4::look_to_rh`.
    /// * `s` is normalized (one square root, one shared division, rounded to nearest) and
    ///   every other element is exact or one floored `dot3`.
    fn look_at_rh(eye: Vec3, center: Vec3, up: Vec3) -> Mat4;
    /// Creates a left-handed view matrix using a camera position, a focal point and an up
    /// direction.
    ///
    /// For a view coordinate system with `+X=right`, `+Y=up` and `+Z=forward`.
    ///
    /// Mirrors `glam::Mat4::look_at_lh`.
    /// #### Panics
    /// * `'Vec3: normalize zero'` if `center` is `eye`, or if the direction and `up` are
    ///   parallel.
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// * `'i64_neg Underflow'` if an element is `MIN`.
    /// * `'i64_sub Overflow'` / `'i64_sub Underflow'` if an element difference leaves the
    ///   scalar range.
    /// #### Deviations
    /// * The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3). `dir`
    ///   and `up` must be normalized.
    /// * Deprecated in glam-rs 0.33.1 in favour of `glam::camera`, which is not ported yet
    ///   (task C1 of `docs/PLAN.md`); the name and the layout are the ones of
    ///   `Mat4::look_to_rh`.
    /// * `s` is normalized (one square root, one shared division, rounded to nearest) and
    ///   every other element is exact or one floored `dot3`.
    fn look_at_lh(eye: Vec3, center: Vec3, up: Vec3) -> Mat4;
}

pub impl Mat4Impl of Mat4Trait {
    const ZERO: Mat4 = Mat4 {
        x_axis: Vec4 {
            x: Fixed { raw: 0 }, y: Fixed { raw: 0 }, z: Fixed { raw: 0 }, w: Fixed { raw: 0 },
        },
        y_axis: Vec4 {
            x: Fixed { raw: 0 }, y: Fixed { raw: 0 }, z: Fixed { raw: 0 }, w: Fixed { raw: 0 },
        },
        z_axis: Vec4 {
            x: Fixed { raw: 0 }, y: Fixed { raw: 0 }, z: Fixed { raw: 0 }, w: Fixed { raw: 0 },
        },
        w_axis: Vec4 {
            x: Fixed { raw: 0 }, y: Fixed { raw: 0 }, z: Fixed { raw: 0 }, w: Fixed { raw: 0 },
        },
    };
    const IDENTITY: Mat4 = Mat4 {
        x_axis: Vec4 {
            x: Fixed { raw: 0x100000000 },
            y: Fixed { raw: 0 },
            z: Fixed { raw: 0 },
            w: Fixed { raw: 0 },
        },
        y_axis: Vec4 {
            x: Fixed { raw: 0 },
            y: Fixed { raw: 0x100000000 },
            z: Fixed { raw: 0 },
            w: Fixed { raw: 0 },
        },
        z_axis: Vec4 {
            x: Fixed { raw: 0 },
            y: Fixed { raw: 0 },
            z: Fixed { raw: 0x100000000 },
            w: Fixed { raw: 0 },
        },
        w_axis: Vec4 {
            x: Fixed { raw: 0 },
            y: Fixed { raw: 0 },
            z: Fixed { raw: 0 },
            w: Fixed { raw: 0x100000000 },
        },
    };

    #[inline(always)]
    fn from_cols(x_axis: Vec4, y_axis: Vec4, z_axis: Vec4, w_axis: Vec4) -> Mat4 {
        Mat4 { x_axis, y_axis, z_axis, w_axis }
    }

    #[inline(always)]
    fn from_rows(row0: Vec4, row1: Vec4, row2: Vec4, row3: Vec4) -> Mat4 {
        Mat4 {
            x_axis: Vec4 { x: row0.x, y: row1.x, z: row2.x, w: row3.x },
            y_axis: Vec4 { x: row0.y, y: row1.y, z: row2.y, w: row3.y },
            z_axis: Vec4 { x: row0.z, y: row1.z, z: row2.z, w: row3.z },
            w_axis: Vec4 { x: row0.w, y: row1.w, z: row2.w, w: row3.w },
        }
    }

    #[inline(always)]
    fn from_cols_array(m: [Fixed; 16]) -> Mat4 {
        let [m00, m01, m02, m03, m10, m11, m12, m13, m20, m21, m22, m23, m30, m31, m32, m33] = m;
        Mat4 {
            x_axis: Vec4 { x: m00, y: m01, z: m02, w: m03 },
            y_axis: Vec4 { x: m10, y: m11, z: m12, w: m13 },
            z_axis: Vec4 { x: m20, y: m21, z: m22, w: m23 },
            w_axis: Vec4 { x: m30, y: m31, z: m32, w: m33 },
        }
    }

    #[inline(always)]
    fn to_cols_array(self: Mat4) -> [Fixed; 16] {
        [
            self.x_axis.x, self.x_axis.y, self.x_axis.z, self.x_axis.w, self.y_axis.x,
            self.y_axis.y, self.y_axis.z, self.y_axis.w, self.z_axis.x, self.z_axis.y,
            self.z_axis.z, self.z_axis.w, self.w_axis.x, self.w_axis.y, self.w_axis.z,
            self.w_axis.w,
        ]
    }

    #[inline(always)]
    fn from_rows_array(m: [Fixed; 16]) -> Mat4 {
        let [m00, m01, m02, m03, m10, m11, m12, m13, m20, m21, m22, m23, m30, m31, m32, m33] = m;
        Mat4 {
            x_axis: Vec4 { x: m00, y: m10, z: m20, w: m30 },
            y_axis: Vec4 { x: m01, y: m11, z: m21, w: m31 },
            z_axis: Vec4 { x: m02, y: m12, z: m22, w: m32 },
            w_axis: Vec4 { x: m03, y: m13, z: m23, w: m33 },
        }
    }

    #[inline(always)]
    fn to_rows_array(self: Mat4) -> [Fixed; 16] {
        [
            self.x_axis.x, self.y_axis.x, self.z_axis.x, self.w_axis.x, self.x_axis.y,
            self.y_axis.y, self.z_axis.y, self.w_axis.y, self.x_axis.z, self.y_axis.z,
            self.z_axis.z, self.w_axis.z, self.x_axis.w, self.y_axis.w, self.z_axis.w,
            self.w_axis.w,
        ]
    }

    #[inline(always)]
    fn from_cols_array_2d(m: [[Fixed; 4]; 4]) -> Mat4 {
        let [x_axis, y_axis, z_axis, w_axis] = m;
        Mat4 {
            x_axis: Vec4Trait::from_array(x_axis),
            y_axis: Vec4Trait::from_array(y_axis),
            z_axis: Vec4Trait::from_array(z_axis),
            w_axis: Vec4Trait::from_array(w_axis),
        }
    }

    #[inline(always)]
    fn to_cols_array_2d(self: Mat4) -> [[Fixed; 4]; 4] {
        [
            [self.x_axis.x, self.x_axis.y, self.x_axis.z, self.x_axis.w],
            [self.y_axis.x, self.y_axis.y, self.y_axis.z, self.y_axis.w],
            [self.z_axis.x, self.z_axis.y, self.z_axis.z, self.z_axis.w],
            [self.w_axis.x, self.w_axis.y, self.w_axis.z, self.w_axis.w],
        ]
    }

    #[inline(always)]
    fn from_diagonal(diagonal: Vec4) -> Mat4 {
        Mat4 {
            x_axis: Vec4 {
                x: diagonal.x, y: Fixed { raw: 0 }, z: Fixed { raw: 0 }, w: Fixed { raw: 0 },
            },
            y_axis: Vec4 {
                x: Fixed { raw: 0 }, y: diagonal.y, z: Fixed { raw: 0 }, w: Fixed { raw: 0 },
            },
            z_axis: Vec4 {
                x: Fixed { raw: 0 }, y: Fixed { raw: 0 }, z: diagonal.z, w: Fixed { raw: 0 },
            },
            w_axis: Vec4 {
                x: Fixed { raw: 0 }, y: Fixed { raw: 0 }, z: Fixed { raw: 0 }, w: diagonal.w,
            },
        }
    }

    #[inline(always)]
    fn diagonal(self: Mat4) -> Vec4 {
        Vec4 { x: self.x_axis.x, y: self.y_axis.y, z: self.z_axis.z, w: self.w_axis.w }
    }

    #[inline(always)]
    fn col(self: Mat4, index: usize) -> Vec4 {
        match index {
            0 => self.x_axis,
            1 => self.y_axis,
            2 => self.z_axis,
            3 => self.w_axis,
            _ => core::panic_with_felt252('Mat4: index out of bounds'),
        }
    }

    #[inline(always)]
    fn row(self: Mat4, index: usize) -> Vec4 {
        match index {
            0 => Vec4 { x: self.x_axis.x, y: self.y_axis.x, z: self.z_axis.x, w: self.w_axis.x },
            1 => Vec4 { x: self.x_axis.y, y: self.y_axis.y, z: self.z_axis.y, w: self.w_axis.y },
            2 => Vec4 { x: self.x_axis.z, y: self.y_axis.z, z: self.z_axis.z, w: self.w_axis.z },
            3 => Vec4 { x: self.x_axis.w, y: self.y_axis.w, z: self.z_axis.w, w: self.w_axis.w },
            _ => core::panic_with_felt252('Mat4: index out of bounds'),
        }
    }

    #[inline(always)]
    fn transpose(self: Mat4) -> Mat4 {
        Mat4 {
            x_axis: Vec4 { x: self.x_axis.x, y: self.y_axis.x, z: self.z_axis.x, w: self.w_axis.x },
            y_axis: Vec4 { x: self.x_axis.y, y: self.y_axis.y, z: self.z_axis.y, w: self.w_axis.y },
            z_axis: Vec4 { x: self.x_axis.z, y: self.y_axis.z, z: self.z_axis.z, w: self.w_axis.z },
            w_axis: Vec4 { x: self.x_axis.w, y: self.y_axis.w, z: self.z_axis.w, w: self.w_axis.w },
        }
    }

    #[inline(always)]
    fn determinant(self: Mat4) -> Fixed {
        let coef00 = mul_sub(self.z_axis.z, self.w_axis.w, self.w_axis.z, self.z_axis.w);
        let coef04 = mul_sub(self.z_axis.y, self.w_axis.w, self.w_axis.y, self.z_axis.w);
        let coef08 = mul_sub(self.z_axis.y, self.w_axis.z, self.w_axis.y, self.z_axis.z);
        let coef12 = mul_sub(self.z_axis.x, self.w_axis.w, self.w_axis.x, self.z_axis.w);
        let coef16 = mul_sub(self.z_axis.x, self.w_axis.z, self.w_axis.x, self.z_axis.z);
        let coef20 = mul_sub(self.z_axis.x, self.w_axis.y, self.w_axis.x, self.z_axis.y);
        let q0 = wide_mul(self.y_axis.y, coef00)
            .sub(wide_mul(self.y_axis.z, coef04))
            .add(wide_mul(self.y_axis.w, coef08));
        let q1 = wide_mul(self.y_axis.z, coef12)
            .sub(wide_mul(self.y_axis.x, coef00))
            .sub(wide_mul(self.y_axis.w, coef16));
        let q2 = wide_mul(self.y_axis.x, coef04)
            .sub(wide_mul(self.y_axis.y, coef12))
            .add(wide_mul(self.y_axis.w, coef20));
        let q3 = wide_mul(self.y_axis.y, coef16)
            .sub(wide_mul(self.y_axis.x, coef08))
            .sub(wide_mul(self.y_axis.z, coef20));
        q0
            .mul(self.x_axis.x)
            .add(q1.mul(self.x_axis.y))
            .add(q2.mul(self.x_axis.z))
            .add(q3.mul(self.x_axis.w))
            .narrow()
    }

    #[inline(always)]
    fn mul_vec4(self: Mat4, rhs: Vec4) -> Vec4 {
        Vec4 {
            x: dot4(
                self.x_axis.x,
                rhs.x,
                self.y_axis.x,
                rhs.y,
                self.z_axis.x,
                rhs.z,
                self.w_axis.x,
                rhs.w,
            ),
            y: dot4(
                self.x_axis.y,
                rhs.x,
                self.y_axis.y,
                rhs.y,
                self.z_axis.y,
                rhs.z,
                self.w_axis.y,
                rhs.w,
            ),
            z: dot4(
                self.x_axis.z,
                rhs.x,
                self.y_axis.z,
                rhs.y,
                self.z_axis.z,
                rhs.z,
                self.w_axis.z,
                rhs.w,
            ),
            w: dot4(
                self.x_axis.w,
                rhs.x,
                self.y_axis.w,
                rhs.y,
                self.z_axis.w,
                rhs.z,
                self.w_axis.w,
                rhs.w,
            ),
        }
    }

    #[inline(always)]
    fn mul_transpose_vec4(self: Mat4, rhs: Vec4) -> Vec4 {
        Vec4 {
            x: dot4(
                self.x_axis.x,
                rhs.x,
                self.x_axis.y,
                rhs.y,
                self.x_axis.z,
                rhs.z,
                self.x_axis.w,
                rhs.w,
            ),
            y: dot4(
                self.y_axis.x,
                rhs.x,
                self.y_axis.y,
                rhs.y,
                self.y_axis.z,
                rhs.z,
                self.y_axis.w,
                rhs.w,
            ),
            z: dot4(
                self.z_axis.x,
                rhs.x,
                self.z_axis.y,
                rhs.y,
                self.z_axis.z,
                rhs.z,
                self.z_axis.w,
                rhs.w,
            ),
            w: dot4(
                self.w_axis.x,
                rhs.x,
                self.w_axis.y,
                rhs.y,
                self.w_axis.z,
                rhs.z,
                self.w_axis.w,
                rhs.w,
            ),
        }
    }

    #[inline(always)]
    fn mul_mat4(self: Mat4, rhs: Mat4) -> Mat4 {
        Mat4 {
            x_axis: Self::mul_vec4(self, rhs.x_axis),
            y_axis: Self::mul_vec4(self, rhs.y_axis),
            z_axis: Self::mul_vec4(self, rhs.z_axis),
            w_axis: Self::mul_vec4(self, rhs.w_axis),
        }
    }

    #[inline(always)]
    fn add_mat4(self: Mat4, rhs: Mat4) -> Mat4 {
        Mat4 {
            x_axis: Vec4 {
                x: self.x_axis.x + rhs.x_axis.x,
                y: self.x_axis.y + rhs.x_axis.y,
                z: self.x_axis.z + rhs.x_axis.z,
                w: self.x_axis.w + rhs.x_axis.w,
            },
            y_axis: Vec4 {
                x: self.y_axis.x + rhs.y_axis.x,
                y: self.y_axis.y + rhs.y_axis.y,
                z: self.y_axis.z + rhs.y_axis.z,
                w: self.y_axis.w + rhs.y_axis.w,
            },
            z_axis: Vec4 {
                x: self.z_axis.x + rhs.z_axis.x,
                y: self.z_axis.y + rhs.z_axis.y,
                z: self.z_axis.z + rhs.z_axis.z,
                w: self.z_axis.w + rhs.z_axis.w,
            },
            w_axis: Vec4 {
                x: self.w_axis.x + rhs.w_axis.x,
                y: self.w_axis.y + rhs.w_axis.y,
                z: self.w_axis.z + rhs.w_axis.z,
                w: self.w_axis.w + rhs.w_axis.w,
            },
        }
    }

    #[inline(always)]
    fn sub_mat4(self: Mat4, rhs: Mat4) -> Mat4 {
        Mat4 {
            x_axis: Vec4 {
                x: self.x_axis.x - rhs.x_axis.x,
                y: self.x_axis.y - rhs.x_axis.y,
                z: self.x_axis.z - rhs.x_axis.z,
                w: self.x_axis.w - rhs.x_axis.w,
            },
            y_axis: Vec4 {
                x: self.y_axis.x - rhs.y_axis.x,
                y: self.y_axis.y - rhs.y_axis.y,
                z: self.y_axis.z - rhs.y_axis.z,
                w: self.y_axis.w - rhs.y_axis.w,
            },
            z_axis: Vec4 {
                x: self.z_axis.x - rhs.z_axis.x,
                y: self.z_axis.y - rhs.z_axis.y,
                z: self.z_axis.z - rhs.z_axis.z,
                w: self.z_axis.w - rhs.z_axis.w,
            },
            w_axis: Vec4 {
                x: self.w_axis.x - rhs.w_axis.x,
                y: self.w_axis.y - rhs.w_axis.y,
                z: self.w_axis.z - rhs.w_axis.z,
                w: self.w_axis.w - rhs.w_axis.w,
            },
        }
    }

    #[inline(always)]
    fn mul_scalar(self: Mat4, rhs: Fixed) -> Mat4 {
        Mat4 {
            x_axis: Vec4 {
                x: self.x_axis.x * rhs,
                y: self.x_axis.y * rhs,
                z: self.x_axis.z * rhs,
                w: self.x_axis.w * rhs,
            },
            y_axis: Vec4 {
                x: self.y_axis.x * rhs,
                y: self.y_axis.y * rhs,
                z: self.y_axis.z * rhs,
                w: self.y_axis.w * rhs,
            },
            z_axis: Vec4 {
                x: self.z_axis.x * rhs,
                y: self.z_axis.y * rhs,
                z: self.z_axis.z * rhs,
                w: self.z_axis.w * rhs,
            },
            w_axis: Vec4 {
                x: self.w_axis.x * rhs,
                y: self.w_axis.y * rhs,
                z: self.w_axis.z * rhs,
                w: self.w_axis.w * rhs,
            },
        }
    }

    #[inline(always)]
    fn div_scalar(self: Mat4, rhs: Fixed) -> Mat4 {
        let r = RecipTrait::new(rhs);
        Mat4 {
            x_axis: Vec4 {
                x: r.mul(self.x_axis.x),
                y: r.mul(self.x_axis.y),
                z: r.mul(self.x_axis.z),
                w: r.mul(self.x_axis.w),
            },
            y_axis: Vec4 {
                x: r.mul(self.y_axis.x),
                y: r.mul(self.y_axis.y),
                z: r.mul(self.y_axis.z),
                w: r.mul(self.y_axis.w),
            },
            z_axis: Vec4 {
                x: r.mul(self.z_axis.x),
                y: r.mul(self.z_axis.y),
                z: r.mul(self.z_axis.z),
                w: r.mul(self.z_axis.w),
            },
            w_axis: Vec4 {
                x: r.mul(self.w_axis.x),
                y: r.mul(self.w_axis.y),
                z: r.mul(self.w_axis.z),
                w: r.mul(self.w_axis.w),
            },
        }
    }

    #[inline(always)]
    fn mul_diagonal_scale(self: Mat4, scale: Vec4) -> Mat4 {
        Mat4 {
            x_axis: Vec4 {
                x: self.x_axis.x * scale.x,
                y: self.x_axis.y * scale.x,
                z: self.x_axis.z * scale.x,
                w: self.x_axis.w * scale.x,
            },
            y_axis: Vec4 {
                x: self.y_axis.x * scale.y,
                y: self.y_axis.y * scale.y,
                z: self.y_axis.z * scale.y,
                w: self.y_axis.w * scale.y,
            },
            z_axis: Vec4 {
                x: self.z_axis.x * scale.z,
                y: self.z_axis.y * scale.z,
                z: self.z_axis.z * scale.z,
                w: self.z_axis.w * scale.z,
            },
            w_axis: Vec4 {
                x: self.w_axis.x * scale.w,
                y: self.w_axis.y * scale.w,
                z: self.w_axis.z * scale.w,
                w: self.w_axis.w * scale.w,
            },
        }
    }

    fn inverse(self: Mat4) -> Mat4 {
        inverse_checked(self).expect('Mat4: singular')
    }

    fn try_inverse(self: Mat4) -> Option<Mat4> {
        inverse_checked(self)
    }

    #[allow(manual_unwrap_or)]
    fn inverse_or_zero(self: Mat4) -> Mat4 {
        match inverse_checked(self) {
            Some(m) => m,
            None => Self::ZERO,
        }
    }

    #[inline(always)]
    fn abs(self: Mat4) -> Mat4 {
        Mat4 {
            x_axis: Vec4 {
                x: self.x_axis.x.abs(),
                y: self.x_axis.y.abs(),
                z: self.x_axis.z.abs(),
                w: self.x_axis.w.abs(),
            },
            y_axis: Vec4 {
                x: self.y_axis.x.abs(),
                y: self.y_axis.y.abs(),
                z: self.y_axis.z.abs(),
                w: self.y_axis.w.abs(),
            },
            z_axis: Vec4 {
                x: self.z_axis.x.abs(),
                y: self.z_axis.y.abs(),
                z: self.z_axis.z.abs(),
                w: self.z_axis.w.abs(),
            },
            w_axis: Vec4 {
                x: self.w_axis.x.abs(),
                y: self.w_axis.y.abs(),
                z: self.w_axis.z.abs(),
                w: self.w_axis.w.abs(),
            },
        }
    }

    #[inline(always)]
    fn recip(self: Mat4) -> Mat4 {
        Mat4 {
            x_axis: Vec4 {
                x: self.x_axis.x.recip(),
                y: self.x_axis.y.recip(),
                z: self.x_axis.z.recip(),
                w: self.x_axis.w.recip(),
            },
            y_axis: Vec4 {
                x: self.y_axis.x.recip(),
                y: self.y_axis.y.recip(),
                z: self.y_axis.z.recip(),
                w: self.y_axis.w.recip(),
            },
            z_axis: Vec4 {
                x: self.z_axis.x.recip(),
                y: self.z_axis.y.recip(),
                z: self.z_axis.z.recip(),
                w: self.z_axis.w.recip(),
            },
            w_axis: Vec4 {
                x: self.w_axis.x.recip(),
                y: self.w_axis.y.recip(),
                z: self.w_axis.z.recip(),
                w: self.w_axis.w.recip(),
            },
        }
    }

    #[inline(always)]
    fn abs_diff_eq(self: Mat4, rhs: Mat4, max_abs_diff: Fixed) -> bool {
        Vec4Trait::abs_diff_eq(self.x_axis, rhs.x_axis, max_abs_diff)
            && Vec4Trait::abs_diff_eq(self.y_axis, rhs.y_axis, max_abs_diff)
            && Vec4Trait::abs_diff_eq(self.z_axis, rhs.z_axis, max_abs_diff)
            && Vec4Trait::abs_diff_eq(self.w_axis, rhs.w_axis, max_abs_diff)
    }

    #[inline(always)]
    fn mul_affine3(self: Mat4, rhs: Affine3) -> Mat4 {
        Self::mul_mat4(self, Into::<Affine3, Mat4>::into(rhs))
    }

    #[inline(always)]
    fn from_mat3(m: Mat3) -> Mat4 {
        Mat4 {
            x_axis: Vec4 { x: m.x_axis.x, y: m.x_axis.y, z: m.x_axis.z, w: Fixed { raw: 0 } },
            y_axis: Vec4 { x: m.y_axis.x, y: m.y_axis.y, z: m.y_axis.z, w: Fixed { raw: 0 } },
            z_axis: Vec4 { x: m.z_axis.x, y: m.z_axis.y, z: m.z_axis.z, w: Fixed { raw: 0 } },
            w_axis: Vec4 {
                x: Fixed { raw: 0 },
                y: Fixed { raw: 0 },
                z: Fixed { raw: 0 },
                w: Fixed { raw: 0x100000000 },
            },
        }
    }

    #[inline(always)]
    fn from_mat3_translation(mat3: Mat3, translation: Vec3) -> Mat4 {
        Mat4 {
            x_axis: Vec4 {
                x: mat3.x_axis.x, y: mat3.x_axis.y, z: mat3.x_axis.z, w: Fixed { raw: 0 },
            },
            y_axis: Vec4 {
                x: mat3.y_axis.x, y: mat3.y_axis.y, z: mat3.y_axis.z, w: Fixed { raw: 0 },
            },
            z_axis: Vec4 {
                x: mat3.z_axis.x, y: mat3.z_axis.y, z: mat3.z_axis.z, w: Fixed { raw: 0 },
            },
            w_axis: Vec4 {
                x: translation.x, y: translation.y, z: translation.z, w: Fixed { raw: 0x100000000 },
            },
        }
    }

    #[inline(always)]
    fn from_translation(translation: Vec3) -> Mat4 {
        Mat4 {
            x_axis: Vec4 {
                x: Fixed { raw: 0x100000000 },
                y: Fixed { raw: 0 },
                z: Fixed { raw: 0 },
                w: Fixed { raw: 0 },
            },
            y_axis: Vec4 {
                x: Fixed { raw: 0 },
                y: Fixed { raw: 0x100000000 },
                z: Fixed { raw: 0 },
                w: Fixed { raw: 0 },
            },
            z_axis: Vec4 {
                x: Fixed { raw: 0 },
                y: Fixed { raw: 0 },
                z: Fixed { raw: 0x100000000 },
                w: Fixed { raw: 0 },
            },
            w_axis: Vec4 {
                x: translation.x, y: translation.y, z: translation.z, w: Fixed { raw: 0x100000000 },
            },
        }
    }

    #[inline(always)]
    fn from_scale(scale: Vec3) -> Mat4 {
        Mat4 {
            x_axis: Vec4 {
                x: scale.x, y: Fixed { raw: 0 }, z: Fixed { raw: 0 }, w: Fixed { raw: 0 },
            },
            y_axis: Vec4 {
                x: Fixed { raw: 0 }, y: scale.y, z: Fixed { raw: 0 }, w: Fixed { raw: 0 },
            },
            z_axis: Vec4 {
                x: Fixed { raw: 0 }, y: Fixed { raw: 0 }, z: scale.z, w: Fixed { raw: 0 },
            },
            w_axis: Vec4 {
                x: Fixed { raw: 0 },
                y: Fixed { raw: 0 },
                z: Fixed { raw: 0 },
                w: Fixed { raw: 0x100000000 },
            },
        }
    }

    #[inline(always)]
    fn from_quat(rotation: Quat) -> Mat4 {
        let x2 = rotation.x + rotation.x;
        let y2 = rotation.y + rotation.y;
        let z2 = rotation.z + rotation.z;
        Mat4 {
            x_axis: Vec4 {
                x: wide_from(F_ONE)
                    .sub(wide_mul(rotation.y, y2))
                    .sub(wide_mul(rotation.z, z2))
                    .narrow(),
                y: wide_mul(rotation.x, y2).add(wide_mul(rotation.w, z2)).narrow(),
                z: wide_mul(rotation.x, z2).sub(wide_mul(rotation.w, y2)).narrow(),
                w: Fixed { raw: 0 },
            },
            y_axis: Vec4 {
                x: wide_mul(rotation.x, y2).sub(wide_mul(rotation.w, z2)).narrow(),
                y: wide_from(F_ONE)
                    .sub(wide_mul(rotation.x, x2))
                    .sub(wide_mul(rotation.z, z2))
                    .narrow(),
                z: wide_mul(rotation.y, z2).add(wide_mul(rotation.w, x2)).narrow(),
                w: Fixed { raw: 0 },
            },
            z_axis: Vec4 {
                x: wide_mul(rotation.x, z2).add(wide_mul(rotation.w, y2)).narrow(),
                y: wide_mul(rotation.y, z2).sub(wide_mul(rotation.w, x2)).narrow(),
                z: wide_from(F_ONE)
                    .sub(wide_mul(rotation.x, x2))
                    .sub(wide_mul(rotation.y, y2))
                    .narrow(),
                w: Fixed { raw: 0 },
            },
            w_axis: Vec4 {
                x: Fixed { raw: 0 },
                y: Fixed { raw: 0 },
                z: Fixed { raw: 0 },
                w: Fixed { raw: 0x100000000 },
            },
        }
    }

    #[inline(always)]
    fn from_rotation_translation(rotation: Quat, translation: Vec3) -> Mat4 {
        let x2 = rotation.x + rotation.x;
        let y2 = rotation.y + rotation.y;
        let z2 = rotation.z + rotation.z;
        Mat4 {
            x_axis: Vec4 {
                x: wide_from(F_ONE)
                    .sub(wide_mul(rotation.y, y2))
                    .sub(wide_mul(rotation.z, z2))
                    .narrow(),
                y: wide_mul(rotation.x, y2).add(wide_mul(rotation.w, z2)).narrow(),
                z: wide_mul(rotation.x, z2).sub(wide_mul(rotation.w, y2)).narrow(),
                w: Fixed { raw: 0 },
            },
            y_axis: Vec4 {
                x: wide_mul(rotation.x, y2).sub(wide_mul(rotation.w, z2)).narrow(),
                y: wide_from(F_ONE)
                    .sub(wide_mul(rotation.x, x2))
                    .sub(wide_mul(rotation.z, z2))
                    .narrow(),
                z: wide_mul(rotation.y, z2).add(wide_mul(rotation.w, x2)).narrow(),
                w: Fixed { raw: 0 },
            },
            z_axis: Vec4 {
                x: wide_mul(rotation.x, z2).add(wide_mul(rotation.w, y2)).narrow(),
                y: wide_mul(rotation.y, z2).sub(wide_mul(rotation.w, x2)).narrow(),
                z: wide_from(F_ONE)
                    .sub(wide_mul(rotation.x, x2))
                    .sub(wide_mul(rotation.y, y2))
                    .narrow(),
                w: Fixed { raw: 0 },
            },
            w_axis: Vec4 {
                x: translation.x, y: translation.y, z: translation.z, w: Fixed { raw: 0x100000000 },
            },
        }
    }

    #[inline(always)]
    fn from_scale_rotation_translation(scale: Vec3, rotation: Quat, translation: Vec3) -> Mat4 {
        let x2 = rotation.x + rotation.x;
        let y2 = rotation.y + rotation.y;
        let z2 = rotation.z + rotation.z;
        Mat4 {
            x_axis: Vec4 {
                x: wide_from(F_ONE)
                    .sub(wide_mul(rotation.y, y2))
                    .sub(wide_mul(rotation.z, z2))
                    .mul(scale.x)
                    .narrow(),
                y: wide_mul(rotation.x, y2).add(wide_mul(rotation.w, z2)).mul(scale.x).narrow(),
                z: wide_mul(rotation.x, z2).sub(wide_mul(rotation.w, y2)).mul(scale.x).narrow(),
                w: Fixed { raw: 0 },
            },
            y_axis: Vec4 {
                x: wide_mul(rotation.x, y2).sub(wide_mul(rotation.w, z2)).mul(scale.y).narrow(),
                y: wide_from(F_ONE)
                    .sub(wide_mul(rotation.x, x2))
                    .sub(wide_mul(rotation.z, z2))
                    .mul(scale.y)
                    .narrow(),
                z: wide_mul(rotation.y, z2).add(wide_mul(rotation.w, x2)).mul(scale.y).narrow(),
                w: Fixed { raw: 0 },
            },
            z_axis: Vec4 {
                x: wide_mul(rotation.x, z2).add(wide_mul(rotation.w, y2)).mul(scale.z).narrow(),
                y: wide_mul(rotation.y, z2).sub(wide_mul(rotation.w, x2)).mul(scale.z).narrow(),
                z: wide_from(F_ONE)
                    .sub(wide_mul(rotation.x, x2))
                    .sub(wide_mul(rotation.y, y2))
                    .mul(scale.z)
                    .narrow(),
                w: Fixed { raw: 0 },
            },
            w_axis: Vec4 {
                x: translation.x, y: translation.y, z: translation.z, w: Fixed { raw: 0x100000000 },
            },
        }
    }

    fn to_scale_rotation_translation(self: Mat4) -> (Vec3, Quat, Vec3) {
        let r = Mat3Trait::from_mat4(self);
        // The length of each column, the sign of the determinant carried by the first.
        let len_x = Vec3Trait::length(r.x_axis);
        let scale = Vec3 {
            x: if Mat3Trait::determinant(r).is_negative() {
                -len_x
            } else {
                len_x
            },
            y: Vec3Trait::length(r.y_axis),
            z: Vec3Trait::length(r.z_axis),
        };
        // One shared reciprocal per column: three divisions instead of nine.
        let rx = RecipTrait::new(scale.x);
        let ry = RecipTrait::new(scale.y);
        let rz = RecipTrait::new(scale.z);
        let rotation = QuatTrait::from_rotation_axes(
            Vec3 { x: rx.mul(r.x_axis.x), y: rx.mul(r.x_axis.y), z: rx.mul(r.x_axis.z) },
            Vec3 { x: ry.mul(r.y_axis.x), y: ry.mul(r.y_axis.y), z: ry.mul(r.y_axis.z) },
            Vec3 { x: rz.mul(r.z_axis.x), y: rz.mul(r.z_axis.y), z: rz.mul(r.z_axis.z) },
        );
        (scale, rotation, Vec4Trait::truncate(self.w_axis))
    }

    #[inline(always)]
    fn from_axis_angle(axis: Vec3, angle: Fixed) -> Mat4 {
        let (sin, cos) = angle.sin_cos();
        let omc = F_ONE - cos;
        Mat4 {
            x_axis: Vec4 {
                x: wide_mul(axis.x, axis.x).mul(omc).add(wide_from(cos).lift()).narrow(),
                y: wide_mul(axis.x, axis.y).mul(omc).add(wide_mul(axis.z, sin).lift()).narrow(),
                z: wide_mul(axis.x, axis.z).mul(omc).sub(wide_mul(axis.y, sin).lift()).narrow(),
                w: Fixed { raw: 0 },
            },
            y_axis: Vec4 {
                x: wide_mul(axis.x, axis.y).mul(omc).sub(wide_mul(axis.z, sin).lift()).narrow(),
                y: wide_mul(axis.y, axis.y).mul(omc).add(wide_from(cos).lift()).narrow(),
                z: wide_mul(axis.y, axis.z).mul(omc).add(wide_mul(axis.x, sin).lift()).narrow(),
                w: Fixed { raw: 0 },
            },
            z_axis: Vec4 {
                x: wide_mul(axis.x, axis.z).mul(omc).add(wide_mul(axis.y, sin).lift()).narrow(),
                y: wide_mul(axis.y, axis.z).mul(omc).sub(wide_mul(axis.x, sin).lift()).narrow(),
                z: wide_mul(axis.z, axis.z).mul(omc).add(wide_from(cos).lift()).narrow(),
                w: Fixed { raw: 0 },
            },
            w_axis: Vec4 {
                x: Fixed { raw: 0 },
                y: Fixed { raw: 0 },
                z: Fixed { raw: 0 },
                w: Fixed { raw: 0x100000000 },
            },
        }
    }

    #[inline(always)]
    fn from_rotation_x(angle: Fixed) -> Mat4 {
        let (sin, cos) = angle.sin_cos();
        Mat4 {
            x_axis: Vec4 {
                x: Fixed { raw: 0x100000000 },
                y: Fixed { raw: 0 },
                z: Fixed { raw: 0 },
                w: Fixed { raw: 0 },
            },
            y_axis: Vec4 { x: Fixed { raw: 0 }, y: cos, z: sin, w: Fixed { raw: 0 } },
            z_axis: Vec4 { x: Fixed { raw: 0 }, y: -sin, z: cos, w: Fixed { raw: 0 } },
            w_axis: Vec4 {
                x: Fixed { raw: 0 },
                y: Fixed { raw: 0 },
                z: Fixed { raw: 0 },
                w: Fixed { raw: 0x100000000 },
            },
        }
    }

    #[inline(always)]
    fn from_rotation_y(angle: Fixed) -> Mat4 {
        let (sin, cos) = angle.sin_cos();
        Mat4 {
            x_axis: Vec4 { x: cos, y: Fixed { raw: 0 }, z: -sin, w: Fixed { raw: 0 } },
            y_axis: Vec4 {
                x: Fixed { raw: 0 },
                y: Fixed { raw: 0x100000000 },
                z: Fixed { raw: 0 },
                w: Fixed { raw: 0 },
            },
            z_axis: Vec4 { x: sin, y: Fixed { raw: 0 }, z: cos, w: Fixed { raw: 0 } },
            w_axis: Vec4 {
                x: Fixed { raw: 0 },
                y: Fixed { raw: 0 },
                z: Fixed { raw: 0 },
                w: Fixed { raw: 0x100000000 },
            },
        }
    }

    #[inline(always)]
    fn from_rotation_z(angle: Fixed) -> Mat4 {
        let (sin, cos) = angle.sin_cos();
        Mat4 {
            x_axis: Vec4 { x: cos, y: sin, z: Fixed { raw: 0 }, w: Fixed { raw: 0 } },
            y_axis: Vec4 { x: -sin, y: cos, z: Fixed { raw: 0 }, w: Fixed { raw: 0 } },
            z_axis: Vec4 {
                x: Fixed { raw: 0 },
                y: Fixed { raw: 0 },
                z: Fixed { raw: 0x100000000 },
                w: Fixed { raw: 0 },
            },
            w_axis: Vec4 {
                x: Fixed { raw: 0 },
                y: Fixed { raw: 0 },
                z: Fixed { raw: 0 },
                w: Fixed { raw: 0x100000000 },
            },
        }
    }

    #[inline(always)]
    fn transform_point3(self: Mat4, rhs: Vec3) -> Vec3 {
        Vec3 {
            x: dot3_add(
                self.x_axis.x, rhs.x, self.y_axis.x, rhs.y, self.z_axis.x, rhs.z, self.w_axis.x,
            ),
            y: dot3_add(
                self.x_axis.y, rhs.x, self.y_axis.y, rhs.y, self.z_axis.y, rhs.z, self.w_axis.y,
            ),
            z: dot3_add(
                self.x_axis.z, rhs.x, self.y_axis.z, rhs.y, self.z_axis.z, rhs.z, self.w_axis.z,
            ),
        }
    }

    #[inline(always)]
    fn transform_vector3(self: Mat4, rhs: Vec3) -> Vec3 {
        Vec3 {
            x: dot3(self.x_axis.x, rhs.x, self.y_axis.x, rhs.y, self.z_axis.x, rhs.z),
            y: dot3(self.x_axis.y, rhs.x, self.y_axis.y, rhs.y, self.z_axis.y, rhs.z),
            z: dot3(self.x_axis.z, rhs.x, self.y_axis.z, rhs.y, self.z_axis.z, rhs.z),
        }
    }

    fn project_point3(self: Mat4, rhs: Vec3) -> Vec3 {
        let w = dot3_add(
            self.x_axis.w, rhs.x, self.y_axis.w, rhs.y, self.z_axis.w, rhs.z, self.w_axis.w,
        );
        let r = RecipTrait::new(w);
        Vec3 {
            x: r
                .mul(
                    dot3_add(
                        self.x_axis.x,
                        rhs.x,
                        self.y_axis.x,
                        rhs.y,
                        self.z_axis.x,
                        rhs.z,
                        self.w_axis.x,
                    ),
                ),
            y: r
                .mul(
                    dot3_add(
                        self.x_axis.y,
                        rhs.x,
                        self.y_axis.y,
                        rhs.y,
                        self.z_axis.y,
                        rhs.z,
                        self.w_axis.y,
                    ),
                ),
            z: r
                .mul(
                    dot3_add(
                        self.x_axis.z,
                        rhs.x,
                        self.y_axis.z,
                        rhs.y,
                        self.z_axis.z,
                        rhs.z,
                        self.w_axis.z,
                    ),
                ),
        }
    }

    fn look_to_rh(eye: Vec3, dir: Vec3, up: Vec3) -> Mat4 {
        let s = Vec3Trait::normalize(Vec3Trait::cross(dir, up));
        let u = Vec3Trait::cross(s, dir);
        Mat4 {
            x_axis: Vec4 { x: s.x, y: u.x, z: -dir.x, w: F_ZERO },
            y_axis: Vec4 { x: s.y, y: u.y, z: -dir.y, w: F_ZERO },
            z_axis: Vec4 { x: s.z, y: u.z, z: -dir.z, w: F_ZERO },
            w_axis: Vec4 {
                x: -Vec3Trait::dot(eye, s),
                y: -Vec3Trait::dot(eye, u),
                z: Vec3Trait::dot(eye, dir),
                w: F_ONE,
            },
        }
    }

    fn look_to_lh(eye: Vec3, dir: Vec3, up: Vec3) -> Mat4 {
        Self::look_to_rh(eye, -dir, up)
    }

    fn look_at_rh(eye: Vec3, center: Vec3, up: Vec3) -> Mat4 {
        Self::look_to_rh(eye, Vec3Trait::normalize(center - eye), up)
    }

    fn look_at_lh(eye: Vec3, center: Vec3, up: Vec3) -> Mat4 {
        Self::look_to_lh(eye, Vec3Trait::normalize(center - eye), up)
    }
}

/// `Default` is `Mat4::IDENTITY`, as in glam-rs (not the all-zero derived value).
///
/// Mirrors `impl Default for glam::Mat4`.
pub impl Mat4Default of Default<Mat4> {
    #[inline(always)]
    fn default() -> Mat4 {
        Mat4Trait::IDENTITY
    }
}

/// Element-wise `+`. Exact. Panics with the `i64_add` overflow messages.
///
/// Mirrors `impl Add for glam::Mat4`.
pub impl Mat4Add of Add<Mat4> {
    #[inline(always)]
    fn add(lhs: Mat4, rhs: Mat4) -> Mat4 {
        Mat4 {
            x_axis: lhs.x_axis + rhs.x_axis,
            y_axis: lhs.y_axis + rhs.y_axis,
            z_axis: lhs.z_axis + rhs.z_axis,
            w_axis: lhs.w_axis + rhs.w_axis,
        }
    }
}

/// Element-wise `-`. Exact. Panics with the `i64_sub` overflow messages.
///
/// Mirrors `impl Sub for glam::Mat4`.
pub impl Mat4Sub of Sub<Mat4> {
    #[inline(always)]
    fn sub(lhs: Mat4, rhs: Mat4) -> Mat4 {
        Mat4 {
            x_axis: lhs.x_axis - rhs.x_axis,
            y_axis: lhs.y_axis - rhs.y_axis,
            z_axis: lhs.z_axis - rhs.z_axis,
            w_axis: lhs.w_axis - rhs.w_axis,
        }
    }
}

/// Element-wise negation. Panics with `'i64_neg Underflow'` on `Fixed::MIN`.
///
/// Mirrors `impl Neg for glam::Mat4`.
pub impl Mat4Neg of Neg<Mat4> {
    #[inline(always)]
    fn neg(a: Mat4) -> Mat4 {
        Mat4 { x_axis: -a.x_axis, y_axis: -a.y_axis, z_axis: -a.z_axis, w_axis: -a.w_axis }
    }
}

/// The matrix product (see `Mat4Trait::mul_mat4`).
///
/// Mirrors `impl Mul for glam::Mat4`.
pub impl Mat4Mul of Mul<Mat4> {
    #[inline(always)]
    fn mul(lhs: Mat4, rhs: Mat4) -> Mat4 {
        Mat4Trait::mul_mat4(lhs, rhs)
    }
}

/// Mirrors `impl AddAssign for glam::Mat4`.
pub impl Mat4AddAssign of AddAssign<Mat4, Mat4> {
    #[inline(always)]
    fn add_assign(ref self: Mat4, rhs: Mat4) {
        self = self + rhs;
    }
}

/// Mirrors `impl SubAssign for glam::Mat4`.
pub impl Mat4SubAssign of SubAssign<Mat4, Mat4> {
    #[inline(always)]
    fn sub_assign(ref self: Mat4, rhs: Mat4) {
        self = self - rhs;
    }
}

/// Mirrors `impl MulAssign for glam::Mat4`.
pub impl Mat4MulAssign of MulAssign<Mat4, Mat4> {
    #[inline(always)]
    fn mul_assign(ref self: Mat4, rhs: Mat4) {
        self = self * rhs;
    }
}

/// Mirrors `impl MulAssign<f32> for glam::Mat4` (see `Mat4Trait::mul_scalar`).
pub impl Mat4MulAssignScalar of MulAssign<Mat4, Fixed> {
    #[inline(always)]
    fn mul_assign(ref self: Mat4, rhs: Fixed) {
        self = Mat4Trait::mul_scalar(self, rhs);
    }
}

/// Mirrors `impl DivAssign<f32> for glam::Mat4` (see `Mat4Trait::div_scalar`).
pub impl Mat4DivAssignScalar of DivAssign<Mat4, Fixed> {
    #[inline(always)]
    fn div_assign(ref self: Mat4, rhs: Fixed) {
        self = Mat4Trait::div_scalar(self, rhs);
    }
}

/// Multiplies by a 3D affine transform through `Mat4Trait::mul_affine3`.
///
/// Mirrors `impl MulAssign<Affine3> for glam::Mat4`.
pub impl Mat4MulAssignAffine3 of MulAssign<Mat4, Affine3> {
    #[inline(always)]
    fn mul_assign(ref self: Mat4, rhs: Affine3) {
        self = Mat4Trait::mul_affine3(self, rhs);
    }
}

/// Mirrors `impl From<[f32; 16]> for glam::Mat4` (column major).
pub impl FixedArrayIntoMat4 of Into<[Fixed; 16], Mat4> {
    #[inline(always)]
    fn into(self: [Fixed; 16]) -> Mat4 {
        Mat4Trait::from_cols_array(self)
    }
}

/// Mirrors `impl From<glam::Mat4> for [f32; 16]` (column major).
pub impl Mat4IntoFixedArray of Into<Mat4, [Fixed; 16]> {
    #[inline(always)]
    fn into(self: Mat4) -> [Fixed; 16] {
        Mat4Trait::to_cols_array(self)
    }
}

/// Mirrors `impl From<[[f32; 4]; 4]> for glam::Mat4` (column major).
pub impl FixedArray2dIntoMat4 of Into<[[Fixed; 4]; 4], Mat4> {
    #[inline(always)]
    fn into(self: [[Fixed; 4]; 4]) -> Mat4 {
        Mat4Trait::from_cols_array_2d(self)
    }
}

/// Mirrors `impl From<glam::Mat4> for [[f32; 4]; 4]` (column major).
pub impl Mat4IntoFixedArray2d of Into<Mat4, [[Fixed; 4]; 4]> {
    #[inline(always)]
    fn into(self: Mat4) -> [[Fixed; 4]; 4] {
        Mat4Trait::to_cols_array_2d(self)
    }
}

/// The shared body of `inverse`, `try_inverse` and `inverse_or_zero`: the adjugate through the
/// fused kernels of `fixed::wide`, then ONE division (`Recip`) for the 16 elements. `None` when
/// the determinant is zero, which is the definition of singular here (docs/DESIGN.md section 3).
#[inline(never)]
fn inverse_checked(m: Mat4) -> Option<Mat4> {
    let coef00 = mul_sub(m.z_axis.z, m.w_axis.w, m.w_axis.z, m.z_axis.w);
    let coef02 = mul_sub(m.y_axis.z, m.w_axis.w, m.w_axis.z, m.y_axis.w);
    let coef03 = mul_sub(m.y_axis.z, m.z_axis.w, m.z_axis.z, m.y_axis.w);
    let coef04 = mul_sub(m.z_axis.y, m.w_axis.w, m.w_axis.y, m.z_axis.w);
    let coef06 = mul_sub(m.y_axis.y, m.w_axis.w, m.w_axis.y, m.y_axis.w);
    let coef07 = mul_sub(m.y_axis.y, m.z_axis.w, m.z_axis.y, m.y_axis.w);
    let coef08 = mul_sub(m.z_axis.y, m.w_axis.z, m.w_axis.y, m.z_axis.z);
    let coef10 = mul_sub(m.y_axis.y, m.w_axis.z, m.w_axis.y, m.y_axis.z);
    let coef11 = mul_sub(m.y_axis.y, m.z_axis.z, m.z_axis.y, m.y_axis.z);
    let coef12 = mul_sub(m.z_axis.x, m.w_axis.w, m.w_axis.x, m.z_axis.w);
    let coef14 = mul_sub(m.y_axis.x, m.w_axis.w, m.w_axis.x, m.y_axis.w);
    let coef15 = mul_sub(m.y_axis.x, m.z_axis.w, m.z_axis.x, m.y_axis.w);
    let coef16 = mul_sub(m.z_axis.x, m.w_axis.z, m.w_axis.x, m.z_axis.z);
    let coef18 = mul_sub(m.y_axis.x, m.w_axis.z, m.w_axis.x, m.y_axis.z);
    let coef19 = mul_sub(m.y_axis.x, m.z_axis.z, m.z_axis.x, m.y_axis.z);
    let coef20 = mul_sub(m.z_axis.x, m.w_axis.y, m.w_axis.x, m.z_axis.y);
    let coef22 = mul_sub(m.y_axis.x, m.w_axis.y, m.w_axis.x, m.y_axis.y);
    let coef23 = mul_sub(m.y_axis.x, m.z_axis.y, m.z_axis.x, m.y_axis.y);
    let q0 = wide_mul(m.y_axis.y, coef00)
        .sub(wide_mul(m.y_axis.z, coef04))
        .add(wide_mul(m.y_axis.w, coef08));
    let q1 = wide_mul(m.y_axis.z, coef12)
        .sub(wide_mul(m.y_axis.x, coef00))
        .sub(wide_mul(m.y_axis.w, coef16));
    let q2 = wide_mul(m.y_axis.x, coef04)
        .sub(wide_mul(m.y_axis.y, coef12))
        .add(wide_mul(m.y_axis.w, coef20));
    let q3 = wide_mul(m.y_axis.y, coef16)
        .sub(wide_mul(m.y_axis.x, coef08))
        .sub(wide_mul(m.y_axis.z, coef20));
    let det = q0
        .mul(m.x_axis.x)
        .add(q1.mul(m.x_axis.y))
        .add(q2.mul(m.x_axis.z))
        .add(q3.mul(m.x_axis.w))
        .narrow();
    if det == F_ZERO {
        return None;
    }
    let q00 = q0.narrow();
    let q10 = q1.narrow();
    let q20 = q2.narrow();
    let q30 = q3.narrow();
    let q01 = wide_mul(m.x_axis.z, coef04)
        .sub(wide_mul(m.x_axis.y, coef00))
        .sub(wide_mul(m.x_axis.w, coef08))
        .narrow();
    let q02 = wide_mul(m.x_axis.y, coef02)
        .sub(wide_mul(m.x_axis.z, coef06))
        .add(wide_mul(m.x_axis.w, coef10))
        .narrow();
    let q03 = wide_mul(m.x_axis.z, coef07)
        .sub(wide_mul(m.x_axis.y, coef03))
        .sub(wide_mul(m.x_axis.w, coef11))
        .narrow();
    let q11 = wide_mul(m.x_axis.x, coef00)
        .sub(wide_mul(m.x_axis.z, coef12))
        .add(wide_mul(m.x_axis.w, coef16))
        .narrow();
    let q12 = wide_mul(m.x_axis.z, coef14)
        .sub(wide_mul(m.x_axis.x, coef02))
        .sub(wide_mul(m.x_axis.w, coef18))
        .narrow();
    let q13 = wide_mul(m.x_axis.x, coef03)
        .sub(wide_mul(m.x_axis.z, coef15))
        .add(wide_mul(m.x_axis.w, coef19))
        .narrow();
    let q21 = wide_mul(m.x_axis.y, coef12)
        .sub(wide_mul(m.x_axis.x, coef04))
        .sub(wide_mul(m.x_axis.w, coef20))
        .narrow();
    let q22 = wide_mul(m.x_axis.x, coef06)
        .sub(wide_mul(m.x_axis.y, coef14))
        .add(wide_mul(m.x_axis.w, coef22))
        .narrow();
    let q23 = wide_mul(m.x_axis.y, coef15)
        .sub(wide_mul(m.x_axis.x, coef07))
        .sub(wide_mul(m.x_axis.w, coef23))
        .narrow();
    let q31 = wide_mul(m.x_axis.x, coef08)
        .sub(wide_mul(m.x_axis.y, coef16))
        .add(wide_mul(m.x_axis.z, coef20))
        .narrow();
    let q32 = wide_mul(m.x_axis.y, coef18)
        .sub(wide_mul(m.x_axis.x, coef10))
        .sub(wide_mul(m.x_axis.z, coef22))
        .narrow();
    let q33 = wide_mul(m.x_axis.x, coef11)
        .sub(wide_mul(m.x_axis.y, coef19))
        .add(wide_mul(m.x_axis.z, coef23))
        .narrow();
    let r = RecipTrait::new(det);
    Some(
        Mat4 {
            x_axis: Vec4 { x: r.mul(q00), y: r.mul(q01), z: r.mul(q02), w: r.mul(q03) },
            y_axis: Vec4 { x: r.mul(q10), y: r.mul(q11), z: r.mul(q12), w: r.mul(q13) },
            z_axis: Vec4 { x: r.mul(q20), y: r.mul(q21), z: r.mul(q22), w: r.mul(q23) },
            w_axis: Vec4 { x: r.mul(q30), y: r.mul(q31), z: r.mul(q32), w: r.mul(q33) },
        },
    )
}

/// `0`.
const F_ZERO: Fixed = Fixed { raw: 0 };

/// `1`.
const F_ONE: Fixed = Fixed { raw: 0x100000000 };
