// GENERATED by tools/codegen/swizzles.py - do not edit by hand.
//! Port of glam-rs `swizzles` @ 0.33.8: the `Vec2Swizzles`, `Vec3Swizzles` and
//! `Vec4Swizzles` traits, once per vector type of glam.cairo (`Vec*`, `IVec*`, `UVec*`).
//!
//! The nine submodules are generated by `tools/codegen/swizzles.py`; the traits are
//! re-exported here (`use glam::swizzles::Vec3Swizzles;`).

pub mod ivec2;
pub mod ivec3;
pub mod ivec4;
pub mod uvec2;
pub mod uvec3;
pub mod uvec4;
pub mod vec2;
pub mod vec3;
pub mod vec4;
pub use ivec2::{IVec2Swizzles, IVec2SwizzlesImpl};
pub use ivec3::{IVec3Swizzles, IVec3SwizzlesImpl};
pub use ivec4::{IVec4Swizzles, IVec4SwizzlesImpl};
pub use uvec2::{UVec2Swizzles, UVec2SwizzlesImpl};
pub use uvec3::{UVec3Swizzles, UVec3SwizzlesImpl};
pub use uvec4::{UVec4Swizzles, UVec4SwizzlesImpl};

pub use vec2::{Vec2Swizzles, Vec2SwizzlesImpl};
pub use vec3::{Vec3Swizzles, Vec3SwizzlesImpl};
pub use vec4::{Vec4Swizzles, Vec4SwizzlesImpl};
