// GENERATED by tools/codegen/intvec.py - do not edit by hand.
//! Port of glam-rs `u32/uvec4.rs` @ 0.33.8: a 4-dimensional `u32` vector.
//!
//! The six integer vector modules are generated from one template (`tools/codegen/intvec.py`),
//! as in glam-rs. Every formulation is the cheapest of the candidates measured in
//! `gas/uvec4.snap`; the losing candidates live in `benches::alt::uvec4`.
//!
//! Overflow: the operators and the plain methods panic (corelib messages, or `'UVec4: overflow'`
//! for the fused kernels); the `checked_*` / `wrapping_*` / `saturating_*` families never do. They
//! exist for their semantics: they are slower than the panicking operators.

use core::num::traits::{
    CheckedAdd, CheckedSub, SaturatingAdd, SaturatingSub, WideMul, WrappingAdd, WrappingMul,
    WrappingSub,
};
use core::ops::index::IndexView;
use core::ops::{AddAssign, DivAssign, MulAssign, RemAssign, SubAssign};
use core::traits::{BitAnd, BitNot, BitOr, BitXor, DivRem};
use crate::bvec4::BVec4;
use crate::ivec4::IVec4;
use crate::uvec2::UVec2;
use crate::uvec3::UVec3;

/// A 4-dimensional `u32` vector.
///
/// Mirrors `glam::UVec4`.
/// #### Deviations
/// * `Debug` is the derived Cairo formatting; `Display` is not implemented.
/// * Not ported: `map` (a closure parameter cannot be force-inlined, E2143), `from_slice` /
///   `write_to_slice` (no `Span` in fixed-size math), `Sum` / `Product`, `IndexMut`, the
///   by-reference operator overloads, the scalar-on-the-left operators (`2 * v`), the scalar
///   bit operators (use `v & UVec4Trait::splat(s)`), shifts by a vector or by another integer
///   width, and the casts to types that do not exist in glam-cairo (`as_i64vec4`, ...).
/// * `as_vec4` (and `as_dvec4`) will land with the `Vec4` port.
#[derive(Copy, Drop, Serde, PartialEq, Debug, Default, Hash)]
pub struct UVec4 {
    pub x: u32,
    pub y: u32,
    pub z: u32,
    pub w: u32,
}

/// Creates a 4-dimensional `u32` vector.
///
/// Mirrors `glam::uvec4`.
/// #### Panics
/// * Never.
/// #### Deviations
/// * None.
#[inline(always)]
pub fn uvec4(x: u32, y: u32, z: u32, w: u32) -> UVec4 {
    UVec4 { x, y, z, w }
}

pub trait UVec4Trait {
    /// All zeroes.
    ///
    /// Mirrors `glam::UVec4::ZERO`.
    const ZERO: UVec4;
    /// All ones.
    ///
    /// Mirrors `glam::UVec4::ONE`.
    const ONE: UVec4;
    /// All `u32::MIN`.
    ///
    /// Mirrors `glam::UVec4::MIN`.
    const MIN: UVec4;
    /// All `u32::MAX`.
    ///
    /// Mirrors `glam::UVec4::MAX`.
    const MAX: UVec4;
    /// A unit vector pointing along the positive X axis.
    ///
    /// Mirrors `glam::UVec4::X`.
    const X: UVec4;
    /// A unit vector pointing along the positive Y axis.
    ///
    /// Mirrors `glam::UVec4::Y`.
    const Y: UVec4;
    /// A unit vector pointing along the positive Z axis.
    ///
    /// Mirrors `glam::UVec4::Z`.
    const Z: UVec4;
    /// A unit vector pointing along the positive W axis.
    ///
    /// Mirrors `glam::UVec4::W`.
    const W: UVec4;
    /// The unit axes.
    ///
    /// Mirrors `glam::UVec4::AXES`.
    const AXES: [UVec4; 4];
    /// Creates a new vector.
    ///
    /// Mirrors `glam::UVec4::new`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn new(x: u32, y: u32, z: u32, w: u32) -> UVec4;
    /// Creates a vector with all elements set to `v`.
    ///
    /// Mirrors `glam::UVec4::splat`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn splat(v: u32) -> UVec4;
    /// Creates a vector from the elements in `if_true` and `if_false`, selecting which to
    /// use for each element of `self`.
    ///
    /// A true element in the mask uses the corresponding element from `if_true`, and false
    /// uses the element from `if_false`.
    ///
    /// Mirrors `glam::UVec4::select`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn select(mask: BVec4, if_true: UVec4, if_false: UVec4) -> UVec4;
    /// Creates a new vector from an array.
    ///
    /// Mirrors `glam::UVec4::from_array`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn from_array(a: [u32; 4]) -> UVec4;
    /// Converts `self` to `[x, y, z, w]`.
    ///
    /// Mirrors `glam::UVec4::to_array`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn to_array(self: UVec4) -> [u32; 4];
    /// Creates a 3D vector from the `x`, `y`, `z` elements of `self`, discarding `w`.
    ///
    /// Mirrors `glam::UVec4::truncate`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn truncate(self: UVec4) -> UVec3;
    /// Creates a 4D vector from `self` with the given value of `x`.
    ///
    /// Mirrors `glam::UVec4::with_x`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn with_x(self: UVec4, x: u32) -> UVec4;
    /// Creates a 4D vector from `self` with the given value of `y`.
    ///
    /// Mirrors `glam::UVec4::with_y`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn with_y(self: UVec4, y: u32) -> UVec4;
    /// Creates a 4D vector from `self` with the given value of `z`.
    ///
    /// Mirrors `glam::UVec4::with_z`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn with_z(self: UVec4, z: u32) -> UVec4;
    /// Creates a 4D vector from `self` with the given value of `w`.
    ///
    /// Mirrors `glam::UVec4::with_w`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn with_w(self: UVec4, w: u32) -> UVec4;
    /// Computes the dot product of `self` and `rhs`.
    ///
    /// Mirrors `glam::UVec4::dot`.
    /// #### Panics
    /// * `'UVec4: overflow'` if the result does not fit `u32`.
    /// #### Deviations
    /// * Only the final result is range-checked: an intermediate product or sum that
    ///   leaves the `u32` range does not panic when the result fits (glam-rs panics in
    ///   debug builds and wraps in release builds).
    fn dot(self: UVec4, rhs: UVec4) -> u32;
    /// Returns a vector where every component is the dot product of `self` and `rhs`.
    ///
    /// Mirrors `glam::UVec4::dot_into_vec`.
    /// #### Panics
    /// * `'UVec4: overflow'` if the result does not fit `u32`.
    /// #### Deviations
    /// * Only the final result is range-checked: an intermediate product or sum that
    ///   leaves the `u32` range does not panic when the result fits (glam-rs panics in
    ///   debug builds and wraps in release builds).
    fn dot_into_vec(self: UVec4, rhs: UVec4) -> UVec4;
    /// Returns a vector containing the minimum values for each element of `self` and
    /// `rhs`.
    ///
    /// In other words this computes `[min(x, rhs.x), min(self.y, rhs.y), ..]`.
    ///
    /// Mirrors `glam::UVec4::min`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn min(self: UVec4, rhs: UVec4) -> UVec4;
    /// Returns a vector containing the maximum values for each element of `self` and
    /// `rhs`.
    ///
    /// In other words this computes `[max(self.x, rhs.x), max(self.y, rhs.y), ..]`.
    ///
    /// Mirrors `glam::UVec4::max`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn max(self: UVec4, rhs: UVec4) -> UVec4;
    /// Component-wise clamping of values, similar to `u32::clamp`.
    ///
    /// Each element in `min` must be less-or-equal to the corresponding element in `max`.
    /// The direct if-chain is 10 to 30 % cheaper than composing `max` and `min`.
    ///
    /// Mirrors `glam::UVec4::clamp`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * The `glam_assert!(min <= max)` precondition is not checked. When it is violated
    ///   the result differs from the `self.max(min).min(max)` of glam-rs: an element below
    ///   `min` clamps to `min` (glam-rs: to `max`).
    fn clamp(self: UVec4, min: UVec4, max: UVec4) -> UVec4;
    /// Returns the horizontal minimum of `self`.
    ///
    /// In other words this computes `min(x, y, ..)`.
    ///
    /// Mirrors `glam::UVec4::min_element`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn min_element(self: UVec4) -> u32;
    /// Returns the horizontal maximum of `self`.
    ///
    /// In other words this computes `max(x, y, ..)`.
    ///
    /// Mirrors `glam::UVec4::max_element`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn max_element(self: UVec4) -> u32;
    /// Returns the index of the first minimum element of `self`.
    ///
    /// Mirrors `glam::UVec4::min_position`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn min_position(self: UVec4) -> usize;
    /// Returns the index of the first maximum element of `self`.
    ///
    /// Mirrors `glam::UVec4::max_position`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn max_position(self: UVec4) -> usize;
    /// Returns the sum of all elements of `self`.
    ///
    /// In other words, this computes `self.x + self.y + ..`.
    ///
    /// Mirrors `glam::UVec4::element_sum`.
    /// #### Panics
    /// * `'UVec4: overflow'` if the result does not fit `u32`.
    /// #### Deviations
    /// * Only the final result is range-checked: an intermediate product or sum that
    ///   leaves the `u32` range does not panic when the result fits (glam-rs panics in
    ///   debug builds and wraps in release builds).
    fn element_sum(self: UVec4) -> u32;
    /// Returns the product of all elements of `self`.
    ///
    /// In other words, this computes `self.x * self.y * ..`.
    ///
    /// Mirrors `glam::UVec4::element_product`.
    /// #### Panics
    /// * `'UVec4: overflow'` if the result does not fit `u32`.
    /// #### Deviations
    /// * Only the final result is range-checked: an intermediate product or sum that
    ///   leaves the `u32` range does not panic when the result fits (glam-rs panics in
    ///   debug builds and wraps in release builds).
    fn element_product(self: UVec4) -> u32;
    /// Returns a vector mask containing the result of a `==` comparison for each element
    /// of `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x == rhs.x, self.y == rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::UVec4::cmpeq`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmpeq(self: UVec4, rhs: UVec4) -> BVec4;
    /// Returns a vector mask containing the result of a `!=` comparison for each element
    /// of `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x != rhs.x, self.y != rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::UVec4::cmpne`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmpne(self: UVec4, rhs: UVec4) -> BVec4;
    /// Returns a vector mask containing the result of a `>=` comparison for each element
    /// of `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x >= rhs.x, self.y >= rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::UVec4::cmpge`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmpge(self: UVec4, rhs: UVec4) -> BVec4;
    /// Returns a vector mask containing the result of a `>` comparison for each element of
    /// `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x > rhs.x, self.y > rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::UVec4::cmpgt`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmpgt(self: UVec4, rhs: UVec4) -> BVec4;
    /// Returns a vector mask containing the result of a `<=` comparison for each element
    /// of `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x <= rhs.x, self.y <= rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::UVec4::cmple`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmple(self: UVec4, rhs: UVec4) -> BVec4;
    /// Returns a vector mask containing the result of a `<` comparison for each element of
    /// `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x < rhs.x, self.y < rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::UVec4::cmplt`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmplt(self: UVec4, rhs: UVec4) -> BVec4;
    /// Computes the squared length of `self`.
    ///
    /// Mirrors `glam::UVec4::length_squared`.
    /// #### Panics
    /// * `'UVec4: overflow'` if the result does not fit `u32`.
    /// #### Deviations
    /// * Only the final result is range-checked: an intermediate product or sum that
    ///   leaves the `u32` range does not panic when the result fits (glam-rs panics in
    ///   debug builds and wraps in release builds).
    fn length_squared(self: UVec4) -> u32;
    /// Computes the manhattan distance between two points.
    ///
    /// See also `checked_manhattan_distance`.
    ///
    /// Mirrors `glam::UVec4::manhattan_distance`.
    /// #### Panics
    /// * `'UVec4: overflow'` if the result does not fit `u32`.
    /// #### Deviations
    /// * None.
    fn manhattan_distance(self: UVec4, rhs: UVec4) -> u32;
    /// Computes the manhattan distance between two points.
    ///
    /// This will return `None` if the result is greater than `u32::MAX`.
    ///
    /// Mirrors `glam::UVec4::checked_manhattan_distance`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_manhattan_distance(self: UVec4, rhs: UVec4) -> Option<u32>;
    /// Computes the chebyshev distance between two points.
    ///
    /// Mirrors `glam::UVec4::chebyshev_distance`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn chebyshev_distance(self: UVec4, rhs: UVec4) -> u32;
    /// Casts all elements of `self` to `i32`.
    ///
    /// Like the Rust `as` cast this is the two's complement reinterpretation: `u32::MAX`
    /// becomes `-1`. The checked conversion is `TryInto<UVec4, IVec4>`.
    ///
    /// Mirrors `glam::UVec4::as_ivec4`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn as_ivec4(self: UVec4) -> IVec4;
    /// Returns a vector containing the checked addition of `self` and `rhs`.
    ///
    /// In other words this computes `Some([self.x + rhs.x, self.y + rhs.y, ..])` but
    /// returns `None` on any overflow.
    ///
    /// Mirrors `glam::UVec4::checked_add`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_add(self: UVec4, rhs: UVec4) -> Option<UVec4>;
    /// Returns a vector containing the checked subtraction of `self` and `rhs`.
    ///
    /// In other words this computes `Some([self.x - rhs.x, self.y - rhs.y, ..])` but
    /// returns `None` on any overflow.
    ///
    /// Mirrors `glam::UVec4::checked_sub`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_sub(self: UVec4, rhs: UVec4) -> Option<UVec4>;
    /// Returns a vector containing the checked multiplication of `self` and `rhs`.
    ///
    /// In other words this computes `Some([self.x * rhs.x, self.y * rhs.y, ..])` but
    /// returns `None` on any overflow.
    ///
    /// Mirrors `glam::UVec4::checked_mul`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_mul(self: UVec4, rhs: UVec4) -> Option<UVec4>;
    /// Returns a vector containing the checked division of `self` and `rhs`.
    ///
    /// In other words this computes `Some([self.x / rhs.x, self.y / rhs.y, ..])` but
    /// returns `None` on any division by zero.
    ///
    /// Mirrors `glam::UVec4::checked_div`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_div(self: UVec4, rhs: UVec4) -> Option<UVec4>;
    /// Returns a vector containing the wrapping addition of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.wrapping_add(rhs.x),
    /// self.y.wrapping_add(rhs.y), ..]`.
    ///
    /// Mirrors `glam::UVec4::wrapping_add`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn wrapping_add(self: UVec4, rhs: UVec4) -> UVec4;
    /// Returns a vector containing the wrapping subtraction of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.wrapping_sub(rhs.x),
    /// self.y.wrapping_sub(rhs.y), ..]`.
    ///
    /// Mirrors `glam::UVec4::wrapping_sub`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn wrapping_sub(self: UVec4, rhs: UVec4) -> UVec4;
    /// Returns a vector containing the wrapping multiplication of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.wrapping_mul(rhs.x),
    /// self.y.wrapping_mul(rhs.y), ..]`.
    ///
    /// Mirrors `glam::UVec4::wrapping_mul`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn wrapping_mul(self: UVec4, rhs: UVec4) -> UVec4;
    /// Returns a vector containing the wrapping division of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.wrapping_div(rhs.x),
    /// self.y.wrapping_div(rhs.y), ..]`.
    ///
    /// Mirrors `glam::UVec4::wrapping_div`.
    /// #### Panics
    /// * `'Division by 0'` if any `rhs` element is 0.
    /// #### Deviations
    /// * None.
    fn wrapping_div(self: UVec4, rhs: UVec4) -> UVec4;
    /// Returns a vector containing the saturating addition of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.saturating_add(rhs.x),
    /// self.y.saturating_add(rhs.y), ..]`.
    ///
    /// Mirrors `glam::UVec4::saturating_add`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn saturating_add(self: UVec4, rhs: UVec4) -> UVec4;
    /// Returns a vector containing the saturating subtraction of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.saturating_sub(rhs.x),
    /// self.y.saturating_sub(rhs.y), ..]`.
    ///
    /// Mirrors `glam::UVec4::saturating_sub`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn saturating_sub(self: UVec4, rhs: UVec4) -> UVec4;
    /// Returns a vector containing the saturating multiplication of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.saturating_mul(rhs.x),
    /// self.y.saturating_mul(rhs.y), ..]`.
    ///
    /// Mirrors `glam::UVec4::saturating_mul`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn saturating_mul(self: UVec4, rhs: UVec4) -> UVec4;
    /// Returns a vector containing the saturating division of `self` and `rhs`.
    ///
    /// In other words this computes `[self.x.saturating_div(rhs.x),
    /// self.y.saturating_div(rhs.y), ..]`.
    ///
    /// Mirrors `glam::UVec4::saturating_div`.
    /// #### Panics
    /// * `'Division by 0'` if any `rhs` element is 0.
    /// #### Deviations
    /// * None.
    fn saturating_div(self: UVec4, rhs: UVec4) -> UVec4;
    /// Returns a vector containing the checked addition of `self` and signed vector `rhs`.
    ///
    /// In other words this computes `Some([self.x + rhs.x, self.y + rhs.y, ..])` but
    /// returns `None` on any overflow.
    ///
    /// Mirrors `glam::UVec4::checked_add_signed`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn checked_add_signed(self: UVec4, rhs: IVec4) -> Option<UVec4>;
    /// Returns a vector containing the wrapping addition of `self` and signed vector
    /// `rhs`.
    ///
    /// In other words this computes `[self.x.wrapping_add_signed(rhs.x),
    /// self.y.wrapping_add_signed(rhs.y), ..]`.
    ///
    /// Mirrors `glam::UVec4::wrapping_add_signed`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn wrapping_add_signed(self: UVec4, rhs: IVec4) -> UVec4;
    /// Returns a vector containing the saturating addition of `self` and signed vector
    /// `rhs`.
    ///
    /// In other words this computes `[self.x.saturating_add_signed(rhs.x),
    /// self.y.saturating_add_signed(rhs.y), ..]`.
    ///
    /// Mirrors `glam::UVec4::saturating_add_signed`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn saturating_add_signed(self: UVec4, rhs: IVec4) -> UVec4;
    /// Returns `[self.x + rhs, self.y + rhs, ..]`.
    ///
    /// Mirrors `impl Add<u32> for glam::UVec4`.
    /// #### Panics
    /// * `'u32_add Overflow'` on overflow.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Add<u32> for UVec4`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    fn add_scalar(self: UVec4, rhs: u32) -> UVec4;
    /// Returns `[self.x - rhs, self.y - rhs, ..]`.
    ///
    /// Mirrors `impl Sub<u32> for glam::UVec4`.
    /// #### Panics
    /// * `'u32_sub Overflow'` on overflow.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Sub<u32> for UVec4`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    fn sub_scalar(self: UVec4, rhs: u32) -> UVec4;
    /// Returns `[self.x * rhs, self.y * rhs, ..]`.
    ///
    /// Mirrors `impl Mul<u32> for glam::UVec4`.
    /// #### Panics
    /// * `'u32_mul Overflow'` on overflow.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Mul<u32> for UVec4`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    fn mul_scalar(self: UVec4, rhs: u32) -> UVec4;
    /// Returns `[self.x / rhs, self.y / rhs, ..]` (truncated division).
    ///
    /// Mirrors `impl Div<u32> for glam::UVec4`.
    /// #### Panics
    /// * `'Division by 0'` if `rhs` is 0.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Div<u32> for UVec4`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    fn div_scalar(self: UVec4, rhs: u32) -> UVec4;
    /// Returns `[self.x % rhs, self.y % rhs, ..]` (the remainder has the sign of `self`).
    ///
    /// Mirrors `impl Rem<u32> for glam::UVec4`.
    /// #### Panics
    /// * `'Division by 0'` if `rhs` is 0.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Rem<u32> for UVec4`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    fn rem_scalar(self: UVec4, rhs: u32) -> UVec4;
    /// Shifts every element left by `rhs` bits: the bits shifted out are lost, as with the
    /// Rust `<<`.
    ///
    /// Mirrors `impl Shl<u32> for glam::UVec4`.
    /// #### Panics
    /// * `'UVec4: shift overflow'` if `rhs >= 32` (Rust: overflow panic in debug builds,
    ///   masked shift amount in release builds).
    /// #### Deviations
    /// * glam-rs spells this with an operator; Cairo has no shift operator nor trait. Only
    ///   the `u32` shift amount is ported (not the 8 integer widths nor the per-component
    ///   vector amounts).
    fn shl(self: UVec4, rhs: u32) -> UVec4;
    /// Shifts every element right by `rhs` bits (a division by `2^rhs`).
    ///
    /// Mirrors `impl Shr<u32> for glam::UVec4`.
    /// #### Panics
    /// * `'UVec4: shift overflow'` if `rhs >= 32` (Rust: overflow panic in debug builds,
    ///   masked shift amount in release builds).
    /// #### Deviations
    /// * glam-rs spells this with an operator; Cairo has no shift operator nor trait. Only
    ///   the `u32` shift amount is ported (not the 8 integer widths nor the per-component
    ///   vector amounts).
    fn shr(self: UVec4, rhs: u32) -> UVec4;
}

pub impl UVec4Impl of UVec4Trait {
    const ZERO: UVec4 = UVec4 { x: 0, y: 0, z: 0, w: 0 };
    const ONE: UVec4 = UVec4 { x: 1, y: 1, z: 1, w: 1 };
    const MIN: UVec4 = UVec4 { x: 0, y: 0, z: 0, w: 0 };
    const MAX: UVec4 = UVec4 { x: 0xffffffff, y: 0xffffffff, z: 0xffffffff, w: 0xffffffff };
    const X: UVec4 = UVec4 { x: 1, y: 0, z: 0, w: 0 };
    const Y: UVec4 = UVec4 { x: 0, y: 1, z: 0, w: 0 };
    const Z: UVec4 = UVec4 { x: 0, y: 0, z: 1, w: 0 };
    const W: UVec4 = UVec4 { x: 0, y: 0, z: 0, w: 1 };
    const AXES: [UVec4; 4] = [
        UVec4 { x: 1, y: 0, z: 0, w: 0 }, UVec4 { x: 0, y: 1, z: 0, w: 0 },
        UVec4 { x: 0, y: 0, z: 1, w: 0 }, UVec4 { x: 0, y: 0, z: 0, w: 1 },
    ];

    #[inline(always)]
    fn new(x: u32, y: u32, z: u32, w: u32) -> UVec4 {
        UVec4 { x, y, z, w }
    }

    #[inline(always)]
    fn splat(v: u32) -> UVec4 {
        UVec4 { x: v, y: v, z: v, w: v }
    }

    #[inline(always)]
    fn select(mask: BVec4, if_true: UVec4, if_false: UVec4) -> UVec4 {
        UVec4 {
            x: if mask.x {
                if_true.x
            } else {
                if_false.x
            },
            y: if mask.y {
                if_true.y
            } else {
                if_false.y
            },
            z: if mask.z {
                if_true.z
            } else {
                if_false.z
            },
            w: if mask.w {
                if_true.w
            } else {
                if_false.w
            },
        }
    }

    #[inline(always)]
    fn from_array(a: [u32; 4]) -> UVec4 {
        let [x, y, z, w] = a;
        UVec4 { x, y, z, w }
    }

    #[inline(always)]
    fn to_array(self: UVec4) -> [u32; 4] {
        [self.x, self.y, self.z, self.w]
    }

    #[inline(always)]
    fn truncate(self: UVec4) -> UVec3 {
        UVec3 { x: self.x, y: self.y, z: self.z }
    }

    #[inline(always)]
    fn with_x(self: UVec4, x: u32) -> UVec4 {
        UVec4 { x: x, y: self.y, z: self.z, w: self.w }
    }

    #[inline(always)]
    fn with_y(self: UVec4, y: u32) -> UVec4 {
        UVec4 { x: self.x, y: y, z: self.z, w: self.w }
    }

    #[inline(always)]
    fn with_z(self: UVec4, z: u32) -> UVec4 {
        UVec4 { x: self.x, y: self.y, z: z, w: self.w }
    }

    #[inline(always)]
    fn with_w(self: UVec4, w: u32) -> UVec4 {
        UVec4 { x: self.x, y: self.y, z: self.z, w: w }
    }

    #[inline(always)]
    fn dot(self: UVec4, rhs: UVec4) -> u32 {
        let d: felt252 = self.x.wide_mul(rhs.x).into()
            + self.y.wide_mul(rhs.y).into()
            + self.z.wide_mul(rhs.z).into()
            + self.w.wide_mul(rhs.w).into();
        d.try_into().expect('UVec4: overflow')
    }

    #[inline(always)]
    fn dot_into_vec(self: UVec4, rhs: UVec4) -> UVec4 {
        let d = Self::dot(self, rhs);
        UVec4 { x: d, y: d, z: d, w: d }
    }

    #[inline(always)]
    fn min(self: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 {
            x: if self.x < rhs.x {
                self.x
            } else {
                rhs.x
            },
            y: if self.y < rhs.y {
                self.y
            } else {
                rhs.y
            },
            z: if self.z < rhs.z {
                self.z
            } else {
                rhs.z
            },
            w: if self.w < rhs.w {
                self.w
            } else {
                rhs.w
            },
        }
    }

    #[inline(always)]
    fn max(self: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 {
            x: if self.x > rhs.x {
                self.x
            } else {
                rhs.x
            },
            y: if self.y > rhs.y {
                self.y
            } else {
                rhs.y
            },
            z: if self.z > rhs.z {
                self.z
            } else {
                rhs.z
            },
            w: if self.w > rhs.w {
                self.w
            } else {
                rhs.w
            },
        }
    }

    #[inline(always)]
    fn clamp(self: UVec4, min: UVec4, max: UVec4) -> UVec4 {
        UVec4 {
            x: if self.x < min.x {
                min.x
            } else if self.x > max.x {
                max.x
            } else {
                self.x
            },
            y: if self.y < min.y {
                min.y
            } else if self.y > max.y {
                max.y
            } else {
                self.y
            },
            z: if self.z < min.z {
                min.z
            } else if self.z > max.z {
                max.z
            } else {
                self.z
            },
            w: if self.w < min.w {
                min.w
            } else if self.w > max.w {
                max.w
            } else {
                self.w
            },
        }
    }

    #[inline(always)]
    fn min_element(self: UVec4) -> u32 {
        let m = if self.z < self.w {
            self.z
        } else {
            self.w
        };
        let m = if self.y < m {
            self.y
        } else {
            m
        };
        let m = if self.x < m {
            self.x
        } else {
            m
        };
        m
    }

    #[inline(always)]
    fn max_element(self: UVec4) -> u32 {
        let m = if self.z > self.w {
            self.z
        } else {
            self.w
        };
        let m = if self.y > m {
            self.y
        } else {
            m
        };
        let m = if self.x > m {
            self.x
        } else {
            m
        };
        m
    }

    #[inline(always)]
    fn min_position(self: UVec4) -> usize {
        let mut m = self.x;
        let mut index = 0;
        if self.y < m {
            m = self.y;
            index = 1;
        }
        if self.z < m {
            m = self.z;
            index = 2;
        }
        if self.w < m {
            index = 3;
        }
        index
    }

    #[inline(always)]
    fn max_position(self: UVec4) -> usize {
        let mut m = self.x;
        let mut index = 0;
        if self.y > m {
            m = self.y;
            index = 1;
        }
        if self.z > m {
            m = self.z;
            index = 2;
        }
        if self.w > m {
            index = 3;
        }
        index
    }

    #[inline(always)]
    fn element_sum(self: UVec4) -> u32 {
        let s: felt252 = self.x.into() + self.y.into() + self.z.into() + self.w.into();
        s.try_into().expect('UVec4: overflow')
    }

    #[inline(always)]
    fn element_product(self: UVec4) -> u32 {
        let p: felt252 = self.x.into() * self.y.into() * self.z.into() * self.w.into();
        p.try_into().expect('UVec4: overflow')
    }

    #[inline(always)]
    fn cmpeq(self: UVec4, rhs: UVec4) -> BVec4 {
        BVec4 { x: self.x == rhs.x, y: self.y == rhs.y, z: self.z == rhs.z, w: self.w == rhs.w }
    }

    #[inline(always)]
    fn cmpne(self: UVec4, rhs: UVec4) -> BVec4 {
        BVec4 { x: self.x != rhs.x, y: self.y != rhs.y, z: self.z != rhs.z, w: self.w != rhs.w }
    }

    #[inline(always)]
    fn cmpge(self: UVec4, rhs: UVec4) -> BVec4 {
        BVec4 { x: self.x >= rhs.x, y: self.y >= rhs.y, z: self.z >= rhs.z, w: self.w >= rhs.w }
    }

    #[inline(always)]
    fn cmpgt(self: UVec4, rhs: UVec4) -> BVec4 {
        BVec4 { x: self.x > rhs.x, y: self.y > rhs.y, z: self.z > rhs.z, w: self.w > rhs.w }
    }

    #[inline(always)]
    fn cmple(self: UVec4, rhs: UVec4) -> BVec4 {
        BVec4 { x: self.x <= rhs.x, y: self.y <= rhs.y, z: self.z <= rhs.z, w: self.w <= rhs.w }
    }

    #[inline(always)]
    fn cmplt(self: UVec4, rhs: UVec4) -> BVec4 {
        BVec4 { x: self.x < rhs.x, y: self.y < rhs.y, z: self.z < rhs.z, w: self.w < rhs.w }
    }

    #[inline(always)]
    fn length_squared(self: UVec4) -> u32 {
        let d: felt252 = self.x.wide_mul(self.x).into()
            + self.y.wide_mul(self.y).into()
            + self.z.wide_mul(self.z).into()
            + self.w.wide_mul(self.w).into();
        d.try_into().expect('UVec4: overflow')
    }

    #[inline(always)]
    fn manhattan_distance(self: UVec4, rhs: UVec4) -> u32 {
        let d: felt252 = abs_diff_u32(self.x, rhs.x).into()
            + abs_diff_u32(self.y, rhs.y).into()
            + abs_diff_u32(self.z, rhs.z).into()
            + abs_diff_u32(self.w, rhs.w).into();
        d.try_into().expect('UVec4: overflow')
    }

    #[inline(always)]
    fn checked_manhattan_distance(self: UVec4, rhs: UVec4) -> Option<u32> {
        let d: felt252 = abs_diff_u32(self.x, rhs.x).into()
            + abs_diff_u32(self.y, rhs.y).into()
            + abs_diff_u32(self.z, rhs.z).into()
            + abs_diff_u32(self.w, rhs.w).into();
        d.try_into()
    }

    #[inline(always)]
    fn chebyshev_distance(self: UVec4, rhs: UVec4) -> u32 {
        let m = abs_diff_u32(self.x, rhs.x);
        let d = abs_diff_u32(self.y, rhs.y);
        let m = if d > m {
            d
        } else {
            m
        };
        let d = abs_diff_u32(self.z, rhs.z);
        let m = if d > m {
            d
        } else {
            m
        };
        let d = abs_diff_u32(self.w, rhs.w);
        let m = if d > m {
            d
        } else {
            m
        };
        m
    }

    #[inline(always)]
    fn as_ivec4(self: UVec4) -> IVec4 {
        IVec4 {
            x: u32_as_i32(self.x),
            y: u32_as_i32(self.y),
            z: u32_as_i32(self.z),
            w: u32_as_i32(self.w),
        }
    }

    #[inline(always)]
    fn checked_add(self: UVec4, rhs: UVec4) -> Option<UVec4> {
        Some(
            UVec4 {
                x: self.x.checked_add(rhs.x)?,
                y: self.y.checked_add(rhs.y)?,
                z: self.z.checked_add(rhs.z)?,
                w: self.w.checked_add(rhs.w)?,
            },
        )
    }

    #[inline(always)]
    fn checked_sub(self: UVec4, rhs: UVec4) -> Option<UVec4> {
        Some(
            UVec4 {
                x: self.x.checked_sub(rhs.x)?,
                y: self.y.checked_sub(rhs.y)?,
                z: self.z.checked_sub(rhs.z)?,
                w: self.w.checked_sub(rhs.w)?,
            },
        )
    }

    #[inline(always)]
    fn checked_mul(self: UVec4, rhs: UVec4) -> Option<UVec4> {
        Some(
            UVec4 {
                x: checked_mul_u32(self.x, rhs.x)?,
                y: checked_mul_u32(self.y, rhs.y)?,
                z: checked_mul_u32(self.z, rhs.z)?,
                w: checked_mul_u32(self.w, rhs.w)?,
            },
        )
    }

    #[inline(always)]
    fn checked_div(self: UVec4, rhs: UVec4) -> Option<UVec4> {
        Some(
            UVec4 {
                x: checked_div_u32(self.x, rhs.x)?,
                y: checked_div_u32(self.y, rhs.y)?,
                z: checked_div_u32(self.z, rhs.z)?,
                w: checked_div_u32(self.w, rhs.w)?,
            },
        )
    }

    #[inline(always)]
    fn wrapping_add(self: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 {
            x: self.x.wrapping_add(rhs.x),
            y: self.y.wrapping_add(rhs.y),
            z: self.z.wrapping_add(rhs.z),
            w: self.w.wrapping_add(rhs.w),
        }
    }

    #[inline(always)]
    fn wrapping_sub(self: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 {
            x: self.x.wrapping_sub(rhs.x),
            y: self.y.wrapping_sub(rhs.y),
            z: self.z.wrapping_sub(rhs.z),
            w: self.w.wrapping_sub(rhs.w),
        }
    }

    #[inline(always)]
    fn wrapping_mul(self: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 {
            x: self.x.wrapping_mul(rhs.x),
            y: self.y.wrapping_mul(rhs.y),
            z: self.z.wrapping_mul(rhs.z),
            w: self.w.wrapping_mul(rhs.w),
        }
    }

    #[inline(always)]
    fn wrapping_div(self: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 { x: self.x / rhs.x, y: self.y / rhs.y, z: self.z / rhs.z, w: self.w / rhs.w }
    }

    #[inline(always)]
    fn saturating_add(self: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 {
            x: self.x.saturating_add(rhs.x),
            y: self.y.saturating_add(rhs.y),
            z: self.z.saturating_add(rhs.z),
            w: self.w.saturating_add(rhs.w),
        }
    }

    #[inline(always)]
    fn saturating_sub(self: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 {
            x: self.x.saturating_sub(rhs.x),
            y: self.y.saturating_sub(rhs.y),
            z: self.z.saturating_sub(rhs.z),
            w: self.w.saturating_sub(rhs.w),
        }
    }

    #[inline(always)]
    fn saturating_mul(self: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 {
            x: saturating_mul_u32(self.x, rhs.x),
            y: saturating_mul_u32(self.y, rhs.y),
            z: saturating_mul_u32(self.z, rhs.z),
            w: saturating_mul_u32(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn saturating_div(self: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 { x: self.x / rhs.x, y: self.y / rhs.y, z: self.z / rhs.z, w: self.w / rhs.w }
    }

    #[inline(always)]
    fn checked_add_signed(self: UVec4, rhs: IVec4) -> Option<UVec4> {
        Some(
            UVec4 {
                x: checked_add_signed(self.x, rhs.x)?,
                y: checked_add_signed(self.y, rhs.y)?,
                z: checked_add_signed(self.z, rhs.z)?,
                w: checked_add_signed(self.w, rhs.w)?,
            },
        )
    }

    #[inline(always)]
    fn wrapping_add_signed(self: UVec4, rhs: IVec4) -> UVec4 {
        UVec4 {
            x: wrapping_add_signed(self.x, rhs.x),
            y: wrapping_add_signed(self.y, rhs.y),
            z: wrapping_add_signed(self.z, rhs.z),
            w: wrapping_add_signed(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn saturating_add_signed(self: UVec4, rhs: IVec4) -> UVec4 {
        UVec4 {
            x: saturating_add_signed(self.x, rhs.x),
            y: saturating_add_signed(self.y, rhs.y),
            z: saturating_add_signed(self.z, rhs.z),
            w: saturating_add_signed(self.w, rhs.w),
        }
    }

    #[inline(always)]
    fn add_scalar(self: UVec4, rhs: u32) -> UVec4 {
        UVec4 { x: self.x + rhs, y: self.y + rhs, z: self.z + rhs, w: self.w + rhs }
    }

    #[inline(always)]
    fn sub_scalar(self: UVec4, rhs: u32) -> UVec4 {
        UVec4 { x: self.x - rhs, y: self.y - rhs, z: self.z - rhs, w: self.w - rhs }
    }

    #[inline(always)]
    fn mul_scalar(self: UVec4, rhs: u32) -> UVec4 {
        UVec4 { x: self.x * rhs, y: self.y * rhs, z: self.z * rhs, w: self.w * rhs }
    }

    #[inline(always)]
    fn div_scalar(self: UVec4, rhs: u32) -> UVec4 {
        let d: NonZero<u32> = rhs.try_into().expect('Division by 0');
        let (x, _) = DivRem::div_rem(self.x, d);
        let (y, _) = DivRem::div_rem(self.y, d);
        let (z, _) = DivRem::div_rem(self.z, d);
        let (w, _) = DivRem::div_rem(self.w, d);
        UVec4 { x, y, z, w }
    }

    #[inline(always)]
    fn rem_scalar(self: UVec4, rhs: u32) -> UVec4 {
        let d: NonZero<u32> = rhs.try_into().expect('Division by 0');
        let (_, x) = DivRem::div_rem(self.x, d);
        let (_, y) = DivRem::div_rem(self.y, d);
        let (_, z) = DivRem::div_rem(self.z, d);
        let (_, w) = DivRem::div_rem(self.w, d);
        UVec4 { x, y, z, w }
    }

    #[inline(always)]
    fn shl(self: UVec4, rhs: u32) -> UVec4 {
        let p = pow2(rhs);
        UVec4 {
            x: shl_u32(self.x, p),
            y: shl_u32(self.y, p),
            z: shl_u32(self.z, p),
            w: shl_u32(self.w, p),
        }
    }

    #[inline(always)]
    fn shr(self: UVec4, rhs: u32) -> UVec4 {
        let p: NonZero<u32> = pow2(rhs).try_into().unwrap();
        let (x, _) = DivRem::div_rem(self.x, p);
        let (y, _) = DivRem::div_rem(self.y, p);
        let (z, _) = DivRem::div_rem(self.z, p);
        let (w, _) = DivRem::div_rem(self.w, p);
        UVec4 { x, y, z, w }
    }
}

/// Component-wise `+`. Panics with the corelib `u32_add` overflow messages.
///
/// Mirrors `impl Add for glam::UVec4`.
pub impl UVec4Add of Add<UVec4> {
    #[inline(always)]
    fn add(lhs: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 { x: lhs.x + rhs.x, y: lhs.y + rhs.y, z: lhs.z + rhs.z, w: lhs.w + rhs.w }
    }
}

/// Component-wise `-`. Panics with the corelib `u32_sub` overflow messages.
///
/// Mirrors `impl Sub for glam::UVec4`.
pub impl UVec4Sub of Sub<UVec4> {
    #[inline(always)]
    fn sub(lhs: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 { x: lhs.x - rhs.x, y: lhs.y - rhs.y, z: lhs.z - rhs.z, w: lhs.w - rhs.w }
    }
}

/// Component-wise `*`. Panics with `'u32_mul Overflow'`.
///
/// Mirrors `impl Mul for glam::UVec4`.
pub impl UVec4Mul of Mul<UVec4> {
    #[inline(always)]
    fn mul(lhs: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 { x: lhs.x * rhs.x, y: lhs.y * rhs.y, z: lhs.z * rhs.z, w: lhs.w * rhs.w }
    }
}

/// Component-wise `/`. Truncated division. Panics with `'Division by 0'`.
///
/// Mirrors `impl Div for glam::UVec4`.
pub impl UVec4Div of Div<UVec4> {
    #[inline(always)]
    fn div(lhs: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 { x: lhs.x / rhs.x, y: lhs.y / rhs.y, z: lhs.z / rhs.z, w: lhs.w / rhs.w }
    }
}

/// Component-wise `%`. The remainder has the sign of `lhs`. Panics with `'Division by 0'`.
///
/// Mirrors `impl Rem for glam::UVec4`.
pub impl UVec4Rem of Rem<UVec4> {
    #[inline(always)]
    fn rem(lhs: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 { x: lhs.x % rhs.x, y: lhs.y % rhs.y, z: lhs.z % rhs.z, w: lhs.w % rhs.w }
    }
}

/// Mirrors `impl AddAssign for glam::UVec4`.
pub impl UVec4AddAssign of AddAssign<UVec4, UVec4> {
    #[inline(always)]
    fn add_assign(ref self: UVec4, rhs: UVec4) {
        self = self + rhs;
    }
}

/// Mirrors `impl SubAssign for glam::UVec4`.
pub impl UVec4SubAssign of SubAssign<UVec4, UVec4> {
    #[inline(always)]
    fn sub_assign(ref self: UVec4, rhs: UVec4) {
        self = self - rhs;
    }
}

/// Mirrors `impl MulAssign for glam::UVec4`.
pub impl UVec4MulAssign of MulAssign<UVec4, UVec4> {
    #[inline(always)]
    fn mul_assign(ref self: UVec4, rhs: UVec4) {
        self = self * rhs;
    }
}

/// Mirrors `impl DivAssign for glam::UVec4`.
pub impl UVec4DivAssign of DivAssign<UVec4, UVec4> {
    #[inline(always)]
    fn div_assign(ref self: UVec4, rhs: UVec4) {
        self = self / rhs;
    }
}

/// Mirrors `impl RemAssign for glam::UVec4`.
pub impl UVec4RemAssign of RemAssign<UVec4, UVec4> {
    #[inline(always)]
    fn rem_assign(ref self: UVec4, rhs: UVec4) {
        self = self % rhs;
    }
}

/// Mirrors `impl AddAssign<u32> for glam::UVec4` (see `UVec4Trait::add_scalar`).
pub impl UVec4AddAssignScalar of AddAssign<UVec4, u32> {
    #[inline(always)]
    fn add_assign(ref self: UVec4, rhs: u32) {
        self = UVec4Trait::add_scalar(self, rhs);
    }
}

/// Mirrors `impl SubAssign<u32> for glam::UVec4` (see `UVec4Trait::sub_scalar`).
pub impl UVec4SubAssignScalar of SubAssign<UVec4, u32> {
    #[inline(always)]
    fn sub_assign(ref self: UVec4, rhs: u32) {
        self = UVec4Trait::sub_scalar(self, rhs);
    }
}

/// Mirrors `impl MulAssign<u32> for glam::UVec4` (see `UVec4Trait::mul_scalar`).
pub impl UVec4MulAssignScalar of MulAssign<UVec4, u32> {
    #[inline(always)]
    fn mul_assign(ref self: UVec4, rhs: u32) {
        self = UVec4Trait::mul_scalar(self, rhs);
    }
}

/// Mirrors `impl DivAssign<u32> for glam::UVec4` (see `UVec4Trait::div_scalar`).
pub impl UVec4DivAssignScalar of DivAssign<UVec4, u32> {
    #[inline(always)]
    fn div_assign(ref self: UVec4, rhs: u32) {
        self = UVec4Trait::div_scalar(self, rhs);
    }
}

/// Mirrors `impl RemAssign<u32> for glam::UVec4` (see `UVec4Trait::rem_scalar`).
pub impl UVec4RemAssignScalar of RemAssign<UVec4, u32> {
    #[inline(always)]
    fn rem_assign(ref self: UVec4, rhs: u32) {
        self = UVec4Trait::rem_scalar(self, rhs);
    }
}

/// Component-wise bitwise `&`. One bitwise builtin cell per component.
///
/// Mirrors `impl BitAnd for glam::UVec4`.
pub impl UVec4BitAnd of BitAnd<UVec4> {
    #[inline(always)]
    fn bitand(lhs: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 { x: lhs.x & rhs.x, y: lhs.y & rhs.y, z: lhs.z & rhs.z, w: lhs.w & rhs.w }
    }
}

/// Component-wise bitwise `|`. One bitwise builtin cell per component.
///
/// Mirrors `impl BitOr for glam::UVec4`.
pub impl UVec4BitOr of BitOr<UVec4> {
    #[inline(always)]
    fn bitor(lhs: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 { x: lhs.x | rhs.x, y: lhs.y | rhs.y, z: lhs.z | rhs.z, w: lhs.w | rhs.w }
    }
}

/// Component-wise bitwise `^`. One bitwise builtin cell per component.
///
/// Mirrors `impl BitXor for glam::UVec4`.
pub impl UVec4BitXor of BitXor<UVec4> {
    #[inline(always)]
    fn bitxor(lhs: UVec4, rhs: UVec4) -> UVec4 {
        UVec4 { x: lhs.x ^ rhs.x, y: lhs.y ^ rhs.y, z: lhs.z ^ rhs.z, w: lhs.w ^ rhs.w }
    }
}

/// Component-wise bitwise NOT (`~v`). No bitwise builtin.
///
/// Mirrors `impl Not for glam::UVec4` (the Rust `!v`; Cairo spells the bitwise
/// complement of an integer `~`).
pub impl UVec4BitNot of BitNot<UVec4> {
    #[inline(always)]
    fn bitnot(a: UVec4) -> UVec4 {
        UVec4 { x: ~a.x, y: ~a.y, z: ~a.z, w: ~a.w }
    }
}

/// `v[i]`. Panics with `'UVec4: index out of bounds'` if `index >= 4`.
///
/// Mirrors `impl Index<usize> for glam::UVec4`.
/// #### Panics
/// * `'UVec4: index out of bounds'` if `index >= 4`.
/// #### Deviations
/// * `IndexView` returns the element by value; `IndexMut` is not ported (see the struct).
/// * The panic message is the `felt252` `'UVec4: index out of bounds'` (glam-rs panics with
///   `index out of bounds`).
pub impl UVec4IndexView of IndexView<UVec4, usize> {
    type Target = u32;
    #[inline(always)]
    fn index(self: @UVec4, index: usize) -> u32 {
        match index {
            0 => *self.x,
            1 => *self.y,
            2 => *self.z,
            3 => *self.w,
            _ => core::panic_with_felt252('UVec4: index out of bounds'),
        }
    }
}

/// Mirrors `impl From<[u32; 4]> for glam::UVec4`.
pub impl U32ArrayIntoUVec4 of Into<[u32; 4], UVec4> {
    #[inline(always)]
    fn into(self: [u32; 4]) -> UVec4 {
        UVec4Trait::from_array(self)
    }
}

/// Mirrors `impl From<glam::UVec4> for [u32; 4]`.
pub impl UVec4IntoU32Array of Into<UVec4, [u32; 4]> {
    #[inline(always)]
    fn into(self: UVec4) -> [u32; 4] {
        [self.x, self.y, self.z, self.w]
    }
}

/// Mirrors `impl From<(u32, u32, u32, u32)> for glam::UVec4`.
pub impl U32TupleIntoUVec4 of Into<(u32, u32, u32, u32), UVec4> {
    #[inline(always)]
    fn into(self: (u32, u32, u32, u32)) -> UVec4 {
        let (x, y, z, w) = self;
        UVec4 { x, y, z, w }
    }
}

/// Mirrors `impl From<glam::UVec4> for (u32, u32, u32, u32)`.
pub impl UVec4IntoU32Tuple of Into<UVec4, (u32, u32, u32, u32)> {
    #[inline(always)]
    fn into(self: UVec4) -> (u32, u32, u32, u32) {
        (self.x, self.y, self.z, self.w)
    }
}

/// Mirrors `impl From<(UVec3, u32)> for glam::UVec4`.
pub impl UVec3U32IntoUVec4 of Into<(UVec3, u32), UVec4> {
    #[inline(always)]
    fn into(self: (UVec3, u32)) -> UVec4 {
        let (v, w) = self;
        UVec4 { x: v.x, y: v.y, z: v.z, w }
    }
}

/// Mirrors `impl From<(u32, UVec3)> for glam::UVec4`.
pub impl U32UVec3IntoUVec4 of Into<(u32, UVec3), UVec4> {
    #[inline(always)]
    fn into(self: (u32, UVec3)) -> UVec4 {
        let (x, v) = self;
        UVec4 { x, y: v.x, z: v.y, w: v.z }
    }
}

/// Mirrors `impl From<(UVec2, u32, u32)> for glam::UVec4`.
pub impl UVec2U32U32IntoUVec4 of Into<(UVec2, u32, u32), UVec4> {
    #[inline(always)]
    fn into(self: (UVec2, u32, u32)) -> UVec4 {
        let (v, z, w) = self;
        UVec4 { x: v.x, y: v.y, z, w }
    }
}

/// Mirrors `impl From<(UVec2, UVec2)> for glam::UVec4`.
pub impl UVec2UVec2IntoUVec4 of Into<(UVec2, UVec2), UVec4> {
    #[inline(always)]
    fn into(self: (UVec2, UVec2)) -> UVec4 {
        let (v, u) = self;
        UVec4 { x: v.x, y: v.y, z: u.x, w: u.y }
    }
}

/// `true` maps to 1 and `false` to 0.
///
/// Mirrors `impl From<BVec4> for glam::UVec4`.
pub impl BVec4IntoUVec4 of Into<BVec4, UVec4> {
    #[inline(always)]
    fn into(self: BVec4) -> UVec4 {
        UVec4 {
            x: if self.x {
                1
            } else {
                0
            },
            y: if self.y {
                1
            } else {
                0
            },
            z: if self.z {
                1
            } else {
                0
            },
            w: if self.w {
                1
            } else {
                0
            },
        }
    }
}

/// Checked conversion: `None` if an element does not fit `u32`.
///
/// Mirrors `impl TryFrom<IVec4> for glam::UVec4`.
pub impl IVec4TryIntoUVec4 of TryInto<IVec4, UVec4> {
    #[inline(always)]
    fn try_into(self: IVec4) -> Option<UVec4> {
        Some(
            UVec4 {
                x: self.x.try_into()?,
                y: self.y.try_into()?,
                z: self.z.try_into()?,
                w: self.w.try_into()?,
            },
        )
    }
}

/// `2^n`. Shifts are a multiplication / division by a power of two taken from a jump table
/// (a runtime `pow(2, n)` costs ~10 000 gas more, a `const` array lookup ~200 more).
#[inline(always)]
fn pow2(n: u32) -> u32 {
    match n {
        0 => 0x1,
        1 => 0x2,
        2 => 0x4,
        3 => 0x8,
        4 => 0x10,
        5 => 0x20,
        6 => 0x40,
        7 => 0x80,
        8 => 0x100,
        9 => 0x200,
        10 => 0x400,
        11 => 0x800,
        12 => 0x1000,
        13 => 0x2000,
        14 => 0x4000,
        15 => 0x8000,
        16 => 0x10000,
        17 => 0x20000,
        18 => 0x40000,
        19 => 0x80000,
        20 => 0x100000,
        21 => 0x200000,
        22 => 0x400000,
        23 => 0x800000,
        24 => 0x1000000,
        25 => 0x2000000,
        26 => 0x4000000,
        27 => 0x8000000,
        28 => 0x10000000,
        29 => 0x20000000,
        30 => 0x40000000,
        31 => 0x80000000,
        _ => core::panic_with_felt252('UVec4: shift overflow'),
    }
}

/// `(a << n) mod 2^32` with `p = 2^n`: widening multiplication, then the low 32 bits.
#[inline(always)]
fn shl_u32(a: u32, p: u32) -> u32 {
    let (_, lo) = DivRem::div_rem(a.wide_mul(p), 0x100000000);
    lo.try_into().unwrap()
}

/// Two's complement reinterpretation: `a - 2^32` when `a >= 2^31`.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn u32_as_i32(a: u32) -> i32 {
    match a.try_into() {
        Some(v) => v,
        None => {
            let f: felt252 = a.into();
            (f - 0x100000000).try_into().unwrap()
        },
    }
}

/// `|a - b|` (never overflows): `checked_sub` is the comparison and the subtraction at once.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn abs_diff_u32(a: u32, b: u32) -> u32 {
    match a.checked_sub(b) {
        Some(d) => d,
        None => b - a,
    }
}

/// `wide_mul` (1 step) and a downcast: cheaper than the corelib `CheckedMul`.
#[inline(always)]
fn checked_mul_u32(a: u32, b: u32) -> Option<u32> {
    a.wide_mul(b).try_into()
}

/// `wide_mul` (1 step) and a downcast: cheaper than the corelib `SaturatingMul`.
#[inline(always)]
fn saturating_mul_u32(a: u32, b: u32) -> u32 {
    a.wide_mul(b).try_into().unwrap_or(0xffffffff)
}

#[allow(manual_unwrap_or)]
#[inline(always)]
fn checked_div_u32(a: u32, b: u32) -> Option<u32> {
    match TryInto::<u32, NonZero<u32>>::try_into(b) {
        Some(d) => {
            let (q, _) = DivRem::div_rem(a, d);
            Some(q)
        },
        None => None,
    }
}

#[inline(always)]
fn checked_add_signed(a: u32, b: i32) -> Option<u32> {
    let s: felt252 = a.into() + b.into();
    s.try_into()
}

/// `-2^31 <= a + b < 2^32 + 2^31`: at most one wrap, in the direction of the sign of `b`.
#[allow(manual_unwrap_or)]
#[inline(always)]
fn wrapping_add_signed(a: u32, b: i32) -> u32 {
    let s: felt252 = a.into() + b.into();
    match s.try_into() {
        Some(v) => v,
        None => if b < 0 {
            (s + 0x100000000).try_into().unwrap()
        } else {
            (s - 0x100000000).try_into().unwrap()
        },
    }
}

#[allow(manual_unwrap_or)]
#[inline(always)]
fn saturating_add_signed(a: u32, b: i32) -> u32 {
    let s: felt252 = a.into() + b.into();
    match s.try_into() {
        Some(v) => v,
        None => if b < 0 {
            0
        } else {
            0xffffffff
        },
    }
}
