// GENERATED by tools/codegen/fvec.py - do not edit by hand.
//! Port of glam-rs `f32/vec3.rs` @ 0.33.8 on the Q32.32 scalar: a 3-dimensional
//! `fixed::Fixed` vector.
//!
//! The three fixed-point vector modules are generated from one template
//! (`tools/codegen/fvec.py`), as in glam-rs. Every product goes through a fused kernel of
//! `fixed::wide` (one rescale per output scalar, docs/DESIGN.md section 2.1) and every
//! formulation is the cheapest of the candidates measured in `gas/vec3.snap`; the losing
//! candidates live in `benches::alt::vec3`.
//!
//! There is no NaN and no infinity: overflow, division by zero and the normalization of the zero
//! vector panic (docs/DESIGN.md section 3).

use core::ops::index::IndexView;
use core::ops::{AddAssign, DivAssign, MulAssign, RemAssign, SubAssign};
use fixed::exp::ExpTrait;
use fixed::fixed::{Fixed, FixedTrait, PI};
use fixed::trig::TrigTrait;
use fixed::wide::{
    Norm, NormTrait, RecipTrait, WideAdd, WideLift, WideMul, WideNarrow, WideSub, det3, distance3,
    distance3_squared, dot2, dot3, is_unit3, mul_add, mul_sub, norm3, norm3_squared, norm3_wide,
    wide_from, wide_mul,
};
use crate::bvec3::{BVec3, BVec3Trait};
use crate::ivec3::IVec3;
use crate::quat::QuatTrait;
use crate::uvec3::UVec3;
use crate::vec2::Vec2;
use crate::vec4::Vec4;

/// A 3-dimensional vector of Q32.32 fixed-point scalars.
///
/// Mirrors `glam::Vec3`.
/// #### Deviations
/// * `Debug` is the derived Cairo formatting; `Display` is not implemented.
/// * No `NAN` / `INFINITY` / `NEG_INFINITY` consts and no `is_nan` / `is_finite` /
///   `is_nan_mask` / `is_finite_mask`: those values do not exist (docs/DESIGN.md section 3).
/// * Not ported: `map` (a closure parameter cannot be force-inlined, E2143), `from_slice` /
///   `write_to_slice` (no `Span` in fixed-size math), `Sum` / `Product` (no iterator trait to
///   implement), `IndexMut`, the by-reference operator overloads, the scalar-on-the-left
///   operators (`2.0 * v`) and the casts to types that do not exist in glam.cairo
///   (`as_dvec3`, `as_i8vec3`, ...).
#[derive(Copy, Drop, Serde, PartialEq, Debug, Default, Hash)]
pub struct Vec3 {
    pub x: Fixed,
    pub y: Fixed,
    pub z: Fixed,
}

/// Creates a 3-dimensional vector.
///
/// Mirrors `glam::vec3`.
/// #### Panics
/// * Never.
/// #### Deviations
/// * None.
#[inline(always)]
pub fn vec3(x: Fixed, y: Fixed, z: Fixed) -> Vec3 {
    Vec3 { x, y, z }
}

pub trait Vec3Trait {
    /// All zeroes.
    ///
    /// Mirrors `glam::Vec3::ZERO`.
    const ZERO: Vec3;
    /// All ones.
    ///
    /// Mirrors `glam::Vec3::ONE`.
    const ONE: Vec3;
    /// All negative ones.
    ///
    /// Mirrors `glam::Vec3::NEG_ONE`.
    const NEG_ONE: Vec3;
    /// All `Fixed::MIN` (`-2^31`).
    ///
    /// Mirrors `glam::Vec3::MIN`.
    const MIN: Vec3;
    /// All `Fixed::MAX` (`2^31 - 2^-32`).
    ///
    /// Mirrors `glam::Vec3::MAX`.
    const MAX: Vec3;
    /// A unit vector pointing along the positive X axis.
    ///
    /// Mirrors `glam::Vec3::X`.
    const X: Vec3;
    /// A unit vector pointing along the positive Y axis.
    ///
    /// Mirrors `glam::Vec3::Y`.
    const Y: Vec3;
    /// A unit vector pointing along the positive Z axis.
    ///
    /// Mirrors `glam::Vec3::Z`.
    const Z: Vec3;
    /// A unit vector pointing along the negative X axis.
    ///
    /// Mirrors `glam::Vec3::NEG_X`.
    const NEG_X: Vec3;
    /// A unit vector pointing along the negative Y axis.
    ///
    /// Mirrors `glam::Vec3::NEG_Y`.
    const NEG_Y: Vec3;
    /// A unit vector pointing along the negative Z axis.
    ///
    /// Mirrors `glam::Vec3::NEG_Z`.
    const NEG_Z: Vec3;
    /// The unit axes.
    ///
    /// Mirrors `glam::Vec3::AXES`.
    const AXES: [Vec3; 3];
    /// Creates a new vector.
    ///
    /// Mirrors `glam::Vec3::new`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn new(x: Fixed, y: Fixed, z: Fixed) -> Vec3;
    /// Creates a vector with all elements set to `v`.
    ///
    /// Mirrors `glam::Vec3::splat`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn splat(v: Fixed) -> Vec3;
    /// Creates a vector from the elements in `if_true` and `if_false`, selecting which to
    /// use for each element of `self`.
    ///
    /// A true element in the mask uses the corresponding element from `if_true`, and false
    /// uses the element from `if_false`.
    ///
    /// Mirrors `glam::Vec3::select`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn select(mask: BVec3, if_true: Vec3, if_false: Vec3) -> Vec3;
    /// Creates a new vector from an array.
    ///
    /// Mirrors `glam::Vec3::from_array`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn from_array(a: [Fixed; 3]) -> Vec3;
    /// Converts `self` to `[x, y, z]`.
    ///
    /// Mirrors `glam::Vec3::to_array`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn to_array(self: Vec3) -> [Fixed; 3];
    /// Creates a 4D vector from `self` and the given `w` value.
    ///
    /// Mirrors `glam::Vec3::extend`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn extend(self: Vec3, w: Fixed) -> Vec4;
    /// Creates a 2D vector from the `x`, `y` elements of `self`, discarding `z`.
    ///
    /// Mirrors `glam::Vec3::truncate`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn truncate(self: Vec3) -> Vec2;
    /// Creates a 3D vector from `self` with the given value of `x`.
    ///
    /// Mirrors `glam::Vec3::with_x`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn with_x(self: Vec3, x: Fixed) -> Vec3;
    /// Creates a 3D vector from `self` with the given value of `y`.
    ///
    /// Mirrors `glam::Vec3::with_y`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn with_y(self: Vec3, y: Fixed) -> Vec3;
    /// Creates a 3D vector from `self` with the given value of `z`.
    ///
    /// Mirrors `glam::Vec3::with_z`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn with_z(self: Vec3, z: Fixed) -> Vec3;
    /// Creates a 3D vector from `v` divided by its `w` component: the perspective divide
    /// of a homogeneous coordinate.
    ///
    /// Mirrors `glam::Vec3::from_homogeneous`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if `w` is zero (`glam_assert!` in glam-rs, which
    ///   otherwise returns infinity or NaN).
    /// * `'Fixed: overflow'` if a quotient does not fit the scalar range.
    /// #### Deviations
    /// * One shared `fixed::wide::Recip` of `w` (one division, rounded to nearest) and one
    ///   fused product per component, instead of three truncated `Fixed / Fixed`: it pays
    ///   off from two divisions on (`alt_from_homogeneous_div` in `gas/vec3.snap`). A
    ///   result may differ by 1 ULP from the truncated division.
    fn from_homogeneous(v: Vec4) -> Vec3;
    /// Creates a homogeneous coordinate from `self`, equivalent to `self.extend(1.0)`.
    ///
    /// Mirrors `glam::Vec3::to_homogeneous`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn to_homogeneous(self: Vec3) -> Vec4;
    /// Computes the dot product of `self` and `rhs`.
    ///
    /// Mirrors `glam::Vec3::dot`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * The `dot3` fused kernel: the exact sum of the 3 products is rescaled once
    ///   (floored), so the result is at most 1 ULP below the exact dot product and an
    ///   intermediate term outside the scalar range does not panic.
    fn dot(self: Vec3, rhs: Vec3) -> Fixed;
    /// Returns a vector where every component is the dot product of `self` and `rhs`.
    ///
    /// Mirrors `glam::Vec3::dot_into_vec`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * As `dot`.
    fn dot_into_vec(self: Vec3, rhs: Vec3) -> Vec3;
    /// Computes the cross product of `self` and `rhs`.
    ///
    /// Mirrors `glam::Vec3::cross`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One `mul_sub` fused kernel per component: the exact `a * b - c * d` is rescaled
    ///   once (floored), at most 1 ULP below the exact result.
    fn cross(self: Vec3, rhs: Vec3) -> Vec3;
    /// Returns a vector containing the minimum values for each element of `self` and
    /// `rhs`.
    ///
    /// In other words this computes `[min(x, rhs.x), min(self.y, rhs.y), ..]`.
    ///
    /// Mirrors `glam::Vec3::min`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * No NaN propagation question: `Fixed` is totally ordered.
    fn min(self: Vec3, rhs: Vec3) -> Vec3;
    /// Returns a vector containing the maximum values for each element of `self` and
    /// `rhs`.
    ///
    /// In other words this computes `[max(self.x, rhs.x), max(self.y, rhs.y), ..]`.
    ///
    /// Mirrors `glam::Vec3::max`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * No NaN propagation question: `Fixed` is totally ordered.
    fn max(self: Vec3, rhs: Vec3) -> Vec3;
    /// Component-wise clamping of values, similar to `Fixed::clamp`.
    ///
    /// Each element in `min` must be less-or-equal to the corresponding element in `max`.
    ///
    /// Mirrors `glam::Vec3::clamp`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * The `glam_assert!(min <= max)` precondition is not checked. When it is violated
    ///   the result differs from the `self.max(min).min(max)` of glam-rs: an element below
    ///   `min` clamps to `min` (glam-rs: to `max`). The if-chain is measurably cheaper.
    fn clamp(self: Vec3, min: Vec3, max: Vec3) -> Vec3;
    /// Returns the horizontal minimum of `self`.
    ///
    /// In other words this computes `min(x, y, ..)`.
    ///
    /// Mirrors `glam::Vec3::min_element`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn min_element(self: Vec3) -> Fixed;
    /// Returns the horizontal maximum of `self`.
    ///
    /// In other words this computes `max(x, y, ..)`.
    ///
    /// Mirrors `glam::Vec3::max_element`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn max_element(self: Vec3) -> Fixed;
    /// Returns the index of the first minimum element of `self`.
    ///
    /// Mirrors `glam::Vec3::min_position`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn min_position(self: Vec3) -> usize;
    /// Returns the index of the first maximum element of `self`.
    ///
    /// Mirrors `glam::Vec3::max_position`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn max_position(self: Vec3) -> usize;
    /// Returns the sum of all elements of `self`.
    ///
    /// In other words, this computes `self.x + self.y + ..`.
    ///
    /// Mirrors `glam::Vec3::element_sum`.
    /// #### Panics
    /// * `'i64_add Overflow'` / `'i64_add Underflow'` if a partial sum leaves the scalar
    ///   range.
    /// #### Deviations
    /// * Exact: `Fixed` addition is an integer addition.
    fn element_sum(self: Vec3) -> Fixed;
    /// Returns the product of all elements of `self`.
    ///
    /// In other words, this computes `self.x * self.y * ..`.
    ///
    /// Mirrors `glam::Vec3::element_product`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * The three products are accumulated exactly at the Q96.96 scale and rescaled once
    ///   instead of one rescale per multiplication: the result is the floor of the exact
    ///   product, which a left-to-right chain of `Fixed * Fixed` is not.
    fn element_product(self: Vec3) -> Fixed;
    /// Returns a vector mask containing the result of a `==` comparison for each element
    /// of `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x == rhs.x, self.y == rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::Vec3::cmpeq`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmpeq(self: Vec3, rhs: Vec3) -> BVec3;
    /// Returns a vector mask containing the result of a `!=` comparison for each element
    /// of `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x != rhs.x, self.y != rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::Vec3::cmpne`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmpne(self: Vec3, rhs: Vec3) -> BVec3;
    /// Returns a vector mask containing the result of a `>=` comparison for each element
    /// of `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x >= rhs.x, self.y >= rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::Vec3::cmpge`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmpge(self: Vec3, rhs: Vec3) -> BVec3;
    /// Returns a vector mask containing the result of a `>` comparison for each element of
    /// `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x > rhs.x, self.y > rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::Vec3::cmpgt`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmpgt(self: Vec3, rhs: Vec3) -> BVec3;
    /// Returns a vector mask containing the result of a `<=` comparison for each element
    /// of `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x <= rhs.x, self.y <= rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::Vec3::cmple`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmple(self: Vec3, rhs: Vec3) -> BVec3;
    /// Returns a vector mask containing the result of a `<` comparison for each element of
    /// `self` and `rhs`.
    ///
    /// In other words, this computes `[self.x < rhs.x, self.y < rhs.y, ..]` for all
    /// elements.
    ///
    /// Mirrors `glam::Vec3::cmplt`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn cmplt(self: Vec3, rhs: Vec3) -> BVec3;
    /// Returns a vector containing the absolute value of each element of `self`.
    ///
    /// Mirrors `glam::Vec3::abs`.
    /// #### Panics
    /// * `'Fixed: overflow'` if an element is `Fixed::MIN`.
    /// #### Deviations
    /// * None.
    fn abs(self: Vec3) -> Vec3;
    /// Returns a vector with elements representing the sign of `self`: `1` for a positive
    /// element or zero, `-1` for a negative one.
    ///
    /// Mirrors `glam::Vec3::signum`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * `signum(0)` is `+1` as for `+0.0` in Rust; there is no negative zero and no NaN
    ///   (docs/DESIGN.md section 3).
    fn signum(self: Vec3) -> Vec3;
    /// Returns a vector with signs of `rhs` and the magnitudes of `self`.
    ///
    /// Mirrors `glam::Vec3::copysign`.
    /// #### Panics
    /// * `'Fixed: overflow'` if an element of `self` is `Fixed::MIN` and the matching
    ///   element of `rhs` is not negative.
    /// #### Deviations
    /// * Zero counts as positive.
    fn copysign(self: Vec3, rhs: Vec3) -> Vec3;
    /// Returns a bitmask with the lowest 3 bits set to the sign bits from the elements of
    /// `self`.
    ///
    /// A negative element results in a `1` bit and a positive element in a `0` bit.
    /// Element `x` goes into the first lowest bit, element `y` into the second, etc.
    ///
    /// Mirrors `glam::Vec3::is_negative_bitmask`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * Zero is positive: there is no negative zero, no NaN and no negative infinity.
    fn is_negative_bitmask(self: Vec3) -> u32;
    /// Returns a mask indicating which components are negative.
    ///
    /// Mirrors `glam::Vec3::is_negative_mask`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * Zero is positive (see `is_negative_bitmask`).
    fn is_negative_mask(self: Vec3) -> BVec3;
    /// Returns a vector containing the nearest integer to a number for each element of
    /// `self`. Round half-way cases away from zero.
    ///
    /// Mirrors `glam::Vec3::round`.
    /// #### Panics
    /// * `'Fixed: overflow'` if an element is at least `2^31 - 1/2`.
    /// #### Deviations
    /// * None.
    fn round(self: Vec3) -> Vec3;
    /// Returns a vector containing the largest integer less than or equal to a number for
    /// each element of `self`.
    ///
    /// Mirrors `glam::Vec3::floor`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn floor(self: Vec3) -> Vec3;
    /// Returns a vector containing the smallest integer greater than or equal to a number
    /// for each element of `self`.
    ///
    /// Mirrors `glam::Vec3::ceil`.
    /// #### Panics
    /// * `'Fixed: overflow'` if an element is greater than `2^31 - 1`.
    /// #### Deviations
    /// * None.
    fn ceil(self: Vec3) -> Vec3;
    /// Returns a vector containing the integer part of each element of `self`. This means
    /// numbers are always truncated towards zero.
    ///
    /// Mirrors `glam::Vec3::trunc`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * None.
    fn trunc(self: Vec3) -> Vec3;
    /// Returns a vector containing the fractional part of the vector as `self -
    /// self.trunc()`.
    ///
    /// Mirrors `glam::Vec3::fract`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * Exact (integer arithmetic on the raw values), not an f32 approximation.
    fn fract(self: Vec3) -> Vec3;
    /// Returns a vector containing the fractional part of the vector as `self -
    /// self.floor()`.
    ///
    /// Mirrors `glam::Vec3::fract_gl`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * Exact (integer arithmetic on the raw values), not an f32 approximation.
    fn fract_gl(self: Vec3) -> Vec3;
    /// Returns a vector containing the reciprocal `1 / n` of each element of `self`.
    ///
    /// Mirrors `glam::Vec3::recip`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if an element is zero.
    /// * `'Fixed: overflow'` if an element is `1` or `2` raw (the reciprocal does not
    ///   fit).
    /// #### Deviations
    /// * There is no NaN nor infinity: the operation panics instead of producing one.
    fn recip(self: Vec3) -> Vec3;
    /// Returns a vector containing the sine for each element of `self` (in radians).
    ///
    /// Mirrors `glam::Vec3::sin`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * Element-wise `TrigTrait::sin`: within 1.02 ULP of the exact sine over a turn
    ///   (2.03 at the extremes of the range), `sin(0) = 0` exactly and `sin(-x) =
    ///   -sin(x)`.
    /// * 3 independent scalar calls: no work is shared between the elements. The wrapper
    ///   adds no gas to the scalar calls and is not force-inlined (`alt_sin_inline` in
    ///   `gas/vec3.snap`).
    fn sin(self: Vec3) -> Vec3;
    /// Returns a vector containing the cosine for each element of `self` (in radians).
    ///
    /// Mirrors `glam::Vec3::cos`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * Element-wise `TrigTrait::cos`: within 0.86 ULP of the exact cosine over a turn
    ///   (1.71 at the extremes of the range), `cos(0) = 1` exactly and `cos(-x) = cos(x)`.
    /// * 3 independent scalar calls: no work is shared between the elements.
    fn cos(self: Vec3) -> Vec3;
    /// Returns a tuple of two vectors containing the sine and cosine for each element of
    /// `self`.
    ///
    /// Mirrors `glam::Vec3::sin_cos`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * Bit-identical to `(self.sin(), self.cos())`, one shared range reduction per
    ///   element (`TrigTrait::sin_cos`, 1.4x the cost of `sin` alone instead of 2x).
    /// * 3 independent scalar calls: no work is shared between the elements.
    fn sin_cos(self: Vec3) -> (Vec3, Vec3);
    /// Returns a vector containing `e^self` for each element of `self`.
    ///
    /// Mirrors `glam::Vec3::exp`.
    /// #### Panics
    /// * `'Fixed: exp overflow'` if an element is `>= 21.487` (`31 ln 2`), where the
    ///   result no longer fits the scalar range.
    /// * The elements are evaluated in order (`x` first): the panic is the one of the
    ///   first offending element.
    /// #### Deviations
    /// * Element-wise `ExpTrait::exp`: an element below `-22.873` gives `0`; the result is
    ///   within 2.02 ULP below the exact value (below `2^16`), `exp(0) = 1` exactly and
    ///   each element is non-decreasing.
    /// * 3 independent scalar calls: no work is shared between the elements.
    fn exp(self: Vec3) -> Vec3;
    /// Returns a vector containing `2^self` for each element of `self`.
    ///
    /// Mirrors `glam::Vec3::exp2`.
    /// #### Panics
    /// * `'Fixed: exp overflow'` if an element is `>= 31`.
    /// * The elements are evaluated in order (`x` first): the panic is the one of the
    ///   first offending element.
    /// #### Deviations
    /// * Element-wise `ExpTrait::exp2`: an element below `-33` gives `0`; within 2.02 ULP
    ///   below the exact value (below `2^16`), exact for an integer element in `[-32,
    ///   30]`.
    /// * 3 independent scalar calls: no work is shared between the elements.
    fn exp2(self: Vec3) -> Vec3;
    /// Returns a vector containing the natural logarithm for each element of `self`.
    ///
    /// Mirrors `glam::Vec3::ln`.
    /// #### Panics
    /// * `'Fixed: ln domain'` if an element is `<= 0`.
    /// * The elements are evaluated in order (`x` first): the panic is the one of the
    ///   first offending element.
    /// #### Deviations
    /// * Panics where glam-rs returns NaN (negative element) or negative infinity (zero
    ///   element).
    /// * Element-wise `ExpTrait::ln`: within 0.66 ULP of the exact value, `ln(1) = 0`
    ///   exactly.
    /// * 3 independent scalar calls: no work is shared between the elements.
    fn ln(self: Vec3) -> Vec3;
    /// Returns a vector containing the base 2 logarithm for each element of `self`.
    ///
    /// Mirrors `glam::Vec3::log2`.
    /// #### Panics
    /// * `'Fixed: ln domain'` if an element is `<= 0`.
    /// * The elements are evaluated in order (`x` first): the panic is the one of the
    ///   first offending element.
    /// #### Deviations
    /// * Panics where glam-rs returns NaN (negative element) or negative infinity (zero
    ///   element).
    /// * Element-wise `ExpTrait::log2`: within 0.75 ULP of the exact value, `log2(2^k) =
    ///   k` exactly for `k` in `[-32, 30]`.
    /// * 3 independent scalar calls: no work is shared between the elements.
    fn log2(self: Vec3) -> Vec3;
    /// Returns a vector containing each element of `self` raised to the power of `n`.
    ///
    /// Mirrors `glam::Vec3::powf`.
    /// #### Panics
    /// * `'Fixed: overflow'` if a result does not fit the scalar range.
    /// * `'Fixed: division by zero'` if an element is zero and `n` is negative.
    /// * `'Fixed: powf domain'` if an element is negative and `n` is not an integer.
    /// * `'i64_neg Underflow'` if an element is `Fixed::MIN`.
    /// * The elements are evaluated in order (`x` first): the panic is the one of the
    ///   first offending element.
    /// #### Deviations
    /// * Element-wise `ExpTrait::powf` (`exp2(n * log2(x))` with the product kept at 88
    ///   fractional bits): panics where glam-rs returns infinity or NaN; within 2.05 ULP
    ///   below 1 and `0.44 * 2^-30` relative above (`x` in `[2^-8, 2^8]`, `n` in `[-4,
    ///   4]`); `powf(x, 1)` is not bit-identical to `x`.
    /// * 3 independent scalar calls: no work is shared between the elements. The wrapper
    ///   adds no gas to the scalar calls and is not force-inlined (`alt_powf_inline` in
    ///   `gas/vec3.snap`).
    fn powf(self: Vec3, n: Fixed) -> Vec3;
    /// Returns a vector containing the square root for each element of `self`.
    ///
    /// Mirrors `glam::Vec3::sqrt`.
    /// #### Panics
    /// * `'Fixed: sqrt negative'` if an element is negative.
    /// * The elements are evaluated in order (`x` first): the panic is the one of the
    ///   first offending element.
    /// #### Deviations
    /// * Panics where glam-rs returns NaN.
    /// * Element-wise `FixedTrait::sqrt`: the floor of the exact root (integer square root
    ///   of `raw * 2^32`), bit-exact. Inlined: cheaper than the call (`alt_sqrt_noinline`
    ///   in `gas/vec3.snap`).
    fn sqrt(self: Vec3) -> Vec3;
    /// Returns a vector containing `0.0` if `rhs < self` and `1.0` otherwise, per element.
    ///
    /// Similar to glsl's step(edge, x), which translates into edge.step(x).
    ///
    /// Mirrors `glam::Vec3::step`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * Exact: `Fixed::step` on each pair (`1` when the elements are equal).
    fn step(self: Vec3, rhs: Vec3) -> Vec3;
    /// Performs Hermite interpolation between `0.0` and `1.0` using `x` normalized to
    /// `[edge0, edge1]`.
    ///
    /// This is equivalent to `t * t * (3.0 - 2.0 * t)`, where `t` is clamped to `[0.0,
    /// 1.0]`. Results are undefined if any element of `edge0` is greater than or equal to
    /// the corresponding element of `edge1`.
    ///
    /// Mirrors `glam::Vec3::smoothstep`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if an element of `edge0` equals the one of `edge1`.
    /// * `'i64_sub Overflow'` / `'i64_sub Underflow'` / `'Fixed: overflow'` if `self -
    ///   edge0`, `edge1 - edge0` or their quotient does not fit the scalar range.
    /// #### Deviations
    /// * The `edge0 < edge1` precondition (`glam_assert!`) is only checked for equality,
    ///   by the division; the result for `edge0 > edge1` is the one of the formula.
    /// * Element-wise `Fixed::smoothstep`: `t = saturate(trunc((x - edge0) / (edge1 -
    ///   edge0)))`, then the polynomial is evaluated exactly and rescaled once (floored),
    ///   instead of the three rescaled vector operations of glam-rs (`alt_smoothstep_glam`
    ///   in `gas/vec3.snap`). Inlined: cheaper than the call (`alt_smoothstep_noinline`).
    fn smoothstep(self: Vec3, edge0: Vec3, edge1: Vec3) -> Vec3;
    /// Returns a vector containing all elements of `self` clamped to the range of `[0,
    /// 1]`.
    ///
    /// Mirrors `glam::Vec3::saturate`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * Exact.
    fn saturate(self: Vec3) -> Vec3;
    /// Computes the length of `self`.
    ///
    /// Mirrors `glam::Vec3::length`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the length does not fit the scalar range.
    /// #### Deviations
    /// * The `norm3` fused kernel: the integer square root of the exact raw sum of
    ///   squares. No intermediate rescale, so `length` is defined (and non-zero) for
    ///   vectors whose `length_squared` would underflow to zero; the result is the floor
    ///   of the exact length.
    fn length(self: Vec3) -> Fixed;
    /// Computes the squared length of `self`.
    ///
    /// Mirrors `glam::Vec3::length_squared`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One floor rescale of the exact sum of squares. It overflows (and panics) for
    ///   `|self| >= 2^31`, i.e. as soon as the squared length leaves the scalar range.
    fn length_squared(self: Vec3) -> Fixed;
    /// Computes `1 / length()`.
    ///
    /// Mirrors `glam::Vec3::length_recip`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if `self` is zero.
    /// * `'Fixed: overflow'` if the length or its reciprocal does not fit the scalar
    ///   range.
    /// #### Deviations
    /// * The length is floored, then the division truncates: at most 2 ULP off the exact
    ///   value for `|self| >= 1`. For valid results `self` must not be of length zero: it
    ///   panics instead of returning infinity.
    fn length_recip(self: Vec3) -> Fixed;
    /// Computes the Euclidean distance between two points in space.
    ///
    /// Mirrors `glam::Vec3::distance`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the distance does not fit the scalar range.
    /// #### Deviations
    /// * The `distance3` fused kernel: the differences are exact (65 bits), so unlike
    ///   `(self - rhs).length()` it cannot overflow on the subtraction.
    fn distance(self: Vec3, rhs: Vec3) -> Fixed;
    /// Computes the squared Euclidean distance between two points in space.
    ///
    /// Mirrors `glam::Vec3::distance_squared`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * Exact differences and one floor rescale (see `distance`).
    fn distance_squared(self: Vec3, rhs: Vec3) -> Fixed;
    /// Returns the element-wise quotient of Euclidean division of `self` by `rhs`.
    ///
    /// Mirrors `glam::Vec3::div_euclid`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if an element of `rhs` is zero.
    /// * `'Fixed: overflow'` if a quotient does not fit the scalar range.
    /// #### Deviations
    /// * Exact: computed on the raw integers, with no intermediate rounding.
    fn div_euclid(self: Vec3, rhs: Vec3) -> Vec3;
    /// Returns the element-wise remainder of Euclidean division of `self` by `rhs`.
    ///
    /// Mirrors `glam::Vec3::rem_euclid`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if an element of `rhs` is zero.
    /// #### Deviations
    /// * Exact: always strictly below `|rhs|` (the f32 version can round up to `|rhs|`).
    fn rem_euclid(self: Vec3, rhs: Vec3) -> Vec3;
    /// Returns `self` normalized to length 1.
    ///
    /// For valid results, `self` must not be of length zero.
    ///
    /// Mirrors `glam::Vec3::normalize`.
    /// #### Panics
    /// * `'Vec3: normalize zero'` if the length of `self` is zero (raw sum of squares
    ///   below 1).
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One square root and one division shared by the components, then one fused
    ///   multiplication each (rounded to nearest, ties toward +infinity): every component
    ///   is within `1 / |self|` ULP of the exact value, and an axis-aligned vector
    ///   normalizes to exactly `+-1`.
    /// * Panics instead of returning a NaN vector (docs/DESIGN.md section 3).
    fn normalize(self: Vec3) -> Vec3;
    /// Returns `self` normalized to length 1 if possible, else returns `None`.
    ///
    /// In particular, if the input is zero the result of this operation will be `None`.
    ///
    /// Mirrors `glam::Vec3::try_normalize`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One square root and one division shared by the components, then one fused
    ///   multiplication each (rounded to nearest, ties toward +infinity): every component
    ///   is within `1 / |self|` ULP of the exact value, and an axis-aligned vector
    ///   normalizes to exactly `+-1`.
    /// * `None` only for the zero vector: there is no non-finite input.
    fn try_normalize(self: Vec3) -> Option<Vec3>;
    /// Returns `self` normalized to length 1 if possible, else returns a fallback value.
    ///
    /// In particular, if the input is zero the result of this operation will be the
    /// fallback value.
    ///
    /// Mirrors `glam::Vec3::normalize_or`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One square root and one division shared by the components, then one fused
    ///   multiplication each (rounded to nearest, ties toward +infinity): every component
    ///   is within `1 / |self|` ULP of the exact value, and an axis-aligned vector
    ///   normalizes to exactly `+-1`.
    /// * The fallback is returned only for the zero vector.
    fn normalize_or(self: Vec3, fallback: Vec3) -> Vec3;
    /// Returns `self` normalized to length 1 if possible, else returns zero.
    ///
    /// Mirrors `glam::Vec3::normalize_or_zero`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One square root and one division shared by the components, then one fused
    ///   multiplication each (rounded to nearest, ties toward +infinity): every component
    ///   is within `1 / |self|` ULP of the exact value, and an axis-aligned vector
    ///   normalizes to exactly `+-1`.
    /// * Zero is returned only for the zero vector.
    fn normalize_or_zero(self: Vec3) -> Vec3;
    /// Returns `self` normalized to length 1 and the length of `self`.
    ///
    /// If `self` is zero length then `(Self::X, 0)` is returned.
    ///
    /// Mirrors `glam::Vec3::normalize_and_length`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the length does not fit the scalar range.
    /// #### Deviations
    /// * One square root and one division shared by the components, then one fused
    ///   multiplication each (rounded to nearest, ties toward +infinity): every component
    ///   is within `1 / |self|` ULP of the exact value, and an axis-aligned vector
    ///   normalizes to exactly `+-1`.
    /// * One square root shared by the normalization and the returned length.
    fn normalize_and_length(self: Vec3) -> (Vec3, Fixed);
    /// Returns whether `self` is of length `1` or not.
    ///
    /// Uses a precision threshold of `1024` raw ULP (`2^-22`) on the squared length.
    ///
    /// Mirrors `glam::Vec3::is_normalized`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * The threshold is re-derived for Q32.32: `|length_squared - 1| <= 1024` raw ULP,
    ///   about `2.4e-7`, where glam-rs uses `2e-4` (about 1700 f32 epsilons). The squared
    ///   length of the output of `normalize` is within 7 ULP of 1, so the margin is a
    ///   hundredfold.
    /// * The exact wide sum of squares is compared without narrowing, so long vectors
    ///   return `false` instead of panicking.
    fn is_normalized(self: Vec3) -> bool;
    /// Returns the vector projection of `self` onto `rhs`.
    ///
    /// `rhs` must be of non-zero length.
    ///
    /// Mirrors `glam::Vec3::project_onto`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if `rhs.dot(rhs)` is zero, i.e. if `rhs` is zero or
    ///   shorter than `2^-16` (its squared length then rounds to zero).
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * A single division `dot(self, rhs) / dot(rhs, rhs)` (truncated toward zero), then
    ///   one floor rescale per component. A shared `Recip` is measurably more expensive
    ///   for one division: it is kept in `benches::alt`.
    fn project_onto(self: Vec3, rhs: Vec3) -> Vec3;
    /// Returns the vector rejection of `self` from `rhs`.
    ///
    /// The vector rejection is the vector perpendicular to the projection of `self` onto
    /// `rhs`, in other words the result of `self - self.project_onto(rhs)`.
    ///
    /// `rhs` must be of non-zero length.
    ///
    /// Mirrors `glam::Vec3::reject_from`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if `rhs.dot(rhs)` is zero (see `project_onto`).
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One rescale per component (`self - rhs * k` fused) instead of the two of `self -
    ///   self.project_onto(rhs)`: 1 ULP more accurate and cheaper, but the two forms can
    ///   differ by 1 ULP per component.
    fn reject_from(self: Vec3, rhs: Vec3) -> Vec3;
    /// Returns the vector projection of `self` onto `rhs`.
    ///
    /// `rhs` must be normalized.
    ///
    /// Mirrors `glam::Vec3::project_onto_normalized`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * The `rhs.is_normalized()` precondition is not checked (`glam_assert!`).
    /// * One floor rescale per component.
    fn project_onto_normalized(self: Vec3, rhs: Vec3) -> Vec3;
    /// Returns the vector rejection of `self` from `rhs`.
    ///
    /// `rhs` must be normalized.
    ///
    /// Mirrors `glam::Vec3::reject_from_normalized`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * The `rhs.is_normalized()` precondition is not checked (`glam_assert!`).
    /// * One rescale per component (`self - rhs * dot` fused) instead of the two of `self
    ///   - self.project_onto_normalized(rhs)`: the two forms can differ by 1 ULP per
    ///   component.
    fn reject_from_normalized(self: Vec3, rhs: Vec3) -> Vec3;
    /// Returns the reflection vector for a given incident vector `self` and surface normal
    /// `normal`.
    ///
    /// `normal` must be normalized.
    ///
    /// Mirrors `glam::Vec3::reflect`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// * `'i64_add Overflow'` / `'i64_neg Underflow'` if `2 * self.dot(normal)` leaves the
    ///   scalar range.
    /// #### Deviations
    /// * The `normal.is_normalized()` precondition is not checked (`glam_assert!`).
    /// * One `mul_add` fused kernel per component: `self - 2 * dot * normal` with a single
    ///   floor rescale each.
    fn reflect(self: Vec3, normal: Vec3) -> Vec3;
    /// Returns the refraction direction for a given incident vector `self`, surface normal
    /// `normal` and ratio of indices of refraction, `eta`. When total internal reflection
    /// occurs, a zero vector will be returned.
    ///
    /// `self` and `normal` must be normalized.
    ///
    /// Mirrors `glam::Vec3::refract`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * The `is_normalized` preconditions are not checked (`glam_assert!`).
    /// * `k = 1 - eta^2 * (1 - n_dot_i^2)` is evaluated with two floor rescales and its
    ///   square root is floored; each output component is one `mul_sub` fused kernel.
    fn refract(self: Vec3, normal: Vec3, eta: Fixed) -> Vec3;
    /// Returns the angle (in radians) between two vectors in the range `[0, +π]`.
    ///
    /// For the full rotation between two vectors as a quaternion, see
    /// `Quat::from_rotation_arc`.
    ///
    /// The inputs do not need to be unit vectors however they must be non-zero.
    ///
    /// Mirrors `glam::Vec3::angle_between`.
    /// #### Panics
    /// * `'Fixed: overflow'` if `|self x rhs|` or `dot` does not fit the scalar range,
    ///   i.e. for `|self| * |rhs| >= 2^31`.
    /// #### Deviations
    /// * `atan2(|self x rhs|, dot)` instead of the `acos_approx(dot / sqrt(|self|^2 *
    ///   |rhs|^2))` of glam-rs. It is not a change of formula but of conditioning: the
    ///   `acos` form loses the angle near `0` and `PI` (the slope of `acos` is infinite
    ///   there: one ULP of the cosine near 1 is up to `2e-5` rad), the `atan2` form does
    ///   not. The `acos_clamped` form is kept in `benches::alt`.
    /// * The three cross components are `mul_sub` kernels (one floor each), their norm is
    ///   the integer square root of the raw sum of squares, `dot` is floored once: the
    ///   total error is below `3.22 + 2.9 / (|self| * |rhs|)` ULP, about 6 ULP for vectors
    ///   whose lengths multiply to at least 1, growing as they shrink.
    /// * Parallel vectors give `0` and anti-parallel ones `PI` exactly; a zero input gives
    ///   `0` (the non-zero precondition is not checked).
    fn angle_between(self: Vec3, rhs: Vec3) -> Fixed;
    /// Returns the signed angle (in radians) from `self` to `rhs` around `axis` in the
    /// range `[-π, +π]`.
    ///
    /// The `axis` must be a unit vector. The angle follows the right-hand rule around
    /// `axis` and can be used with `rotate_axis`, e.g. `self.rotate_axis(axis,
    /// self.angle_to(rhs, axis))` will be equal to `rhs`.
    ///
    /// For the unsigned angle without a reference axis, see `angle_between`.
    ///
    /// The inputs do not need to be unit vectors however they must be non-zero.
    ///
    /// Mirrors `glam::Vec3::angle_to`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the triple product or `dot` does not fit the scalar range,
    ///   i.e. for `|self| * |rhs| >= 2^31`.
    /// #### Deviations
    /// * `self.cross(rhs).dot(axis)` is the `det3` kernel (the scalar triple product, one
    ///   floor rescale of the exact value) instead of three cross components rounded and
    ///   then a dot product; `dot` is floored once. The error is below `3.22 + 1.42 /
    ///   |(triple, dot)|` ULP.
    /// * The `axis.is_normalized()` precondition and the non-zero inputs are not checked
    ///   (`glam_assert!`).
    /// * `self.rotate_axis(axis, self.angle_to(rhs, axis))` closes the round trip of the
    ///   doc above to within `10 |self|` ULP (see `rotate_axis`).
    fn angle_to(self: Vec3, rhs: Vec3, axis: Vec3) -> Fixed;
    /// Rotates around the x axis by `angle` (in radians).
    ///
    /// Mirrors `glam::Vec3::rotate_x`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One shared `sin_cos`, then one fused kernel (`mul_sub` / `dot2`, one floor
    ///   rescale) per rotated component: each is within `1.02 * (|y| + |z|) + 1` ULP of
    ///   the exact rotation, the `x` component is unchanged.
    fn rotate_x(self: Vec3, angle: Fixed) -> Vec3;
    /// Rotates around the y axis by `angle` (in radians).
    ///
    /// Mirrors `glam::Vec3::rotate_y`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One shared `sin_cos`, then one fused kernel (`mul_sub` / `dot2`, one floor
    ///   rescale) per rotated component: each is within `1.02 * (|z| + |x|) + 1` ULP of
    ///   the exact rotation, the `y` component is unchanged.
    fn rotate_y(self: Vec3, angle: Fixed) -> Vec3;
    /// Rotates around the z axis by `angle` (in radians).
    ///
    /// Mirrors `glam::Vec3::rotate_z`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * One shared `sin_cos`, then one fused kernel (`mul_sub` / `dot2`, one floor
    ///   rescale) per rotated component: each is within `1.02 * (|x| + |y|) + 1` ULP of
    ///   the exact rotation, the `z` component is unchanged.
    fn rotate_z(self: Vec3, angle: Fixed) -> Vec3;
    /// Rotates around `axis` by `angle` (in radians).
    ///
    /// The axis must be a unit vector.
    ///
    /// Mirrors `glam::Vec3::rotate_axis`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * The `axis.is_normalized()` precondition is not checked (`glam_assert!`).
    /// * `Quat::from_axis_angle(axis, angle).mul_vec3(self)` as in glam-rs: one `sin_cos`
    ///   (about 1 ULP over a turn), then the 15-multiplication rotation kernel of
    ///   `Quat::mul_vec3`, which rescales once per component. The total error is below `4
    ///   |self|` ULP for a unit `axis`.
    /// * Building the same rotation as a `Mat3::from_axis_angle` and multiplying costs 15
    ///   % more (58 730 against 51 120 gas, `alt_rotate_axis_mat3`).
    fn rotate_axis(self: Vec3, axis: Vec3, angle: Fixed) -> Vec3;
    /// Rotates towards `rhs` up to `max_angle` (in radians).
    ///
    /// When `max_angle` is `0`, the result will be equal to `self`. When `max_angle` is
    /// equal to `self.angle_between(rhs)`, the result will be parallel to `rhs`. If
    /// `max_angle` is negative, rotates towards the exact opposite of `rhs`. Will not go
    /// past the target.
    ///
    /// Mirrors `glam::Vec3::rotate_towards`.
    /// #### Panics
    /// * `'Fixed: overflow'` if `|self x rhs|` or `self.dot(rhs)` does not fit the scalar
    ///   range, i.e. for `|self| * |rhs| >= 2^31`.
    /// * `'i64_sub Overflow'` / `'i64_sub Underflow'` if a component difference leaves the
    ///   scalar range.
    /// #### Deviations
    /// * One `atan2` (`angle_between`, error bound as there) and the `from_axis_angle` /
    ///   `mul_vec3` pair of `rotate_axis`: the total error is below `10 |self|` ULP.
    /// * The rotation axis is the normalized `self.cross(rhs)`, falling back to the
    ///   normalized `any_orthogonal_vector` when the two vectors are parallel, as in glam-
    ///   rs (`try_normalize` there). The length of the fallback is never zero for a non-
    ///   zero `self`. The cross product and its norm are shared with the `atan2` angle;
    ///   axis normalization adds one division but no second square root.
    /// * `max_angle` is clamped with `FixedTrait::clamp`, which panics on a reversed
    ///   range; here `angle_between - PI <= angle_between` always holds.
    fn rotate_towards(self: Vec3, rhs: Vec3, max_angle: Fixed) -> Vec3;
    /// Returns some vector that is orthogonal to the given one.
    ///
    /// The input vector must be non-zero.
    ///
    /// The output vector is not necessarily unit length. For that use
    /// `any_orthonormal_vector` instead.
    ///
    /// Mirrors `glam::Vec3::any_orthogonal_vector`.
    /// #### Panics
    /// * `'i64_neg Underflow'` if a component is `MIN`.
    /// #### Deviations
    /// * Exact: `self x Y` or `self x X`, whichever of the two is the longer, as in glam-
    ///   rs.
    /// * The `|x| > |y|` test is the one of glam-rs; it is a comparison of absolute
    ///   values, not of the components.
    fn any_orthogonal_vector(self: Vec3) -> Vec3;
    /// Returns any unit vector that is orthogonal to the given one.
    ///
    /// The input vector must be unit length.
    ///
    /// Mirrors `glam::Vec3::any_orthonormal_vector`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// * `'i64_neg Underflow'` if a component is `MIN`.
    /// #### Deviations
    /// * The `self.is_normalized()` precondition is not checked (`glam_assert!`).
    /// * `a = -1 / (sign + z)` is one truncated division; every other term is a triple
    ///   product rescaled once. The inputs are unit vectors, so `|sign + z| >= 1` and the
    ///   division is always defined.
    fn any_orthonormal_vector(self: Vec3) -> Vec3;
    /// Given a unit vector return two other vectors that together form a right-handed
    /// orthonormal basis. That is, all three vectors are orthogonal to each other and are
    /// normalized.
    ///
    /// The input vector must be unit length.
    ///
    /// Mirrors `glam::Vec3::any_orthonormal_pair`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// * `'i64_neg Underflow'` if a component is `MIN`.
    /// #### Deviations
    /// * The `self.is_normalized()` precondition is not checked (`glam_assert!`).
    /// * `a = -1 / (sign + z)` is one truncated division; every other term is a triple
    ///   product rescaled once. The inputs are unit vectors, so `|sign + z| >= 1` and the
    ///   division is always defined.
    /// * The second vector is exactly `any_orthonormal_vector`.
    fn any_orthonormal_pair(self: Vec3) -> (Vec3, Vec3);
    /// Performs a spherical linear interpolation between `self` and `rhs` based on the
    /// value `s`.
    ///
    /// When `s` is `0`, the result will be equal to `self`. When `s` is `1`, the result
    /// will be equal to `rhs`. When `s` is outside of range `[0, 1]`, the result is
    /// linearly extrapolated.
    ///
    /// Mirrors `glam::Vec3::slerp`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if `self` or `rhs` is zero.
    /// * `'Fixed: overflow'` if `|self| * |rhs|` does not fit the scalar range, i.e. for
    ///   `|self| * |rhs| >= 2^31`.
    /// * `'i64_sub Overflow'` / `'i64_sub Underflow'` if a component difference leaves the
    ///   scalar range.
    /// #### Deviations
    /// * The three branches of glam-rs, with the `1 - 3e-7` cosine band replaced by
    ///   [`NEAR_ONE`] (`1 - 2^-20`), re-derived for Q32.32 (docs/DESIGN.md section 3).
    /// * The four divisions are `fixed::wide::Recip` (one wide reciprocal, rounded to
    ///   nearest) and each component of the interpolated direction is one exact two-term
    ///   sum rescaled once. In the general branch the error is below `(2 + 5 / sin(theta))
    ///   |result|` ULP; it is the `1 / sin(theta)` term that the band bounds at `3.4e-7`
    ///   relative.
    /// * `acos_clamped` (7.6e-10) instead of the degree-7 `acos_approx` of glam-rs; the
    ///   cosine is ill-conditioned near `+-1` but the error of `theta` cancels between the
    ///   three sines to first order, which is why the band can be as tight as it is.
    /// * glam-rs returns `self.lerp(rhs, s)` when the dot product is NaN; there is no NaN
    ///   here (a zero input divides by zero and panics).
    fn slerp(self: Vec3, rhs: Vec3, s: Fixed) -> Vec3;
    /// Performs a linear interpolation between `self` and `rhs` based on the value `s`.
    ///
    /// When `s` is `0`, the result will be equal to `self`. When `s` is `1`, the result
    /// will be equal to `rhs`. When `s` is outside of range `[0, 1]`, the result is
    /// linearly extrapolated.
    ///
    /// Mirrors `glam::Vec3::lerp`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * `self + (rhs - self) * s` (the `FloatExt::lerp` form) with one floor rescale per
    ///   component, instead of the `self * (1 - s) + rhs * s` of glam-rs: exact at `s = 0`
    ///   and `s = 1`, and `rhs - self` cannot overflow.
    fn lerp(self: Vec3, rhs: Vec3, s: Fixed) -> Vec3;
    /// Moves towards `rhs` based on the value `d`.
    ///
    /// When `d` is `0`, the result will be equal to `self`. When `d` is equal to
    /// `self.distance(rhs)`, the result will be equal to `rhs`. Will not go past `rhs`.
    ///
    /// Mirrors `glam::Vec3::move_towards`.
    /// #### Panics
    /// * `'i64_sub Overflow'` / `'i64_sub Underflow'` if a component difference leaves the
    ///   scalar range.
    /// * `'Fixed: overflow'` if the distance or a component of the result does not fit the
    ///   scalar range.
    /// #### Deviations
    /// * `self + (rhs - self) * (d / len)`: one division shared by the components and one
    ///   fused `mul_add` each, instead of the two rescales per component of `self + a /
    ///   len * d`.
    /// * The `len <= 1e-4` guard of glam-rs is replaced by the exact `len == 0` test: the
    ///   division is exact enough at every non-zero length.
    fn move_towards(self: Vec3, rhs: Vec3, d: Fixed) -> Vec3;
    /// Calculates the midpoint between `self` and `rhs`.
    ///
    /// The midpoint is the average of, or halfway point between, two vectors.
    /// `a.midpoint(b)` should yield the same result as `a.lerp(b, 0.5)` while being
    /// slightly cheaper to compute.
    ///
    /// Mirrors `glam::Vec3::midpoint`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * `self + (rhs - self) / 2` instead of `(self + rhs) * 0.5`: the sum of the two
    ///   vectors cannot overflow this way, and the result is the floor of the exact
    ///   midpoint.
    fn midpoint(self: Vec3, rhs: Vec3) -> Vec3;
    /// Fused multiply-add. Computes `(self * a) + b` element-wise with only one rounding
    /// error.
    ///
    /// Mirrors `glam::Vec3::mul_add`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * The `mul_add` fused kernel: the exact `self * a + b` is rescaled once (floored).
    ///   Unlike f32 it is always at least as accurate as the unfused form, never slower,
    ///   and `b` is added exactly.
    fn mul_add(self: Vec3, a: Vec3, b: Vec3) -> Vec3;
    /// Returns true if the absolute difference of all elements between `self` and `rhs` is
    /// less than or equal to `max_abs_diff`.
    ///
    /// This can be used to compare if two vectors contain similar elements.
    ///
    /// Mirrors `glam::Vec3::abs_diff_eq`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * The differences are computed exactly on 65 bits: unlike `(self - rhs).abs()` it
    ///   never overflows.
    fn abs_diff_eq(self: Vec3, rhs: Vec3, max_abs_diff: Fixed) -> bool;
    /// Returns a vector with a length no less than `min` and no more than `max`.
    ///
    /// `min` and `max` must be non-negative and `min` must not be greater than `max`.
    ///
    /// Mirrors `glam::Vec3::clamp_length`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if `self` is zero and `min` is positive.
    /// * `'Fixed: overflow'` if the length or a scaled component does not fit the scalar
    ///   range.
    /// #### Deviations
    /// * The `0 <= min <= max` precondition is not checked (`glam_assert!`).
    /// * The comparison is on the length (floored) instead of the squared length: it
    ///   cannot overflow, and it is the same test up to 1 ULP. Scaling is one division
    ///   shared by the components and one floor rescale each.
    fn clamp_length(self: Vec3, min: Fixed, max: Fixed) -> Vec3;
    /// Returns a vector with a length no more than `max`.
    ///
    /// `max` must be non-negative.
    ///
    /// Mirrors `glam::Vec3::clamp_length_max`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the length or a scaled component does not fit the scalar
    ///   range.
    /// #### Deviations
    /// * The `0 <= max` precondition is not checked (`glam_assert!`).
    /// * The comparison is on the length (floored) instead of the squared length: it
    ///   cannot overflow, and it is the same test up to 1 ULP. Scaling is one division
    ///   shared by the components and one floor rescale each.
    fn clamp_length_max(self: Vec3, max: Fixed) -> Vec3;
    /// Returns a vector with a length no less than `min`.
    ///
    /// `min` must be non-negative.
    ///
    /// Mirrors `glam::Vec3::clamp_length_min`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if `self` is zero and `min` is positive.
    /// * `'Fixed: overflow'` if the length or a scaled component does not fit the scalar
    ///   range.
    /// #### Deviations
    /// * The `0 <= min` precondition is not checked (`glam_assert!`).
    /// * The comparison is on the length (floored) instead of the squared length: it
    ///   cannot overflow, and it is the same test up to 1 ULP. Scaling is one division
    ///   shared by the components and one floor rescale each.
    fn clamp_length_min(self: Vec3, min: Fixed) -> Vec3;
    /// Returns `[self.x + rhs, self.y + rhs, ..]`.
    ///
    /// Mirrors `glam::Vec3::splat`.
    /// #### Panics
    /// * `'i64_add Overflow'` / `'i64_add Underflow'` if a component sum leaves the scalar
    ///   range.
    /// #### Deviations
    /// * glam-rs has no scalar `+` on vectors: it spells this `v + Vec3::splat(s)`, and
    ///   the core operator traits of Cairo are homogeneous anyway (docs/DESIGN.md section
    ///   3).
    fn add_scalar(self: Vec3, rhs: Fixed) -> Vec3;
    /// Returns `[self.x - rhs, self.y - rhs, ..]`.
    ///
    /// Mirrors `glam::Vec3::splat`.
    /// #### Panics
    /// * `'i64_sub Overflow'` / `'i64_sub Underflow'` if a component difference leaves the
    ///   scalar range.
    /// #### Deviations
    /// * glam-rs has no scalar `-` on vectors: it spells this `v - Vec3::splat(s)`, and
    ///   the core operator traits of Cairo are homogeneous anyway (docs/DESIGN.md section
    ///   3).
    fn sub_scalar(self: Vec3, rhs: Fixed) -> Vec3;
    /// Returns `[self.x * rhs, self.y * rhs, ..]`.
    ///
    /// Mirrors `impl Mul<f32> for glam::Vec3`.
    /// #### Panics
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Mul<f32> for Vec3`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    /// * The product is floored (one rescale per component), not rounded to nearest: at
    ///   most 1 ULP below the exact result.
    fn mul_scalar(self: Vec3, rhs: Fixed) -> Vec3;
    /// Returns `[self.x / rhs, self.y / rhs, ..]`.
    ///
    /// Mirrors `impl Div<f32> for glam::Vec3`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if `rhs` is zero.
    /// * `'Fixed: overflow'` if the result does not fit the scalar range.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Div<f32> for Vec3`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    /// * One division shared by the components (`Recip`) and one fused multiplication
    ///   each, rounded to nearest: cheaper than, and up to 1 ULP away from, the component-
    ///   wise truncated `Fixed / Fixed` kept in `benches::alt`.
    fn div_scalar(self: Vec3, rhs: Fixed) -> Vec3;
    /// Returns `[self.x % rhs, self.y % rhs, ..]` (the remainder has the sign of `self`).
    ///
    /// Mirrors `impl Rem<f32> for glam::Vec3`.
    /// #### Panics
    /// * `'Fixed: division by zero'` if `rhs` is zero.
    /// #### Deviations
    /// * glam-rs spells this with an operator (`impl Rem<f32> for Vec3`); the core
    ///   operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).
    /// * Exact.
    fn rem_scalar(self: Vec3, rhs: Fixed) -> Vec3;
    /// Casts all elements of `self` to `i32`, truncating toward zero.
    ///
    /// Mirrors `glam::Vec3::as_ivec3`.
    /// #### Panics
    /// * Never.
    /// #### Deviations
    /// * Never fails: the integer part of a `Fixed` always fits an `i32`.
    fn as_ivec3(self: Vec3) -> IVec3;
    /// Casts all elements of `self` to `u32`, truncating toward zero.
    ///
    /// Mirrors `glam::Vec3::as_uvec3`.
    /// #### Panics
    /// * `'Vec3: cast out of range'` if an element is negative.
    /// #### Deviations
    /// * The Rust `as` cast saturates (a negative float becomes `0`); this one panics
    ///   (docs/DESIGN.md section 3).
    fn as_uvec3(self: Vec3) -> UVec3;
}

pub impl Vec3Impl of Vec3Trait {
    const ZERO: Vec3 = Vec3 { x: Fixed { raw: 0 }, y: Fixed { raw: 0 }, z: Fixed { raw: 0 } };
    const ONE: Vec3 = Vec3 {
        x: Fixed { raw: 0x100000000 }, y: Fixed { raw: 0x100000000 }, z: Fixed { raw: 0x100000000 },
    };
    const NEG_ONE: Vec3 = Vec3 {
        x: Fixed { raw: -0x100000000 },
        y: Fixed { raw: -0x100000000 },
        z: Fixed { raw: -0x100000000 },
    };
    const MIN: Vec3 = Vec3 {
        x: Fixed { raw: -0x8000000000000000 },
        y: Fixed { raw: -0x8000000000000000 },
        z: Fixed { raw: -0x8000000000000000 },
    };
    const MAX: Vec3 = Vec3 {
        x: Fixed { raw: 0x7fffffffffffffff },
        y: Fixed { raw: 0x7fffffffffffffff },
        z: Fixed { raw: 0x7fffffffffffffff },
    };
    const X: Vec3 = Vec3 {
        x: Fixed { raw: 0x100000000 }, y: Fixed { raw: 0 }, z: Fixed { raw: 0 },
    };
    const Y: Vec3 = Vec3 {
        x: Fixed { raw: 0 }, y: Fixed { raw: 0x100000000 }, z: Fixed { raw: 0 },
    };
    const Z: Vec3 = Vec3 {
        x: Fixed { raw: 0 }, y: Fixed { raw: 0 }, z: Fixed { raw: 0x100000000 },
    };
    const NEG_X: Vec3 = Vec3 {
        x: Fixed { raw: -0x100000000 }, y: Fixed { raw: 0 }, z: Fixed { raw: 0 },
    };
    const NEG_Y: Vec3 = Vec3 {
        x: Fixed { raw: 0 }, y: Fixed { raw: -0x100000000 }, z: Fixed { raw: 0 },
    };
    const NEG_Z: Vec3 = Vec3 {
        x: Fixed { raw: 0 }, y: Fixed { raw: 0 }, z: Fixed { raw: -0x100000000 },
    };
    const AXES: [Vec3; 3] = [
        Vec3 { x: Fixed { raw: 0x100000000 }, y: Fixed { raw: 0 }, z: Fixed { raw: 0 } },
        Vec3 { x: Fixed { raw: 0 }, y: Fixed { raw: 0x100000000 }, z: Fixed { raw: 0 } },
        Vec3 { x: Fixed { raw: 0 }, y: Fixed { raw: 0 }, z: Fixed { raw: 0x100000000 } },
    ];

    #[inline(always)]
    fn new(x: Fixed, y: Fixed, z: Fixed) -> Vec3 {
        Vec3 { x, y, z }
    }

    #[inline(always)]
    fn splat(v: Fixed) -> Vec3 {
        Vec3 { x: v, y: v, z: v }
    }

    #[inline(always)]
    fn select(mask: BVec3, if_true: Vec3, if_false: Vec3) -> Vec3 {
        Vec3 {
            x: if mask.x {
                if_true.x
            } else {
                if_false.x
            },
            y: if mask.y {
                if_true.y
            } else {
                if_false.y
            },
            z: if mask.z {
                if_true.z
            } else {
                if_false.z
            },
        }
    }

    #[inline(always)]
    fn from_array(a: [Fixed; 3]) -> Vec3 {
        let [x, y, z] = a;
        Vec3 { x, y, z }
    }

    #[inline(always)]
    fn to_array(self: Vec3) -> [Fixed; 3] {
        [self.x, self.y, self.z]
    }

    #[inline(always)]
    fn extend(self: Vec3, w: Fixed) -> Vec4 {
        Vec4 { x: self.x, y: self.y, z: self.z, w }
    }

    #[inline(always)]
    fn truncate(self: Vec3) -> Vec2 {
        Vec2 { x: self.x, y: self.y }
    }

    #[inline(always)]
    fn with_x(self: Vec3, x: Fixed) -> Vec3 {
        Vec3 { x: x, y: self.y, z: self.z }
    }

    #[inline(always)]
    fn with_y(self: Vec3, y: Fixed) -> Vec3 {
        Vec3 { x: self.x, y: y, z: self.z }
    }

    #[inline(always)]
    fn with_z(self: Vec3, z: Fixed) -> Vec3 {
        Vec3 { x: self.x, y: self.y, z: z }
    }

    #[inline(always)]
    fn from_homogeneous(v: Vec4) -> Vec3 {
        let r = RecipTrait::new(v.w);
        Vec3 { x: r.mul(v.x), y: r.mul(v.y), z: r.mul(v.z) }
    }

    #[inline(always)]
    fn to_homogeneous(self: Vec3) -> Vec4 {
        Self::extend(self, F_ONE)
    }

    #[inline(always)]
    fn dot(self: Vec3, rhs: Vec3) -> Fixed {
        dot3(self.x, rhs.x, self.y, rhs.y, self.z, rhs.z)
    }

    #[inline(always)]
    fn dot_into_vec(self: Vec3, rhs: Vec3) -> Vec3 {
        let d = Self::dot(self, rhs);
        Vec3 { x: d, y: d, z: d }
    }

    #[inline(always)]
    fn cross(self: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 {
            x: mul_sub(self.y, rhs.z, rhs.y, self.z),
            y: mul_sub(self.z, rhs.x, rhs.z, self.x),
            z: mul_sub(self.x, rhs.y, rhs.x, self.y),
        }
    }

    #[inline(always)]
    fn min(self: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 {
            x: if self.x < rhs.x {
                self.x
            } else {
                rhs.x
            },
            y: if self.y < rhs.y {
                self.y
            } else {
                rhs.y
            },
            z: if self.z < rhs.z {
                self.z
            } else {
                rhs.z
            },
        }
    }

    #[inline(always)]
    fn max(self: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 {
            x: if self.x > rhs.x {
                self.x
            } else {
                rhs.x
            },
            y: if self.y > rhs.y {
                self.y
            } else {
                rhs.y
            },
            z: if self.z > rhs.z {
                self.z
            } else {
                rhs.z
            },
        }
    }

    #[inline(always)]
    fn clamp(self: Vec3, min: Vec3, max: Vec3) -> Vec3 {
        Vec3 {
            x: if self.x < min.x {
                min.x
            } else if self.x > max.x {
                max.x
            } else {
                self.x
            },
            y: if self.y < min.y {
                min.y
            } else if self.y > max.y {
                max.y
            } else {
                self.y
            },
            z: if self.z < min.z {
                min.z
            } else if self.z > max.z {
                max.z
            } else {
                self.z
            },
        }
    }

    #[inline(always)]
    fn min_element(self: Vec3) -> Fixed {
        let m = if self.y < self.z {
            self.y
        } else {
            self.z
        };
        let m = if self.x < m {
            self.x
        } else {
            m
        };
        m
    }

    #[inline(always)]
    fn max_element(self: Vec3) -> Fixed {
        let m = if self.y > self.z {
            self.y
        } else {
            self.z
        };
        let m = if self.x > m {
            self.x
        } else {
            m
        };
        m
    }

    #[inline(always)]
    fn min_position(self: Vec3) -> usize {
        let mut m = self.x;
        let mut index = 0;
        if self.y < m {
            m = self.y;
            index = 1;
        }
        if self.z < m {
            index = 2;
        }
        index
    }

    #[inline(always)]
    fn max_position(self: Vec3) -> usize {
        let mut m = self.x;
        let mut index = 0;
        if self.y > m {
            m = self.y;
            index = 1;
        }
        if self.z > m {
            index = 2;
        }
        index
    }

    #[inline(always)]
    fn element_sum(self: Vec3) -> Fixed {
        self.x + self.y + self.z
    }

    #[inline(always)]
    fn element_product(self: Vec3) -> Fixed {
        wide_mul(self.x, self.y).mul(self.z).narrow()
    }

    #[inline(always)]
    fn cmpeq(self: Vec3, rhs: Vec3) -> BVec3 {
        BVec3 { x: self.x == rhs.x, y: self.y == rhs.y, z: self.z == rhs.z }
    }

    #[inline(always)]
    fn cmpne(self: Vec3, rhs: Vec3) -> BVec3 {
        BVec3 { x: self.x != rhs.x, y: self.y != rhs.y, z: self.z != rhs.z }
    }

    #[inline(always)]
    fn cmpge(self: Vec3, rhs: Vec3) -> BVec3 {
        BVec3 { x: self.x >= rhs.x, y: self.y >= rhs.y, z: self.z >= rhs.z }
    }

    #[inline(always)]
    fn cmpgt(self: Vec3, rhs: Vec3) -> BVec3 {
        BVec3 { x: self.x > rhs.x, y: self.y > rhs.y, z: self.z > rhs.z }
    }

    #[inline(always)]
    fn cmple(self: Vec3, rhs: Vec3) -> BVec3 {
        BVec3 { x: self.x <= rhs.x, y: self.y <= rhs.y, z: self.z <= rhs.z }
    }

    #[inline(always)]
    fn cmplt(self: Vec3, rhs: Vec3) -> BVec3 {
        BVec3 { x: self.x < rhs.x, y: self.y < rhs.y, z: self.z < rhs.z }
    }

    #[inline(always)]
    fn abs(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.abs(), y: self.y.abs(), z: self.z.abs() }
    }

    #[inline(always)]
    fn signum(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.signum(), y: self.y.signum(), z: self.z.signum() }
    }

    #[inline(always)]
    fn copysign(self: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 { x: self.x.copysign(rhs.x), y: self.y.copysign(rhs.y), z: self.z.copysign(rhs.z) }
    }

    #[inline(always)]
    fn is_negative_bitmask(self: Vec3) -> u32 {
        Self::is_negative_mask(self).bitmask()
    }

    #[inline(always)]
    fn is_negative_mask(self: Vec3) -> BVec3 {
        BVec3 { x: self.x.is_negative(), y: self.y.is_negative(), z: self.z.is_negative() }
    }

    #[inline(always)]
    fn round(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.round(), y: self.y.round(), z: self.z.round() }
    }

    #[inline(always)]
    fn floor(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.floor(), y: self.y.floor(), z: self.z.floor() }
    }

    #[inline(always)]
    fn ceil(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.ceil(), y: self.y.ceil(), z: self.z.ceil() }
    }

    #[inline(always)]
    fn trunc(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.trunc(), y: self.y.trunc(), z: self.z.trunc() }
    }

    #[inline(always)]
    fn fract(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.fract(), y: self.y.fract(), z: self.z.fract() }
    }

    #[inline(always)]
    fn fract_gl(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.fract_gl(), y: self.y.fract_gl(), z: self.z.fract_gl() }
    }

    #[inline(always)]
    fn recip(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.recip(), y: self.y.recip(), z: self.z.recip() }
    }

    fn sin(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.sin(), y: self.y.sin(), z: self.z.sin() }
    }

    fn cos(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.cos(), y: self.y.cos(), z: self.z.cos() }
    }

    fn sin_cos(self: Vec3) -> (Vec3, Vec3) {
        let (sx, cx) = self.x.sin_cos();
        let (sy, cy) = self.y.sin_cos();
        let (sz, cz) = self.z.sin_cos();
        (Vec3 { x: sx, y: sy, z: sz }, Vec3 { x: cx, y: cy, z: cz })
    }

    fn exp(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.exp(), y: self.y.exp(), z: self.z.exp() }
    }

    fn exp2(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.exp2(), y: self.y.exp2(), z: self.z.exp2() }
    }

    fn ln(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.ln(), y: self.y.ln(), z: self.z.ln() }
    }

    fn log2(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.log2(), y: self.y.log2(), z: self.z.log2() }
    }

    fn powf(self: Vec3, n: Fixed) -> Vec3 {
        Vec3 { x: self.x.powf(n), y: self.y.powf(n), z: self.z.powf(n) }
    }

    #[inline(always)]
    fn sqrt(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.sqrt(), y: self.y.sqrt(), z: self.z.sqrt() }
    }

    #[inline(always)]
    fn step(self: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 { x: self.x.step(rhs.x), y: self.y.step(rhs.y), z: self.z.step(rhs.z) }
    }

    #[inline(always)]
    fn smoothstep(self: Vec3, edge0: Vec3, edge1: Vec3) -> Vec3 {
        Vec3 {
            x: self.x.smoothstep(edge0.x, edge1.x),
            y: self.y.smoothstep(edge0.y, edge1.y),
            z: self.z.smoothstep(edge0.z, edge1.z),
        }
    }

    #[inline(always)]
    fn saturate(self: Vec3) -> Vec3 {
        Vec3 { x: self.x.saturate(), y: self.y.saturate(), z: self.z.saturate() }
    }

    #[inline(always)]
    fn length(self: Vec3) -> Fixed {
        norm3(self.x, self.y, self.z)
    }

    #[inline(always)]
    fn length_squared(self: Vec3) -> Fixed {
        norm3_squared(self.x, self.y, self.z)
    }

    #[inline(always)]
    fn length_recip(self: Vec3) -> Fixed {
        Self::length(self).recip()
    }

    #[inline(always)]
    fn distance(self: Vec3, rhs: Vec3) -> Fixed {
        distance3(self.x, self.y, self.z, rhs.x, rhs.y, rhs.z)
    }

    #[inline(always)]
    fn distance_squared(self: Vec3, rhs: Vec3) -> Fixed {
        distance3_squared(self.x, self.y, self.z, rhs.x, rhs.y, rhs.z)
    }

    #[inline(always)]
    fn div_euclid(self: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 {
            x: self.x.div_euclid(rhs.x), y: self.y.div_euclid(rhs.y), z: self.z.div_euclid(rhs.z),
        }
    }

    #[inline(always)]
    fn rem_euclid(self: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 {
            x: self.x.rem_euclid(rhs.x), y: self.y.rem_euclid(rhs.y), z: self.z.rem_euclid(rhs.z),
        }
    }

    #[inline(always)]
    fn normalize(self: Vec3) -> Vec3 {
        let n = norm3_wide(self.x, self.y, self.z);
        match n.try_recip() {
            Some(r) => Vec3 { x: r.mul(self.x), y: r.mul(self.y), z: r.mul(self.z) },
            None => core::panic_with_felt252('Vec3: normalize zero'),
        }
    }

    #[inline(always)]
    fn try_normalize(self: Vec3) -> Option<Vec3> {
        let n = norm3_wide(self.x, self.y, self.z);
        match n.try_recip() {
            Some(r) => Some(Vec3 { x: r.mul(self.x), y: r.mul(self.y), z: r.mul(self.z) }),
            None => None,
        }
    }

    #[allow(manual_unwrap_or)]
    #[inline(always)]
    fn normalize_or(self: Vec3, fallback: Vec3) -> Vec3 {
        let n = norm3_wide(self.x, self.y, self.z);
        match n.try_recip() {
            Some(r) => Vec3 { x: r.mul(self.x), y: r.mul(self.y), z: r.mul(self.z) },
            None => fallback,
        }
    }

    #[inline(always)]
    fn normalize_or_zero(self: Vec3) -> Vec3 {
        Self::normalize_or(self, Self::ZERO)
    }

    #[inline(always)]
    fn normalize_and_length(self: Vec3) -> (Vec3, Fixed) {
        let n = norm3_wide(self.x, self.y, self.z);
        match n.try_recip() {
            Some(r) => (
                Vec3 { x: r.mul(self.x), y: r.mul(self.y), z: r.mul(self.z) }, n.to_fixed(),
            ),
            None => (Self::X, F_ZERO),
        }
    }

    #[inline(always)]
    fn is_normalized(self: Vec3) -> bool {
        is_unit3(self.x, self.y, self.z, NORMALIZED_EPS_RAW)
    }

    #[inline(always)]
    fn project_onto(self: Vec3, rhs: Vec3) -> Vec3 {
        let k = Self::dot(self, rhs) / Self::dot(rhs, rhs);
        Vec3 { x: rhs.x * k, y: rhs.y * k, z: rhs.z * k }
    }

    #[inline(always)]
    fn reject_from(self: Vec3, rhs: Vec3) -> Vec3 {
        let k = Self::dot(self, rhs) / Self::dot(rhs, rhs);
        Vec3 {
            x: wide_from(self.x).sub(wide_mul(rhs.x, k)).narrow(),
            y: wide_from(self.y).sub(wide_mul(rhs.y, k)).narrow(),
            z: wide_from(self.z).sub(wide_mul(rhs.z, k)).narrow(),
        }
    }

    #[inline(always)]
    fn project_onto_normalized(self: Vec3, rhs: Vec3) -> Vec3 {
        let d = Self::dot(self, rhs);
        Vec3 { x: rhs.x * d, y: rhs.y * d, z: rhs.z * d }
    }

    #[inline(always)]
    fn reject_from_normalized(self: Vec3, rhs: Vec3) -> Vec3 {
        let d = Self::dot(self, rhs);
        Vec3 {
            x: wide_from(self.x).sub(wide_mul(rhs.x, d)).narrow(),
            y: wide_from(self.y).sub(wide_mul(rhs.y, d)).narrow(),
            z: wide_from(self.z).sub(wide_mul(rhs.z, d)).narrow(),
        }
    }

    #[inline(always)]
    fn reflect(self: Vec3, normal: Vec3) -> Vec3 {
        let d = Self::dot(self, normal);
        let t = -(d + d);
        Vec3 {
            x: mul_add(t, normal.x, self.x),
            y: mul_add(t, normal.y, self.y),
            z: mul_add(t, normal.z, self.z),
        }
    }

    #[inline(always)]
    fn refract(self: Vec3, normal: Vec3, eta: Fixed) -> Vec3 {
        let n_dot_i = Self::dot(normal, self);
        let s = wide_from(F_ONE).sub(wide_mul(n_dot_i, n_dot_i)).narrow();
        let k = wide_from(F_ONE).lift().sub(wide_mul(eta, eta).mul(s)).narrow();
        if k.is_negative() {
            Self::ZERO
        } else {
            let f = mul_add(eta, n_dot_i, k.sqrt());
            Vec3 {
                x: mul_sub(eta, self.x, f, normal.x),
                y: mul_sub(eta, self.y, f, normal.y),
                z: mul_sub(eta, self.z, f, normal.z),
            }
        }
    }

    #[inline(always)]
    fn angle_between(self: Vec3, rhs: Vec3) -> Fixed {
        let c = Self::cross(self, rhs);
        norm3(c.x, c.y, c.z).atan2(Self::dot(self, rhs))
    }

    #[inline(always)]
    fn angle_to(self: Vec3, rhs: Vec3, axis: Vec3) -> Fixed {
        let s = det3(axis.x, axis.y, axis.z, self.x, self.y, self.z, rhs.x, rhs.y, rhs.z);
        s.atan2(Self::dot(self, rhs))
    }

    #[inline(always)]
    fn rotate_x(self: Vec3, angle: Fixed) -> Vec3 {
        let (s, c) = angle.sin_cos();
        Vec3 { x: self.x, y: mul_sub(self.y, c, self.z, s), z: dot2(self.y, s, self.z, c) }
    }

    #[inline(always)]
    fn rotate_y(self: Vec3, angle: Fixed) -> Vec3 {
        let (s, c) = angle.sin_cos();
        Vec3 { x: dot2(self.x, c, self.z, s), y: self.y, z: mul_sub(self.z, c, self.x, s) }
    }

    #[inline(always)]
    fn rotate_z(self: Vec3, angle: Fixed) -> Vec3 {
        let (s, c) = angle.sin_cos();
        Vec3 { x: mul_sub(self.x, c, self.y, s), y: dot2(self.x, s, self.y, c), z: self.z }
    }

    fn rotate_axis(self: Vec3, axis: Vec3, angle: Fixed) -> Vec3 {
        QuatTrait::mul_vec3(QuatTrait::from_axis_angle(axis, angle), self)
    }

    fn rotate_towards(self: Vec3, rhs: Vec3, max_angle: Fixed) -> Vec3 {
        let c = Self::cross(self, rhs);
        let cn = norm3_wide(c.x, c.y, c.z);
        let angle_between = cn.to_fixed().atan2(Self::dot(self, rhs));
        // When `max_angle < 0`, rotate no further than `PI` radians away
        let angle = max_angle.clamp(angle_between - PI, angle_between);
        // The rotation axis: the normalized cross product, or an arbitrary orthogonal
        // direction when the two vectors are parallel.
        let axis = match cn.try_recip() {
            Some(r) => Vec3 { x: r.mul(c.x), y: r.mul(c.y), z: r.mul(c.z) },
            None => Self::normalize(Self::any_orthogonal_vector(self)),
        };
        QuatTrait::mul_vec3(QuatTrait::from_axis_angle(axis, angle), self)
    }

    #[inline(always)]
    fn any_orthogonal_vector(self: Vec3) -> Vec3 {
        if self.x.abs() > self.y.abs() {
            // `self.cross(Vec3::Y)`
            Vec3 { x: -self.z, y: F_ZERO, z: self.x }
        } else {
            // `self.cross(Vec3::X)`
            Vec3 { x: F_ZERO, y: self.z, z: -self.y }
        }
    }

    #[inline(always)]
    fn any_orthonormal_vector(self: Vec3) -> Vec3 {
        let sign = self.z.signum();
        let a = -(sign + self.z).recip();
        Vec3 {
            x: wide_mul(self.x, self.y).mul(a).narrow(),
            y: wide_from(sign).lift().add(wide_mul(self.y, self.y).mul(a)).narrow(),
            z: -self.y,
        }
    }

    #[inline(always)]
    fn any_orthonormal_pair(self: Vec3) -> (Vec3, Vec3) {
        let neg = self.z.is_negative();
        let sign = if neg {
            F_NEG_ONE
        } else {
            F_ONE
        };
        // `sign * self.x`, so that the products below stay triple products.
        let sx = if neg {
            -self.x
        } else {
            self.x
        };
        let a = -(sign + self.z).recip();
        let b = wide_mul(self.x, self.y).mul(a).narrow();
        (
            Vec3 {
                x: wide_from(F_ONE).lift().add(wide_mul(sx, self.x).mul(a)).narrow(),
                y: if neg {
                    -b
                } else {
                    b
                },
                z: -sx,
            },
            Vec3 {
                x: b,
                y: wide_from(sign).lift().add(wide_mul(self.y, self.y).mul(a)).narrow(),
                z: -self.y,
            },
        )
    }

    fn slerp(self: Vec3, rhs: Vec3, s: Fixed) -> Vec3 {
        let la = norm3_wide(self.x, self.y, self.z);
        let lb = norm3_wide(rhs.x, rhs.y, rhs.z);
        let self_length = la.to_fixed();
        let rhs_length = lb.to_fixed();
        // The cosine of the angle between the two directions.
        let d = RecipTrait::new(self_length * rhs_length).mul(Self::dot(self, rhs));
        if d.abs() < NEAR_ONE {
            let theta = d.acos_clamped();
            let r = RecipTrait::new(theta.sin());
            let t1 = r.mul((theta * (F_ONE - s)).sin());
            let t2 = r.mul((theta * s).sin());
            // The interpolated length, then one shared division per operand.
            let len = self_length.lerp(rhs_length, s);
            let k1 = la.recip().mul(len * t1);
            let k2 = lb.recip().mul(len * t2);
            Vec3 {
                x: wide_mul(self.x, k1).add(wide_mul(rhs.x, k2)).narrow(),
                y: wide_mul(self.y, k1).add(wide_mul(rhs.y, k2)).narrow(),
                z: wide_mul(self.z, k1).add(wide_mul(rhs.z, k2)).narrow(),
            }
        } else if d.is_negative() {
            // Almost anti-parallel: turn by `PI * s` around an arbitrary orthogonal axis.
            let q = QuatTrait::from_axis_angle(
                Self::normalize(Self::any_orthogonal_vector(self)), PI * s,
            );
            let k = la.recip().mul(self_length.lerp(rhs_length, s));
            Self::mul_scalar(QuatTrait::mul_vec3(q, self), k)
        } else {
            // Almost parallel: the linear interpolation is the spherical one to within
            // `theta^2 / 8`.
            Self::lerp(self, rhs, s)
        }
    }

    #[inline(always)]
    fn lerp(self: Vec3, rhs: Vec3, s: Fixed) -> Vec3 {
        Vec3 { x: self.x.lerp(rhs.x, s), y: self.y.lerp(rhs.y, s), z: self.z.lerp(rhs.z, s) }
    }

    #[inline(always)]
    fn move_towards(self: Vec3, rhs: Vec3, d: Fixed) -> Vec3 {
        let a = rhs - self;
        let n = norm3_wide(a.x, a.y, a.z);
        if n.is_zero() || n.to_fixed() <= d {
            rhs
        } else {
            let k = n.recip().mul(d);
            Vec3 {
                x: mul_add(a.x, k, self.x), y: mul_add(a.y, k, self.y), z: mul_add(a.z, k, self.z),
            }
        }
    }

    #[inline(always)]
    fn midpoint(self: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 {
            x: self.x.lerp(rhs.x, F_HALF),
            y: self.y.lerp(rhs.y, F_HALF),
            z: self.z.lerp(rhs.z, F_HALF),
        }
    }

    #[inline(always)]
    fn mul_add(self: Vec3, a: Vec3, b: Vec3) -> Vec3 {
        Vec3 {
            x: mul_add(self.x, a.x, b.x),
            y: mul_add(self.y, a.y, b.y),
            z: mul_add(self.z, a.z, b.z),
        }
    }

    #[inline(always)]
    fn abs_diff_eq(self: Vec3, rhs: Vec3, max_abs_diff: Fixed) -> bool {
        self.x.abs_diff_eq(rhs.x, max_abs_diff)
            && self.y.abs_diff_eq(rhs.y, max_abs_diff)
            && self.z.abs_diff_eq(rhs.z, max_abs_diff)
    }

    #[inline(always)]
    fn clamp_length(self: Vec3, min: Fixed, max: Fixed) -> Vec3 {
        let n = norm3_wide(self.x, self.y, self.z);
        let len = n.to_fixed();
        if len < min {
            scaled(self, n, min)
        } else if len > max {
            scaled(self, n, max)
        } else {
            self
        }
    }

    #[inline(always)]
    fn clamp_length_max(self: Vec3, max: Fixed) -> Vec3 {
        let n = norm3_wide(self.x, self.y, self.z);
        if n.to_fixed() > max {
            scaled(self, n, max)
        } else {
            self
        }
    }

    #[inline(always)]
    fn clamp_length_min(self: Vec3, min: Fixed) -> Vec3 {
        let n = norm3_wide(self.x, self.y, self.z);
        if n.to_fixed() < min {
            scaled(self, n, min)
        } else {
            self
        }
    }

    #[inline(always)]
    fn add_scalar(self: Vec3, rhs: Fixed) -> Vec3 {
        Vec3 { x: self.x + rhs, y: self.y + rhs, z: self.z + rhs }
    }

    #[inline(always)]
    fn sub_scalar(self: Vec3, rhs: Fixed) -> Vec3 {
        Vec3 { x: self.x - rhs, y: self.y - rhs, z: self.z - rhs }
    }

    #[inline(always)]
    fn mul_scalar(self: Vec3, rhs: Fixed) -> Vec3 {
        Vec3 { x: self.x * rhs, y: self.y * rhs, z: self.z * rhs }
    }

    #[inline(always)]
    fn div_scalar(self: Vec3, rhs: Fixed) -> Vec3 {
        let r = RecipTrait::new(rhs);
        Vec3 { x: r.mul(self.x), y: r.mul(self.y), z: r.mul(self.z) }
    }

    #[inline(always)]
    fn rem_scalar(self: Vec3, rhs: Fixed) -> Vec3 {
        Vec3 { x: self.x % rhs, y: self.y % rhs, z: self.z % rhs }
    }

    #[inline(always)]
    fn as_ivec3(self: Vec3) -> IVec3 {
        IVec3 { x: self.x.to_int_trunc(), y: self.y.to_int_trunc(), z: self.z.to_int_trunc() }
    }

    #[inline(always)]
    fn as_uvec3(self: Vec3) -> UVec3 {
        UVec3 { x: to_u32(self.x), y: to_u32(self.y), z: to_u32(self.z) }
    }
}

/// Component-wise `+`. Exact. Panics with the `i64_add` overflow messages.
///
/// Mirrors `impl Add for glam::Vec3`.
pub impl Vec3Add of Add<Vec3> {
    #[inline(always)]
    fn add(lhs: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 { x: lhs.x + rhs.x, y: lhs.y + rhs.y, z: lhs.z + rhs.z }
    }
}

/// Component-wise `-`. Exact. Panics with the `i64_sub` overflow messages.
///
/// Mirrors `impl Sub for glam::Vec3`.
pub impl Vec3Sub of Sub<Vec3> {
    #[inline(always)]
    fn sub(lhs: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 { x: lhs.x - rhs.x, y: lhs.y - rhs.y, z: lhs.z - rhs.z }
    }
}

/// Component-wise `*`. One floor rescale per component. Panics with `'Fixed: overflow'`.
///
/// Mirrors `impl Mul for glam::Vec3`.
pub impl Vec3Mul of Mul<Vec3> {
    #[inline(always)]
    fn mul(lhs: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 { x: lhs.x * rhs.x, y: lhs.y * rhs.y, z: lhs.z * rhs.z }
    }
}

/// Component-wise `/`. Truncated toward zero. Panics with `'Fixed: division by zero'` or `'Fixed:
/// overflow'`.
///
/// Mirrors `impl Div for glam::Vec3`.
pub impl Vec3Div of Div<Vec3> {
    #[inline(always)]
    fn div(lhs: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 { x: lhs.x / rhs.x, y: lhs.y / rhs.y, z: lhs.z / rhs.z }
    }
}

/// Component-wise `%`. The remainder has the sign of `lhs` (exact). Panics with `'Fixed: division
/// by zero'`.
///
/// Mirrors `impl Rem for glam::Vec3`.
pub impl Vec3Rem of Rem<Vec3> {
    #[inline(always)]
    fn rem(lhs: Vec3, rhs: Vec3) -> Vec3 {
        Vec3 { x: lhs.x % rhs.x, y: lhs.y % rhs.y, z: lhs.z % rhs.z }
    }
}

/// Component-wise negation. Panics with `'i64_neg Underflow'` on `Fixed::MIN`.
///
/// Mirrors `impl Neg for glam::Vec3`.
pub impl Vec3Neg of Neg<Vec3> {
    #[inline(always)]
    fn neg(a: Vec3) -> Vec3 {
        Vec3 { x: -a.x, y: -a.y, z: -a.z }
    }
}

/// Mirrors `impl AddAssign for glam::Vec3`.
pub impl Vec3AddAssign of AddAssign<Vec3, Vec3> {
    #[inline(always)]
    fn add_assign(ref self: Vec3, rhs: Vec3) {
        self = self + rhs;
    }
}

/// Mirrors `impl SubAssign for glam::Vec3`.
pub impl Vec3SubAssign of SubAssign<Vec3, Vec3> {
    #[inline(always)]
    fn sub_assign(ref self: Vec3, rhs: Vec3) {
        self = self - rhs;
    }
}

/// Mirrors `impl MulAssign for glam::Vec3`.
pub impl Vec3MulAssign of MulAssign<Vec3, Vec3> {
    #[inline(always)]
    fn mul_assign(ref self: Vec3, rhs: Vec3) {
        self = self * rhs;
    }
}

/// Mirrors `impl DivAssign for glam::Vec3`.
pub impl Vec3DivAssign of DivAssign<Vec3, Vec3> {
    #[inline(always)]
    fn div_assign(ref self: Vec3, rhs: Vec3) {
        self = self / rhs;
    }
}

/// Mirrors `impl RemAssign for glam::Vec3`.
pub impl Vec3RemAssign of RemAssign<Vec3, Vec3> {
    #[inline(always)]
    fn rem_assign(ref self: Vec3, rhs: Vec3) {
        self = self % rhs;
    }
}

/// Mirrors `impl AddAssign<f32> for glam::Vec3` (see `Vec3Trait::add_scalar`).
pub impl Vec3AddAssignScalar of AddAssign<Vec3, Fixed> {
    #[inline(always)]
    fn add_assign(ref self: Vec3, rhs: Fixed) {
        self = Vec3Trait::add_scalar(self, rhs);
    }
}

/// Mirrors `impl SubAssign<f32> for glam::Vec3` (see `Vec3Trait::sub_scalar`).
pub impl Vec3SubAssignScalar of SubAssign<Vec3, Fixed> {
    #[inline(always)]
    fn sub_assign(ref self: Vec3, rhs: Fixed) {
        self = Vec3Trait::sub_scalar(self, rhs);
    }
}

/// Mirrors `impl MulAssign<f32> for glam::Vec3` (see `Vec3Trait::mul_scalar`).
pub impl Vec3MulAssignScalar of MulAssign<Vec3, Fixed> {
    #[inline(always)]
    fn mul_assign(ref self: Vec3, rhs: Fixed) {
        self = Vec3Trait::mul_scalar(self, rhs);
    }
}

/// Mirrors `impl DivAssign<f32> for glam::Vec3` (see `Vec3Trait::div_scalar`).
pub impl Vec3DivAssignScalar of DivAssign<Vec3, Fixed> {
    #[inline(always)]
    fn div_assign(ref self: Vec3, rhs: Fixed) {
        self = Vec3Trait::div_scalar(self, rhs);
    }
}

/// Mirrors `impl RemAssign<f32> for glam::Vec3` (see `Vec3Trait::rem_scalar`).
pub impl Vec3RemAssignScalar of RemAssign<Vec3, Fixed> {
    #[inline(always)]
    fn rem_assign(ref self: Vec3, rhs: Fixed) {
        self = Vec3Trait::rem_scalar(self, rhs);
    }
}

/// `v[i]`. Panics with `'Vec3: index out of bounds'` if `index >= 3`.
///
/// Mirrors `impl Index<usize> for glam::Vec3`.
/// #### Panics
/// * `'Vec3: index out of bounds'` if `index >= 3`.
/// #### Deviations
/// * `IndexView` returns the element by value; `IndexMut` is not ported (see the struct).
/// * The panic message is the `felt252` `'Vec3: index out of bounds'` (glam-rs panics with
///   `index out of bounds`).
pub impl Vec3IndexView of IndexView<Vec3, usize> {
    type Target = Fixed;
    #[inline(always)]
    fn index(self: @Vec3, index: usize) -> Fixed {
        match index {
            0 => *self.x,
            1 => *self.y,
            2 => *self.z,
            _ => core::panic_with_felt252('Vec3: index out of bounds'),
        }
    }
}

/// Mirrors `impl From<[f32; 3]> for glam::Vec3`.
pub impl FixedArrayIntoVec3 of Into<[Fixed; 3], Vec3> {
    #[inline(always)]
    fn into(self: [Fixed; 3]) -> Vec3 {
        Vec3Trait::from_array(self)
    }
}

/// Mirrors `impl From<glam::Vec3> for [f32; 3]`.
pub impl Vec3IntoFixedArray of Into<Vec3, [Fixed; 3]> {
    #[inline(always)]
    fn into(self: Vec3) -> [Fixed; 3] {
        [self.x, self.y, self.z]
    }
}

/// Mirrors `impl From<(f32, f32, f32)> for glam::Vec3`.
pub impl FixedTupleIntoVec3 of Into<(Fixed, Fixed, Fixed), Vec3> {
    #[inline(always)]
    fn into(self: (Fixed, Fixed, Fixed)) -> Vec3 {
        let (x, y, z) = self;
        Vec3 { x, y, z }
    }
}

/// Mirrors `impl From<glam::Vec3> for (f32, f32, f32)`.
pub impl Vec3IntoFixedTuple of Into<Vec3, (Fixed, Fixed, Fixed)> {
    #[inline(always)]
    fn into(self: Vec3) -> (Fixed, Fixed, Fixed) {
        (self.x, self.y, self.z)
    }
}

/// Mirrors `impl From<(Vec2, f32)> for glam::Vec3`.
pub impl Vec2FixedIntoVec3 of Into<(Vec2, Fixed), Vec3> {
    #[inline(always)]
    fn into(self: (Vec2, Fixed)) -> Vec3 {
        let (v, z) = self;
        Vec3 { x: v.x, y: v.y, z }
    }
}

/// `true` becomes `1` and `false` becomes `0`.
///
/// Mirrors `impl From<glam::BVec3> for glam::Vec3`.
pub impl BVec3IntoVec3 of Into<BVec3, Vec3> {
    #[inline(always)]
    fn into(self: BVec3) -> Vec3 {
        Vec3 {
            x: if self.x {
                F_ONE
            } else {
                F_ZERO
            },
            y: if self.y {
                F_ONE
            } else {
                F_ZERO
            },
            z: if self.z {
                F_ONE
            } else {
                F_ZERO
            },
        }
    }
}

/// The `IVec3 -> Vec3` cast (exact: every `i32` is representable).
///
/// Mirrors `glam::IVec3::as_vec3` and `impl From<glam::IVec3> for glam::Vec3`.
pub impl IVec3IntoVec3 of Into<IVec3, Vec3> {
    #[inline(always)]
    fn into(self: IVec3) -> Vec3 {
        Vec3 {
            x: FixedTrait::from_int(self.x),
            y: FixedTrait::from_int(self.y),
            z: FixedTrait::from_int(self.z),
        }
    }
}

/// The `UVec3 -> Vec3` cast. Panics with `'Vec3: cast out of range'` above `2^31 - 1`, where the
/// Rust `as` cast is lossy but total.
///
/// Mirrors `glam::UVec3::as_vec3` and `impl From<glam::UVec3> for glam::Vec3`.
pub impl UVec3IntoVec3 of Into<UVec3, Vec3> {
    #[inline(always)]
    fn into(self: UVec3) -> Vec3 {
        Vec3 {
            x: self.x.try_into().expect('Vec3: cast out of range'),
            y: self.y.try_into().expect('Vec3: cast out of range'),
            z: self.z.try_into().expect('Vec3: cast out of range'),
        }
    }
}

/// `0`.
const F_ZERO: Fixed = Fixed { raw: 0 };

/// `1`.
const F_ONE: Fixed = Fixed { raw: 0x100000000 };

/// `-1`.
const F_NEG_ONE: Fixed = Fixed { raw: -0x100000000 };

/// `1 / 2`.
const F_HALF: Fixed = Fixed { raw: 0x80000000 };

/// The `is_normalized` threshold: 1024 raw ULP (`2^-22`) on the squared length.
/// The squared length of a vector normalized by this module is within a few ULP of 1; glam-rs
/// uses `2e-4`, which is ~1700 f32 epsilons, while this is ~1000 Q32.32 epsilons.
const NORMALIZED_EPS_RAW: u16 = 1024;

/// `1 - 2^-20`, the cosine band in which [`Vec3Trait::slerp`] falls back to a linear
/// interpolation, where glam-rs uses `1 - 3e-7`.
///
/// Below `theta = acos(NEAR_ONE) = 1.38e-3` rad the slerp branch divides the two sine weights
/// by `sin(theta)`, which costs `2 ULP / sin(theta) = 3.4e-7` relative on the result, while the
/// linear fallback differs from the exact slerp by `theta^2 / 8 = 2.4e-7`: the two branches
/// meet with the same accuracy, which is what fixes the threshold. It is the same value as
/// `quat::NEAR_ONE`, whose derivation is the same one on the half angle.
pub const NEAR_ONE: Fixed = Fixed { raw: 0xfffff000 };

/// `v * (target / len)`: one division shared by the components, one fused product each.
#[inline(always)]
fn scaled(v: Vec3, n: Norm, target: Fixed) -> Vec3 {
    let k = n.recip().mul(target);
    Vec3 { x: v.x * k, y: v.y * k, z: v.z * k }
}

/// Truncation toward zero to `u32`. The integer part always fits an `i32`, so only a negative
/// value can fail.
#[inline(always)]
fn to_u32(v: Fixed) -> u32 {
    v.to_int_trunc().try_into().expect('Vec3: cast out of range')
}
