//! Loop-free transcendentals on the `FI64` (i64 Q32.32) representation.
//!
//! Internals run on `felt252` accumulators at scale 2^60 with floor shifts (`shrK`), i.e. the same
//! "lazy" arithmetic as the fused linear-algebra kernels: one field mul + one field add + one
//! range-checked shift per Horner step. Inputs and outputs are plain `FI64`.
//! Constants, tables and Horner evaluators are generated by scripts/gen_trig.py, which also holds a
//! bit-exact Python mirror of every function below (used for the error sweeps).
#[feature("bounded-int-utils")]
use core::internal::bounded_int::{self, NegateHelper, upcast};
use core::num::traits::{Sqrt, WideMul};
use crate::fixed::i64b::FI64;
use crate::trig_gen::{
    COS_TABLE, HALF_PI, PI, SIN_TABLE, ZT, acos_poly_x, atan_segments, cos_poly_u, lut_split, reduce8, shr22,
    shr28, shr60, sin_poly_u,
};

#[inline(always)]
fn to_fixed(v: felt252) -> FI64 {
    FI64 { raw: v.try_into().expect('fixed overflow') }
}

/// sin(z) for z in [0, pi/4], result raw Q32.32.
#[inline(always)]
fn sin_core(z: felt252, u: felt252) -> felt252 {
    shr60(z * sin_poly_u(u))
}
/// cos(z) for z in [0, pi/4], result raw Q32.32.
#[inline(always)]
fn cos_core(u: felt252) -> felt252 {
    shr28(cos_poly_u(u))
}

pub fn sin(x: FI64) -> FI64 {
    let (oct, z) = reduce8(x.raw);
    let z: felt252 = upcast(z);
    let u = z * z;
    to_fixed(
        match oct {
            0 | 3 => sin_core(z, u),
            1 | 2 => cos_core(u),
            4 | 7 => -sin_core(z, u),
            _ => -cos_core(u),
        },
    )
}

pub fn cos(x: FI64) -> FI64 {
    let (oct, z) = reduce8(x.raw);
    let z: felt252 = upcast(z);
    let u = z * z;
    to_fixed(
        match oct {
            0 | 7 => cos_core(u),
            1 | 6 => sin_core(z, u),
            2 | 5 => -sin_core(z, u),
            _ => -cos_core(u),
        },
    )
}

/// Both at once: shares the range reduction and u = z^2.
pub fn sin_cos(x: FI64) -> (FI64, FI64) {
    let (oct, z) = reduce8(x.raw);
    let z: felt252 = upcast(z);
    let u = z * z;
    let s = sin_core(z, u);
    let c = cos_core(u);
    let (rs, rc) = match oct {
        0 => (s, c),
        1 => (c, s),
        2 => (c, -s),
        3 => (s, -c),
        4 => (-s, -c),
        5 => (-c, -s),
        6 => (-c, s),
        _ => (-s, c),
    };
    (to_fixed(rs), to_fixed(rc))
}

#[inline(always)]
fn lut_eval(table: Span<i64>, z: ZT) -> felt252 {
    let (i, j, f) = lut_split(z);
    let lo: felt252 = (*table[i]).into();
    let hi: felt252 = (*table[j]).into();
    lo + shr22((hi - lo) * f)
}

/// Const-array LUT (step 2^-10 rad on [0, pi/4], one sin and one cos table) + linear interpolation.
pub fn sin_lut(x: FI64) -> FI64 {
    let (oct, z) = reduce8(x.raw);
    to_fixed(
        match oct {
            0 | 3 => lut_eval(SIN_TABLE.span(), z),
            1 | 2 => lut_eval(COS_TABLE.span(), z),
            4 | 7 => -lut_eval(SIN_TABLE.span(), z),
            _ => -lut_eval(COS_TABLE.span(), z),
        },
    )
}

#[inline(always)]
fn abs_sign(v: i64) -> (u64, bool) {
    match bounded_int::constrain::<i64, 0>(v) {
        Ok(lt0) => (upcast(lt0.negate()), true),
        Err(ge0) => (upcast(ge0), false),
    }
}

/// atan2(y, x): one division, 8 segments x degree-5 Horner selected by a jump table, octant fix-up.
pub fn atan2(y: FI64, x: FI64) -> FI64 {
    let (ax, x_neg) = abs_sign(x.raw);
    let (ay, y_neg) = abs_sign(y.raw);
    let (mn, mx, swap) = if ay > ax {
        (ax, ay, true)
    } else {
        (ay, ax, false)
    };
    if mx == 0 {
        return FI64 { raw: 0 };
    }
    let num: u128 = WideMul::wide_mul(mn, 0x100000000_u64);
    let z: u128 = num / mx.into();
    let (idx, t) = DivRem::div_rem(z, 0x20000000);
    let mut a = shr28(atan_segments(idx.into(), t.into()));
    if swap {
        a = HALF_PI - a;
    }
    if x_neg {
        a = PI - a;
    }
    if y_neg {
        a = -a;
    }
    to_fixed(a)
}

pub fn atan(x: FI64) -> FI64 {
    atan2(x, FI64 { raw: 0x100000000 })
}

/// acos(x) = sqrt(1 - |x|) * P(|x|), reflected for x < 0. One core sqrt, degree-10 Horner, no division.
pub fn acos(x: FI64) -> FI64 {
    let (ax, neg) = abs_sign(x.raw);
    let om: u64 = 0x100000000 - ax; // panics if |x| > 1
    let s: u64 = Sqrt::sqrt(WideMul::wide_mul(om, 0x100000000_u64));
    let r = shr60(s.into() * acos_poly_x(ax.into()));
    to_fixed(if neg {
        PI - r
    } else {
        r
    })
}

pub fn asin(x: FI64) -> FI64 {
    FI64 { raw: (HALF_PI - acos(x).raw.into()).try_into().expect('fixed overflow') }
}
