#!/usr/bin/env python3
"""Generates the three fixed-point matrix modules of `glam` from one template.

    Mat2 / Mat3 / Mat4  (column major, columns are `Vec2` / `Vec3` / `Vec4`)

glam-rs generates these types from a single template too (`codegen/templates/mat.rs.tera`); this
script plays the same role, as `fvec.py` does for the vectors. For every type it emits

    packages/glam/src/<m>.cairo               the library module
    packages/glam/tests/test_<m>.cairo        the tests (expected values computed here, in Python)
    packages/benches/tests/bench_<m>.cairo    one `X__base` / `X__op` pair per public function
    packages/benches/src/alt/<m>.cairo        the losing formulations, kept for comparison

usage:
    tools/codegen/fmat.py            regenerate the files (then runs `scarb fmt` on them)
    tools/codegen/fmat.py --check    exit 1 if the committed files differ from the output

The dimension-independent part (consts, constructors, the column-major plumbing, component-wise
operations, the matrix products, conversions, operators) is templated; the numerics that have no
dimension-independent shape (`determinant`, `inverse`, the rotation constructors, the affine
transforms) are per-type snippets, not `if n ==` soup.

Every product goes through a fused kernel of `fixed::wide`: one rescale per output scalar
(docs/DESIGN.md section 2.1). The generator is split in two files (dependency-free, python >= 3.8):
    fmat.py        type model, driver, library module template, bench and `alt` templates
    fmat_tests.py  test template
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import fvec as g  # noqa: E402  (doc helpers, `Method`, `Bench`, `Alt`, literals)

ROOT = Path(__file__).resolve().parents[2]
HEADER = "// GENERATED by tools/codegen/fmat.py - do not edit by hand.\n"

ONE_RAW = g.ONE_RAW
indent, fixed_lit, Method = g.indent, g.fixed_lit, g.Method


def doc(summary, mirrors, panics=None, dev=None, indent_="    "):
    semantic_dev = [
        item for item in (dev or [])
        if not item.startswith(("Exact", "As "))
        and not any(word in item.lower() for word in ("gas", "bench", "inlin"))
    ]
    if not semantic_dev and panics and any(
        "Overflow" in item or "overflow" in item for item in panics
    ):
        dev = (dev or []) + [
            "Overflow panics where f32 returns infinity or a larger finite value: "
            "docs/DESIGN.md section 3, \"overflow\".",
        ]
    return g.doc(summary, mirrors, panics, dev, indent_)


class Ty:
    """One of the three matrix types."""

    def __init__(self, n):
        self.n = n
        self.name = f"Mat{n}"
        self.mod = f"mat{n}"
        self.V = f"Vec{n}"
        self.vmod = f"vec{n}"
        self.cols = ["x_axis", "y_axis", "z_axis", "w_axis"][:n]
        self.c = "xyzw"[:n]
        self.arr = f"[Fixed; {n * n}]"
        self.arr2d = f"[[Fixed; {n}]; {n}]"

    def dim(self, n):
        return Ty(n)

    def el(self, m, i, j):
        """The element of column `i`, row `j` of the matrix expression `m`."""
        return f"{m}.{self.cols[i]}.{self.c[j]}"

    def mat(self, f, name=None):
        """`Mat3 { x_axis: f(0), y_axis: f(1), z_axis: f(2) }`."""
        return (f"{name or self.name} {{ "
                + ", ".join(f"{col}: {f(i)}" for i, col in enumerate(self.cols)) + " }")

    def vec(self, f, name=None):
        """`Vec3 { x: f(0), y: f(1), z: f(2) }`."""
        return (f"{name or self.V} {{ "
                + ", ".join(f"{c}: {f(j)}" for j, c in enumerate(self.c)) + " }")

    def by_col(self, f):
        """A matrix whose column `i` is `f(i)` applied component-wise (`f(i, j)`)."""
        return self.mat(lambda i: self.vec(lambda j: f(i, j)))


TYPES = [Ty(n) for n in (2, 3, 4)]


# --------------------------------------------------------------------------------------------
# Kernel calls (`fixed::wide`): one rescale per output scalar
# --------------------------------------------------------------------------------------------
def dot_call(pairs, add=None):
    """`dotN(a0, b0, a1, b1, ..)`, or `dotN_add(.., c)` when `add` is given."""
    args = ", ".join(f"{a}, {b}" for a, b in pairs)
    suffix = "_add" if add else ""
    return f"dot{len(pairs)}{suffix}({args}" + (f", {add})" if add else ")")


def mul_sub_call(a, b, c, d):
    return f"mul_sub({a}, {b}, {c}, {d})"


# --------------------------------------------------------------------------------------------
# Shared panic / deviation wordings
# --------------------------------------------------------------------------------------------
OVF = "`'Fixed: overflow'` if the result does not fit the scalar range."
ADD_P = ("`'i64_add Overflow'` / `'i64_add Underflow'` if an element sum leaves the scalar "
         "range.")
SUB_P = ("`'i64_sub Overflow'` / `'i64_sub Underflow'` if an element difference leaves the "
         "scalar range.")
NEG_P = "`'i64_neg Underflow'` if an element is `MIN`."
DIV0 = "`'Fixed: division by zero'` if `rhs` is zero."
FLOOR_DEV = ("The product is floored (one rescale per element), not rounded to nearest: at most "
             "1 ULP below the exact result.")
DOT_DEV = ("One `dot{n}` fused kernel per element of the result: the exact Q64.64 sum of the {n} "
           "products is rescaled once (floored), so no intermediate term can overflow and the "
           "element is at most 1 ULP below the exact value.")
TRIG_DEV = ("`fixed::trig::sin_cos` is accurate to about 1 ULP over a turn (see its "
            "documentation); the products that follow add one floor rescale each.")
GLAM_ASSERT = "The `glam_assert!` precondition is not checked (docs/DESIGN.md section 3)."
QUAT_DEV = [
    GLAM_ASSERT + " `rotation` must be normalized: as in glam-rs the elements are the ones of "
    "the rotation matrix of a unit quaternion, and a quaternion of length `l` scales the matrix "
    "by `l^2`.",
    "Every element is one exact two-term sum of raw products rescaled once (floored): "
    "`1 - 2 (b^2 + c^2)` on the diagonal, `2 (ab +- cd)` off it, with the doubling folded into "
    "the second factor. Nine rescales for the nine elements, at most 1 ULP below the exact "
    "value each. The literal glam-rs expression rescales the twelve products one by one and "
    "costs 2.1x as much (43 460 against 20 660 gas for `Mat3`): it is kept in `benches::alt`.",
]


def index_msg(t):
    return f"'{t.name}: index out of bounds'"


def singular_msg(t):
    return f"'{t.name}: singular'"


def ident_dev(t):
    return (f"`Default` is `{t.name}::IDENTITY` as in glam-rs, not the derived all-zero value: "
            "the impl is written by hand.")


# --------------------------------------------------------------------------------------------
# Consts
# --------------------------------------------------------------------------------------------
def consts(t):
    zero = t.by_col(lambda i, j: fixed_lit(0))
    ident = t.by_col(lambda i, j: fixed_lit(ONE_RAW if i == j else 0))
    return [
        ("ZERO", t.name, "A matrix with all elements set to `0`.", zero),
        ("IDENTITY", t.name,
         "The identity matrix: all diagonal elements are `1` and all off-diagonal elements are "
         "`0`.", ident),
    ]


# --------------------------------------------------------------------------------------------
# Bodies shared by the library and by `benches::alt`
# --------------------------------------------------------------------------------------------
def wsum(terms):
    """A signed sum of products as one accumulator chain (`wide_mul(..).sub(..).add(..)`).

    The sign is folded into the accumulation instead of negating the narrowed result: the sum
    stays exact and a single floor applies to the signed value."""
    first = next(i for i, (_, _, s) in enumerate(terms) if s > 0)
    a, b, _ = terms[first]
    out = f"wide_mul({a}, {b})"
    for i, (a, b, s) in enumerate(terms):
        if i != first:
            out += f".{'add' if s > 0 else 'sub'}(wide_mul({a}, {b}))"
    return out


def body_mul_vec(t, fused):
    """`self * rhs`: one `dotN` per row of the result."""
    if fused:
        return t.vec(lambda j: dot_call([(t.el("self", i, j), f"rhs.{t.c[i]}")
                                         for i in range(t.n)]))
    return t.vec(lambda j: " + ".join(f"{t.el('self', i, j)} * rhs.{t.c[i]}"
                                      for i in range(t.n)))


def body_mul_mat(t, fused):
    if fused:
        return t.mat(lambda i: f"Self::mul_vec{t.n}(self, rhs.{t.cols[i]})")
    # transpose once, then one `dot` per element (the rows of `self` become columns)
    lines = ["let m = Self::transpose(self);"]
    body = t.mat(lambda i: t.vec(
        lambda j: dot_call([(f"m.{t.cols[j]}.{t.c[k]}", f"rhs.{t.cols[i]}.{t.c[k]}")
                            for k in range(t.n)])))
    return "\n".join(lines) + "\n" + body


def body_div_scalar(t, fused):
    if fused:
        return ("let r = RecipTrait::new(rhs);\n"
                + t.by_col(lambda i, j: f"r.mul({t.el('self', i, j)})"))
    return t.by_col(lambda i, j: f"{t.el('self', i, j)} / rhs")


def body_determinant(t, fused):
    n = t.n
    if n == 2:
        return mul_sub_call(t.el("self", 0, 0), t.el("self", 1, 1),
                            t.el("self", 0, 1), t.el("self", 1, 0))
    if n == 3:
        if fused:
            return "det3(" + ", ".join(t.el("self", i, j) for i in range(3)
                                       for j in range(3)) + ")"
        # the literal glam-rs `x_axis.dot(y_axis.cross(z_axis))`: the cross product is floored
        # before the dot product
        return ("let c = Vec3Trait::cross(self.y_axis, self.z_axis);\n"
                "Vec3Trait::dot(self.x_axis, c)")
    if fused:
        six = [name for name, _, _, _, _ in COEFS if name in MAT4_DET_MINORS]
        return (minors(t, six) + "\n" + mat4_cofactors(t) + "\n" + mat4_det(t))
    # expansion along the first row with four `det3` kernels instead of six shared 2x2 minors
    dets = []
    for i in range(4):
        rest = [k for k in range(4) if k != i]
        args = ", ".join(t.el("self", k, j) for k in rest for j in (1, 2, 3))
        dets.append(f"let d{i} = det3({args});")
    terms = [(t.el("self", i, 0), f"d{i}", 1 if i % 2 == 0 else -1) for i in range(4)]
    return "\n".join(dets) + "\n" + wsum(terms) + ".narrow()"


# The 18 2x2 minors of glam-rs `Mat4::inverse_checked` (`coef00` .. `coef23`), as
# `(name, a, b, c, d)` = `m[a] * m[b] - m[c] * m[d]` with `m[(i, j)]` the element of column `i`
# and row `j`. The six of them whose rows are `{2, 3}` are also what `determinant` expands on.
COEFS = [
    ("coef00", (2, 2), (3, 3), (3, 2), (2, 3)),
    ("coef02", (1, 2), (3, 3), (3, 2), (1, 3)),
    ("coef03", (1, 2), (2, 3), (2, 2), (1, 3)),
    ("coef04", (2, 1), (3, 3), (3, 1), (2, 3)),
    ("coef06", (1, 1), (3, 3), (3, 1), (1, 3)),
    ("coef07", (1, 1), (2, 3), (2, 1), (1, 3)),
    ("coef08", (2, 1), (3, 2), (3, 1), (2, 2)),
    ("coef10", (1, 1), (3, 2), (3, 1), (1, 2)),
    ("coef11", (1, 1), (2, 2), (2, 1), (1, 2)),
    ("coef12", (2, 0), (3, 3), (3, 0), (2, 3)),
    ("coef14", (1, 0), (3, 3), (3, 0), (1, 3)),
    ("coef15", (1, 0), (2, 3), (2, 0), (1, 3)),
    ("coef16", (2, 0), (3, 2), (3, 0), (2, 2)),
    ("coef18", (1, 0), (3, 2), (3, 0), (1, 2)),
    ("coef19", (1, 0), (2, 2), (2, 0), (1, 2)),
    ("coef20", (2, 0), (3, 1), (3, 0), (2, 1)),
    ("coef22", (1, 0), (3, 1), (3, 0), (1, 1)),
    ("coef23", (1, 0), (2, 1), (2, 0), (1, 1)),
]
# The six of the 18 whose rows are `{2, 3}`: `determinant` needs only those.
MAT4_DET_MINORS = ("coef00", "coef04", "coef08", "coef12", "coef16", "coef20")
# glam-rs `fac0` .. `fac5`, by the row of the result that uses them (`x`/`y`, `z`, `w`).
FACS = [("coef00", "coef02", "coef03"), ("coef04", "coef06", "coef07"),
        ("coef08", "coef10", "coef11"), ("coef12", "coef14", "coef15"),
        ("coef16", "coef18", "coef19"), ("coef20", "coef22", "coef23")]
# The three `fac` and the three elements (`vec0` .. `vec3`) each column of the adjugate uses.
ADJ_FACS = {0: (0, 1, 2), 1: (0, 3, 4), 2: (1, 3, 5), 3: (2, 4, 5)}
ADJ_VECS = {0: (1, 2, 3), 1: (0, 2, 3), 2: (0, 1, 3), 3: (0, 1, 2)}


def minors(t, names, m="self"):
    """`let coefXX = mul_sub(..);` for the named 2x2 minors."""
    out = []
    for name, a, b, c, d in COEFS:
        if name in names:
            out.append(f"let {name} = " + mul_sub_call(
                t.el(m, *a), t.el(m, *b), t.el(m, *c), t.el(m, *d)) + ";")
    return "\n".join(out)


def adjugate_terms(t, i, j, m="self"):
    """The three signed products of the adjugate element of column `i`, row `j` (Q64.64).

    The cofactor sign `(-1)^(i + j)` is folded into the accumulation: the sum is exact and a
    single floor applies to the signed value."""
    facs, vecs = ADJ_FACS[i], ADJ_VECS[i]
    comp = 0 if j <= 1 else j - 1
    col = t.cols[1] if j == 0 else t.cols[0]
    sign = 1 if (i + j) % 2 == 0 else -1
    signs = [sign, -sign, sign]
    return [(f"{m}.{col}.{t.c[vecs[k]]}", FACS[facs[k]][comp], signs[k]) for k in range(3)]


def mat4_cofactors(t, m="self"):
    """`q0` .. `q3`: the four cofactors of the first row, kept wide (Q64.64)."""
    return "\n".join(f"let q{i} = " + wsum(adjugate_terms(t, i, 0, m)) + ";" for i in range(4))


def mat4_det(t, m="self"):
    """`det = m00 * q0 + m01 * q1 + m02 * q2 + m03 * q3` (the signs are in the cofactors): four
    exact Q96.96 triple products and one rescale."""
    return "\n".join([f"q0.mul({t.el(m, 0, 0)})"]
                     + [f"    .add(q{k}.mul({t.el(m, 0, k)}))" for k in (1, 2, 3)]
                     + ["    .narrow()"])


def body_inverse_checked(t, fused):
    """The shared body of `inverse`, `try_inverse` and `inverse_or_zero`: the adjugate through
    fused kernels, then ONE division shared by every element (`Recip`)."""
    n = t.n
    div = ("let r = RecipTrait::new(det);\n", "r.mul({})") if fused \
        else ("", "{} / det")
    head, mul = div
    if n == 2:
        adj = {(0, 0): t.el("m", 1, 1), (0, 1): "-" + t.el("m", 0, 1),
               (1, 0): "-" + t.el("m", 1, 0), (1, 1): t.el("m", 0, 0)}
        return ("let det = " + mul_sub_call(t.el("m", 0, 0), t.el("m", 1, 1),
                                            t.el("m", 0, 1), t.el("m", 1, 0)) + ";\n"
                "if det == F_ZERO {\n    return None;\n}\n" + head
                + "Some(" + t.by_col(lambda i, j: mul.format(adj[(i, j)])) + ")")
    if n == 3:
        cross = ("let t{k} = " + t.vec(lambda j: mul_sub_call(
            "{a}." + t.c[(j + 1) % 3], "{b}." + t.c[(j + 2) % 3],
            "{a}." + t.c[(j + 2) % 3], "{b}." + t.c[(j + 1) % 3])) + ";")
        pairs = [(0, "m.y_axis", "m.z_axis"), (1, "m.z_axis", "m.x_axis"),
                 (2, "m.x_axis", "m.y_axis")]
        body = "\n".join(cross.replace("{k}", str(k)).replace("{a}", a).replace("{b}", b)
                         for k, a, b in pairs)
        return ("let det = det3(" + ", ".join(t.el("m", i, j) for i in range(3)
                                              for j in range(3)) + ");\n"
                "if det == F_ZERO {\n    return None;\n}\n" + body + "\n" + head
                # the adjugate is the transpose of (t0, t1, t2)
                + "Some(" + t.by_col(lambda i, j: mul.format(f"t{j}.{t.c[i]}")) + ")")
    names = [name for name, _, _, _, _ in COEFS]
    entries = "\n".join(
        f"let q{i}{j} = " + wsum(adjugate_terms(t, i, j, "m")) + ".narrow();"
        for i in range(4) for j in range(4) if j > 0)
    return (minors(t, names, "m") + "\n"
            + mat4_cofactors(t, "m") + "\n"
            + "let det = " + mat4_det(t, "m").replace("\n", "\n    ") + ";\n"
            + "if det == F_ZERO {\n    return None;\n}\n"
            + "\n".join(f"let q{i}0 = q{i}.narrow();" for i in range(4)) + "\n"
            + entries + "\n" + head
            + "Some(" + t.by_col(lambda i, j: mul.format(f"q{i}{j}")) + ")")


# --------------------------------------------------------------------------------------------
# Per-dimension snippets
# --------------------------------------------------------------------------------------------
def rotation_axis(t):
    """`from_axis_angle`: every element is one exact triple product plus one lifted term,
    rescaled once."""
    n = t.n
    off = {(0, 1): ("axis.z", 1), (0, 2): ("axis.y", -1), (1, 0): ("axis.z", -1),
           (1, 2): ("axis.x", 1), (2, 0): ("axis.y", 1), (2, 1): ("axis.x", -1)}

    def el(i, j):
        if i == 3 or j == 3:
            return fixed_lit(ONE_RAW if i == j else 0)
        if i == j:
            return (f"wide_mul(axis.{t.c[i]}, axis.{t.c[i]}).mul(omc)"
                    ".add(wide_from(cos).lift()).narrow()")
        a, b = sorted((i, j))
        term, sign = off[(i, j)]
        op = "add" if sign > 0 else "sub"
        return (f"wide_mul(axis.{t.c[a]}, axis.{t.c[b]}).mul(omc)"
                f".{op}(wide_mul({term}, sin).lift()).narrow()")

    return ("let (sin, cos) = angle.sin_cos();\nlet omc = F_ONE - cos;\n"
            + t.by_col(el))


def rotation_axis_named(t, axis):
    """`from_rotation_x/y/z`: the two rotated columns of the identity."""
    k = "xyz".index(axis)
    u, v = (k + 1) % 3, (k + 2) % 3

    def el(i, j):
        if i == j == k or i == 3 or j == 3:
            return fixed_lit(ONE_RAW if i == j else 0)
        if (i, j) == (u, u) or (i, j) == (v, v):
            return "cos"
        if (i, j) == (u, v):
            return "sin"
        if (i, j) == (v, u):
            return "-sin"
        return fixed_lit(0)

    return "let (sin, cos) = angle.sin_cos();\n" + t.by_col(el)


def quat_axes(t, q="rotation", scale=None, translation=None, fused=True):
    """`from_quat` and the TRS constructors: the 9 elements of the rotation matrix of a unit
    quaternion, each one an exact two-term sum of raw products rescaled once.

    `m[i][j] = 1 - 2 (b^2 + c^2)` on the diagonal and `+-2 (ab +- cd)` off it, with the doubling
    folded into the second factor (`x2 = x + x`, exact for a unit quaternion), so that every
    element is one `dot2` / `mul_sub` kernel. `scale` multiplies column `i` inside the same
    rescale (`W2 * Fixed -> T2`), never after it."""
    d = {c: f"{q}.{c}" for c in "xyzw"}
    dbl = {c: f"{c}2" for c in "xyz"}
    # (column, row) -> (a, b, c, d, sign): the element is `a * b2 (+-) c * d2`.
    off = {(0, 1): ("x", "y", "w", "z", 1), (0, 2): ("x", "z", "w", "y", -1),
           (1, 0): ("x", "y", "w", "z", -1), (1, 2): ("y", "z", "w", "x", 1),
           (2, 0): ("x", "z", "w", "y", 1), (2, 1): ("y", "z", "w", "x", -1)}

    def term(i, j):
        """The element as a wide accumulator expression (before the scale and the rescale)."""
        if i == j:
            a, b = [c for c in "xyz" if c != "xyz"[i]]
            return (f"wide_from(F_ONE).sub(wide_mul({d[a]}, {dbl[a]}))"
                    f".sub(wide_mul({d[b]}, {dbl[b]}))")
        a, b, c, e, sign = off[(i, j)]
        op = "add" if sign > 0 else "sub"
        return f"wide_mul({d[a]}, {dbl[b]}).{op}(wide_mul({d[c]}, {dbl[e]}))"

    def el(i, j):
        if i == 3:
            return fixed_lit(ONE_RAW) if j == 3 else f"{translation}.{t.c[j]}"
        if j == 3:
            return fixed_lit(0)
        if not fused:
            return unfused_el(i, j) if scale is None else f"({unfused_el(i, j)}) * {scale}.{t.c[i]}"
        acc = term(i, j)
        return acc + (f".mul({scale}.{t.c[i]}).narrow()" if scale else ".narrow()")

    def unfused_el(i, j):
        """The literal glam-rs expression: one rescale per product."""
        if i == j:
            a, b = [c for c in "xyz" if c != "xyz"[i]]
            return f"F_ONE - ({d[a]} * {dbl[a]} + {d[b]} * {dbl[b]})"
        a, b, c, e, sign = off[(i, j)]
        return f"{d[a]} * {dbl[b]} {'+' if sign > 0 else '-'} {d[c]} * {dbl[e]}"

    head = "".join(f"let {c}2 = {d[c]} + {d[c]};\n" for c in "xyz")
    if translation is None and t.n == 4:
        return head + t.by_col(lambda i, j: (fixed_lit(ONE_RAW if i == j else 0) if i == 3
                                             else el(i, j)))
    return head + t.by_col(el)


def affine2(t, scale=None, angle=False, translation=None):
    """The 2D affine constructors of `Mat3`: scale, rotation and translation in one 3x3."""
    def el(i, j):
        if i == 2:
            if j == 2:
                return fixed_lit(ONE_RAW)
            return f"{translation}.{t.c[j]}" if translation else fixed_lit(0)
        if j == 2:
            return fixed_lit(0)
        k = f"{scale}.{t.c[i]}" if scale else None
        if angle:
            if i == j:
                return f"cos * {k}" if k else "cos"
            if (i, j) == (0, 1):
                return f"sin * {k}" if k else "sin"
            return f"(-sin) * {k}" if k else "-sin"
        if i != j:
            return fixed_lit(0)
        return k if k else fixed_lit(ONE_RAW)

    head = "let (sin, cos) = angle.sin_cos();\n" if angle else ""
    return head + t.by_col(el)


def minor_match(t, src, msg):
    """`from_mat{n + 1}_minor`: the 2D `match (i, j)` of glam-rs as nested matches (no if-chain,
    no arithmetic on the indices)."""
    n = t.n
    up = t.dim(n + 1)
    arms = []
    for i in range(n + 1):
        cols = [k for k in range(n + 1) if k != i]
        inner = []
        for j in range(n + 1):
            rows = [k for k in range(n + 1) if k != j]
            value = t.mat(lambda ci: t.vec(lambda rj:
                                           f"{src}.{up.cols[cols[ci]]}.{up.c[rows[rj]]}"))
            inner.append(f"{j} => {value},")
        inner.append(f"_ => core::panic_with_felt252({msg}),")
        arms.append(f"{i} => match j {{\n" + indent("\n".join(inner), 4) + "\n},")
    arms.append(f"_ => core::panic_with_felt252({msg}),")
    return "match i {\n" + indent("\n".join(arms), 4) + "\n}"


FUSED_BODIES = {
    "mul_vec": body_mul_vec, "mul_mat": body_mul_mat, "div_scalar": body_div_scalar,
    "determinant": body_determinant, "inverse_checked": body_inverse_checked,
}


def fused_ops(t):
    """The formulations that exist as a (library, alternative) pair."""
    return ["mul_vec", "mul_mat", "div_scalar", "determinant", "inverse_checked"]


def is_fused(t, op):
    """The measured winner for (type, op). See `gas/<m>.snap`: `<op>` vs `alt_<op>`."""
    return True


# --------------------------------------------------------------------------------------------
# The trait
# --------------------------------------------------------------------------------------------
def methods(t):
    T, n, V, N = t.name, t.n, t.V, t.n * t.n
    m = []
    add = lambda *a, **k: m.append(Method(*a, **k))
    cols = ", ".join(t.cols)
    el = lambda i, j: t.el("self", i, j)

    def fz(op):
        return FUSED_BODIES[op](t, is_fused(t, op))

    # ------------------------------------------------------------------------- constructors
    add("from_cols", f"({', '.join(f'{c}: {V}' for c in t.cols)}) -> {T}",
        f"Creates a {n}x{n} matrix from {n} column vectors.", f"{T} {{ {cols} }}")
    add("from_rows", f"({', '.join(f'row{j}: {V}' for j in range(n))}) -> {T}",
        f"Creates a {n}x{n} matrix from {n} row vectors.\n\nMatrices are stored in column major "
        "order, so the given rows are permuted into the matrix layout. Use `from_cols` instead "
        "when the data is already in column major order.",
        t.by_col(lambda i, j: f"row{j}.{t.c[i]}"))
    names = [f"m{i}{j}" for i in range(n) for j in range(n)]
    add("from_cols_array", f"(m: {t.arr}) -> {T}",
        f"Creates a {n}x{n} matrix from a `{t.arr}` array stored in column major order.\n\nIf "
        "the data is in row major order use `from_rows_array` instead.",
        f"let [{', '.join(names)}] = m;\n" + t.by_col(lambda i, j: f"m{i}{j}"))
    add("to_cols_array", f"(self: {T}) -> {t.arr}",
        f"Creates a `{t.arr}` array storing data in column major order.\n\nIf you require the "
        "data in row major order use `to_rows_array` instead.",
        "[" + ", ".join(el(i, j) for i in range(n) for j in range(n)) + "]")
    add("from_rows_array", f"(m: {t.arr}) -> {T}",
        f"Creates a {n}x{n} matrix from a `{t.arr}` array stored in row major order.\n\nMatrices "
        "are stored in column major order, so the array is permuted into the matrix layout.",
        f"let [{', '.join(names)}] = m;\n" + t.by_col(lambda i, j: f"m{j}{i}"))
    add("to_rows_array", f"(self: {T}) -> {t.arr}",
        f"Creates a `{t.arr}` array storing data in row major order.",
        "[" + ", ".join(el(i, j) for j in range(n) for i in range(n)) + "]")
    add("from_cols_array_2d", f"(m: {t.arr2d}) -> {T}",
        f"Creates a {n}x{n} matrix from a `{t.arr2d}` 2D array stored in column major "
        "order.\n\nIf the data is in row major order `transpose` the returned matrix.",
        f"let [{', '.join(t.cols)}] = m;\n"
        + t.mat(lambda i: f"{V}Trait::from_array({t.cols[i]})"))
    add("to_cols_array_2d", f"(self: {T}) -> {t.arr2d}",
        f"Creates a `{t.arr2d}` 2D array storing data in column major order.\n\nIf you require "
        "row major order `transpose` the matrix first.",
        "[" + ", ".join("[" + ", ".join(el(i, j) for j in range(n)) + "]"
                        for i in range(n)) + "]")
    add("from_diagonal", f"(diagonal: {V}) -> {T}",
        f"Creates a {n}x{n} matrix with its diagonal set to `diagonal` and all other entries set "
        "to 0.", t.by_col(lambda i, j: f"diagonal.{t.c[i]}" if i == j else fixed_lit(0)))
    add("diagonal", f"(self: {T}) -> {V}", "Returns the diagonal of `self`.",
        t.vec(lambda j: el(j, j)))

    # ---------------------------------------------------------------------------- accessors
    arms = "\n".join(f"{i} => self.{c}," for i, c in enumerate(t.cols))
    add("col", f"(self: {T}, index: usize) -> {V}",
        "Returns the matrix column for the given `index`.",
        f"match index {{\n{arms}\n_ => core::panic_with_felt252({index_msg(t)}),\n}}",
        [f"`{index_msg(t)}` if `index` is greater than {n - 1}."],
        ["`col_mut` is not ported: there is no `&mut` in Cairo."])
    arms = "\n".join(f"{j} => " + t.vec(lambda i: el(i, j)) + "," for j in range(n))
    add("row", f"(self: {T}, index: usize) -> {V}",
        "Returns the matrix row for the given `index`.",
        f"match index {{\n{arms}\n_ => core::panic_with_felt252({index_msg(t)}),\n}}",
        [f"`{index_msg(t)}` if `index` is greater than {n - 1}."],
        ["`set_row` is not ported: there is no `&mut` in Cairo."])

    # ------------------------------------------------------------------- transpose, products
    add("transpose", f"(self: {T}) -> {T}", "Returns the transpose of `self`.",
        t.by_col(lambda i, j: el(j, i)), None, ["Exact: a permutation of the elements."])
    add("determinant", f"(self: {T}) -> Fixed", "Returns the determinant of `self`.",
        fz("determinant"), [OVF], DET_DEV[n])
    add("mul_vec{n}".format(n=n), f"(self: {T}, rhs: {V}) -> {V}",
        f"Transforms a {n}D vector.", fz("mul_vec"), [OVF], [DOT_DEV.format(n=n)],
        mirrors=f"glam::{T}::mul_vec{n}")
    add(f"mul_transpose_vec{n}", f"(self: {T}, rhs: {V}) -> {V}",
        f"Transforms a {n}D vector by the transpose of `self`.",
        t.vec(lambda i: dot_call([(el(i, j), f"rhs.{t.c[j]}") for j in range(n)])),
        [OVF], [DOT_DEV.format(n=n)])
    add(f"mul_mat{n}", f"(self: {T}, rhs: {T}) -> {T}",
        f"Multiplies two {n}x{n} matrices.", fz("mul_mat"), [OVF],
        [DOT_DEV.format(n=n) + f" The {n * n} elements are {n * n} kernels, one rescale each.",
         f"glam-rs spells this `self * rhs`; the operator is also implemented "
         f"(`impl Mul<{T}> for {T}`)."])
    add(f"add_mat{n}", f"(self: {T}, rhs: {T}) -> {T}",
        f"Adds two {n}x{n} matrices.", t.by_col(lambda i, j: f"{el(i, j)} + rhs.{t.cols[i]}."
                                                f"{t.c[j]}"), [ADD_P], ["Exact."])
    add(f"sub_mat{n}", f"(self: {T}, rhs: {T}) -> {T}",
        f"Subtracts two {n}x{n} matrices.",
        t.by_col(lambda i, j: f"{el(i, j)} - rhs.{t.cols[i]}.{t.c[j]}"), [SUB_P], ["Exact."])
    add("mul_scalar", f"(self: {T}, rhs: Fixed) -> {T}",
        f"Multiplies a {n}x{n} matrix by a scalar.",
        t.by_col(lambda i, j: f"{el(i, j)} * rhs"), [OVF],
        ["glam-rs spells this with an operator (`impl Mul<f32> for "
         f"{T}`); the core operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).",
         FLOOR_DEV], mirrors=f"glam::{T}::mul_scalar")
    add("div_scalar", f"(self: {T}, rhs: Fixed) -> {T}",
        f"Divides a {n}x{n} matrix by a scalar.", fz("div_scalar"), [DIV0, OVF],
        ["glam-rs spells this with an operator (`impl Div<f32> for "
         f"{T}`); the core operator traits of Cairo are homogeneous (docs/DESIGN.md section 3).",
         f"One division shared by the {N} elements (`Recip`) and one fused multiplication each, "
         "rounded to nearest: cheaper than, and up to 1 ULP away from, the element-wise "
         "truncated `Fixed / Fixed` kept in `benches::alt`."])
    add("mul_diagonal_scale", f"(self: {T}, scale: {V}) -> {T}",
        "Multiplies `self` by a scaling vector `scale`. This is faster than creating a whole "
        "diagonal scaling matrix and then multiplying that. This operation is commutative.",
        t.by_col(lambda i, j: f"{el(i, j)} * scale.{t.c[i]}"), [OVF], [FLOOR_DEV])

    # ------------------------------------------------------------------------------ inverse
    inv_dev = [f"One division shared by the {N} elements of the adjugate (`Recip`, rounded to "
               "nearest) instead of one per element: the exact `x / det` whenever it is "
               "representable.", ADJ_DEV[n]]
    add("inverse", f"(self: {T}) -> {T}",
        "Returns the inverse of `self`.\n\nIf the matrix is not invertible this function panics.",
        f"inverse_checked(self).expect({singular_msg(t)})",
        [f"`{singular_msg(t)}` if the determinant of `self` is zero.", OVF],
        ["glam-rs returns an invalid matrix (`glam_assert!` only) when the determinant is zero; "
         "there is no NaN here, so a singular matrix panics (docs/DESIGN.md section 3)."]
        + inv_dev, inline=False)
    add("try_inverse", f"(self: {T}) -> Option<{T}>",
        "Returns the inverse of `self` or `None` if the matrix is not invertible.",
        "inverse_checked(self)", [OVF], inv_dev, inline=False)
    add("inverse_or_zero", f"(self: {T}) -> {T}",
        f"Returns the inverse of `self` or `{T}::ZERO` if the matrix is not invertible.",
        "match inverse_checked(self) {\n    Some(m) => m,\n    None => Self::ZERO,\n}",
        [OVF], inv_dev, inline=False, attrs=["allow(manual_unwrap_or)"])

    # ---------------------------------------------------------------- element-wise, compare
    add("abs", f"(self: {T}) -> {T}", "Takes the absolute value of each element in `self`.",
        t.by_col(lambda i, j: f"{el(i, j)}.abs()"),
        ["`'Fixed: overflow'` if an element is `Fixed::MIN`."],
        ["Overflow panics where f32 returns the finite value `2^31`: docs/DESIGN.md section 3, "
         "\"overflow\"."])
    add("recip", f"(self: {T}) -> {T}",
        "Returns a matrix containing the reciprocal `1 / n` of each element of `self`.",
        t.by_col(lambda i, j: f"{el(i, j)}.recip()"),
        ["`'Fixed: division by zero'` if an element is zero.",
         "`'Fixed: overflow'` if an element is `1` or `2` raw (the reciprocal does not fit)."],
        ["There is no NaN nor infinity: the operation panics instead of producing one."])
    add("abs_diff_eq", f"(self: {T}, rhs: {T}, max_abs_diff: Fixed) -> bool",
        "Returns true if the absolute difference of all elements between `self` and `rhs` is "
        "less than or equal to `max_abs_diff`.\n\nThis can be used to compare if two matrices "
        "contain similar elements.",
        " && ".join(f"{V}Trait::abs_diff_eq(self.{c}, rhs.{c}, max_abs_diff)" for c in t.cols),
        None, ["The differences are computed exactly on 65 bits: unlike `(self - rhs).abs()` it "
               "never overflows."])
    return m + per_dimension(t)


DET_DEV = {
    2: ["The `mul_sub` fused kernel: one floor rescale of the exact `m00 * m11 - m01 * m10`, so "
        "an intermediate product outside the scalar range does not panic."],
    3: ["The `det3` fused kernel: the six triple products are summed exactly at the Q96.96 scale "
        "and rescaled once (floored), at most 1 ULP below the exact determinant."],
    4: ["Laplace expansion on the six 2x2 minors of the last two columns (glam-rs `a2323` .. "
        "`a0123`): each minor is one fused `mul_sub` (floored, at most 1 ULP below the exact "
        "value), the four 3x3 cofactors stay exact at the Q64.64 scale and their products with "
        "the first column are summed at the Q96.96 scale and rescaled once. The error is "
        "therefore at most `sum |m0i * m1j| + 1` ULP.",
        "Quadruple products do not fit a felt252 (docs/DESIGN.md section 2.1), so the 2x2 minors "
        "cannot stay wide: those six rescales are what makes a 4x4 determinant expressible."],
}
ADJ_DEV = {
    2: "The adjugate is exact (a permutation with two negations): only the division rounds.",
    3: "The adjugate is three fused cross products (one floor rescale per element) and the "
       "determinant is the exact `det3` kernel, so `inverse` is singular exactly when "
       "`determinant` is zero.",
    4: "The adjugate is 18 fused 2x2 minors (one floor rescale each) and 16 exact Q64.64 "
       "cofactor sums (one rescale each); the determinant is the expansion of `determinant` on "
       "the same minors, so `inverse` is singular exactly when `determinant` is zero.",
}


def per_dimension(t):
    """The methods that exist on one type only: conversions, rotations, affine transforms."""
    T, n, V = t.name, t.n, t.V
    out = []
    add = lambda *a, **k: out.append(Method(*a, **k))
    el = lambda i, j: t.el("self", i, j)

    def angle_matrix(body):
        return "let (sin, cos) = angle.sin_cos();\n" + body

    if n == 2:
        add("from_angle", "(angle: Fixed) -> Mat2",
            "Creates a 2x2 matrix containing a rotation of `angle` (in radians).",
            affine2(Ty(2), angle=True), None, [TRIG_DEV])
        add("from_scale_angle", "(scale: Vec2, angle: Fixed) -> Mat2",
            "Creates a 2x2 matrix containing the combining non-uniform `scale` and rotation of "
            "`angle` (in radians).", affine2(Ty(2), scale="scale", angle=True), [OVF],
            [TRIG_DEV, FLOOR_DEV])
        add("from_mat3", "(m: Mat3) -> Mat2",
            "Creates a 2x2 matrix from a 3x3 matrix, discarding the 2nd row and column.",
            t.mat(lambda i: f"Vec3Trait::truncate(m.{t.cols[i]})"), None, ["Exact."])
        add("from_mat3_minor", "(m: Mat3, i: usize, j: usize) -> Mat2",
            "Creates a 2x2 matrix from the minor of the given 3x3 matrix, discarding the `i`th "
            "column and `j`th row.", minor_match(t, "m", index_msg(t)),
            [f"`{index_msg(t)}` if `i` or `j` is greater than 2."],
            ["Exact. glam-rs panics with `'index out of bounds'`; the message is the one of this "
             "module."])
    if n == 3:
        v2 = Ty(2)
        add("from_mat2", "(m: Mat2) -> Mat3",
            "Creates an affine transformation matrix from the given 2x2 matrix.\n\nThe resulting "
            "matrix can be used to transform 2D points and vectors. See `transform_point2` and "
            "`transform_vector2`.",
            t.by_col(lambda i, j: fixed_lit(ONE_RAW if (i, j) == (2, 2) else 0)
                     if i == 2 or j == 2 else f"m.{v2.cols[i]}.{v2.c[j]}"), None, ["Exact."])
        add("from_mat4", "(m: Mat4) -> Mat3",
            "Creates a 3x3 matrix from a 4x4 matrix, discarding the 4th row and column.",
            t.mat(lambda i: f"Vec4Trait::truncate(m.{t.cols[i]})"), None, ["Exact."])
        add("from_mat4_minor", "(m: Mat4, i: usize, j: usize) -> Mat3",
            "Creates a 3x3 matrix from the minor of the given 4x4 matrix, discarding the `i`th "
            "column and `j`th row.", minor_match(t, "m", index_msg(t)),
            [f"`{index_msg(t)}` if `i` or `j` is greater than 3."],
            ["Exact. glam-rs panics with `'index out of bounds'`; the message is the one of this "
             "module."])
        add("from_quat", "(rotation: Quat) -> Mat3",
            "Creates a 3D rotation matrix from the given quaternion.", quat_axes(t), [OVF, ADD_P],
            QUAT_DEV)
        add("from_axis_angle", "(axis: Vec3, angle: Fixed) -> Mat3",
            "Creates a 3D rotation matrix from a normalized rotation `axis` and `angle` (in "
            "radians).", rotation_axis(t), [OVF],
            [GLAM_ASSERT + " `axis` must be normalized.", TRIG_DEV,
             "Every element is one exact triple product plus one exact term, rescaled once "
             "(floored)."])
        for axis in "xyz":
            add(f"from_rotation_{axis}", "(angle: Fixed) -> Mat3",
                f"Creates a 3D rotation matrix from `angle` (in radians) around the {axis} axis.",
                rotation_axis_named(t, axis), None, [TRIG_DEV])
        add("from_angle", "(angle: Fixed) -> Mat3",
            "Creates an affine transformation matrix from the given 2D rotation `angle` (in "
            "radians).\n\nThe resulting matrix can be used to transform 2D points and vectors. "
            "See `transform_point2` and `transform_vector2`.",
            affine2(t, angle=True), None, [TRIG_DEV])
        add("from_translation", "(translation: Vec2) -> Mat3",
            "Creates an affine transformation matrix from the given 2D `translation`.\n\nThe "
            "resulting matrix can be used to transform 2D points and vectors. See "
            "`transform_point2` and `transform_vector2`.",
            affine2(t, translation="translation"), None, ["Exact."])
        add("from_scale", "(scale: Vec2) -> Mat3",
            "Creates an affine transformation matrix from the given non-uniform 2D "
            "`scale`.\n\nThe resulting matrix can be used to transform 2D points and vectors. "
            "See `transform_point2` and `transform_vector2`.",
            affine2(t, scale="scale"), None,
            [GLAM_ASSERT + " glam-rs asserts that `scale` is not entirely zero.", "Exact."])
        add("from_scale_angle_translation", "(scale: Vec2, angle: Fixed, translation: Vec2) "
            "-> Mat3",
            "Creates an affine transformation matrix from the given 2D `scale`, rotation `angle` "
            "(in radians) and `translation`.\n\nThe resulting matrix can be used to transform 2D "
            "points and vectors. See `transform_point2` and `transform_vector2`.",
            affine2(t, scale="scale", angle=True, translation="translation"), [OVF],
            [TRIG_DEV, FLOOR_DEV])
        add("transform_point2", "(self: Mat3, rhs: Vec2) -> Vec2",
            "Transforms the given 2D vector as a point.\n\nThis is the equivalent of multiplying "
            "`rhs` as a 3D vector where `z` is `1`.\n\nThis method assumes that `self` contains a "
            "valid affine transform.",
            v2.vec(lambda j: dot_call([(el(i, j), f"rhs.{v2.c[i]}") for i in range(2)],
                                      add=el(2, j))), [OVF],
            [GLAM_ASSERT + " The 3rd row of `self` must be `(0, 0, 1)`.",
             "One `dot2_add` fused kernel per element: the translation is added exactly inside "
             "the single rescale, so the result is at most 1 ULP below the exact value."])
        add("transform_vector2", "(self: Mat3, rhs: Vec2) -> Vec2",
            "Rotates the given 2D vector.\n\nThis is the equivalent of multiplying `rhs` as a 3D "
            "vector where `z` is `0`.\n\nThis method assumes that `self` contains a valid affine "
            "transform.",
            v2.vec(lambda j: dot_call([(el(i, j), f"rhs.{v2.c[i]}") for i in range(2)])), [OVF],
            [GLAM_ASSERT + " The 3rd row of `self` must be `(0, 0, 1)`.", DOT_DEV.format(n=2)])
    if n == 4:
        v3 = Ty(3)
        add("mul_affine3", "(self: Mat4, rhs: Affine3) -> Mat4",
            "Multiplies this matrix by a 3D affine transform.",
            "Self::mul_mat4(self, Into::<Affine3, Mat4>::into(rhs))", [OVF],
            ["Cairo's core `Mul` is homogeneous, so the heterogeneous operator is named "
             "`mul_affine3`.",
             "The affine transform is embedded with the exact 4th row `(0, 0, 0, 1)`, then "
             "the fused `Mat4` product is used."],
            mirrors="impl Mul<Affine3> for glam::Mat4")
        add("from_mat3", "(m: Mat3) -> Mat4",
            "Creates an affine transformation matrix from the given 3x3 linear transformation "
            "matrix.\n\nThe resulting matrix can be used to transform 3D points and vectors. See "
            "`transform_point3` and `transform_vector3`.",
            t.by_col(lambda i, j: fixed_lit(ONE_RAW if (i, j) == (3, 3) else 0)
                     if i == 3 or j == 3 else f"m.{v3.cols[i]}.{v3.c[j]}"), None, ["Exact."])
        add("from_mat3_translation", "(mat3: Mat3, translation: Vec3) -> Mat4",
            "Creates an affine transformation matrix from the given 3x3 linear transformation "
            "matrix and `translation` vector.\n\nThe resulting matrix can be used to transform "
            "3D points and vectors. See `transform_point3` and `transform_vector3`.",
            t.by_col(lambda i, j: (fixed_lit(ONE_RAW) if j == 3 else f"translation.{v3.c[j]}")
                     if i == 3 else (fixed_lit(0) if j == 3
                                     else f"mat3.{v3.cols[i]}.{v3.c[j]}")), None, ["Exact."])
        add("from_translation", "(translation: Vec3) -> Mat4",
            "Creates an affine transformation matrix from the given 3D `translation`.\n\nThe "
            "resulting matrix can be used to transform 3D points and vectors. See "
            "`transform_point3` and `transform_vector3`.",
            t.by_col(lambda i, j: (fixed_lit(ONE_RAW) if j == 3 else f"translation.{v3.c[j]}")
                     if i == 3 else fixed_lit(ONE_RAW if i == j else 0)), None, ["Exact."])
        add("from_scale", "(scale: Vec3) -> Mat4",
            "Creates an affine transformation matrix containing the given 3D non-uniform "
            "`scale`.\n\nThe resulting matrix can be used to transform 3D points and vectors. "
            "See `transform_point3` and `transform_vector3`.",
            t.by_col(lambda i, j: fixed_lit(0) if i != j
                     else (fixed_lit(ONE_RAW) if i == 3 else f"scale.{v3.c[i]}")), None,
            [GLAM_ASSERT + " glam-rs asserts that `scale` is not entirely zero.", "Exact."])
        add("from_quat", "(rotation: Quat) -> Mat4",
            "Creates an affine transformation matrix from the given `rotation` "
            "quaternion.\n\nThe resulting matrix can be used to transform 3D points and "
            "vectors. See `transform_point3` and `transform_vector3`.", quat_axes(t),
            [OVF, ADD_P], QUAT_DEV)
        add("from_rotation_translation", "(rotation: Quat, translation: Vec3) -> Mat4",
            "Creates an affine transformation matrix from the given `rotation` quaternion and "
            "3D `translation`.\n\nThe resulting matrix can be used to transform 3D points and "
            "vectors. See `transform_point3` and `transform_vector3`.",
            quat_axes(t, translation="translation"), [OVF, ADD_P], QUAT_DEV)
        add("from_scale_rotation_translation",
            "(scale: Vec3, rotation: Quat, translation: Vec3) -> Mat4",
            "Creates an affine transformation matrix from the given 3D `scale`, `rotation` and "
            "`translation`.\n\nThe resulting matrix can be used to transform 3D points and "
            "vectors. See `transform_point3` and `transform_vector3`.",
            quat_axes(t, scale="scale", translation="translation"), [OVF, ADD_P],
            QUAT_DEV + ["The scale of column `i` is applied inside the single rescale of each "
                        "element (`W2 * Fixed -> T2`), not after it: the elements are still one "
                        "floor rescale away from the exact product, where glam-rs rounds the "
                        "rotation matrix first and the scaled one second. The nine "
                        "multiplications are free (21 360 gas, the cost of `from_quat`): a "
                        "`WideMul` is one step and no range check."])
        add("to_scale_rotation_translation", "(self: Mat4) -> (Vec3, Quat, Vec3)",
            "Extracts `scale`, `rotation` and `translation` from `self`.\n\nThe input matrix is "
            "expected to be a 3D affine transformation matrix otherwise the output will be "
            "invalid.",
            "let r = Mat3Trait::from_mat4(self);\n"
            "// The length of each column, the sign of the determinant carried by the first.\n"
            "let len_x = Vec3Trait::length(r.x_axis);\n"
            "let scale = Vec3 {\n"
            "    x: if Mat3Trait::determinant(r).is_negative() {\n        -len_x\n"
            "    } else {\n        len_x\n    },\n"
            "    y: Vec3Trait::length(r.y_axis),\n"
            "    z: Vec3Trait::length(r.z_axis),\n"
            "};\n"
            "// One shared reciprocal per column: three divisions instead of nine.\n"
            "let rx = RecipTrait::new(scale.x);\n"
            "let ry = RecipTrait::new(scale.y);\n"
            "let rz = RecipTrait::new(scale.z);\n"
            "let rotation = QuatTrait::from_rotation_axes(\n"
            "    Vec3 { x: rx.mul(r.x_axis.x), y: rx.mul(r.x_axis.y), z: rx.mul(r.x_axis.z) },\n"
            "    Vec3 { x: ry.mul(r.y_axis.x), y: ry.mul(r.y_axis.y), z: ry.mul(r.y_axis.z) },\n"
            "    Vec3 { x: rz.mul(r.z_axis.x), y: rz.mul(r.z_axis.y), z: rz.mul(r.z_axis.z) },\n"
            ");\n"
            "(scale, rotation, Vec4Trait::truncate(self.w_axis))",
            ["`'Fixed: division by zero'` if a column of the linear part is zero.",
             "`'Fixed: overflow'` if a column length or an element of the determinant does not "
             "fit the scalar range.", NEG_P],
            [GLAM_ASSERT + " The 4th row of `self` must be `(0, 0, 0, 1)` and the determinant "
             "must not be zero; the latter panics here instead (`'Fixed: division by zero'`).",
             "The sign of the determinant is applied to `scale.x` by negating the length "
             "(exact) instead of multiplying it by `signum(det)`; `signum(0)` is `+1` as "
             "everywhere else (docs/DESIGN.md section 3), but a zero determinant means a zero "
             "column, which panics.",
             "Each column is divided by its own shared `Recip` (rounded to nearest, one "
             "division for three components) instead of the `scale.recip()` then "
             "`column * inv_scale` of glam-rs, which rounds twice. Each length is the floor of "
             "the exact one, so a normalized column is within `1 / scale` ULP per component.",
             "The rotation is `Quat::from_rotation_axes` of the normalized columns: its own "
             "error (a square root and a shared division) adds to the above. Measured over "
             "20 000 random `(scale, rotation, translation)` triples of the Python mirror, the "
             "round trip `to_scale_rotation_translation(from_scale_rotation_translation(..))` "
             "recovers the translation exactly, the rotation within 13 raw ULP per component "
             "and the scale within `5 |scale| + 2` ULP, the linear term being the drift of the "
             "squared length of the quantized quaternion."], inline=False)
        add("from_axis_angle", "(axis: Vec3, angle: Fixed) -> Mat4",
            "Creates an affine transformation matrix containing a 3D rotation around a "
            "normalized rotation `axis` of `angle` (in radians).", rotation_axis(t), [OVF],
            [GLAM_ASSERT + " `axis` must be normalized.", TRIG_DEV,
             "Every element is one exact triple product plus one exact term, rescaled once "
             "(floored)."])
        for axis in "xyz":
            add(f"from_rotation_{axis}", "(angle: Fixed) -> Mat4",
                "Creates an affine transformation matrix containing a 3D rotation around the "
                f"{axis} axis of `angle` (in radians).", rotation_axis_named(t, axis), None,
                [TRIG_DEV])
        add("transform_point3", "(self: Mat4, rhs: Vec3) -> Vec3",
            "Transforms the given 3D vector as a point.\n\nThis is the equivalent of multiplying "
            "the 3D vector as a 4D vector where `w` is `1`.\n\nThis method assumes that `self` "
            "contains a valid affine transform. It does not perform a perspective divide: use "
            "`project_point3` for a projective transform.",
            v3.vec(lambda j: dot_call([(el(i, j), f"rhs.{v3.c[i]}") for i in range(3)],
                                      add=el(3, j))), [OVF],
            [GLAM_ASSERT + " The 4th row of `self` must be `(0, 0, 0, 1)`.",
             "One `dot3_add` fused kernel per element: the translation is added exactly inside "
             "the single rescale, so the result is at most 1 ULP below the exact value."])
        add("transform_vector3", "(self: Mat4, rhs: Vec3) -> Vec3",
            "Transforms the given 3D vector as a direction.\n\nThis is the equivalent of "
            "multiplying the 3D vector as a 4D vector where `w` is `0`.\n\nThis method assumes "
            "that `self` contains a valid affine transform.",
            v3.vec(lambda j: dot_call([(el(i, j), f"rhs.{v3.c[i]}") for i in range(3)])), [OVF],
            [GLAM_ASSERT + " The 4th row of `self` must be `(0, 0, 0, 1)`.",
             DOT_DEV.format(n=3)])
        add("project_point3", "(self: Mat4, rhs: Vec3) -> Vec3",
            "Transforms the given 3D vector as a point, applying perspective correction.\n\nThis "
            "is the equivalent of multiplying the 3D vector as a 4D vector where `w` is `1`. The "
            "perspective divide is performed, meaning the resulting 3D vector is divided by "
            "`w`.\n\nThis method assumes that `self` contains a projective transform.",
            "let w = " + dot_call([(el(i, 3), f"rhs.{v3.c[i]}") for i in range(3)],
                                  add=el(3, 3)) + ";\n"
            "let r = RecipTrait::new(w);\n"
            + v3.vec(lambda j: "r.mul("
                     + dot_call([(el(i, j), f"rhs.{v3.c[i]}") for i in range(3)], add=el(3, j))
                     + ")"),
            ["`'Fixed: division by zero'` if the projected `w` is zero.", OVF],
            ["One division shared by the three components (`Recip`, rounded to nearest) instead "
             "of the three of `res / res.w`.",
             "Each numerator is one `dot3_add` fused kernel (one floor rescale), so the result "
             "is within `1 / |w|` ULP of the exact projection plus the rounding of the shared "
             "division."], inline=False)
        look = ("let s = Vec3Trait::normalize(Vec3Trait::cross(dir, up));\n"
                "let u = Vec3Trait::cross(s, dir);\n"
                + t.mat(lambda i: t.vec(lambda j: (
                    {0: "s", 1: "u"}.get(j, "") + f".{v3.c[i]}" if j < 2
                    else (f"-dir.{v3.c[i]}" if j == 2 else "F_ZERO")) if i < 3 else
                    {0: "-Vec3Trait::dot(eye, s)", 1: "-Vec3Trait::dot(eye, u)",
                     2: "Vec3Trait::dot(eye, dir)", 3: "F_ONE"}[j])))
        look_panics = ["`'Vec3: normalize zero'` if `dir` and `up` are parallel.",
                       OVF, NEG_P]
        look_dev = [GLAM_ASSERT + " `dir` and `up` must be normalized.",
                    "Deprecated in glam-rs 0.33.1 in favour of `glam::camera`, which is not "
                    "ported yet (task C1 of `docs/PLAN.md`); the name and the layout are the "
                    "ones of `Mat4::look_to_rh`.",
                    "`s` is normalized (one square root, one shared division, rounded to "
                    "nearest) and every other element is exact or one floored `dot3`."]
        add("look_to_rh", "(eye: Vec3, dir: Vec3, up: Vec3) -> Mat4",
            "Creates a right-handed view matrix using a camera position, a facing direction and "
            "an up direction.\n\nFor a view coordinate system with `+X=right`, `+Y=up` and "
            "`+Z=back`.", look, look_panics, look_dev, inline=False)
        add("look_to_lh", "(eye: Vec3, dir: Vec3, up: Vec3) -> Mat4",
            "Creates a left-handed view matrix using a camera position, a facing direction and "
            "an up direction.\n\nFor a view coordinate system with `+X=right`, `+Y=up` and "
            "`+Z=forward`.", "Self::look_to_rh(eye, -dir, up)", look_panics, look_dev,
            inline=False)
        add("look_at_rh", "(eye: Vec3, center: Vec3, up: Vec3) -> Mat4",
            "Creates a right-handed view matrix using a camera position, a focal point and an up "
            "direction.\n\nFor a view coordinate system with `+X=right`, `+Y=up` and `+Z=back`.",
            "Self::look_to_rh(eye, Vec3Trait::normalize(center - eye), up)",
            ["`'Vec3: normalize zero'` if `center` is `eye`, or if the direction and `up` are "
             "parallel.", OVF, NEG_P, SUB_P], look_dev, inline=False)
        add("look_at_lh", "(eye: Vec3, center: Vec3, up: Vec3) -> Mat4",
            "Creates a left-handed view matrix using a camera position, a focal point and an up "
            "direction.\n\nFor a view coordinate system with `+X=right`, `+Y=up` and "
            "`+Z=forward`.",
            "Self::look_to_lh(eye, Vec3Trait::normalize(center - eye), up)",
            ["`'Vec3: normalize zero'` if `center` is `eye`, or if the direction and `up` are "
             "parallel.", OVF, NEG_P, SUB_P], look_dev, inline=False)
    return out


# --------------------------------------------------------------------------------------------
# Operator and conversion impls
# --------------------------------------------------------------------------------------------
def operators(t):
    T, n, N = t.name, t.n, t.n * t.n
    out = []

    def impl(docline, header, fn_sig, body, extra=""):
        out.append(f"/// {docline}\npub impl {header} {{\n{extra}    #[inline(always)]\n"
                   f"    fn {fn_sig} {{\n{indent(body, 8)}\n    }}\n}}\n")

    impl(f"`Default` is `{T}::IDENTITY`, as in glam-rs (not the all-zero derived value)."
         f"\n///\n/// Mirrors `impl Default for glam::{T}`.",
         f"{T}Default of Default<{T}>", f"default() -> {T}", f"{T}Trait::IDENTITY")
    impl(f"Element-wise `+`. Exact. Panics with the `i64_add` overflow messages.\n///\n"
         f"/// Mirrors `impl Add for glam::{T}`.",
         f"{T}Add of Add<{T}>", f"add(lhs: {T}, rhs: {T}) -> {T}",
         t.mat(lambda i: f"lhs.{t.cols[i]} + rhs.{t.cols[i]}"))
    impl(f"Element-wise `-`. Exact. Panics with the `i64_sub` overflow messages.\n///\n"
         f"/// Mirrors `impl Sub for glam::{T}`.",
         f"{T}Sub of Sub<{T}>", f"sub(lhs: {T}, rhs: {T}) -> {T}",
         t.mat(lambda i: f"lhs.{t.cols[i]} - rhs.{t.cols[i]}"))
    impl(f"Element-wise negation. Panics with `'i64_neg Underflow'` on `Fixed::MIN`.\n///\n"
         f"/// Mirrors `impl Neg for glam::{T}`.",
         f"{T}Neg of Neg<{T}>", f"neg(a: {T}) -> {T}",
         t.mat(lambda i: f"-a.{t.cols[i]}"))
    impl(f"The matrix product (see `{T}Trait::mul_mat{n}`).\n///\n"
         f"/// Mirrors `impl Mul for glam::{T}`.",
         f"{T}Mul of Mul<{T}>", f"mul(lhs: {T}, rhs: {T}) -> {T}",
         f"{T}Trait::mul_mat{n}(lhs, rhs)")
    for tr, fn, sym in [("Add", "add", "+"), ("Sub", "sub", "-"), ("Mul", "mul", "*")]:
        impl(f"Mirrors `impl {tr}Assign for glam::{T}`.",
             f"{T}{tr}Assign of {tr}Assign<{T}, {T}>", f"{fn}_assign(ref self: {T}, rhs: {T})",
             f"self = self {sym} rhs;")
    for tr, fn in [("Mul", "mul"), ("Div", "div")]:
        impl(f"Mirrors `impl {tr}Assign<f32> for glam::{T}` (see `{T}Trait::{fn}_scalar`).",
             f"{T}{tr}AssignScalar of {tr}Assign<{T}, Fixed>",
             f"{fn}_assign(ref self: {T}, rhs: Fixed)", f"self = {T}Trait::{fn}_scalar(self, rhs);")
    if n == 3:
        impl("Multiplies by a 2D affine transform embedded in a 3x3 matrix.\n///\n"
             "/// Mirrors `impl MulAssign<Affine2> for glam::Mat3`.",
             "Mat3MulAssignAffine2 of MulAssign<Mat3, Affine2>",
             "mul_assign(ref self: Mat3, rhs: Affine2)",
             "self = self * Into::<Affine2, Mat3>::into(rhs);")
    if n == 4:
        impl("Multiplies by a 3D affine transform through `Mat4Trait::mul_affine3`.\n///\n"
             "/// Mirrors `impl MulAssign<Affine3> for glam::Mat4`.",
             "Mat4MulAssignAffine3 of MulAssign<Mat4, Affine3>",
             "mul_assign(ref self: Mat4, rhs: Affine3)",
             "self = Mat4Trait::mul_affine3(self, rhs);")

    def into(docline, name, src, dst, body):
        impl(docline, f"{name} of Into<{src}, {dst}>", f"into(self: {src}) -> {dst}", body)

    into(f"Mirrors `impl From<[f32; {N}]> for glam::{T}` (column major).",
         f"FixedArrayInto{T}", t.arr, T, f"{T}Trait::from_cols_array(self)")
    into(f"Mirrors `impl From<glam::{T}> for [f32; {N}]` (column major).",
         f"{T}IntoFixedArray", T, t.arr, f"{T}Trait::to_cols_array(self)")
    into(f"Mirrors `impl From<[[f32; {n}]; {n}]> for glam::{T}` (column major).",
         f"FixedArray2dInto{T}", t.arr2d, T, f"{T}Trait::from_cols_array_2d(self)")
    into(f"Mirrors `impl From<glam::{T}> for [[f32; {n}]; {n}]` (column major).",
         f"{T}IntoFixedArray2d", T, t.arr2d, f"{T}Trait::to_cols_array_2d(self)")
    return "\n".join(out)


# --------------------------------------------------------------------------------------------
# Private helpers of each module
# --------------------------------------------------------------------------------------------
# Whether `inverse_checked` is inlined in its three callers: measured in `gas/<m>.snap`.
INV_INLINE = {2: "#[inline(always)]", 3: "#[inline(always)]", 4: "#[inline(never)]"}

# What is still missing from each module, in the header of the type. `Mat2` is complete.
TODO_NOTE = {
    2: "",
    3: ("/// * `from_euler` / `to_euler` are the extension trait `glam::euler::Mat3EulerTrait`.\n"),
    4: ("/// * `from_euler` / `to_euler` are the extension trait `glam::euler::Mat4EulerTrait`.\n") + ("/// * The projection matrices (`perspective_*`, `orthographic_*`, "
                          "`frustum_*`, deprecated in\n///   glam-rs 0.33.1 in favour of "
                          "`glam::camera`) are not ported yet: see\n"
                          "///   `docs/PORTING_STATUS.md`.\n"),
}

F_ZERO = "\n/// `0`.\nconst F_ZERO: Fixed = Fixed { raw: 0 };\n"
F_ONE = f"\n/// `1`.\nconst F_ONE: Fixed = Fixed {{ raw: {hex(ONE_RAW)} }};\n"

WIDE_NAMES = ["det3", "dot2", "dot2_add", "dot3", "dot3_add", "dot4", "mul_sub", "wide_from",
              "wide_mul"]


def wide_imports(code):
    names = [n for n in WIDE_NAMES if n + "(" in code]
    traits = []
    if "RecipTrait::" in code:
        traits.append("RecipTrait")
    if ".add(" in code:
        traits.append("WideAdd")
    if ".lift()" in code:
        traits.append("WideLift")
    if ".narrow()" in code:
        traits += ["WideMul", "WideNarrow"]
    if ".sub(" in code:
        traits.append("WideSub")
    return sorted(set(traits)) + sorted(names)


def module_uses(t, code):
    uses = ["use core::ops::{AddAssign, DivAssign, MulAssign, SubAssign};",
            "use fixed::fixed::{Fixed, FixedTrait};"]
    if ".sin_cos()" in code:
        uses.append("use fixed::trig::TrigTrait;")
    wide = wide_imports(code)
    if wide:
        uses.append("use fixed::wide::{" + ", ".join(wide) + "};")
    quat = [x for x in ("Quat", "QuatTrait") if re.search(rf"\b{x}\b(?!Trait)", code)]
    if quat:
        uses.append("use crate::quat::"
                    + (quat[0] if len(quat) == 1 else "{" + ", ".join(quat) + "}") + ";")
    for k in (2, 3):
        items = [x for x in (f"Affine{k}", f"Affine{k}Trait")
                 if re.search(rf"\b{x}\b(?!Trait)" if not x.endswith("Trait")
                              else rf"\b{x}\b", code)]
        if items:
            uses.append(f"use crate::affine{k}::"
                        + (items[0] if len(items) == 1 else "{" + ", ".join(items) + "}")
                        + ";")
    for k in (2, 3, 4):
        for kind in ("Mat", "Vec"):
            if kind == "Mat" and k == t.n:
                continue
            items = [x for x in (f"{kind}{k}", f"{kind}{k}Trait")
                     if re.search(rf"\b{x}\b(?!Trait)" if not x.endswith("Trait")
                                  else rf"\b{x}\b", code)]
            if kind == "Vec" and k == t.n:
                items = [x for x in items if x != t.V] + [t.V]
                items = sorted(set(items))
            if items:
                uses.append(f"use crate::{kind.lower()}{k}::"
                            + (items[0] if len(items) == 1 else "{" + ", ".join(items) + "}")
                            + ";")
    rank = {"core": 0, "fixed": 1, "crate": 2}
    return sorted(set(uses), key=lambda u: (rank[u.split("::")[0][4:]], u))


def gen_module(t):
    T, n, V, N = t.name, t.n, t.V, t.n * t.n
    ms = methods(t)
    ops = operators(t)
    inv = body_inverse_checked(t, is_fused(t, "inverse_checked"))

    decl, impl = [], []
    for name, ty, summary, value in consts(t):
        decl.append(f"    /// {summary}\n    ///\n    /// Mirrors `glam::{T}::{name}`.\n"
                    f"    const {name}: {ty};")
        impl.append(f"    const {name}: {ty} = {value};")
    impl.append("")
    for meth in ms:
        mirrors = meth.mirrors or f"glam::{T}::{meth.name}"
        decl.append(doc(meth.summary, mirrors, meth.panics, meth.dev)
                    + f"\n    fn {meth.name}{meth.sig};")
        attrs = "".join(f"    #[{a}]\n" for a in meth.attrs)
        attrs += "    #[inline(always)]\n" if meth.inline else ""
        impl.append(f"{attrs}    fn {meth.name}{meth.sig} {{\n{indent(meth.body, 8)}\n    }}\n")

    helper = (f"""
/// The shared body of `inverse`, `try_inverse` and `inverse_or_zero`: the adjugate through the
/// fused kernels of `fixed::wide`, then ONE division (`Recip`) for the {N} elements. `None` when
/// the determinant is zero, which is the definition of singular here (docs/DESIGN.md section 3).
{INV_INLINE[n]}
fn inverse_checked(m: {T}) -> Option<{T}> {{
{indent(inv, 4)}
}}
""")
    body = "\n".join(impl) + ops + helper
    helpers = "".join(h for h, name in ((F_ZERO, "F_ZERO"), (F_ONE, "F_ONE"))
                      if re.search(rf"\b{name}\b", body))
    code = body + helpers
    uses = module_uses(t, code)

    head = f"""{HEADER}//! Port of glam-rs `f32/{t.mod}.rs` @ 0.33.8 on the Q32.32 scalar: a column major {n}x{n}
//! `fixed::Fixed` matrix whose columns are `{V}`.
//!
//! The three fixed-point matrix modules are generated from one template
//! (`tools/codegen/fmat.py`), as in glam-rs. Every product goes through a fused kernel of
//! `fixed::wide` (one rescale per output scalar, docs/DESIGN.md section 2.1) and every
//! formulation is the cheapest of the candidates measured in `gas/{t.mod}.snap`; the losing
//! candidates live in `benches::alt::{t.mod}`.
//!
//! There is no NaN and no infinity: overflow, division by zero and the inversion of a singular
//! matrix panic (docs/DESIGN.md section 3).

{chr(10).join(uses)}

/// A column major {n}x{n} matrix of Q32.32 fixed-point scalars.
///
/// Mirrors `glam::{T}`.
/// #### Deviations
/// * `Debug` is the derived Cairo formatting; `Display` is not implemented.
/// * No `NAN` const and no `is_nan` / `is_finite`: those values do not exist
///   (docs/DESIGN.md section 3).
/// * Not ported: `col_mut` / `set_row` (no `&mut`), `from_cols_slice` / `from_rows_slice` /
///   `write_cols_to_slice` (no `Span` in fixed-size math), `Sum` / `Product` (no iterator trait
///   to implement), the by-reference operator overloads, the scalar-on-the-left operators
///   (`2.0 * m`) and the casts to types that do not exist in glam.cairo (`as_dmat{n}`, `Mat3A`).
{TODO_NOTE[n]}#[derive(Copy, Drop, Serde, PartialEq, Debug, Hash)]
pub struct {T} {{
{chr(10).join(f"    pub {c}: {V}," for c in t.cols)}
}}

/// Creates a {n}x{n} matrix from {n} column vectors.
///
/// Mirrors `glam::{t.mod}`.
/// #### Panics
/// * Never.
/// #### Deviations
/// * None.
#[inline(always)]
pub fn {t.mod}({', '.join(f'{c}: {V}' for c in t.cols)}) -> {T} {{
    {T} {{ {', '.join(t.cols)} }}
}}

pub trait {T}Trait {{
{chr(10).join(decl)}
}}

pub impl {T}Impl of {T}Trait {{
{chr(10).join(impl)}}}

{ops}{helper}{helpers}"""
    return head




# --------------------------------------------------------------------------------------------
# Benches
# --------------------------------------------------------------------------------------------
Bench = g.Bench


def frac(v):
    """The raw Q32.32 value of an operand given in units (an int or a `(num, den)` pair)."""
    return g.raw_of(v)


def mat_const(t, cells):
    """`cells(i, j)` in value units -> the Cairo literal of the matrix."""
    return t.by_col(lambda i, j: fixed_lit(frac(cells(i, j))))


def vec_const(k, vals):
    d = Ty(k) if k > 1 else None
    return Ty(k).vec(lambda j: fixed_lit(frac(vals[j])))


OFF_A = [(-1, 2), (1, 4), (3, 4), (-3, 8)]
OFF_B = [(1, 2), (-1, 4), (-5, 8), (7, 8)]
VALS = {
    "V": [(3, 2), (-7, 4), (11, 8), (-13, 16)],
    "VB": [(-5, 2), (1, 2), (9, 4), (5, 4)],
    "DIAG": [2, -3, 5, 7],
}
# A normalized axis (9 + 36 + 4 = 49) and a generic angle.
AXIS = [(3, 7), (6, 7), (2, 7)]
UP = [0, 1, 0]
EYE = [1, 2, 3]
CENTER = [4, -1, 2]

# Unit quaternions with exactly rational components (`1 + 4 + 4 + 16 = 25`), one per branch of
# `Quat::from_rotation_axes`: the branch is decided by `z^2 + w^2 > 1/2` then by `w^2 > z^2`
# (respectively `x^2 > y^2`), so permuting the same four numerators reaches the four of them.
ROT_Q = (1, 2, 2, 4)
BRANCH_Q = {"w": (1, 2, 2, 4), "z": (1, 2, 4, 2), "x": (4, 2, 2, 1), "y": (2, 4, 2, 1)}


def quat_const(q, den=5):
    """The Cairo literal of the unit quaternion `q / den` (floored to Q32.32)."""
    return ("Quat { "
            + ", ".join(f"{c}: {fixed_lit(v * ONE_RAW // den)}" for c, v in zip("xyzw", q))
            + " }")


def trs_const(q, translation, den=5):
    """`Mat4::from_rotation_translation(q / den, translation)` as a Cairo literal: the rotation
    matrix of the unit quaternion, floored element by element, plus the translation column."""
    x, y, z, w = (v for v in q)
    d2 = den * den
    # `num(i, j) * 2 / d2` off the diagonal, `1 - 2 num / d2` on it (exact integer numerators).
    diag = {0: y * y + z * z, 1: x * x + z * z, 2: x * x + y * y}
    off = {(0, 1): (x * y, w * z, 1), (0, 2): (x * z, w * y, -1), (1, 0): (x * y, w * z, -1),
           (1, 2): (y * z, w * x, 1), (2, 0): (x * z, w * y, 1), (2, 1): (y * z, w * x, -1)}

    def raw(i, j):
        if i == 3:
            return ONE_RAW if j == 3 else translation[j] * ONE_RAW
        if j == 3:
            return 0
        if i == j:
            return (d2 - 2 * diag[i]) * ONE_RAW // d2
        a, b, sign = off[(i, j)]
        return 2 * (a + sign * b) * ONE_RAW // d2

    return Ty(4).by_col(lambda i, j: fixed_lit(raw(i, j)))


def bench_consts(t):
    """name -> (type, const value) of every operand a bench of `t` may use."""
    n = t.name
    # diagonally dominant (invertible) operands; `SING` has rank 1
    a = mat_const(t, lambda i, j: ((5 + 2 * i, 2) if i == j else OFF_A[(i + 2 * j) % 4]))
    b = mat_const(t, lambda i, j: ((3 + i, 2) if i == j else OFF_B[(2 * i + j) % 4]))
    sing = mat_const(t, lambda i, j: (i + 1) * (j + 1))
    out = {
        "A": (n, a), "B": (n, b), "SING": (n, sing),
        "V": (t.V, vec_const(t.n, VALS["V"])), "VB": (t.V, vec_const(t.n, VALS["VB"])),
        "DIAG": (t.V, vec_const(t.n, VALS["DIAG"])),
        "K_ONE": ("Fixed", fixed_lit(frac(1))),
        "K_THREE": ("Fixed", fixed_lit(frac(3))),
        "K_HALF": ("Fixed", fixed_lit(frac((1, 2)))),
        "K_1_1024": ("Fixed", fixed_lit(frac((1, 1024)))),
        "ANGLE": ("Fixed", fixed_lit(frac((7, 10)))),
    }
    out["V2"] = ("Vec2", vec_const(2, VALS["V"]))
    out["SCALE2"] = ("Vec2", vec_const(2, [(3, 2), (5, 4)]))
    out["TRANS2"] = ("Vec2", vec_const(2, [3, -2]))
    out["M2"] = ("Mat2", mat_const(Ty(2), lambda i, j: ((5 + 2 * i, 2) if i == j
                                                        else OFF_A[(i + 2 * j) % 4])))
    out["V3"] = ("Vec3", vec_const(3, VALS["V"]))
    out["SCALE3"] = ("Vec3", vec_const(3, [(3, 2), (5, 4), 2]))
    out["TRANS3"] = ("Vec3", vec_const(3, [3, -2, 1]))
    out["M3"] = ("Mat3", mat_const(Ty(3), lambda i, j: ((5 + 2 * i, 2) if i == j
                                                        else OFF_A[(i + 2 * j) % 4])))
    out["AXIS"] = ("Vec3", vec_const(3, AXIS))
    out["UP"] = ("Vec3", vec_const(3, UP))
    out["EYE"] = ("Vec3", vec_const(3, EYE))
    out["CENTER"] = ("Vec3", vec_const(3, CENTER))
    out["M4"] = ("Mat4", mat_const(Ty(4), lambda i, j: ((5 + 2 * i, 2) if i == j
                                                        else OFF_A[(i + 2 * j) % 4])))
    out["AFFINE2"] = (
        "Affine2",
        "Affine2 { matrix2: "
        + mat_const(Ty(2), lambda i, j: ((5 + 2 * i, 2) if i == j
                                         else OFF_A[(i + 2 * j) % 4]))
        + ", translation: " + vec_const(2, [3, -2]) + " }",
    )
    out["AFFINE3"] = (
        "Affine3",
        "Affine3 { matrix3: "
        + mat_const(Ty(3), lambda i, j: ((5 + 2 * i, 2) if i == j
                                         else OFF_A[(i + 2 * j) % 4]))
        + ", translation: " + vec_const(3, [3, -2, 1]) + " }",
    )
    out["ROT"] = ("Quat", quat_const(ROT_Q))
    for branch, q in BRANCH_Q.items():
        out[f"TRS_{branch.upper()}"] = ("Mat4", trs_const(q, [3, -2, 1]))
    return out


def lib_benches(t):
    """One bench (or one per branch) for every public function that computes something."""
    T, n, V = t.name, t.n, t.V
    out = []

    def b(name, inputs, res, op, pre=""):
        out.append(Bench(name, inputs, res, op, pre))

    b("from_cols", [("a", "V"), ("c", "VB")], "A",
      f"{T}Trait::from_cols(" + ", ".join(["a", "c"] + ["a"] * (n - 2)) + ")")
    b("from_rows", [("a", "V"), ("c", "VB")], "A",
      f"{T}Trait::from_rows(" + ", ".join(["a", "c"] + ["a"] * (n - 2)) + ")")
    b("from_cols_array", [("a", "A")], "A",
      f"{T}Trait::from_cols_array({T}Trait::to_cols_array(a))")
    b("to_cols_array", [("a", "A")], f"{T}Trait::to_cols_array(A)", "a.to_cols_array()")
    b("from_rows_array", [("a", "A")], "A",
      f"{T}Trait::from_rows_array({T}Trait::to_rows_array(a))")
    b("to_rows_array", [("a", "A")], f"{T}Trait::to_cols_array(A)", "a.to_rows_array()")
    b("from_cols_array_2d", [("a", "A")], "A",
      f"{T}Trait::from_cols_array_2d({T}Trait::to_cols_array_2d(a))")
    b("to_cols_array_2d", [("a", "A")], f"{T}Trait::to_cols_array_2d(A)",
      "a.to_cols_array_2d()")
    b("from_diagonal", [("d", "DIAG")], "A", f"{T}Trait::from_diagonal(d)")
    b("diagonal", [("a", "A")], "V", "a.diagonal()")
    b("col_first", [("a", "A"), ("i", "0_usize")], "V", "a.col(i)")
    b("col_last", [("a", "A"), ("i", f"{n - 1}_usize")], "V", "a.col(i)")
    b("row_first", [("a", "A"), ("i", "0_usize")], "V", "a.row(i)")
    b("row_last", [("a", "A"), ("i", f"{n - 1}_usize")], "V", "a.row(i)")
    b("transpose", [("a", "A")], "A", "a.transpose()")
    b("determinant", [("a", "A")], "K_ONE", "a.determinant()")
    b("determinant_singular", [("a", "SING")], "K_ONE", "a.determinant()")
    b("inverse", [("a", "A")], "A", "a.inverse()")
    b("try_inverse_some", [("a", "A")], "Some(A)", "a.try_inverse()")
    b("try_inverse_none", [("a", "SING")], "Some(A)", "a.try_inverse()")
    b("inverse_or_zero_some", [("a", "A")], "A", "a.inverse_or_zero()")
    b("inverse_or_zero_none", [("a", "SING")], "A", "a.inverse_or_zero()")
    b(f"mul_vec{n}", [("a", "A"), ("v", "V")], "V", f"a.mul_vec{n}(v)")
    b(f"mul_transpose_vec{n}", [("a", "A"), ("v", "V")], "V", f"a.mul_transpose_vec{n}(v)")
    b(f"mul_mat{n}", [("a", "A"), ("c", "B")], "A", f"a.mul_mat{n}(c)")
    b(f"add_mat{n}", [("a", "A"), ("c", "B")], "A", f"a.add_mat{n}(c)")
    b(f"sub_mat{n}", [("a", "A"), ("c", "B")], "A", f"a.sub_mat{n}(c)")
    b("mul_scalar", [("a", "A"), ("k", "K_THREE")], "A", "a.mul_scalar(k)")
    b("div_scalar", [("a", "A"), ("k", "K_THREE")], "A", "a.div_scalar(k)")
    b("mul_diagonal_scale", [("a", "A"), ("d", "DIAG")], "A", "a.mul_diagonal_scale(d)")
    b("abs", [("a", "A")], "A", "a.abs()")
    b("recip", [("a", "A")], "A", "a.recip()")
    b("abs_diff_eq_true", [("a", "A"), ("c", "A"), ("e", "K_ONE")], "true",
      "a.abs_diff_eq(c, e)")
    b("abs_diff_eq_false", [("a", "A"), ("c", "B"), ("e", "K_1_1024")], "true",
      "a.abs_diff_eq(c, e)")
    for f, sym in [("add", "+"), ("sub", "-"), ("mul", "*")]:
        b(f, [("a", "A"), ("c", "B")], "A", f"a {sym} c")
        b(f"{f}_assign", [("a", "A"), ("c", "B")], "A", "a", pre=f"let a = a {sym} c;")
    b("neg", [("a", "A")], "A", "-a")
    b("mul_assign_scalar", [("a", "A"), ("k", "K_THREE")], "A", "a",
      pre=f"let a = {T}Trait::mul_scalar(a, k);")
    b("div_assign_scalar", [("a", "A"), ("k", "K_THREE")], "A", "a",
      pre=f"let a = {T}Trait::div_scalar(a, k);")
    if n == 2:
        b("from_angle", [("t", "ANGLE")], "A", "Mat2Trait::from_angle(t)")
        b("from_scale_angle", [("s", "SCALE2"), ("t", "ANGLE")], "A",
          "Mat2Trait::from_scale_angle(s, t)")
        b("from_mat3", [("m", "M3")], "A", "Mat2Trait::from_mat3(m)")
        b("from_mat3_minor_first", [("m", "M3"), ("i", "0_usize"), ("j", "0_usize")], "A",
          "Mat2Trait::from_mat3_minor(m, i, j)")
        b("from_mat3_minor_last", [("m", "M3"), ("i", "2_usize"), ("j", "2_usize")], "A",
          "Mat2Trait::from_mat3_minor(m, i, j)")
    if n == 3:
        b("mul_assign_affine2", [("a", "A"), ("c", "AFFINE2")], "A", "a",
          pre="let mut a = a;\n    a *= c;")
        b("from_mat2", [("m", "M2")], "A", "Mat3Trait::from_mat2(m)")
        b("from_mat4", [("m", "M4")], "A", "Mat3Trait::from_mat4(m)")
        b("from_mat4_minor_first", [("m", "M4"), ("i", "0_usize"), ("j", "0_usize")], "A",
          "Mat3Trait::from_mat4_minor(m, i, j)")
        b("from_mat4_minor_last", [("m", "M4"), ("i", "3_usize"), ("j", "3_usize")], "A",
          "Mat3Trait::from_mat4_minor(m, i, j)")
        b("from_quat", [("q", "ROT")], "A", "Mat3Trait::from_quat(q)")
        b("from_axis_angle", [("x", "AXIS"), ("t", "ANGLE")], "A",
          "Mat3Trait::from_axis_angle(x, t)")
        for axis in "xyz":
            b(f"from_rotation_{axis}", [("t", "ANGLE")], "A",
              f"Mat3Trait::from_rotation_{axis}(t)")
        b("from_angle", [("t", "ANGLE")], "A", "Mat3Trait::from_angle(t)")
        b("from_translation", [("p", "TRANS2")], "A", "Mat3Trait::from_translation(p)")
        b("from_scale", [("s", "SCALE2")], "A", "Mat3Trait::from_scale(s)")
        b("from_scale_angle_translation", [("s", "SCALE2"), ("t", "ANGLE"), ("p", "TRANS2")],
          "A", "Mat3Trait::from_scale_angle_translation(s, t, p)")
        b("transform_point2", [("a", "A"), ("v", "V2")], "V2", "a.transform_point2(v)")
        b("transform_vector2", [("a", "A"), ("v", "V2")], "V2", "a.transform_vector2(v)")
    if n == 4:
        b("mul_affine3", [("a", "A"), ("c", "AFFINE3")], "A", "a.mul_affine3(c)")
        b("mul_assign_affine3", [("a", "A"), ("c", "AFFINE3")], "A", "a",
          pre="let mut a = a;\n    a *= c;")
        b("from_mat3", [("m", "M3")], "A", "Mat4Trait::from_mat3(m)")
        b("from_mat3_translation", [("m", "M3"), ("p", "TRANS3")], "A",
          "Mat4Trait::from_mat3_translation(m, p)")
        b("from_translation", [("p", "TRANS3")], "A", "Mat4Trait::from_translation(p)")
        b("from_scale", [("s", "SCALE3")], "A", "Mat4Trait::from_scale(s)")
        b("from_quat", [("q", "ROT")], "A", "Mat4Trait::from_quat(q)")
        b("from_rotation_translation", [("q", "ROT"), ("p", "TRANS3")], "A",
          "Mat4Trait::from_rotation_translation(q, p)")
        b("from_scale_rotation_translation",
          [("s", "SCALE3"), ("q", "ROT"), ("p", "TRANS3")], "A",
          "Mat4Trait::from_scale_rotation_translation(s, q, p)")
        # The four branches of `Quat::from_rotation_axes` reached through the decomposition.
        for name, src in (("x", "TRS_X"), ("y", "TRS_Y"), ("z", "TRS_Z"), ("w", "TRS_W")):
            b(f"to_scale_rotation_translation_{name}", [("a", src)],
              "(SCALE3, ROT, TRANS3)", "a.to_scale_rotation_translation()")
        b("from_axis_angle", [("x", "AXIS"), ("t", "ANGLE")], "A",
          "Mat4Trait::from_axis_angle(x, t)")
        for axis in "xyz":
            b(f"from_rotation_{axis}", [("t", "ANGLE")], "A",
              f"Mat4Trait::from_rotation_{axis}(t)")
        b("transform_point3", [("a", "A"), ("v", "V3")], "V3", "a.transform_point3(v)")
        b("transform_vector3", [("a", "A"), ("v", "V3")], "V3", "a.transform_vector3(v)")
        b("project_point3", [("a", "A"), ("v", "V3")], "V3", "a.project_point3(v)")
        for hand in ("lh", "rh"):
            b(f"look_to_{hand}", [("e", "EYE"), ("d", "AXIS"), ("u", "UP")], "A",
              f"Mat4Trait::look_to_{hand}(e, d, u)")
            b(f"look_at_{hand}", [("e", "EYE"), ("c", "CENTER"), ("u", "UP")], "A",
              f"Mat4Trait::look_at_{hand}(e, c, u)")
    return out


# --------------------------------------------------------------------------------------------
class Alt:
    """A losing (or reference) formulation: a free function of `benches::alt::<m>` and the
    benches that compare it with the library function (same inputs, same names)."""

    def __init__(self, name, targets, sig, body, note, inline="always"):
        self.name, self.targets, self.sig = name, targets, sig
        self.body, self.note, self.inline = body, note, inline


def to_free(t, body):
    """The body of a method, as the body of a free function of `benches::alt`."""
    return re.sub(r"\bSelf::", f"{t.name}Trait::", re.sub(r"\bself\b", "lhs", body))


def alts(t):
    T, n, V = t.name, t.n, t.V
    out = [
        Alt("mul_vec_unfused", [f"mul_vec{n}"], f"(lhs: {T}, rhs: {V}) -> {V}",
            to_free(t, body_mul_vec(t, False)),
            "The literal glam-rs sum of scaled columns: one rescale per product instead of one "
            f"per element of the result ({n * n} instead of {n})."),
        Alt("mul_mat_transpose", [f"mul_mat{n}"], f"(lhs: {T}, rhs: {T}) -> {T}",
            to_free(t, body_mul_mat(t, False)),
            "One transposition, then one `dot` per element instead of one `mul_vec` per column: "
            "the same kernels on transposed operands."),
        Alt("div_scalar_plain", ["div_scalar"], f"(lhs: {T}, rhs: Fixed) -> {T}",
            to_free(t, body_div_scalar(t, False)),
            f"One truncated `Fixed / Fixed` per element ({n * n} divisions) instead of the "
            "shared `Recip`."),
        Alt("inverse_plain", ["inverse", "try_inverse_some", "try_inverse_none"],
            f"(m: {T}) -> Option<{T}>", body_inverse_checked(t, False),
            f"One truncated division per element of the adjugate ({n * n} divisions) instead of "
            "the shared `Recip`: this is the formulation of glam-rs (`m * (1 / det)`).",
            inline="never"),
    ]
    if n > 2:
        out.append(Alt("from_quat_unfused", ["from_quat"], f"(rotation: Quat) -> {T}",
                       quat_axes(t, fused=False),
                       "The literal glam-rs expression: the twelve products of the nine "
                       "elements rescaled one by one (18 rescales for the 3x3 part) instead of "
                       "one fused two-term kernel per element."))
    if n == 3:
        out.append(Alt("determinant_cross", ["determinant", "determinant_singular"],
                       f"(lhs: {T}) -> Fixed", to_free(t, body_determinant(t, False)),
                       "The literal glam-rs `x_axis.dot(y_axis.cross(z_axis))`: the cross "
                       "product is floored before the dot product (two rescales) instead of the "
                       "single one of `det3`."))
    if n == 4:
        out.append(Alt("determinant_det3", ["determinant", "determinant_singular"],
                       f"(lhs: {T}) -> Fixed", to_free(t, body_determinant(t, False)),
                       "Expansion along the first row with four `det3` kernels (four rescales) "
                       "instead of the six shared 2x2 minors: the 3x3 minors are recomputed "
                       "instead of being shared.", inline="never"))
    return out


def alt_benches(t, lib):
    """Every alternative runs on the inputs of the library bench(es) it competes with."""
    by_name = {x.name: x for x in lib}
    out = []
    for a in alts(t):
        for target in a.targets:
            bench = by_name[target]
            names = [k for k, _ in bench.inputs]
            out.append(Bench(f"alt_{a.name}_{target}", bench.inputs, bench.res,
                             f"alt::{a.name}({', '.join(names)})"))
    return out


def gen_alt(t):
    fns = []
    for a in alts(t):
        attr = f"#[inline({a.inline})]\n" if a.inline else ""
        note = "\n".join(g.wrap(f"Alternative to `{t.name}::{a.targets[0]}`. {a.note}", "///"))
        fns.append(f"{note}\n{attr}pub fn {a.name}{a.sig} {{\n{indent(a.body, 4)}\n}}\n")
    code = "\n".join(fns)
    helpers = "".join(h for h, name in ((F_ZERO, "F_ZERO"), (F_ONE, "F_ONE"))
                      if re.search(rf"\b{name}\b", code))
    code += helpers
    uses = ["use fixed::fixed::Fixed;"]
    wide = wide_imports(code)
    if wide:
        uses.append("use fixed::wide::{" + ", ".join(wide) + "};")
    glam = []
    for k in (2, 3, 4):
        for kind in ("Mat", "Vec"):
            items = sorted({x for x in (f"{kind}{k}", f"{kind}{k}Trait")
                            if re.search(rf"\b{x}\b(?!Trait)" if not x.endswith("Trait")
                                         else rf"\b{x}\b", code)})
            if items:
                glam.append(f"use glam::{kind.lower()}{k}::"
                            + (items[0] if len(items) == 1 else "{" + ", ".join(items) + "}")
                            + ";")
    if re.search(r"\bQuat\b(?!Trait)", code):
        glam.append("use glam::quat::Quat;")
    uses += sorted(glam)
    return (f"{HEADER}//! Alternative implementations benchmarked against `glam::{t.mod}` "
            f"(the `alt_*` rows of\n//! `gas/{t.mod}.snap`). The library ships the cheapest "
            "formulation; the others stay here so that\n//! the comparison is reproducible "
            "across compiler upgrades.\n\n" + "\n".join(uses) + "\n\n" + code)


def gen_bench(t):
    lib = lib_benches(t)
    benches = lib + alt_benches(t, lib)
    body = "\n".join(x.emit() for x in benches)
    pool = bench_consts(t)
    decls = "".join(f"const {name}: {ty} = {value};\n"
                    for name, (ty, value) in pool.items()
                    if re.search(rf"\b{name}\b", body))
    uses = [f"use benches::alt::{t.mod} as alt;"] if "alt::" in body else []
    uses.append("use benches::harness::{bb, sink};")
    uses.append("use fixed::fixed::Fixed;")
    glam = []
    for k in (2, 3, 4):
        for kind, prefix in (("Mat", "mat"), ("Vec", "vec")):
            name = f"{kind}{k}"
            if not re.search(rf"\b{name}\b", body + decls):
                continue
            items = [name] + ([f"{name}Trait"] if re.search(rf"\b{name}Trait\b", body) else [])
            glam.append(f"use glam::{prefix}{k}::"
                        + (items[0] if len(items) == 1 else "{" + ", ".join(items) + "}") + ";")
    if re.search(r"\bQuat\b(?!Trait)", body + decls):
        glam.append("use glam::quat::Quat;")
    for k in (2, 3):
        if re.search(rf"\bAffine{k}\b", body + decls):
            glam.append(f"use glam::affine{k}::Affine{k};")
    uses += sorted(glam)
    return (f"{HEADER}//! Gas benchmarks of `glam::{t.mod}` and of the alternatives kept in "
            f"`benches::alt::{t.mod}`\n//! (the `alt_*` benches).\n//!\n"
            "//! Sierra gas is charged at the most expensive sibling branch, but steps depend "
            "on the path\n//! taken: branching functions are measured on one input per branch "
            "(`_some` / `_none`,\n//! `_first` / `_last`, ...). Every input goes through `bb` "
            "(otherwise the computation is\n//! constant-folded away) and every result through "
            "`sink`.\n\n"
            + "\n".join(uses) + "\n\n" + decls + "\n" + body)


# --------------------------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------------------------
def outputs(kinds=None):
    import fmat_tests
    files = {}
    for t in TYPES:
        files[ROOT / f"packages/glam/src/{t.mod}.cairo"] = gen_module(t)
        files[ROOT / f"packages/glam/tests/test_{t.mod}.cairo"] = fmat_tests.gen_tests(t)
        files[ROOT / f"packages/benches/tests/bench_{t.mod}.cairo"] = gen_bench(t)
        files[ROOT / f"packages/benches/src/alt/{t.mod}.cairo"] = gen_alt(t)
    return files


def fmt(paths):
    """`scarb fmt` takes one path at most: format the workspace (the other files are clean)."""
    subprocess.run(["scarb", "fmt", "--workspace"], cwd=ROOT, check=True, capture_output=True)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="do not modify anything; exit 1 if the committed files are stale")
    ap.add_argument("--only", help="comma-separated kinds: src,tests,bench,alt")
    args = ap.parse_args()

    files = outputs()
    if args.only:
        kinds = {"src": "/glam/src/", "tests": "/glam/tests/", "bench": "/benches/tests/",
                 "alt": "/benches/src/alt/"}
        keep = [kinds[k] for k in args.only.split(",")]
        files = {p: c for p, c in files.items() if any(k in str(p) for k in keep)}
    before = {p: (p.read_text() if p.exists() else None) for p in files}
    for p, content in files.items():
        p.write_text(content)
    try:
        fmt(list(files))
    except subprocess.CalledProcessError as e:
        if args.check:
            for p, old in before.items():
                p.write_text(old) if old is not None else p.unlink()
        sys.exit("scarb fmt failed:\n" + e.stderr.decode())
    if not args.check:
        changed = [p for p in files if before[p] != p.read_text()]
        print(f"{len(files)} files generated, {len(changed)} changed")
        return
    stale = [p for p in files if before[p] != p.read_text()]
    for p, old in before.items():
        p.write_text(old) if old is not None else p.unlink()
    if stale:
        print("stale generated files (run tools/codegen/fmat.py):")
        for p in stale:
            print("  " + str(p.relative_to(ROOT)))
        sys.exit(1)
    print(f"{len(files)} generated files are up to date")


if __name__ == "__main__":
    main()
