[package]
name = "alt"
version = "0.1.0"
edition = "2024_07"

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.19.4"

[dev-dependencies]
cairo_test = "2.19.4"

[[target.executable]]
name = "base"
function = "alt::exe_base"

[[target.executable]]
name = "op"
function = "alt::exe_op"
