// GENERATED by tools/codegen/swizzles.py - do not edit by hand.
//! Port of glam-rs `swizzles` @ 0.33.8: the float vector swizzle traits
//! (`Vec2Swizzles`, ...), once per vector type of glam-cairo. The vector types are in
//! `glam_core`; the `glam` facade re-exports everything as `glam::swizzles::*`.

pub mod vec2;
pub mod vec3;
pub mod vec4;

pub use vec2::{Vec2Swizzles, Vec2SwizzlesImpl};
pub use vec3::{Vec3Swizzles, Vec3SwizzlesImpl};
pub use vec4::{Vec4Swizzles, Vec4SwizzlesImpl};
