// GENERATED by tools/refgen - do not edit by hand.
// Oracle: glam-rs 0.33.8 (f64) on inputs quantized to Q32.32. Sources:
// tools/refgen/specs/euler.toml and tools/refgen/src/oracles/euler.rs
// Regenerate: cargo run --manifest-path tools/refgen/Cargo.toml -- gen euler

use fixed::Fixed;
use glam::euler::{EulerRot, Mat3EulerTrait, Mat4EulerTrait, QuatEulerTrait};
use glam::mat3::Mat3;
use glam::mat4::Mat4;
use glam::quat::Quat;
use glam::vec3::Vec3;
use glam::vec4::Vec4;

fn next_i64(ref d: Span<i64>) -> i64 {
    *d.pop_front().unwrap()
}

fn next_fixed(ref d: Span<i64>) -> Fixed {
    Fixed { raw: next_i64(ref d) }
}

fn next_vec3(ref d: Span<i64>) -> Vec3 {
    let x = next_fixed(ref d);
    let y = next_fixed(ref d);
    let z = next_fixed(ref d);
    Vec3 { x, y, z }
}

fn next_vec4(ref d: Span<i64>) -> Vec4 {
    let x = next_fixed(ref d);
    let y = next_fixed(ref d);
    let z = next_fixed(ref d);
    let w = next_fixed(ref d);
    Vec4 { x, y, z, w }
}

fn next_quat(ref d: Span<i64>) -> Quat {
    let x = next_fixed(ref d);
    let y = next_fixed(ref d);
    let z = next_fixed(ref d);
    let w = next_fixed(ref d);
    Quat { x, y, z, w }
}

fn next_mat3(ref d: Span<i64>) -> Mat3 {
    let x_axis = next_vec3(ref d);
    let y_axis = next_vec3(ref d);
    let z_axis = next_vec3(ref d);
    Mat3 { x_axis, y_axis, z_axis }
}

fn next_mat4(ref d: Span<i64>) -> Mat4 {
    let x_axis = next_vec4(ref d);
    let y_axis = next_vec4(ref d);
    let z_axis = next_vec4(ref d);
    let w_axis = next_vec4(ref d);
    Mat4 { x_axis, y_axis, z_axis, w_axis }
}

fn check_raw(actual: i64, ref d: Span<i64>, tol: i128, name: @ByteArray, case: usize) {
    let expected = next_i64(ref d);
    let diff: i128 = actual.into() - expected.into();
    let diff = if diff < 0 {
        -diff
    } else {
        diff
    };
    assert!(diff <= tol, "{name} #{case}: got {actual}, expected {expected} (tol {tol})");
}

fn check_fixed(actual: Fixed, ref d: Span<i64>, tol: i128, name: @ByteArray, case: usize) {
    check_raw(actual.raw, ref d, tol, name, case);
}

fn check_vec3(actual: Vec3, ref d: Span<i64>, tol: i128, name: @ByteArray, case: usize) {
    check_fixed(actual.x, ref d, tol, name, case);
    check_fixed(actual.y, ref d, tol, name, case);
    check_fixed(actual.z, ref d, tol, name, case);
}

fn check_vec4(actual: Vec4, ref d: Span<i64>, tol: i128, name: @ByteArray, case: usize) {
    check_fixed(actual.x, ref d, tol, name, case);
    check_fixed(actual.y, ref d, tol, name, case);
    check_fixed(actual.z, ref d, tol, name, case);
    check_fixed(actual.w, ref d, tol, name, case);
}

fn check_quat(actual: Quat, ref d: Span<i64>, tol: i128, name: @ByteArray, case: usize) {
    check_fixed(actual.x, ref d, tol, name, case);
    check_fixed(actual.y, ref d, tol, name, case);
    check_fixed(actual.z, ref d, tol, name, case);
    check_fixed(actual.w, ref d, tol, name, case);
}

fn check_mat3(actual: Mat3, ref d: Span<i64>, tol: i128, name: @ByteArray, case: usize) {
    check_vec3(actual.x_axis, ref d, tol, name, case);
    check_vec3(actual.y_axis, ref d, tol, name, case);
    check_vec3(actual.z_axis, ref d, tol, name, case);
}

fn check_mat4(actual: Mat4, ref d: Span<i64>, tol: i128, name: @ByteArray, case: usize) {
    check_vec4(actual.x_axis, ref d, tol, name, case);
    check_vec4(actual.y_axis, ref d, tol, name, case);
    check_vec4(actual.z_axis, ref d, tol, name, case);
    check_vec4(actual.w_axis, ref d, tol, name, case);
}
// euler::mat3_from_euler_zyx: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_ZYX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        1188509392, 649285640, 4075857905, -2395572593, -3345366991, 1231460809, 3360866176,
        -2614133113, -563587342,
];

#[test]
fn golden_euler_mat3_from_euler_zyx() {
    let name: ByteArray = "euler::mat3_from_euler_zyx";
    let mut d = MAT3_FROM_EULER_ZYX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::ZYX, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_zxy: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_ZXY_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        208295330, -4109362652, -1231460809, -649285640, 1188509392, -4075857905, 4240493519,
        383833420, -563587342,
];

#[test]
fn golden_euler_mat3_from_euler_zxy() {
    let name: ByteArray = "euler::mat3_from_euler_zxy";
    let mut d = MAT3_FROM_EULER_ZXY_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::ZXY, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_yxz: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_YXZ_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -3345366991, 1231460809, -2395572593, -2614133113, -563587342, 3360866176, 649285640,
        4075857905, 1188509392,
];

#[test]
fn golden_euler_mat3_from_euler_yxz() {
    let name: ByteArray = "euler::mat3_from_euler_yxz";
    let mut d = MAT3_FROM_EULER_YXZ_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::YXZ, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_yzx: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_YZX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        1188509392, -4075857905, -649285640, 383833420, -563587342, 4240493519, -4109362652,
        -1231460809, 208295330,
];

#[test]
fn golden_euler_mat3_from_euler_yzx() {
    let name: ByteArray = "euler::mat3_from_euler_yzx";
    let mut d = MAT3_FROM_EULER_YZX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::YZX, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_xyz: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_XYZ_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -563587342, 4240493519, 383833420, -1231460809, 208295330, -4109362652, -4075857905,
        -649285640, 1188509392,
];

#[test]
fn golden_euler_mat3_from_euler_xyz() {
    let name: ByteArray = "euler::mat3_from_euler_xyz";
    let mut d = MAT3_FROM_EULER_XYZ_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::XYZ, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_xzy: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_XZY_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -563587342, 3360866176, -2614133113, 4075857905, 1188509392, 649285640, 1231460809,
        -2395572593, -3345366991,
];

#[test]
fn golden_euler_mat3_from_euler_xzy() {
    let name: ByteArray = "euler::mat3_from_euler_xzy";
    let mut d = MAT3_FROM_EULER_XZY_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::XZY, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_zyz: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_ZYZ_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -2366944221, 3157115151, -1696155373, -223813502, -2158929592, -3706167105, -3576901822,
        -1954070371, 1354299234,
];

#[test]
fn golden_euler_mat3_from_euler_zyz() {
    let name: ByteArray = "euler::mat3_from_euler_zyz";
    let mut d = MAT3_FROM_EULER_ZYZ_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::ZYZ, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_zxz: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_ZXZ_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -2158929592, 223813502, -3706167105, -3157115151, -2366944221, 1696155373, -1954070371,
        3576901822, 1354299234,
];

#[test]
fn golden_euler_mat3_from_euler_zxz() {
    let name: ByteArray = "euler::mat3_from_euler_zxz";
    let mut d = MAT3_FROM_EULER_ZXZ_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::ZXZ, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_yxy: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_YXY_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -2158929592, -3706167105, -223813502, -1954070371, 1354299234, -3576901822, 3157115151,
        -1696155373, -2366944221,
];

#[test]
fn golden_euler_mat3_from_euler_yxy() {
    let name: ByteArray = "euler::mat3_from_euler_yxy";
    let mut d = MAT3_FROM_EULER_YXY_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::YXY, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_yzy: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_YZY_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -2366944221, 1696155373, -3157115151, 3576901822, 1354299234, -1954070371, 223813502,
        -3706167105, -2158929592,
];

#[test]
fn golden_euler_mat3_from_euler_yzy() {
    let name: ByteArray = "euler::mat3_from_euler_yzy";
    let mut d = MAT3_FROM_EULER_YZY_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::YZY, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_xyx: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_XYX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        1354299234, -1954070371, 3576901822, -3706167105, -2158929592, 223813502, 1696155373,
        -3157115151, -2366944221,
];

#[test]
fn golden_euler_mat3_from_euler_xyx() {
    let name: ByteArray = "euler::mat3_from_euler_xyx";
    let mut d = MAT3_FROM_EULER_XYX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::XYX, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_xzx: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_XZX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        1354299234, -3576901822, -1954070371, -1696155373, -2366944221, 3157115151, -3706167105,
        -223813502, -2158929592,
];

#[test]
fn golden_euler_mat3_from_euler_xzx() {
    let name: ByteArray = "euler::mat3_from_euler_xzx";
    let mut d = MAT3_FROM_EULER_XZX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::XZX, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_zyx_ex: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_ZYX_EX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        1188509392, -4109362652, 383833420, -649285640, 208295330, 4240493519, -4075857905,
        -1231460809, -563587342,
];

#[test]
fn golden_euler_mat3_from_euler_zyx_ex() {
    let name: ByteArray = "euler::mat3_from_euler_zyx_ex";
    let mut d = MAT3_FROM_EULER_ZYX_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::ZYXEx, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_zxy_ex: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_ZXY_EX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -3345366991, 649285640, -2614133113, -2395572593, 1188509392, 3360866176, 1231460809,
        4075857905, -563587342,
];

#[test]
fn golden_euler_mat3_from_euler_zxy_ex() {
    let name: ByteArray = "euler::mat3_from_euler_zxy_ex";
    let mut d = MAT3_FROM_EULER_ZXY_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::ZXYEx, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_yxz_ex: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_YXZ_EX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        208295330, 4240493519, -649285640, -1231460809, -563587342, -4075857905, -4109362652,
        383833420, 1188509392,
];

#[test]
fn golden_euler_mat3_from_euler_yxz_ex() {
    let name: ByteArray = "euler::mat3_from_euler_yxz_ex";
    let mut d = MAT3_FROM_EULER_YXZ_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::YXZEx, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_yzx_ex: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_YZX_EX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        1188509392, 3360866176, -2395572593, 4075857905, -563587342, 1231460809, 649285640,
        -2614133113, -3345366991,
];

#[test]
fn golden_euler_mat3_from_euler_yzx_ex() {
    let name: ByteArray = "euler::mat3_from_euler_yzx_ex";
    let mut d = MAT3_FROM_EULER_YZX_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::YZXEx, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_xyz_ex: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_XYZ_EX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -563587342, 1231460809, 4075857905, -2614133113, -3345366991, 649285640, 3360866176,
        -2395572593, 1188509392,
];

#[test]
fn golden_euler_mat3_from_euler_xyz_ex() {
    let name: ByteArray = "euler::mat3_from_euler_xyz_ex";
    let mut d = MAT3_FROM_EULER_XYZ_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::XYZEx, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_xzy_ex: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_XZY_EX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -563587342, -4075857905, -1231460809, 383833420, 1188509392, -4109362652, 4240493519,
        -649285640, 208295330,
];

#[test]
fn golden_euler_mat3_from_euler_xzy_ex() {
    let name: ByteArray = "euler::mat3_from_euler_xzy_ex";
    let mut d = MAT3_FROM_EULER_XZY_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::XZYEx, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_zyz_ex: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_ZYZ_EX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -2366944221, 223813502, 3576901822, -3157115151, -2158929592, -1954070371, 1696155373,
        -3706167105, 1354299234,
];

#[test]
fn golden_euler_mat3_from_euler_zyz_ex() {
    let name: ByteArray = "euler::mat3_from_euler_zyz_ex";
    let mut d = MAT3_FROM_EULER_ZYZ_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::ZYZEx, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_zxz_ex: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_ZXZ_EX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -2158929592, 3157115151, -1954070371, -223813502, -2366944221, -3576901822, -3706167105,
        -1696155373, 1354299234,
];

#[test]
fn golden_euler_mat3_from_euler_zxz_ex() {
    let name: ByteArray = "euler::mat3_from_euler_zxz_ex";
    let mut d = MAT3_FROM_EULER_ZXZ_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::ZXZEx, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_yxy_ex: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_YXY_EX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -2158929592, -1954070371, -3157115151, -3706167105, 1354299234, 1696155373, 223813502,
        3576901822, -2366944221,
];

#[test]
fn golden_euler_mat3_from_euler_yxy_ex() {
    let name: ByteArray = "euler::mat3_from_euler_yxy_ex";
    let mut d = MAT3_FROM_EULER_YXY_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::YXYEx, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_yzy_ex: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_YZY_EX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        -2366944221, -3576901822, -223813502, -1696155373, 1354299234, -3706167105, 3157115151,
        -1954070371, -2158929592,
];

#[test]
fn golden_euler_mat3_from_euler_yzy_ex() {
    let name: ByteArray = "euler::mat3_from_euler_yzy_ex";
    let mut d = MAT3_FROM_EULER_YZY_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::YZYEx, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_xyx_ex: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_XYX_EX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        1354299234, -3706167105, -1696155373, -1954070371, -2158929592, 3157115151, -3576901822,
        -223813502, -2366944221,
];

#[test]
fn golden_euler_mat3_from_euler_xyx_ex() {
    let name: ByteArray = "euler::mat3_from_euler_xyx_ex";
    let mut d = MAT3_FROM_EULER_XYX_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::XYXEx, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat3_from_euler_xzx_ex: 2 cases, tolerance 8 ULP - 5 * 1.02 ULP of `sin_cos` + 1 floor +
// 0.5 quantization <= 8 (see the header).
#[cairofmt::skip]
const MAT3_FROM_EULER_XZX_EX_CASES: [i64; 24] = [
    0, 0, 0, 4294967296, 0, 0, 0, 4294967296, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592,
        1354299234, 1696155373, -3706167105, 3576901822, -2366944221, 223813502, -1954070371,
        -3157115151, -2158929592,
];

#[test]
fn golden_euler_mat3_from_euler_xzx_ex() {
    let name: ByteArray = "euler::mat3_from_euler_xzx_ex";
    let mut d = MAT3_FROM_EULER_XZX_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat3 = Mat3EulerTrait::from_euler(EulerRot::XZXEx, a0, a1, a2);
        check_mat3(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::to_euler_xyz: 3 cases, tolerance 5 ULP - exact shared input: 3.22 ULP of `atan2` + 1 of
// the floored `sqrt` <= 5.
#[cairofmt::skip]
const TO_EULER_XYZ_CASES: [i64; 36] = [
    -2771713176, -2774526168, 1751100992, -438883452, -1958183837, -3797320299, 3251419914,
        -2629498941, 980177503,
        5214043516, 3688327929, 12818556317,
    -4013515806, -918209109, 1222835633, 918371372, -4193473767, -134595191, 1222713775, 135697730,
        4115009262,
        -141580773, 1239862829, -12526897378,
    952205046, 2687604396, -3211982602, -2687609033, -2134110702, -2582454893, -3211978722,
        2582459718, 1208651548,
        -4866436961, -3628444801, 5284101805,
];

#[test]
fn golden_euler_to_euler_xyz() {
    let name: ByteArray = "euler::to_euler_xyz";
    let mut d = TO_EULER_XYZ_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat3(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::XYZ);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
// euler::to_euler_xyx_ex: 3 cases, tolerance 5 ULP - exact shared input: 3.22 ULP of `atan2` + 1
// of the floored `sqrt` <= 5.
#[cairofmt::skip]
const TO_EULER_XYX_EX_CASES: [i64; 36] = [
    3705864850, -36, 2171015842, 36, -4294967296, -133, 2171015842, 133, -3705864850,
        -13493037633, -2276062246, 71,
    4282903592, 0, -321684459, 0, -4294967296, -2, -321684459, 2, -4282903592,
        0, -321985980, -13493037705,
    -3246431835, 2036876819, -1938699884, -2036699560, -3744869604, -523975786, -1938886102,
        523286296, 3796529495,
        3478909487, -10427220351, -10013735540,
];

#[test]
fn golden_euler_to_euler_xyx_ex() {
    let name: ByteArray = "euler::to_euler_xyx_ex";
    let mut d = TO_EULER_XYX_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat3(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::XYXEx);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
// euler::to_euler_xzy_ex: 3 cases, tolerance 5 ULP - exact shared input: 3.22 ULP of `atan2` + 1
// of the floored `sqrt` <= 5.
#[cairofmt::skip]
const TO_EULER_XZY_EX_CASES: [i64; 36] = [
    1410308761, 1129888710, -3896296290, 3256426798, 2144770200, 1800663593, 2419392028,
        -3545427530, -152413657,
        4409868578, 1143344891, 5254916059,
    216234065, 1328127122, -4078733290, 1328127485, 3862499166, 1328127122, 4078733172, -1328127485,
        -216234065,
        1422438025, 1350259834, 6519034103,
    -477141489, 4263210531, 210038199, -3673081768, -302439574, -2205389921, -2174293081,
        -424629662, 3679522160,
        9404655555, 6223904878, -11712020734,
];

#[test]
fn golden_euler_to_euler_xzy_ex() {
    let name: ByteArray = "euler::to_euler_xzy_ex";
    let mut d = TO_EULER_XZY_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat3(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::XZYEx);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
// euler::to_euler_yzy: 3 cases, tolerance 5 ULP - exact shared input: 3.22 ULP of `atan2` + 1 of
// the floored `sqrt` <= 5.
#[cairofmt::skip]
const TO_EULER_YZY_CASES: [i64; 36] = [
    2576980378, 24434, -3435973837, -24433, 4294967296, 12218, 3435973837, 12215, 2576980378,
        -11501475450, -27318, -11501967642,
    4236139208, -68723, 708426906, 68723, -4294967216, -827587, 708426906, 827587, -4236139127,
        6390680274, -13492207269, -6390680274,
    4294967296, -1, 2, -1, 3527441919, 2450285205, -2, -2450285205, 3527441919,
        -6746518854, -2607544752, 6746518851,
];

#[test]
fn golden_euler_to_euler_yzy() {
    let name: ByteArray = "euler::to_euler_yzy";
    let mut d = TO_EULER_YZY_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat3(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::YZY);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
// euler::to_euler_zxy: 3 cases, tolerance 5 ULP - exact shared input: 3.22 ULP of `atan2` + 1 of
// the floored `sqrt` <= 5.
#[cairofmt::skip]
const TO_EULER_ZXY_CASES: [i64; 36] = [
    1145071491, 3825734725, -1580920355, 68439939, -1657563073, -3961634096, -4138945678,
        1031010451, -502881890,
        -13315801355, -5043247418, 8069254468,
    -2192156522, 1534431127, -3359570653, -1534431127, 3175285528, 2451494851, 3359570653,
        2451494851, -1072474754,
        1933385991, 2609017777, 8073681125,
    -4009534767, 860932141, 1276389781, -861067876, 1697782525, -3850044244, -1276298216,
        -3850074599, -1412349998,
        2015923597, -4774278691, -10336775008,
];

#[test]
fn golden_euler_to_euler_zxy() {
    let name: ByteArray = "euler::to_euler_zxy";
    let mut d = TO_EULER_ZXY_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat3(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::ZXY);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
// euler::to_euler_zxz_ex: 3 cases, tolerance 5 ULP - exact shared input: 3.22 ULP of `atan2` + 1
// of the floored `sqrt` <= 5.
#[cairofmt::skip]
const TO_EULER_ZXZ_EX_CASES: [i64; 36] = [
    -744980091, 3336006772, 2600539859, -3336006772, -2086820995, 1721331179, 2600539859,
        -1721331179, 2953126392,
        -9257805084, -3490295322, -9257805084,
    -4294967296, -1, 12, 5, -4091680538, 1305716069, 11, 1305716069, 4091680538,
        -13493037665, -1326714620, -36,
    4294967296, 160, 28552, 160, -4294967296, 0, 28552, 0, -4294967296,
        -6746518852, -13493009153, -6746518852,
];

#[test]
fn golden_euler_to_euler_zxz_ex() {
    let name: ByteArray = "euler::to_euler_zxz_ex";
    let mut d = TO_EULER_ZXZ_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat3(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::ZXZEx);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
// euler::to_euler_yzx_ex: 3 cases, tolerance 5 ULP - exact shared input: 3.22 ULP of `atan2` + 1
// of the floored `sqrt` <= 5.
#[cairofmt::skip]
const TO_EULER_YZX_EX_CASES: [i64; 36] = [
    1209478706, 591733446, 4078450302, 591785148, -4231349801, 438421344, 4078442800, 438491123,
        -1273096201,
        5508312524, -593673826, 13049607094,
    -4294967296, 89, 3035, -90, -4294967160, -1079192, 3035, -1079192, 4294967160,
        13493034670, 90, -13491958513,
    -4200688886, -329141449, 832239668, -303940828, -3231913588, -2812311968, 841770118,
        -2809474068, 3137677900,
        12643625566, 304195087, -10417465456,
];

#[test]
fn golden_euler_to_euler_yzx_ex() {
    let name: ByteArray = "euler::to_euler_yzx_ex";
    let mut d = TO_EULER_YZX_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat3(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::YZXEx);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
// euler::to_euler_xzx: 3 cases, tolerance 5 ULP - exact shared input: 3.22 ULP of `atan2` + 1 of
// the floored `sqrt` <= 5.
#[cairofmt::skip]
const TO_EULER_XZX_CASES: [i64; 36] = [
    -3240577039, -1883204172, 2097366581, -1883204172, 3824336669, 524151849, -2097366581,
        -524151849, -3711207666,
        9888923303, 10418288666, -3604114401,
    -1384304363, 177102400, 4061905987, 4061905987, -126666471, 1389827124, 177102400, 4289444535,
        -126666471,
        6559373320, 8155985777, 13305892172,
    4294967296, -38146, 1553, -38147, -4280882153, 347551524, -1539, -347551524, -4280882153,
        13318277501, 38178, -173181953,
];

#[test]
fn golden_euler_to_euler_xzx() {
    let name: ByteArray = "euler::to_euler_xzx";
    let mut d = TO_EULER_XZX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat3(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::XZX);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
// euler::to_euler_yxz: 3 cases, tolerance 5 ULP - exact shared input: 3.22 ULP of `atan2` + 1 of
// the floored `sqrt` <= 5.
#[cairofmt::skip]
const TO_EULER_YXZ_CASES: [i64; 36] = [
    4238091177, 3590, 696654327, -3590, -4294967296, 43967, 696654327, -43967, -4238091177,
        12793291846, 43967, 13493034115,
    -1727376098, 2978320205, -2567591214, -2978320234, 840215099, 2978320205, 2567591181,
        2978320234, 1727376098,
        4202995684, -3291054647, 5565554886,
    4294967296, 0, 0, 0, -4294967296, 266, 0, -266, -4294967296, 13493037705, 266, 13493037705,
];

#[test]
fn golden_euler_to_euler_yxz() {
    let name: ByteArray = "euler::to_euler_yxz";
    let mut d = TO_EULER_YXZ_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat3(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::YXZ);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
// euler::to_euler_yxy_ex: 3 cases, tolerance 5 ULP - exact shared input: 3.22 ULP of `atan2` + 1
// of the floored `sqrt` <= 5.
#[cairofmt::skip]
const TO_EULER_YXY_EX_CASES: [i64; 36] = [
    4294967296, -1, 1, 1, -957484897, -4186880312, 1, 4186880312, -957484897,
        -13493037703, 7712117494, 13493037703,
    -4294967296, 3, 3, -3, 70345200, -4294391182, -3, -4294391182, -70345200,
        3, 6676170507, -13493037702,
    4294967296, 1, -1, -1, 756806804, -4227763893, -1, 4227763893, 756806804,
        13493037704, 5985739921, -13493037704,
];

#[test]
fn golden_euler_to_euler_yxy_ex() {
    let name: ByteArray = "euler::to_euler_yxy_ex";
    let mut d = TO_EULER_YXY_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat3(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::YXYEx);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
// euler::to_euler_xyz_ex: 3 cases, tolerance 5 ULP - exact shared input: 3.22 ULP of `atan2` + 1
// of the floored `sqrt` <= 5.
#[cairofmt::skip]
const TO_EULER_XYZ_EX_CASES: [i64; 36] = [
    704618175, -688923298, 4180387780, 2183812771, 3690535775, 240107369, -3630594866, 2086162615,
        955746062,
        1057126035, -5752216028, -3324889044,
    -264751073, 1534260129, -4002836094, -1534260129, 3710890905, 1523836808, 4002836094,
        1523836808, 319325317,
        5859331069, 5153294976, 7480428489,
    -2061541788, 2387764978, 2914681447, -2368209454, 1763008069, -3119315727, -2930592689,
        -3104371922, 470367444,
        -6103715578, -3203581268, 9805433741,
];

#[test]
fn golden_euler_to_euler_xyz_ex() {
    let name: ByteArray = "euler::to_euler_xyz_ex";
    let mut d = TO_EULER_XYZ_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat3(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::XYZEx);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
// euler::to_euler_zyz: 3 cases, tolerance 5 ULP - exact shared input: 3.22 ULP of `atan2` + 1 of
// the floored `sqrt` <= 5.
#[cairofmt::skip]
const TO_EULER_ZYZ_CASES: [i64; 36] = [
    2741466346, 0, 3306222368, 0, -4294967296, 0, 3306222368, 0, -2741466346,
        0, 9719857820, 13493037705,
    -3345205829, 2693759832, -56842, -2693759832, -3345205829, -8765, -49769, 28824, 4294967296,
        11238386936, 57513, -657105726,
    4294967296, 0, 0, 0, 3716977968, -2151933749, 0, 2151933749, 3716977968,
        6746518852, 2253979929, -6746518852,
];

#[test]
fn golden_euler_to_euler_zyz() {
    let name: ByteArray = "euler::to_euler_zyz";
    let mut d = TO_EULER_ZYZ_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat3(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::ZYZ);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
// euler::quat_from_euler_xyz: 4 cases, tolerance 8 ULP - as `mat3_from_euler_*`, plus the 0.5 ULP
// of the floored half angle: <= 8.
#[cairofmt::skip]
const QUAT_FROM_EULER_XYZ_CASES: [i64; 28] = [
    0, 0, 0, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592, -1583265950, -2040670597, 2503863046, 2346560540,
    -8195135311, 21474836480, -6116, 2806930515, 1486713202, -2096839055, -1990184663,
    -463569553, 5653913073, -9302878972, -2403310734, 1067637208, -3063481263, 1464948783,
];

#[test]
fn golden_euler_quat_from_euler_xyz() {
    let name: ByteArray = "euler::quat_from_euler_xyz";
    let mut d = QUAT_FROM_EULER_XYZ_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Quat = QuatEulerTrait::from_euler(EulerRot::XYZ, a0, a1, a2);
        check_quat(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::quat_from_euler_yxy: 4 cases, tolerance 8 ULP - as `mat3_from_euler_*`, plus the 0.5 ULP
// of the floored half angle: <= 8.
#[cairofmt::skip]
const QUAT_FROM_EULER_YXY_CASES: [i64; 28] = [
    0, 0, 0, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592, -1838714849, 3305370441, -1712940244, 1098286732,
    17179869184, 7847314818, 153185022, -1359633451, 2366119266, -3116554865, -1134330793,
    -21474836480, 22178728856, 14713011755, -1092299181, 2578262398, -2001490163, -2569090638,
];

#[test]
fn golden_euler_quat_from_euler_yxy() {
    let name: ByteArray = "euler::quat_from_euler_yxy";
    let mut d = QUAT_FROM_EULER_YXY_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Quat = QuatEulerTrait::from_euler(EulerRot::YXY, a0, a1, a2);
        check_quat(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::quat_from_euler_zxy: 4 cases, tolerance 8 ULP - as `mat3_from_euler_*`, plus the 0.5 ULP
// of the floored half angle: <= 8.
#[cairofmt::skip]
const QUAT_FROM_EULER_ZXY_CASES: [i64; 28] = [
    0, 0, 0, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592, -2040670597, 2503863046, -1583265950, 2346560540,
    -9537682534, -17065833191, 17179869184, -687074491, -2165843049, -2234399756, -2879453826,
    0, -23622320128, 12027961579, -278227681, -3912247285, -1615436912, -673808726,
];

#[test]
fn golden_euler_quat_from_euler_zxy() {
    let name: ByteArray = "euler::quat_from_euler_zxy";
    let mut d = QUAT_FROM_EULER_ZXY_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Quat = QuatEulerTrait::from_euler(EulerRot::ZXY, a0, a1, a2);
        check_quat(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::quat_from_euler_xzy: 4 cases, tolerance 8 ULP - as `mat3_from_euler_*`, plus the 0.5 ULP
// of the floored half angle: <= 8.
#[cairofmt::skip]
const QUAT_FROM_EULER_XZY_CASES: [i64; 28] = [
    0, 0, 0, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592, 2514447639, 3175696147, -590441041, 1300242479,
    -17640352716, -19137983151, -147, 2323761621, -3011765375, 1578734188, 1218090183,
    614, -88090928, -9799736815, -40035781, -3903850201, -18359496, 1790183719,
];

#[test]
fn golden_euler_quat_from_euler_xzy() {
    let name: ByteArray = "euler::quat_from_euler_xzy";
    let mut d = QUAT_FROM_EULER_XZY_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Quat = QuatEulerTrait::from_euler(EulerRot::XZY, a0, a1, a2);
        check_quat(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::quat_from_euler_yxz_ex: 4 cases, tolerance 8 ULP - as `mat3_from_euler_*`, plus the 0.5
// ULP of the floored half angle: <= 8.
#[cairofmt::skip]
const QUAT_FROM_EULER_YXZ_EX_CASES: [i64; 28] = [
    0, 0, 0, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592, -2040670597, -1583265950, 2503863046, 2346560540,
    9507962769, 0, 2618674950, -1152892234, 3663899334, 576844168, 1833214675,
    1266950, 15032385536, -144221, 4226187413, -183870, 636184, -765560961,
];

#[test]
fn golden_euler_quat_from_euler_yxz_ex() {
    let name: ByteArray = "euler::quat_from_euler_yxz_ex";
    let mut d = QUAT_FROM_EULER_YXZ_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Quat = QuatEulerTrait::from_euler(EulerRot::YXZEx, a0, a1, a2);
        check_quat(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::quat_from_euler_zyz_ex: 4 cases, tolerance 8 ULP - as `mat3_from_euler_*`, plus the 0.5
// ULP of the floored half angle: <= 8.
#[cairofmt::skip]
const QUAT_FROM_EULER_ZYZ_EX_CASES: [i64; 28] = [
    0, 0, 0, 0, 0, 0, 4294967296,
    2147483648, -5368709120, 8589934592, 1712940244, -1838714849, 3305370441, 1098286732,
    2031647019, -2, 11171340331, 1, 0, 4292519046, 144997620,
    21563, 25769803776, 0, 1521, 606105819, -10674, -4251985396,
];

#[test]
fn golden_euler_quat_from_euler_zyz_ex() {
    let name: ByteArray = "euler::quat_from_euler_zyz_ex";
    let mut d = QUAT_FROM_EULER_ZYZ_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Quat = QuatEulerTrait::from_euler(EulerRot::ZYZEx, a0, a1, a2);
        check_quat(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::quat_to_euler_xyz: 2 cases, tolerance 24 ULP - 2 ULP on the matrix entries, amplified by
// `1 / cy <= 4`, plus 5: <= 24.
#[cairofmt::skip]
const QUAT_TO_EULER_XYZ_CASES: [i64; 14] = [
    0, -12785, 4070379120, -1370677895, 24233, 8160, -10702876786,
    2698693444, 2362604259, -180, -2362604259, -8975257526, -2791752139, -4517780179,
];

#[test]
fn golden_euler_quat_to_euler_xyz() {
    let name: ByteArray = "euler::quat_to_euler_xyz";
    let mut d = QUAT_TO_EULER_XYZ_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_quat(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::XYZ);
        check_fixed(r0, ref d, 24, @name, case);
        check_fixed(r1, ref d, 24, @name, case);
        check_fixed(r2, ref d, 24, @name, case);
        case += 1;
    }
}
// euler::quat_to_euler_yxy: 2 cases, tolerance 24 ULP - 2 ULP on the matrix entries, amplified by
// `1 / cy <= 4`, plus 5: <= 24.
#[cairofmt::skip]
const QUAT_TO_EULER_YXY_CASES: [i64; 14] = [
    2436113791, 1341948146, 2454246921, -2165165328, 7720815499, 8039354446, -12486890302,
    -2866709604, -2038444250, 2464440129, 105263, 9796530189, 9245113233, 3696951090,
];

#[test]
fn golden_euler_quat_to_euler_yxy() {
    let name: ByteArray = "euler::quat_to_euler_yxy";
    let mut d = QUAT_TO_EULER_YXY_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_quat(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::YXY);
        check_fixed(r0, ref d, 24, @name, case);
        check_fixed(r1, ref d, 24, @name, case);
        check_fixed(r2, ref d, 24, @name, case);
        case += 1;
    }
}
// euler::quat_to_euler_zxy: 2 cases, tolerance 24 ULP - 2 ULP on the matrix entries, amplified by
// `1 / cy <= 4`, plus 5: <= 24.
#[cairofmt::skip]
const QUAT_TO_EULER_ZXY_CASES: [i64; 14] = [
    59039, -3254408882, -2739420602, 592572073, -3250133367, 5633193124, -9396338645,
    2343234111, -1834307810, -3096984474, 5263, 10774531813, 2849925140, 6528942374,
];

#[test]
fn golden_euler_quat_to_euler_zxy() {
    let name: ByteArray = "euler::quat_to_euler_zxy";
    let mut d = QUAT_TO_EULER_ZXY_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_quat(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::ZXY);
        check_fixed(r0, ref d, 24, @name, case);
        check_fixed(r1, ref d, 24, @name, case);
        check_fixed(r2, ref d, 24, @name, case);
        case += 1;
    }
}
// euler::quat_to_euler_yxz_ex: 2 cases, tolerance 24 ULP - 2 ULP on the matrix entries, amplified
// by `1 / cy <= 4`, plus 5: <= 24.
#[cairofmt::skip]
const QUAT_TO_EULER_YXZ_EX_CASES: [i64; 14] = [
    -2570532711, -2574771760, 2282466829, -1102702, 9322420721, -2965325406, -8350218369,
    1900982514, -201063821, 3603914280, 1343273897, -3895881801, 857341139, 10847309963,
];

#[test]
fn golden_euler_quat_to_euler_yxz_ex() {
    let name: ByteArray = "euler::quat_to_euler_yxz_ex";
    let mut d = QUAT_TO_EULER_YXZ_EX_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_quat(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::YXZEx);
        check_fixed(r0, ref d, 24, @name, case);
        check_fixed(r1, ref d, 24, @name, case);
        check_fixed(r2, ref d, 24, @name, case);
        case += 1;
    }
}
// euler::mat4_from_euler_yxz: 1 cases, tolerance 8 ULP - the 3x3 block is `Mat3::from_euler`
// (same 8 ULP) and the fourth row and column are exact.
#[cairofmt::skip]
const MAT4_FROM_EULER_YXZ_CASES: [i64; 19] = [
    60, -8589934592, -23622320128,
        3043713466, -1261038366, -2755419142, 0, -3030272663, -1266631746, -2767640815, 0, -25,
        3905402711, -1787337053, 0, 0, 0, 0, 4294967296,
];

#[test]
fn golden_euler_mat4_from_euler_yxz() {
    let name: ByteArray = "euler::mat4_from_euler_yxz";
    let mut d = MAT4_FROM_EULER_YXZ_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_fixed(ref d);
        let a1 = next_fixed(ref d);
        let a2 = next_fixed(ref d);
        let actual: Mat4 = Mat4EulerTrait::from_euler(EulerRot::YXZ, a0, a1, a2);
        check_mat4(actual, ref d, 8, @name, case);
        case += 1;
    }
}
// euler::mat4_to_euler_yxz: 3 cases, tolerance 5 ULP - `Mat3::from_mat4` drops the fourth row and
// column exactly, so this is `Mat3::to_euler` on the same quantized matrix: 5 ULP.
#[cairofmt::skip]
const MAT4_TO_EULER_YXZ_CASES: [i64; 57] = [
    46359741, -620409801, 4249668990, 0, 634947312, -4202222943, -620409801, 0, 4247521249,
        634947312, 46359741, 0, 0, 0, 0, 4294967296,
        6699643121, -637283180, -12863483139,
    3841672550, -1920493710, -15996, 0, -1920493709, -3841672549, -112292, 0, 35903, 107594,
        -4294967295, 0, 0, 0, 0, 4294967296,
        13493001802, -107594, -11501992786,
    4294967296, 23450, 1990, 0, 23449, -4233059781, -726600967, 0, -2006, 726600967, -4233059781, 0,
        0, 0, 0, 4294967296,
        -13493035669, -730112288, 13493013912,
];

#[test]
fn golden_euler_mat4_to_euler_yxz() {
    let name: ByteArray = "euler::mat4_to_euler_yxz";
    let mut d = MAT4_TO_EULER_YXZ_CASES.span();
    let mut case: usize = 0;
    while !d.is_empty() {
        let a0 = next_mat4(ref d);
        let (r0, r1, r2): (Fixed, Fixed, Fixed) = a0.to_euler(EulerRot::YXZ);
        check_fixed(r0, ref d, 5, @name, case);
        check_fixed(r1, ref d, 5, @name, case);
        check_fixed(r2, ref d, 5, @name, case);
        case += 1;
    }
}
