// GENERATED by tools/codegen/intvec.py - do not edit by hand.
//! Tests of `glam::ivec4`: the glam-rs integer vector test macros of `tests/vec4.rs`, tables over
//! a pool of edge values (expected values computed by the generator with Python integers, one
//! `const` table and one looping test per function group), seeded fuzz properties against the
//! `i128` reference below, and one test per panic path.

use core::hash::{HashStateExTrait, HashStateTrait};
use core::poseidon::PoseidonTrait;
use glam::bvec4::{BVec4, BVec4Trait, bvec4};
use glam::ivec2::ivec2;
use glam::ivec3::ivec3;
use glam::ivec4::{IVec4, IVec4Trait, ivec4};
use glam::uvec4::{UVec4, UVec4Trait, uvec4};

fn hash(v: IVec4) -> felt252 {
    PoseidonTrait::new().update_with(v).finalize()
}

// Readers of the table rows (`[i64; W]`, one cell per scalar): the value of a column at an offset.

fn sc(r: Span<i64>, o: u32) -> i32 {
    (*r[o]).try_into().unwrap()
}

fn su(r: Span<i64>, o: u32) -> u32 {
    (*r[o]).try_into().unwrap()
}

fn us(r: Span<i64>, o: u32) -> usize {
    (*r[o]).try_into().unwrap()
}

fn vc(r: Span<i64>, o: u32) -> IVec4 {
    ivec4(sc(r, o), sc(r, o + 1), sc(r, o + 2), sc(r, o + 3))
}

fn vo(r: Span<i64>, o: u32) -> UVec4 {
    uvec4(
        (*r[o]).try_into().unwrap(),
        (*r[o + 1]).try_into().unwrap(),
        (*r[o + 2]).try_into().unwrap(),
        (*r[o + 3]).try_into().unwrap(),
    )
}

fn bv(r: Span<i64>, o: u32) -> BVec4 {
    bvec4(*r[o] != 0, *r[o + 1] != 0, *r[o + 2] != 0, *r[o + 3] != 0)
}

fn opt(r: Span<i64>, o: u32) -> Option<IVec4> {
    if *r[o] == 0 {
        None
    } else {
        Some(vc(r, o + 1))
    }
}

fn opto(r: Span<i64>, o: u32) -> Option<UVec4> {
    if *r[o] == 0 {
        None
    } else {
        Some(vo(r, o + 1))
    }
}

fn optu(r: Span<i64>, o: u32) -> Option<u32> {
    if *r[o] == 0 {
        None
    } else {
        Some(su(r, o + 1))
    }
}

// The reference of the fuzz tests: exact arithmetic in `i128`, reduced to `i32` the way Rust does.

fn wide(v: i32) -> i128 {
    v.into()
}

fn wide_o(v: u32) -> i128 {
    v.into()
}

fn wide_u(v: u32) -> i128 {
    v.into()
}

fn abs_wide(v: i128) -> i128 {
    if v < 0 {
        -v
    } else {
        v
    }
}

/// Euclidean remainder of `v` by `2^32`.
fn low32(v: i128) -> i128 {
    let m: i128 = 0x100000000;
    ((v % m) + m) % m
}

/// Two's complement reduction to `i32`.
fn wrap(v: i128) -> i128 {
    let r = low32(v);
    if r >= 0x80000000 {
        r - 0x100000000
    } else {
        r
    }
}

/// Two's complement reduction to `u32`.
fn wrap_o(v: i128) -> i128 {
    let r = low32(v);
    r
}

fn sat(v: i128) -> i128 {
    if v < -2147483648 {
        -2147483648
    } else if v > 2147483647 {
        2147483647
    } else {
        v
    }
}

fn narrow(v: i128) -> i32 {
    v.try_into().unwrap()
}

fn map_wrap(e: [i128; 4]) -> [i32; 4] {
    let [x, y, z, w] = e;
    [narrow(wrap(x)), narrow(wrap(y)), narrow(wrap(z)), narrow(wrap(w))]
}

fn map_sat(e: [i128; 4]) -> [i32; 4] {
    let [x, y, z, w] = e;
    [narrow(sat(x)), narrow(sat(y)), narrow(sat(z)), narrow(sat(w))]
}

fn map_checked(e: [i128; 4]) -> Option<IVec4> {
    let [x, y, z, w] = e;
    if sat(x) == x && sat(y) == y && sat(z) == z && sat(w) == w {
        Some(IVec4 { x: narrow(x), y: narrow(y), z: narrow(z), w: narrow(w) })
    } else {
        None
    }
}

fn pow2(k: u32) -> i128 {
    let mut p: i128 = 1;
    for _ in 0..k {
        p *= 2;
    }
    p
}

/// `floor(a / p)` for `p > 0`.
fn floor_div(a: i128, p: i128) -> i128 {
    let r = ((a % p) + p) % p;
    (a - r) / p
}

/// A non-zero divisor.
fn nz(v: i32) -> i32 {
    if v == 0 {
        3
    } else {
        v
    }
}

#[test]
fn test_new() {
    let v = IVec4Trait::new(1, 2, 3, 4);
    assert_eq!(v.x, 1);
    assert_eq!(v.y, 2);
    assert_eq!(v.z, 3);
    assert_eq!(v.w, 4);
    assert_eq!(v, ivec4(1, 2, 3, 4));
    let t = (1_i32, 2_i32, 3_i32, 4_i32);
    let v: IVec4 = t.into();
    assert_eq!(v, ivec4(1, 2, 3, 4));
    let t2: (i32, i32, i32, i32) = v.into();
    assert_eq!(t2, t);
    let a = [1_i32, 2_i32, 3_i32, 4_i32];
    let v: IVec4 = a.into();
    assert_eq!(v, ivec4(1, 2, 3, 4));
    assert_eq!(IVec4Trait::from_array(a), ivec4(1, 2, 3, 4));
    let a2: [i32; 4] = v.into();
    assert_eq!(a2, a);
    assert_eq!(v.to_array(), a);
    assert_eq!(Default::<IVec4>::default(), IVec4Trait::ZERO);
}

#[test]
fn test_consts() {
    assert_eq!(IVec4Trait::ZERO, ivec4(0, 0, 0, 0));
    assert_eq!(IVec4Trait::ONE, ivec4(1, 1, 1, 1));
    assert_eq!(IVec4Trait::MIN, ivec4(-2147483648, -2147483648, -2147483648, -2147483648));
    assert_eq!(IVec4Trait::MAX, ivec4(2147483647, 2147483647, 2147483647, 2147483647));
    assert_eq!(IVec4Trait::X, ivec4(1, 0, 0, 0));
    assert_eq!(IVec4Trait::Y, ivec4(0, 1, 0, 0));
    assert_eq!(IVec4Trait::Z, ivec4(0, 0, 1, 0));
    assert_eq!(IVec4Trait::W, ivec4(0, 0, 0, 1));
    assert_eq!(IVec4Trait::NEG_ONE, ivec4(-1, -1, -1, -1));
    assert_eq!(IVec4Trait::NEG_X, ivec4(-1, 0, 0, 0));
    assert_eq!(IVec4Trait::NEG_Y, ivec4(0, -1, 0, 0));
    assert_eq!(IVec4Trait::NEG_Z, ivec4(0, 0, -1, 0));
    assert_eq!(IVec4Trait::NEG_W, ivec4(0, 0, 0, -1));
    let [ax, ay, az, aw] = IVec4Trait::AXES;
    assert_eq!(ax, IVec4Trait::X);
    assert_eq!(ay, IVec4Trait::Y);
    assert_eq!(az, IVec4Trait::Z);
    assert_eq!(aw, IVec4Trait::W);
}

#[test]
fn test_splat_with() {
    assert_eq!(IVec4Trait::splat(7), ivec4(7, 7, 7, 7));
    assert_eq!(IVec4Trait::splat(-2147483648), IVec4Trait::MIN);
    assert_eq!(ivec4(1, 2, 3, 4).with_x(9), ivec4(9, 2, 3, 4));
    assert_eq!(ivec4(1, 2, 3, 4).with_y(9), ivec4(1, 9, 3, 4));
    assert_eq!(ivec4(1, 2, 3, 4).with_z(9), ivec4(1, 2, 9, 4));
    assert_eq!(ivec4(1, 2, 3, 4).with_w(9), ivec4(1, 2, 3, 9));
}

#[test]
fn test_accessors() {
    let mut a = IVec4Trait::ZERO;
    a.x = 1;
    a.y = 2;
    a.z = 3;
    a.w = 4;
    assert_eq!(a, ivec4(1, 2, 3, 4));
    assert_eq!(a[0], 1);
    assert_eq!(a[1], 2);
    assert_eq!(a[2], 3);
    assert_eq!(a[3], 4);
}

#[test]
#[should_panic(expected: 'IVec4: index out of bounds')]
fn test_index_out_of_bounds() {
    let _ = ivec4(1, 2, 3, 4)[4];
}

#[test]
fn test_extend_truncate() {
    assert_eq!(ivec4(1, 2, 3, 4).truncate(), ivec3(1, 2, 3));
    let v: IVec4 = (ivec3(1, 2, 3), 4_i32).into();
    assert_eq!(v, ivec4(1, 2, 3, 4));
    let v: IVec4 = (1_i32, ivec3(2, 3, 4)).into();
    assert_eq!(v, ivec4(1, 2, 3, 4));
    let v: IVec4 = (ivec2(1, 2), 3_i32, 4_i32).into();
    assert_eq!(v, ivec4(1, 2, 3, 4));
    let v: IVec4 = (ivec2(1, 2), ivec2(3, 4)).into();
    assert_eq!(v, ivec4(1, 2, 3, 4));
}

const SELECT: [[i64; 16]; 8] = [
    [0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8],
    [1, 1, 1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4],
    [1, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 1, 6, 7, 8],
    [0, 1, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 5, 2, 7, 8],
    [0, 0, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 3, 8],
    [0, 0, 0, 1, 1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 4],
    [1, 0, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 1, 6, 3, 8],
    [0, 1, 0, 1, 1, 2, 3, 4, 5, 6, 7, 8, 5, 2, 7, 4],
];

#[test]
fn test_select() {
    for row in SELECT.span() {
        let r = row.span();
        assert_eq!(IVec4Trait::select(bv(r, 0), vc(r, 4), vc(r, 8)), vc(r, 12));
    }
}

#[test]
fn test_from_bvec() {
    let v: IVec4 = bvec4(true, false, true, false).into();
    assert_eq!(v, ivec4(1, 0, 1, 0));
    let v: IVec4 = bvec4(false, true, false, true).into();
    assert_eq!(v, ivec4(0, 1, 0, 1));
}

const DOT_LENGTH: [[i64; 11]; 5] = [
    [3, -7, 11, -13, -5, 2, 9, 4, 18, 348, 438], [-1, -2, -3, -4, 4, 3, 2, 1, -20, 30, 100],
    [0, 1, -1, 2, 7, -7, 7, -7, -28, 6, 258],
    [100, -200, 300, -400, -9, 8, -7, 6, -7000, 300000, 314230],
    [46340, -3, 1, 0, 46340, 5, -1, 5, 2147395584, 2147395610, 93],
];

#[test]
fn test_dot_length() {
    for row in DOT_LENGTH.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).dot(vc(r, 4)), sc(r, 8));
        assert_eq!(vc(r, 0).dot_into_vec(vc(r, 4)), IVec4Trait::splat(sc(r, 8)));
        assert_eq!(vc(r, 0).length_squared(), sc(r, 9));
        assert_eq!(vc(r, 0).distance_squared(vc(r, 4)), sc(r, 10));
    }
}

#[test]
fn test_dot_axes() {
    assert_eq!(IVec4Trait::X.dot(IVec4Trait::X), 1);
    assert_eq!(IVec4Trait::X.dot(IVec4Trait::Y), 0);
}

const OPS: [[i64; 49]; 5] = [
    [
        3, -7, 11, -13, -5, 2, 9, 4, -5, -2, -5, 20, -9, 8, -9, 2, -17, -15, -14, 99, -52, 0, -3, 1,
        -3, 3, -1, 2, -1, -2, -12, 6, -18, 8, -2, 16, -8, -15, 35, -55, 65, 0, 1, -2, 2, 3, -2, 1,
        -3,
    ],
    [
        -1, -2, -3, -4, 4, 3, 2, 1, 4, 3, 1, -1, -3, -5, -5, -5, -5, -4, -6, -6, -4, 0, 0, -1, -4,
        -1, -2, -1, 0, 3, 2, 1, 0, -5, -6, -7, -8, -4, -8, -12, -16, 0, 0, 0, -1, -1, -2, -3, 0,
    ],
    [
        0, 1, -1, 2, 7, -7, 7, -7, 7, 7, -6, 6, -5, -7, 8, -8, 9, 0, -7, -7, -14, 0, 0, 0, 0, 0, 1,
        -1, 2, 7, 8, 6, 9, -7, -6, -8, -5, 0, 7, -7, 14, 0, 0, 0, 0, 0, 1, -1, 2,
    ],
    [
        100, -200, 300, -400, -9, 8, -7, 6, -9, 91, -192, 293, -394, 109, -208, 307, -406, -900,
        -1600, -2100, -2400, -11, -25, -42, -66, 1, 0, 6, -4, 91, -209, 291, -409, 109, -191, 309,
        -391, -900, 1800, -2700, 3600, -11, 22, -33, 44, 1, -2, 3, -4,
    ],
    [
        46340, -3, 1, 0, 46340, 5, -1, 5, 46340, 92680, 2, 0, 5, 0, -8, 2, -5, 2147395600, -15, -1,
        0, 1, 0, -1, 0, 0, -3, 0, 0, 92680, 46337, 46341, 46340, 0, -46343, -46339, -46340,
        2147395600, -139020, 46340, 0, 1, 0, 0, 0, 0, -3, 1, 0,
    ],
];

#[test]
fn test_ops() {
    for row in OPS.span() {
        let r = row.span();
        assert_eq!(vc(r, 0) + vc(r, 4), vc(r, 9));
        assert_eq!(vc(r, 0) - vc(r, 4), vc(r, 13));
        assert_eq!(vc(r, 0) * vc(r, 4), vc(r, 17));
        assert_eq!(vc(r, 0) / vc(r, 4), vc(r, 21));
        assert_eq!(vc(r, 0) % vc(r, 4), vc(r, 25));
        assert_eq!(vc(r, 0).add_scalar(sc(r, 8)), vc(r, 29));
        assert_eq!(vc(r, 0).sub_scalar(sc(r, 8)), vc(r, 33));
        assert_eq!(vc(r, 0).mul_scalar(sc(r, 8)), vc(r, 37));
        assert_eq!(vc(r, 0).div_scalar(sc(r, 8)), vc(r, 41));
        assert_eq!(vc(r, 0).rem_scalar(sc(r, 8)), vc(r, 45));
    }
}

const ASSIGN_OPS: [[i64; 48]; 2] = [
    [
        20, 40, 80, 160, 2, 3, 7, 9, 22, 43, 87, 169, 18, 37, 73, 151, 40, 120, 560, 1440, 10, 13,
        11, 17, 0, 1, 3, 7, 23, 43, 83, 163, 17, 37, 77, 157, 60, 120, 240, 480, 6, 13, 26, 53, 2,
        1, 2, 1,
    ],
    [
        -20, 40, -80, 160, 3, -3, 7, -9, -17, 37, -73, 151, -23, 43, -87, 169, -60, -120, -560,
        -1440, -6, -13, -11, -17, -2, 1, -3, 7, -17, 43, -77, 163, -23, 37, -83, 157, -60, 120,
        -240, 480, -6, 13, -26, 53, -2, 1, -2, 1,
    ],
];

#[test]
fn test_assign_ops() {
    for row in ASSIGN_OPS.span() {
        let r = row.span();
        let mut a = vc(r, 0);
        a += vc(r, 4);
        assert_eq!(a, vc(r, 8));
        let mut a = vc(r, 0);
        a += 3;
        assert_eq!(a, vc(r, 28));
        let mut a = vc(r, 0);
        a -= vc(r, 4);
        assert_eq!(a, vc(r, 12));
        let mut a = vc(r, 0);
        a -= 3;
        assert_eq!(a, vc(r, 32));
        let mut a = vc(r, 0);
        a *= vc(r, 4);
        assert_eq!(a, vc(r, 16));
        let mut a = vc(r, 0);
        a *= 3;
        assert_eq!(a, vc(r, 36));
        let mut a = vc(r, 0);
        a /= vc(r, 4);
        assert_eq!(a, vc(r, 20));
        let mut a = vc(r, 0);
        a /= 3;
        assert_eq!(a, vc(r, 40));
        let mut a = vc(r, 0);
        a %= vc(r, 4);
        assert_eq!(a, vc(r, 24));
        let mut a = vc(r, 0);
        a %= 3;
        assert_eq!(a, vc(r, 44));
    }
}

const MIN_MAX: [[i64; 16]; 8] = [
    [
        -2147483648, -2147483647, -65536, -46341, 2147483647, 2147483646, 65536, 46340, -2147483648,
        -2147483647, -65536, -46341, 2147483647, 2147483646, 65536, 46340,
    ],
    [
        2147483647, 2147483646, 46340, 65536, 2147483647, 1, 2, -1, 2147483647, 1, 2, -1,
        2147483647, 2147483646, 46340, 65536,
    ],
    [-1, 0, 1, 2, -1, 0, 1, 2, -1, 0, 1, 2, -1, 0, 1, 2],
    [-7, 5, -46341, 46340, 3, -2, -46341, 46340, -7, -2, -46341, 46340, 3, 5, -46341, 46340],
    [
        -2147483648, 2147483647, -2147483648, 2147483647, -1, -1, 1, 1, -2147483648, -1,
        -2147483648, 1, -1, 2147483647, 1, 2147483647,
    ],
    [
        0, 0, 0, 0, -2147483648, 2147483647, 65536, -65536, -2147483648, 0, 0, -65536, 0,
        2147483647, 65536, 0,
    ],
    [
        65536, -65536, 65536, -65536, 65536, 65536, -65536, -65536, 65536, -65536, -65536, -65536,
        65536, 65536, 65536, -65536,
    ],
    [1, 2, 5, -1, -5, 7, -2147483648, -2147483647, -5, 2, -2147483648, -2147483647, 1, 7, 5, -1],
];

#[test]
fn test_min_max() {
    for row in MIN_MAX.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).min(vc(r, 4)), vc(r, 8));
        assert_eq!(vc(r, 4).min(vc(r, 0)), vc(r, 8));
        assert_eq!(vc(r, 0).max(vc(r, 4)), vc(r, 12));
        assert_eq!(vc(r, 4).max(vc(r, 0)), vc(r, 12));
    }
}

const MIN_MAX_POSITION_ELEMENT: [[i64; 8]; 10] = [
    [1, 2, 3, 4, 0, 3, 1, 4], [1, 1, 1, 1, 0, 0, 1, 1], [4, 3, 2, 1, 3, 0, 1, 4],
    [1, 2, 1, 2, 0, 1, 1, 2], [1, 0, 1, 0, 1, 0, 0, 1], [2, 2, 1, 1, 2, 0, 1, 2],
    [3, 3, 3, 4, 0, 3, 3, 4], [-2147483648, -2147483647, -65536, -46341, 0, 3, -2147483648, -46341],
    [2147483647, 2147483646, 46340, 65536, 2, 0, 46340, 2147483647], [-1, 0, 1, 2, 0, 3, -1, 2],
];

#[test]
fn test_min_max_position_element() {
    for row in MIN_MAX_POSITION_ELEMENT.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).min_position(), us(r, 4));
        assert_eq!(vc(r, 0).max_position(), us(r, 5));
        assert_eq!(vc(r, 0).min_element(), sc(r, 6));
        assert_eq!(vc(r, 0).max_element(), sc(r, 7));
    }
}

const CLAMP: [[i64; 16]; 7] = [
    [0, 0, 0, 0, 1, 3, 3, 2, 6, 8, 8, 9, 1, 3, 3, 2],
    [5, 5, 5, 5, 1, 3, 3, 2, 6, 8, 8, 9, 5, 5, 5, 5],
    [9, 9, 9, 9, 1, 3, 3, 2, 6, 8, 8, 9, 6, 8, 8, 9],
    [0, 4, 7, 10, 1, 3, 3, 2, 6, 8, 8, 9, 1, 4, 7, 9],
    [-2147483648, -2147483648, -2147483648, -2147483648, 1, 3, 3, 2, 6, 8, 8, 9, 1, 3, 3, 2],
    [2147483647, 2147483647, 2147483647, 2147483647, 1, 3, 3, 2, 6, 8, 8, 9, 6, 8, 8, 9],
    [
        1, 3, 3, 2, -2147483648, -2147483648, -2147483648, -2147483648, 2147483647, 2147483647,
        2147483647, 2147483647, 1, 3, 3, 2,
    ],
];

#[test]
fn test_clamp() {
    for row in CLAMP.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).clamp(vc(r, 4), vc(r, 8)), vc(r, 12));
    }
}

const SUM_PRODUCT: [[i64; 6]; 5] = [
    [1, 2, 3, 4, 10, 24], [3, -7, 11, -13, -6, 3003], [-1, -2, -3, -4, -10, 24],
    [0, 1, -1, 2, 2, 0], [-1, -1, -1, -1, -4, 1],
];

#[test]
fn test_sum_product() {
    for row in SUM_PRODUCT.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).element_sum(), sc(r, 4));
        assert_eq!(vc(r, 0).element_product(), sc(r, 5));
    }
}

const CMP: [[i64; 32]; 8] = [
    [
        -2147483648, -2147483647, -65536, -46341, 2147483647, 2147483646, 65536, 46340, 0, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
    ],
    [
        2147483647, 2147483646, 46340, 65536, 2147483647, 1, 2, -1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
    ],
    [
        -1, 0, 1, 2, -1, 0, 1, 2, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
        0, 0,
    ],
    [
        -7, 5, -46341, 46340, 3, -2, -46341, 46340, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
        1, 0, 1, 1, 1, 0, 0, 0,
    ],
    [
        -2147483648, 2147483647, -2147483648, 2147483647, -1, -1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
        1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
    ],
    [
        0, 0, 0, 0, -2147483648, 2147483647, 65536, -65536, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
        0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
    ],
    [
        65536, -65536, 65536, -65536, 65536, 65536, -65536, -65536, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
        1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
    ],
    [
        1, 2, 5, -1, -5, 7, -2147483648, -2147483647, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
        1, 0, 1, 0, 0, 0, 1, 0, 0,
    ],
];

#[test]
fn test_cmp() {
    for row in CMP.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).cmpeq(vc(r, 4)), bv(r, 8));
        assert_eq!(vc(r, 0).cmpne(vc(r, 4)), bv(r, 12));
        assert_eq!(vc(r, 0).cmpge(vc(r, 4)), bv(r, 16));
        assert_eq!(vc(r, 0).cmpgt(vc(r, 4)), bv(r, 20));
        assert_eq!(vc(r, 0).cmple(vc(r, 4)), bv(r, 24));
        assert_eq!(vc(r, 0).cmplt(vc(r, 4)), bv(r, 28));
    }
}

#[test]
fn test_cmp_all_any() {
    let a = ivec4(1, 1, 1, 1);
    let b = ivec4(2, 2, 2, 2);
    assert!(a.cmplt(b).all() && a.cmple(b).all() && b.cmpgt(a).all() && b.cmpge(a).all());
    assert!(a.cmpne(b).all() && a.cmpeq(a).all() && !a.cmpeq(b).any() && !a.cmplt(a).any());
    assert!(a == a && a != b);
}

#[test]
fn test_neg() {
    assert_eq!(-ivec4(1, 2, 3, 4), ivec4(-1, -2, -3, -4));
    assert_eq!(-IVec4Trait::ZERO, IVec4Trait::ZERO);
    assert_eq!(-IVec4Trait::MAX, ivec4(-2147483647, -2147483647, -2147483647, -2147483647));
    assert_eq!(-IVec4Trait::ONE, IVec4Trait::NEG_ONE);
}

const IS_NEGATIVE: [[i64; 9]; 8] = [
    [1, 2, 3, 4, 0, 0, 0, 0, 0], [-1, -2, -3, -4, 15, 1, 1, 1, 1], [-1, 2, 3, 4, 1, 1, 0, 0, 0],
    [1, -2, 3, 4, 2, 0, 1, 0, 0], [1, 2, -3, 4, 4, 0, 0, 1, 0], [1, 2, 3, -4, 8, 0, 0, 0, 1],
    [-1, 2, -3, 4, 5, 1, 0, 1, 0], [1, -2, 3, -4, 10, 0, 1, 0, 1],
];

#[test]
fn test_is_negative() {
    for row in IS_NEGATIVE.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).is_negative_bitmask(), su(r, 4));
        assert_eq!(vc(r, 0).is_negative_mask(), bv(r, 5));
    }
}

const ABS_SIGNUM: [[i64; 12]; 4] = [
    [0, 1, -1, 2, 0, 1, 1, 2, 0, 1, -1, 1],
    [2147483647, -2147483647, 65536, -65536, 2147483647, 2147483647, 65536, 65536, 1, -1, 1, -1],
    [-7, 5, -46341, 46340, 7, 5, 46341, 46340, -1, 1, -1, 1],
    [-2147483647, 2147483646, 2, -3, 2147483647, 2147483646, 2, 3, -1, 1, 1, -1],
];

#[test]
fn test_abs_signum() {
    for row in ABS_SIGNUM.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).abs(), vc(r, 4));
        assert_eq!(vc(r, 0).signum(), vc(r, 8));
    }
}

#[test]
fn test_signum_extremes() {
    assert_eq!(IVec4Trait::MIN.signum(), IVec4Trait::NEG_ONE);
    assert_eq!(IVec4Trait::MAX.signum(), IVec4Trait::ONE);
    assert_eq!(IVec4Trait::NEG_ONE.abs(), IVec4Trait::ONE);
}

const DIV_REM: [[i64; 24]; 8] = [
    [3, -3, 3, -3, 2, 2, -2, -2, 1, -1, -1, 1, 1, -1, 1, -1, 1, -2, -1, 2, 1, 1, 1, 1],
    [4, -4, 4, -4, 3, 3, -3, -3, 1, -1, -1, 1, 1, -1, 1, -1, 1, -2, -1, 2, 1, 2, 1, 2],
    [
        -2147483648, -2147483647, -65536, -46341, 2147483647, 2147483646, 65536, 46340, -1, -1, -1,
        -1, -1, -1, 0, -1, -2, -2, -1, -2, 2147483646, 2147483645, 0, 46339,
    ],
    [
        2147483647, 2147483646, 46340, 65536, 2147483647, 1, 2, -1, 1, 2147483646, 23170, -65536, 0,
        0, 0, 0, 1, 2147483646, 23170, -65536, 0, 0, 0, 0,
    ],
    [-1, 0, 1, 2, -1, 3, 1, 2, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0],
    [
        -7, 5, -46341, 46340, 3, -2, -46341, 46340, -2, -2, 1, 1, -1, 1, 0, 0, -3, -2, 1, 1, 2, 1,
        0, 0,
    ],
    [
        -2147483648, 2147483647, 2147483647, -2147483648, -2147483648, -2147483648, 2147483647, 1,
        1, 0, 1, -2147483648, 0, 2147483647, 0, 0, 1, 0, 1, -2147483648, 0, 2147483647, 0, 0,
    ],
    [
        2147483647, -2147483647, 5, -2147483647, -2, 2147483647, -2147483647, 7, -1073741823, -1, 0,
        -306783378, 1, 0, 5, -1, -1073741823, -1, 0, -306783379, 1, 0, 5, 6,
    ],
];

#[test]
fn test_div_rem() {
    for row in DIV_REM.span() {
        let r = row.span();
        assert_eq!(vc(r, 0) / vc(r, 4), vc(r, 8));
        assert_eq!(vc(r, 0) % vc(r, 4), vc(r, 12));
        assert_eq!(vc(r, 0).wrapping_div(vc(r, 4)), vc(r, 8));
        assert_eq!(vc(r, 0).saturating_div(vc(r, 4)), vc(r, 8));
        assert_eq!(vc(r, 0).checked_div(vc(r, 4)), Some(vc(r, 8)));
        assert_eq!(vc(r, 0).div_euclid(vc(r, 4)), vc(r, 16));
        assert_eq!(vc(r, 0).rem_euclid(vc(r, 4)), vc(r, 20));
    }
}

const CHECKED_DIV: [[i64; 13]; 8] = [
    [
        -2147483648, -2147483647, -65536, -46341, 2147483647, 2147483646, 65536, 46340, 1, -1, -1,
        -1, -1,
    ],
    [2147483647, 2147483646, 46340, 65536, 2147483647, 0, 2, -1, 0, 0, 0, 0, 0],
    [-1, 0, 1, 2, -1, 0, 1, 2, 0, 0, 0, 0, 0],
    [-7, 5, -46341, 46340, 3, -2, -46341, 46340, 1, -2, -2, 1, 1],
    [-2147483648, 2147483647, -2147483648, 2147483647, -1, -1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, -2147483648, 2147483647, 65536, -65536, 1, 0, 0, 0, 0],
    [65536, -65536, 65536, -65536, 65536, 65536, 0, -65536, 0, 0, 0, 0, 0],
    [1, 2, 5, -1, -5, 7, -2147483648, -2147483647, 1, 0, 0, 0, 0],
];

#[test]
fn test_checked_div() {
    for row in CHECKED_DIV.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).checked_div(vc(r, 4)), opt(r, 8));
    }
}

#[test]
fn test_div_extremes() {
    assert_eq!(IVec4Trait::MIN.wrapping_div(IVec4Trait::NEG_ONE), IVec4Trait::MIN);
    assert_eq!(IVec4Trait::MIN.saturating_div(IVec4Trait::NEG_ONE), IVec4Trait::MAX);
    assert_eq!(
        IVec4Trait::MAX.checked_div(IVec4Trait::NEG_ONE),
        Some(ivec4(-2147483647, -2147483647, -2147483647, -2147483647)),
    );
    assert_eq!(IVec4Trait::MIN.rem_euclid(IVec4Trait::NEG_ONE), IVec4Trait::ZERO);
}

const WRAPPING_SATURATING_CHECKED: [[i64; 47]; 8] = [
    [
        -2147483648, -2147483647, -65536, -46341, 2147483647, 2147483646, 65536, 46340, -1, -1, 0,
        -1, -1, -1, 0, -1, 1, -1, -1, 0, -1, 1, 3, -131072, -92681, -2147483648, -2147483648,
        -131072, -92681, 0, 0, 0, 0, 0, -2147483648, 2147483646, 0, -2147441940, -2147483648,
        -2147483648, -2147483648, -2147441940, 0, 0, 0, 0, 0,
    ],
    [
        2147483647, 2147483646, 46340, 65536, 2147483647, 1, 2, -1, -2, 2147483647, 46342, 65535,
        2147483647, 2147483647, 46342, 65535, 0, 0, 0, 0, 0, 0, 2147483645, 46338, 65537, 0,
        2147483645, 46338, 65537, 1, 0, 2147483645, 46338, 65537, 1, 2147483646, 92680, -65536,
        2147483647, 2147483646, 92680, -65536, 0, 0, 0, 0, 0,
    ],
    [
        -1, 0, 1, 2, -1, 0, 1, 2, -2, 0, 2, 4, -2, 0, 2, 4, 1, -2, 0, 2, 4, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 1, 4, 1, 0, 1, 4, 1, 1, 0, 1, 4,
    ],
    [
        -7, 5, -46341, 46340, 3, -2, -46341, 46340, -4, 3, -92682, 92680, -4, 3, -92682, 92680, 1,
        -4, 3, -92682, 92680, -10, 7, 0, 0, -10, 7, 0, 0, 1, -10, 7, 0, 0, -21, -10, -2147479015,
        2147395600, -21, -10, 2147483647, 2147395600, 0, 0, 0, 0, 0,
    ],
    [
        -2147483648, 2147483647, -2147483648, 2147483647, -1, -1, 1, 1, 2147483647, 2147483646,
        -2147483647, -2147483648, -2147483648, 2147483646, -2147483647, 2147483647, 0, 0, 0, 0, 0,
        -2147483647, -2147483648, 2147483647, 2147483646, -2147483647, 2147483647, -2147483648,
        2147483646, 0, 0, 0, 0, 0, -2147483648, -2147483647, -2147483648, 2147483647, 2147483647,
        -2147483647, -2147483648, 2147483647, 0, 0, 0, 0, 0,
    ],
    [
        0, 0, 0, 0, -2147483648, 2147483647, 65536, -65536, -2147483648, 2147483647, 65536, -65536,
        -2147483648, 2147483647, 65536, -65536, 1, -2147483648, 2147483647, 65536, -65536,
        -2147483648, -2147483647, -65536, 65536, 2147483647, -2147483647, -65536, 65536, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
    ],
    [
        65536, -65536, 65536, -65536, 65536, 65536, -65536, -65536, 131072, 0, 0, -131072, 131072,
        0, 0, -131072, 1, 131072, 0, 0, -131072, 0, -131072, 131072, 0, 0, -131072, 131072, 0, 1, 0,
        -131072, 131072, 0, 0, 0, 0, 0, 2147483647, -2147483648, -2147483648, 2147483647, 0, 0, 0,
        0, 0,
    ],
    [
        1, 2, 5, -1, -5, 7, -2147483648, -2147483647, -4, 9, -2147483643, -2147483648, -4, 9,
        -2147483643, -2147483648, 1, -4, 9, -2147483643, -2147483648, 6, -5, -2147483643,
        2147483646, 6, -5, 2147483647, 2147483646, 0, 0, 0, 0, 0, -5, 14, -2147483648, 2147483647,
        -5, 14, -2147483648, 2147483647, 0, 0, 0, 0, 0,
    ],
];

#[test]
fn test_wrapping_saturating_checked() {
    for row in WRAPPING_SATURATING_CHECKED.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).wrapping_add(vc(r, 4)), vc(r, 8));
        assert_eq!(vc(r, 0).saturating_add(vc(r, 4)), vc(r, 12));
        assert_eq!(vc(r, 0).checked_add(vc(r, 4)), opt(r, 16));
        assert_eq!(vc(r, 0).wrapping_sub(vc(r, 4)), vc(r, 21));
        assert_eq!(vc(r, 0).saturating_sub(vc(r, 4)), vc(r, 25));
        assert_eq!(vc(r, 0).checked_sub(vc(r, 4)), opt(r, 29));
        assert_eq!(vc(r, 0).wrapping_mul(vc(r, 4)), vc(r, 34));
        assert_eq!(vc(r, 0).saturating_mul(vc(r, 4)), vc(r, 38));
        assert_eq!(vc(r, 0).checked_mul(vc(r, 4)), opt(r, 42));
    }
}

const UNSIGNED_OPS: [[i64; 34]; 8] = [
    [
        -2147483648, -2147483647, -65536, -46341, 65536, 65535, 3, 2, -2147418112, -2147418112,
        -65533, -46339, -2147418112, -2147418112, -65533, -46339, 1, -2147418112, -2147418112,
        -65533, -46339, 2147418112, 2147418114, -65539, -46343, -2147483648, -2147483648, -65539,
        -46343, 0, 0, 0, 0, 0,
    ],
    [
        2147483647, 2147483646, 46340, 65536, 1, 2, 65536, 4294967295, -2147483648, -2147483648,
        111876, 65535, 2147483647, 2147483647, 111876, 2147483647, 0, 0, 0, 0, 0, 2147483646,
        2147483644, -19196, 65537, 2147483646, 2147483644, -19196, -2147483648, 0, 0, 0, 0, 0,
    ],
    [
        -1, 0, 1, 2, 4294967295, 2147483648, 65536, 1, -2, -2147483648, 65537, 3, 2147483647,
        2147483647, 65537, 3, 0, 0, 0, 0, 0, 0, -2147483648, -65535, 1, -2147483648, -2147483648,
        -65535, 1, 0, 0, 0, 0, 0,
    ],
    [
        -7, 5, -46341, 46340, 2147483648, 2147483649, 65535, 65536, 2147483641, -2147483642, 19194,
        111876, 2147483641, 2147483647, 19194, 111876, 0, 0, 0, 0, 0, 2147483641, -2147483644,
        -111876, -19196, -2147483648, -2147483644, -111876, -19196, 0, 0, 0, 0, 0,
    ],
    [
        -2147483648, 2147483647, -2147483648, 2147483647, 13, 2, 1, 0, -2147483635, -2147483647,
        -2147483647, 2147483647, -2147483635, 2147483647, -2147483647, 2147483647, 0, 0, 0, 0, 0,
        2147483635, 2147483645, 2147483647, 2147483647, -2147483648, 2147483645, -2147483648,
        2147483647, 0, 0, 0, 0, 0,
    ],
    [
        0, 0, 0, 0, 4294967295, 4294967294, 2147483648, 2147483649, -1, -2, -2147483648,
        -2147483647, 2147483647, 2147483647, 2147483647, 2147483647, 0, 0, 0, 0, 0, 1, 2,
        -2147483648, 2147483647, -2147483648, -2147483648, -2147483648, -2147483648, 0, 0, 0, 0, 0,
    ],
    [
        65536, -65536, 65536, -65536, 4294967295, 1, 2, 65536, 65535, -65535, 65538, 0, 2147483647,
        -65535, 65538, 0, 0, 0, 0, 0, 0, 65537, -65537, 65534, -131072, -2147483648, -65537, 65534,
        -131072, 0, 0, 0, 0, 0,
    ],
    [
        2147483647, -2147483648, 0, -2147483648, 1, 1, 1, 4294967295, -2147483648, -2147483647, 1,
        2147483647, 2147483647, -2147483647, 1, 2147483647, 0, 0, 0, 0, 0, 2147483646, 2147483647,
        -1, -2147483647, 2147483646, -2147483648, -1, -2147483648, 0, 0, 0, 0, 0,
    ],
];

#[test]
fn test_unsigned_ops() {
    for row in UNSIGNED_OPS.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).wrapping_add_unsigned(vo(r, 4)), vc(r, 8));
        assert_eq!(vc(r, 0).saturating_add_unsigned(vo(r, 4)), vc(r, 12));
        assert_eq!(vc(r, 0).checked_add_unsigned(vo(r, 4)), opt(r, 16));
        assert_eq!(vc(r, 0).wrapping_sub_unsigned(vo(r, 4)), vc(r, 21));
        assert_eq!(vc(r, 0).saturating_sub_unsigned(vo(r, 4)), vc(r, 25));
        assert_eq!(vc(r, 0).checked_sub_unsigned(vo(r, 4)), opt(r, 29));
    }
}

const DISTANCES: [[i64; 11]; 10] = [
    [
        -2147483648, -2147483647, -65536, -46341, 2147483647, 2147483646, 65536, 46340, 0, 0,
        4294967295,
    ],
    [2147483647, 2147483646, 46340, 65536, 2147483647, 1, 2, -1, 1, 2147595520, 2147483645],
    [-1, 0, 1, 2, -1, 0, 1, 2, 1, 0, 0], [-7, 5, -46341, 46340, 3, -2, -46341, 46340, 1, 17, 10],
    [-2147483648, 2147483647, -2147483648, 2147483647, -1, -1, 1, 1, 0, 0, 2147483649],
    [0, 0, 0, 0, -2147483648, 2147483647, 65536, -65536, 0, 0, 2147483648],
    [65536, -65536, 65536, -65536, 65536, 65536, -65536, -65536, 1, 262144, 131072],
    [1, 2, 5, -1, -5, 7, -2147483648, -2147483647, 0, 0, 2147483653],
    [3, 27, 98, 5, 20, 65, 97, 9, 1, 60, 38], [-23, 2, -99, 4, 22, -12, 24, -4, 1, 190, 123],
];

#[test]
fn test_distances() {
    for row in DISTANCES.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).checked_manhattan_distance(vc(r, 4)), optu(r, 8));
        if let Some(d) = optu(r, 8) {
            assert_eq!(vc(r, 0).manhattan_distance(vc(r, 4)), d);
        }
        assert_eq!(vc(r, 0).chebyshev_distance(vc(r, 4)), su(r, 10));
    }
}

const CASTS: [[i64; 13]; 8] = [
    [
        -2147483648, -2147483647, -65536, -46341, 2147483648, 2147483649, 4294901760, 4294920955, 0,
        0, 0, 0, 0,
    ],
    [
        2147483647, 2147483646, 46340, 65536, 2147483647, 2147483646, 46340, 65536, 1, 2147483647,
        2147483646, 46340, 65536,
    ],
    [-1, 0, 1, 2, 4294967295, 0, 1, 2, 0, 0, 0, 0, 0],
    [-7, 5, -46341, 46340, 4294967289, 5, 4294920955, 46340, 0, 0, 0, 0, 0],
    [
        -2147483648, 2147483647, -2147483648, 2147483647, 2147483648, 2147483647, 2147483648,
        2147483647, 0, 0, 0, 0, 0,
    ],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [65536, -65536, 65536, -65536, 65536, 4294901760, 65536, 4294901760, 0, 0, 0, 0, 0],
    [1, 2, 5, -1, 1, 2, 5, 4294967295, 0, 0, 0, 0, 0],
];

#[test]
fn test_casts() {
    for row in CASTS.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).as_uvec4(), vo(r, 4));
        assert_eq!(vo(r, 4).as_ivec4(), vc(r, 0));
        let res: Option<UVec4> = vc(r, 0).try_into();
        assert_eq!(res, opto(r, 8));
    }
}

const BIT_OPS: [[i64; 24]; 8] = [
    [
        -2147483648, -2147483647, -65536, -46341, 2147483647, 2147483646, 65536, 46340, 0, 0, 65536,
        0, -1, -1, -65536, -1, -1, -1, -131072, -1, 2147483647, 2147483646, 65535, 46340,
    ],
    [
        2147483647, 2147483646, 46340, 65536, 2147483647, 1, 2, -1, 2147483647, 0, 0, 65536,
        2147483647, 2147483647, 46342, -1, 0, 2147483647, 46342, -65537, -2147483648, -2147483647,
        -46341, -65537,
    ],
    [-1, 0, 1, 2, -1, 0, 1, 2, -1, 0, 1, 2, -1, 0, 1, 2, 0, 0, 0, 0, 0, -1, -2, -3],
    [
        -7, 5, -46341, 46340, 3, -2, -46341, 46340, 1, 4, -46341, 46340, -5, -1, -46341, 46340, -6,
        -5, 0, 0, 6, -6, 46340, -46341,
    ],
    [
        -2147483648, 2147483647, -2147483648, 2147483647, -1, -1, 1, 1, -2147483648, 2147483647, 0,
        1, -1, -1, -2147483647, 2147483647, 2147483647, -2147483648, -2147483647, 2147483646,
        2147483647, -2147483648, 2147483647, -2147483648,
    ],
    [
        0, 0, 0, 0, -2147483648, 2147483647, 65536, -65536, 0, 0, 0, 0, -2147483648, 2147483647,
        65536, -65536, -2147483648, 2147483647, 65536, -65536, -1, -1, -1, -1,
    ],
    [
        65536, -65536, 65536, -65536, 65536, 65536, -65536, -65536, 65536, 65536, 65536, -65536,
        65536, -65536, -65536, -65536, 0, -131072, -131072, 0, -65537, 65535, -65537, 65535,
    ],
    [
        1, 2, 5, -1, -5, 7, -2147483648, -2147483647, 1, 2, 0, -2147483647, -5, 7, -2147483643, -1,
        -6, 5, -2147483643, 2147483646, -2, -3, -6, 0,
    ],
];

#[test]
fn test_bit_ops() {
    for row in BIT_OPS.span() {
        let r = row.span();
        assert_eq!(vc(r, 0) & vc(r, 4), vc(r, 8));
        assert_eq!(vc(r, 0) | vc(r, 4), vc(r, 12));
        assert_eq!(vc(r, 0) ^ vc(r, 4), vc(r, 16));
        assert_eq!(~vc(r, 0), vc(r, 20));
    }
}

const SHIFTS: [[i64; 13]; 8] = [
    [
        -2147483648, -2147483647, -65536, -46341, 0, -2147483648, -2147483647, -65536, -46341,
        -2147483648, -2147483647, -65536, -46341,
    ],
    [
        2147483647, 2147483646, 46340, 65536, 1, -2, -4, 92680, 131072, 1073741823, 1073741823,
        23170, 32768,
    ],
    [-1, 0, 1, 2, 2, -4, 0, 4, 8, -1, 0, 0, 0],
    [-7, 5, -46341, 46340, 5, -224, 160, -1482912, 1482880, -1, 0, -1449, 1448],
    [
        -2147483648, 2147483647, -2147483648, 2147483647, 15, 0, -32768, 0, -32768, -65536, 65535,
        -65536, 65535,
    ],
    [0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0],
    [65536, -65536, 65536, -65536, 30, 0, 0, 0, 0, 0, -1, 0, -1],
    [1, 2, 5, -1, 31, -2147483648, 0, -2147483648, -2147483648, 0, 0, 0, -1],
];

#[test]
fn test_shifts() {
    for row in SHIFTS.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).shl(su(r, 4)), vc(r, 5));
        assert_eq!(vc(r, 0).shr(su(r, 4)), vc(r, 9));
    }
}

#[test]
fn test_hash_serde() {
    let a = ivec4(1, 2, 3, 4);
    let b = ivec4(4, 3, 2, 1);
    assert_eq!(hash(a), hash(a));
    assert!(hash(a) != hash(b));
    let mut out = array![];
    a.serialize(ref out);
    assert_eq!(out.len(), 4);
    let mut span = out.span();
    assert_eq!(Serde::<IVec4>::deserialize(ref span), Some(a));
}

#[test]
#[should_panic(expected: 'i32_add Overflow')]
fn test_add_overflow() {
    let _ = IVec4Trait::MAX + IVec4Trait::X;
}

#[test]
#[should_panic(expected: 'i32_add Overflow')]
fn test_add_scalar_overflow() {
    let _ = IVec4Trait::MAX.add_scalar(1);
}

#[test]
#[should_panic(expected: 'i32_add Underflow')]
fn test_add_underflow() {
    let _ = IVec4Trait::MIN + IVec4Trait::NEG_X;
}

#[test]
#[should_panic(expected: 'i32_sub Underflow')]
fn test_sub_underflow() {
    let _ = IVec4Trait::MIN - IVec4Trait::X;
}

#[test]
#[should_panic(expected: 'i32_sub Overflow')]
fn test_sub_overflow() {
    let _ = IVec4Trait::MAX - IVec4Trait::NEG_X;
}

#[test]
#[should_panic(expected: 'i32_neg Underflow')]
fn test_neg_overflow() {
    let _ = -IVec4Trait::MIN;
}

#[test]
#[should_panic(expected: 'i32_neg Underflow')]
fn test_abs_overflow() {
    let _ = IVec4Trait::MIN.abs();
}

#[test]
#[should_panic(expected: 'attempt to divide with overflow')]
fn test_div_overflow() {
    let _ = IVec4Trait::MIN / IVec4Trait::NEG_ONE;
}

#[test]
#[should_panic(expected: 'attempt to divide with overflow')]
fn test_rem_overflow() {
    let _ = IVec4Trait::MIN % IVec4Trait::NEG_ONE;
}

#[test]
#[should_panic(expected: 'attempt to divide with overflow')]
fn test_div_scalar_overflow() {
    let _ = IVec4Trait::MIN.div_scalar(-1);
}

#[test]
#[should_panic(expected: 'attempt to divide with overflow')]
fn test_div_euclid_overflow() {
    let _ = IVec4Trait::MIN.div_euclid(IVec4Trait::NEG_ONE);
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_div_euclid_by_zero() {
    let _ = IVec4Trait::ONE.div_euclid(IVec4Trait::X);
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_rem_euclid_by_zero() {
    let _ = IVec4Trait::ONE.rem_euclid(IVec4Trait::X);
}

#[test]
#[should_panic(expected: 'IVec4: overflow')]
fn test_distance_squared_overflow() {
    let _ = IVec4Trait::MAX.distance_squared(IVec4Trait::MIN);
}

#[test]
#[should_panic(expected: 'i32_mul Overflow')]
fn test_mul_overflow() {
    let _ = IVec4Trait::MAX * ivec4(2, 2, 2, 2);
}

#[test]
#[should_panic(expected: 'i32_mul Overflow')]
fn test_mul_scalar_overflow() {
    let _ = IVec4Trait::MAX.mul_scalar(2);
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_div_by_zero() {
    let _ = IVec4Trait::ONE / IVec4Trait::X;
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_rem_by_zero() {
    let _ = IVec4Trait::ONE % IVec4Trait::X;
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_div_scalar_by_zero() {
    let _ = IVec4Trait::ONE.div_scalar(0);
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_rem_scalar_by_zero() {
    let _ = IVec4Trait::ONE.rem_scalar(0);
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_wrapping_div_by_zero() {
    let _ = IVec4Trait::ONE.wrapping_div(IVec4Trait::X);
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_saturating_div_by_zero() {
    let _ = IVec4Trait::ONE.saturating_div(IVec4Trait::X);
}

#[test]
#[should_panic(expected: 'IVec4: overflow')]
fn test_dot_overflow() {
    let _ = IVec4Trait::MAX.dot(IVec4Trait::MAX);
}

#[test]
#[should_panic(expected: 'IVec4: overflow')]
fn test_dot_into_vec_overflow() {
    let _ = IVec4Trait::MAX.dot_into_vec(IVec4Trait::MAX);
}

#[test]
#[should_panic(expected: 'IVec4: overflow')]
fn test_length_squared_overflow() {
    let _ = IVec4Trait::MAX.length_squared();
}

#[test]
#[should_panic(expected: 'IVec4: overflow')]
fn test_element_sum_overflow() {
    let _ = IVec4Trait::MAX.element_sum();
}

#[test]
#[should_panic(expected: 'IVec4: overflow')]
fn test_element_product_overflow() {
    let _ = IVec4Trait::MAX.element_product();
}

#[test]
#[should_panic(expected: 'IVec4: overflow')]
fn test_manhattan_distance_overflow() {
    let _ = IVec4Trait::MIN.manhattan_distance(IVec4Trait::MAX);
}

#[test]
#[should_panic(expected: 'IVec4: shift overflow')]
fn test_shl_overflow() {
    let _ = IVec4Trait::ONE.shl(32);
}

#[test]
#[should_panic(expected: 'IVec4: shift overflow')]
fn test_shr_overflow() {
    let _ = IVec4Trait::ONE.shr(32);
}

#[test]
fn test_fused_kernels_check_the_result_only() {
    assert_eq!(ivec4(2147483647, 2147483647, 5, 5).dot(ivec4(2, -2, 1, 1)), 10);
    assert_eq!(ivec4(2147483647, 7, -2147483648, 1).element_sum(), 7);
    assert_eq!(ivec4(2147483647, 2, 0, 1).element_product(), 0);
}

#[test]
#[fuzzer(runs: 256, seed: 4001)]
fn fuzz_wrapping_checked_saturating(a: i32, b: i32, c: i32, d: i32) {
    let va = ivec4(a, b, a, b);
    let vb = ivec4(c, d, a, c);
    let exact = [wide(a) + wide(c), wide(b) + wide(d), wide(a) + wide(a), wide(b) + wide(c)];
    assert_eq!(va.wrapping_add(vb).to_array(), map_wrap(exact));
    assert_eq!(va.saturating_add(vb).to_array(), map_sat(exact));
    assert_eq!(va.checked_add(vb), map_checked(exact));
    let exact = [wide(a) - wide(c), wide(b) - wide(d), wide(a) - wide(a), wide(b) - wide(c)];
    assert_eq!(va.wrapping_sub(vb).to_array(), map_wrap(exact));
    assert_eq!(va.saturating_sub(vb).to_array(), map_sat(exact));
    assert_eq!(va.checked_sub(vb), map_checked(exact));
    let exact = [wide(a) * wide(c), wide(b) * wide(d), wide(a) * wide(a), wide(b) * wide(c)];
    assert_eq!(va.wrapping_mul(vb).to_array(), map_wrap(exact));
    assert_eq!(va.saturating_mul(vb).to_array(), map_sat(exact));
    assert_eq!(va.checked_mul(vb), map_checked(exact));
    // mixed signedness: the other-signedness operand is `vb` reinterpreted
    let ub = vb.as_uvec4();
    let [ux, uy, uz, uw] = ub.to_array();
    let exact = [
        wide(a) + wide_o(ux), wide(b) + wide_o(uy), wide(a) + wide_o(uz), wide(b) + wide_o(uw),
    ];
    assert_eq!(va.wrapping_add_unsigned(ub).to_array(), map_wrap(exact));
    assert_eq!(va.saturating_add_unsigned(ub).to_array(), map_sat(exact));
    assert_eq!(va.checked_add_unsigned(ub), map_checked(exact));
    let exact = [
        wide(a) - wide_o(ux), wide(b) - wide_o(uy), wide(a) - wide_o(uz), wide(b) - wide_o(uw),
    ];
    assert_eq!(va.wrapping_sub_unsigned(ub).to_array(), map_wrap(exact));
    assert_eq!(va.saturating_sub_unsigned(ub).to_array(), map_sat(exact));
    assert_eq!(va.checked_sub_unsigned(ub), map_checked(exact));
}

#[test]
#[fuzzer(runs: 256, seed: 4002)]
fn fuzz_min_max_clamp_select_cmp_distances(a: i32, b: i32, c: i32, d: i32) {
    let va = ivec4(a, b, a, b);
    let vb = ivec4(c, d, a, c);
    let lo = va.min(vb);
    let hi = va.max(vb);
    assert!(lo.cmple(hi).all());
    assert!(lo.cmple(va).all() && lo.cmple(vb).all());
    assert!(hi.cmpge(va).all() && hi.cmpge(vb).all());
    assert_eq!(IVec4Trait::select(va.cmplt(vb), va, vb), lo);
    assert_eq!(IVec4Trait::select(va.cmpgt(vb), va, vb), hi);
    assert_eq!(va.cmpeq(vb), !va.cmpne(vb));
    assert_eq!(va.cmpge(vb), !va.cmplt(vb));
    assert_eq!(va.cmple(vb), !va.cmpgt(vb));
    let vc = ivec4(d, a, c, d);
    assert_eq!(vc.clamp(lo, hi), vc.max(lo).min(hi));
    assert!(lo.min_element() <= lo.max_element());
    assert_eq!(va[va.min_position()], va.min_element());
    assert_eq!(va[va.max_position()], va.max_element());
    let d = [
        abs_wide(wide(a) - wide(c)), abs_wide(wide(b) - wide(d)), abs_wide(wide(a) - wide(a)),
        abs_wide(wide(b) - wide(c)),
    ];
    let [dx, dy, dz, dw] = d;
    let sum = dx + dy + dz + dw;
    let expected: Option<u32> = sum.try_into();
    assert_eq!(va.checked_manhattan_distance(vb), expected);
    assert_eq!(vb.checked_manhattan_distance(va), expected);
    let mut m = dx;
    if dy > m {
        m = dy;
    }
    if dz > m {
        m = dz;
    }
    if dw > m {
        m = dw;
    }
    assert_eq!(wide_u(va.chebyshev_distance(vb)), m);
}

#[test]
#[fuzzer(runs: 256, seed: 4004)]
fn fuzz_dot_casts_bits_shifts(a: i32, b: i32, c: i32, d: i32, k: u32) {
    // 14-bit operands: nothing overflows
    let va = ivec4(a / 0x40000, b / 0x40000, a / 0x40000, b / 0x40000);
    let vb = ivec4(c / 0x40000, d / 0x40000, a / 0x40000, c / 0x40000);
    let expected = wide(a / 0x40000) * wide(c / 0x40000)
        + wide(b / 0x40000) * wide(d / 0x40000)
        + wide(a / 0x40000) * wide(a / 0x40000)
        + wide(b / 0x40000) * wide(c / 0x40000);
    assert_eq!(wide(va.dot(vb)), expected);
    assert_eq!(va.dot(vb), vb.dot(va));
    assert_eq!(va.length_squared(), va.dot(va));
    assert_eq!(
        wide(va.element_sum()),
        wide(a / 0x40000) + wide(b / 0x40000) + wide(a / 0x40000) + wide(b / 0x40000),
    );
    let tiny = ivec4(a / 0x1000000, b / 0x1000000, a / 0x1000000, b / 0x1000000);
    assert_eq!(
        wide(tiny.element_product()),
        wide(a / 0x1000000) * wide(b / 0x1000000) * wide(a / 0x1000000) * wide(b / 0x1000000),
    );
    assert_eq!(
        wide(va.distance_squared(vb)),
        (wide(a / 0x40000) - wide(c / 0x40000)) * (wide(a / 0x40000) - wide(c / 0x40000))
            + (wide(b / 0x40000) - wide(d / 0x40000)) * (wide(b / 0x40000) - wide(d / 0x40000))
            + (wide(a / 0x40000) - wide(a / 0x40000)) * (wide(a / 0x40000) - wide(a / 0x40000))
            + (wide(b / 0x40000) - wide(c / 0x40000)) * (wide(b / 0x40000) - wide(c / 0x40000)),
    );
    let va = ivec4(a, b, a, b);
    let vb = ivec4(b, a, a, b);
    assert_eq!(va.as_uvec4().as_ivec4(), va);
    assert_eq!(wide_o(va.as_uvec4().x), wrap_o(wide(a)));
    // (a & b) + (a | b) == a + b and (a ^ b) + 2 * (a & b) == a + b
    assert_eq!(wide((va & vb).x) + wide((va | vb).x), wide(a) + wide(b));
    assert_eq!(wide((va ^ vb).x) + 2 * wide((va & vb).x), wide(a) + wide(b));
    assert_eq!((va ^ vb) ^ vb, va);
    assert_eq!(~(va & vb), ~va | ~vb);
    assert_eq!(wide((~va).x), -1 - wide(a));
    let k = k % 32;
    let p = pow2(k);
    assert_eq!(wide(va.shl(k).x), wrap(wide(a) * p));
    assert_eq!(wide(va.shr(k).x), floor_div(wide(a), p));
}

#[test]
#[fuzzer(runs: 256, seed: 4006)]
fn fuzz_div_euclid_rem_euclid_abs_signum(a: i32, b: i32, c: i32, d: i32) {
    let va = ivec4(a, b, a, b);
    let vb = ivec4(nz(c), nz(d), nz(a), nz(c));
    if !((a == -2147483648 && nz(c) == -1)
        || (b == -2147483648 && nz(d) == -1)
        || (a == -2147483648 && nz(a) == -1)
        || (b == -2147483648 && nz(c) == -1)) {
        let q = va.div_euclid(vb);
        let r = va.rem_euclid(vb);
        let tq = va / vb;
        let tr = va % vb;
        assert!(r.cmpge(IVec4Trait::ZERO).all());
        for i in 0..4_usize {
            assert!(wide(r[i]) < abs_wide(wide(vb[i])));
            assert_eq!(wide(q[i]) * wide(vb[i]) + wide(r[i]), wide(va[i]));
            assert_eq!(wide(tq[i]) * wide(vb[i]) + wide(tr[i]), wide(va[i]));
            assert!(abs_wide(wide(tr[i])) < abs_wide(wide(vb[i])));
            assert!(wide(tr[i]) == 0 || (tr[i] < 0) == (va[i] < 0));
        }
        assert_eq!(va.wrapping_div(vb), tq);
    }
    let a = if a == -2147483648 {
        0
    } else {
        a
    };
    let b = if b == -2147483648 {
        0
    } else {
        b
    };
    let va = ivec4(a, b, a, b);
    assert_eq!(va.signum() * va.abs(), va);
    assert_eq!((-va).abs(), va.abs());
    assert_eq!(-(-va), va);
    assert!(va.abs().cmpge(IVec4Trait::ZERO).all());
    assert_eq!(va.is_negative_mask(), va.cmplt(IVec4Trait::ZERO));
    assert_eq!(va.is_negative_bitmask(), va.is_negative_mask().bitmask());
}
