// GENERATED by tools/codegen/intvec.py - do not edit by hand.
//! Tests of `glam::uvec3`: the glam-rs integer vector test macros of `tests/vec3.rs`, tables over
//! a pool of edge values (expected values computed by the generator with Python integers, one
//! `const` table and one looping test per function group), seeded fuzz properties against the
//! `i128` reference below, and one test per panic path.

use core::hash::{HashStateExTrait, HashStateTrait};
use core::poseidon::PoseidonTrait;
use glam::bvec3::{BVec3, BVec3Trait, bvec3};
use glam::ivec3::{IVec3, IVec3Trait, ivec3};
use glam::uvec2::uvec2;
use glam::uvec3::{UVec3, UVec3Trait, uvec3};
use glam::uvec4::uvec4;

fn hash(v: UVec3) -> felt252 {
    PoseidonTrait::new().update_with(v).finalize()
}

// Readers of the table rows (`[i64; W]`, one cell per scalar): the value of a column at an offset.

fn sc(r: Span<i64>, o: u32) -> u32 {
    (*r[o]).try_into().unwrap()
}

fn su(r: Span<i64>, o: u32) -> u32 {
    (*r[o]).try_into().unwrap()
}

fn us(r: Span<i64>, o: u32) -> usize {
    (*r[o]).try_into().unwrap()
}

fn vc(r: Span<i64>, o: u32) -> UVec3 {
    uvec3(sc(r, o), sc(r, o + 1), sc(r, o + 2))
}

fn vo(r: Span<i64>, o: u32) -> IVec3 {
    ivec3(
        (*r[o]).try_into().unwrap(),
        (*r[o + 1]).try_into().unwrap(),
        (*r[o + 2]).try_into().unwrap(),
    )
}

fn bv(r: Span<i64>, o: u32) -> BVec3 {
    bvec3(*r[o] != 0, *r[o + 1] != 0, *r[o + 2] != 0)
}

fn opt(r: Span<i64>, o: u32) -> Option<UVec3> {
    if *r[o] == 0 {
        None
    } else {
        Some(vc(r, o + 1))
    }
}

fn opto(r: Span<i64>, o: u32) -> Option<IVec3> {
    if *r[o] == 0 {
        None
    } else {
        Some(vo(r, o + 1))
    }
}

fn optu(r: Span<i64>, o: u32) -> Option<u32> {
    if *r[o] == 0 {
        None
    } else {
        Some(su(r, o + 1))
    }
}

// The reference of the fuzz tests: exact arithmetic in `i128`, reduced to `u32` the way Rust does.

fn wide(v: u32) -> i128 {
    v.into()
}

fn wide_o(v: i32) -> i128 {
    v.into()
}

fn wide_u(v: u32) -> i128 {
    v.into()
}

fn abs_wide(v: i128) -> i128 {
    if v < 0 {
        -v
    } else {
        v
    }
}

/// Euclidean remainder of `v` by `2^32`.
fn low32(v: i128) -> i128 {
    let m: i128 = 0x100000000;
    ((v % m) + m) % m
}

/// Two's complement reduction to `u32`.
fn wrap(v: i128) -> i128 {
    let r = low32(v);
    r
}

/// Two's complement reduction to `i32`.
fn wrap_o(v: i128) -> i128 {
    let r = low32(v);
    if r >= 0x80000000 {
        r - 0x100000000
    } else {
        r
    }
}

fn sat(v: i128) -> i128 {
    if v < 0 {
        0
    } else if v > 4294967295 {
        4294967295
    } else {
        v
    }
}

fn narrow(v: i128) -> u32 {
    v.try_into().unwrap()
}

fn map_wrap(e: [i128; 3]) -> [u32; 3] {
    let [x, y, z] = e;
    [narrow(wrap(x)), narrow(wrap(y)), narrow(wrap(z))]
}

fn map_sat(e: [i128; 3]) -> [u32; 3] {
    let [x, y, z] = e;
    [narrow(sat(x)), narrow(sat(y)), narrow(sat(z))]
}

fn map_checked(e: [i128; 3]) -> Option<UVec3> {
    let [x, y, z] = e;
    if sat(x) == x && sat(y) == y && sat(z) == z {
        Some(UVec3 { x: narrow(x), y: narrow(y), z: narrow(z) })
    } else {
        None
    }
}

fn pow2(k: u32) -> i128 {
    let mut p: i128 = 1;
    for _ in 0..k {
        p *= 2;
    }
    p
}

/// `floor(a / p)` for `p > 0`.
fn floor_div(a: i128, p: i128) -> i128 {
    let r = ((a % p) + p) % p;
    (a - r) / p
}

/// A non-zero divisor.
fn nz(v: u32) -> u32 {
    if v == 0 {
        3
    } else {
        v
    }
}

#[test]
fn test_new() {
    let v = UVec3Trait::new(1, 2, 3);
    assert_eq!(v.x, 1);
    assert_eq!(v.y, 2);
    assert_eq!(v.z, 3);
    assert_eq!(v, uvec3(1, 2, 3));
    let t = (1_u32, 2_u32, 3_u32);
    let v: UVec3 = t.into();
    assert_eq!(v, uvec3(1, 2, 3));
    let t2: (u32, u32, u32) = v.into();
    assert_eq!(t2, t);
    let a = [1_u32, 2_u32, 3_u32];
    let v: UVec3 = a.into();
    assert_eq!(v, uvec3(1, 2, 3));
    assert_eq!(UVec3Trait::from_array(a), uvec3(1, 2, 3));
    let a2: [u32; 3] = v.into();
    assert_eq!(a2, a);
    assert_eq!(v.to_array(), a);
    assert_eq!(Default::<UVec3>::default(), UVec3Trait::ZERO);
}

#[test]
fn test_consts() {
    assert_eq!(UVec3Trait::ZERO, uvec3(0, 0, 0));
    assert_eq!(UVec3Trait::ONE, uvec3(1, 1, 1));
    assert_eq!(UVec3Trait::MIN, uvec3(0, 0, 0));
    assert_eq!(UVec3Trait::MAX, uvec3(4294967295, 4294967295, 4294967295));
    assert_eq!(UVec3Trait::X, uvec3(1, 0, 0));
    assert_eq!(UVec3Trait::Y, uvec3(0, 1, 0));
    assert_eq!(UVec3Trait::Z, uvec3(0, 0, 1));
    let [ax, ay, az] = UVec3Trait::AXES;
    assert_eq!(ax, UVec3Trait::X);
    assert_eq!(ay, UVec3Trait::Y);
    assert_eq!(az, UVec3Trait::Z);
}

#[test]
fn test_splat_with() {
    assert_eq!(UVec3Trait::splat(7), uvec3(7, 7, 7));
    assert_eq!(UVec3Trait::splat(0), UVec3Trait::MIN);
    assert_eq!(uvec3(1, 2, 3).with_x(9), uvec3(9, 2, 3));
    assert_eq!(uvec3(1, 2, 3).with_y(9), uvec3(1, 9, 3));
    assert_eq!(uvec3(1, 2, 3).with_z(9), uvec3(1, 2, 9));
}

#[test]
fn test_accessors() {
    let mut a = UVec3Trait::ZERO;
    a.x = 1;
    a.y = 2;
    a.z = 3;
    assert_eq!(a, uvec3(1, 2, 3));
    assert_eq!(a[0], 1);
    assert_eq!(a[1], 2);
    assert_eq!(a[2], 3);
}

#[test]
#[should_panic(expected: 'UVec3: index out of bounds')]
fn test_index_out_of_bounds() {
    let _ = uvec3(1, 2, 3)[3];
}

#[test]
fn test_extend_truncate() {
    assert_eq!(uvec3(1, 2, 3).extend(4), uvec4(1, 2, 3, 4));
    assert_eq!(uvec3(1, 2, 3).truncate(), uvec2(1, 2));
    let v: UVec3 = (uvec2(1, 2), 3_u32).into();
    assert_eq!(v, uvec3(1, 2, 3));
}

const SELECT: [[i64; 12]; 8] = [
    [0, 0, 0, 1, 2, 3, 5, 6, 7, 5, 6, 7], [1, 0, 0, 1, 2, 3, 5, 6, 7, 1, 6, 7],
    [0, 1, 0, 1, 2, 3, 5, 6, 7, 5, 2, 7], [1, 1, 0, 1, 2, 3, 5, 6, 7, 1, 2, 7],
    [0, 0, 1, 1, 2, 3, 5, 6, 7, 5, 6, 3], [1, 0, 1, 1, 2, 3, 5, 6, 7, 1, 6, 3],
    [0, 1, 1, 1, 2, 3, 5, 6, 7, 5, 2, 3], [1, 1, 1, 1, 2, 3, 5, 6, 7, 1, 2, 3],
];

#[test]
fn test_select() {
    for row in SELECT.span() {
        let r = row.span();
        assert_eq!(UVec3Trait::select(bv(r, 0), vc(r, 3), vc(r, 6)), vc(r, 9));
    }
}

#[test]
fn test_from_bvec() {
    let v: UVec3 = bvec3(true, false, true).into();
    assert_eq!(v, uvec3(1, 0, 1));
    let v: UVec3 = bvec3(false, true, false).into();
    assert_eq!(v, uvec3(0, 1, 0));
}

const DOT_LENGTH: [[i64; 8]; 5] = [
    [30, 7, 110, 5, 2, 9, 1154, 13049], [1, 2, 3, 4, 3, 2, 16, 14], [0, 1, 5, 7, 9, 7, 44, 26],
    [100, 200, 300, 9, 8, 7, 4600, 140000], [65535, 3, 1, 65535, 5, 1, 4294836241, 4294836235],
];

#[test]
fn test_dot_length() {
    for row in DOT_LENGTH.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).dot(vc(r, 3)), sc(r, 6));
        assert_eq!(vc(r, 0).dot_into_vec(vc(r, 3)), UVec3Trait::splat(sc(r, 6)));
        assert_eq!(vc(r, 0).length_squared(), sc(r, 7));
    }
}

const CROSS: [[i64; 9]; 5] = [
    [3, 0, 0, 2, 5, 0, 0, 0, 15], [0, 4, 0, 0, 0, 6, 24, 0, 0], [0, 0, 5, 7, 0, 0, 0, 35, 0],
    [5, 7, 0, 5, 7, 0, 0, 0, 0], [1, 2, 3, 1, 2, 3, 0, 0, 0],
];

#[test]
fn test_cross() {
    for row in CROSS.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).cross(vc(r, 3)), vc(r, 6));
    }
}

#[test]
fn test_dot_cross_axes() {
    assert_eq!(UVec3Trait::X.dot(UVec3Trait::X), 1);
    assert_eq!(UVec3Trait::X.dot(UVec3Trait::Y), 0);
    assert_eq!(UVec3Trait::X.cross(UVec3Trait::Y), UVec3Trait::Z);
    assert_eq!(UVec3Trait::Y.cross(UVec3Trait::Z), UVec3Trait::X);
    assert_eq!(UVec3Trait::Z.cross(UVec3Trait::X), UVec3Trait::Y);
}

const OPS: [[i64; 37]; 5] = [
    [
        30, 7, 110, 5, 2, 9, 7, 35, 9, 119, 25, 5, 101, 150, 14, 990, 6, 3, 12, 0, 1, 2, 37, 14,
        117, 23, 0, 103, 210, 49, 770, 4, 1, 15, 2, 0, 5,
    ],
    [
        4, 3, 3, 1, 2, 2, 3, 5, 5, 5, 3, 1, 1, 4, 6, 6, 4, 1, 1, 0, 1, 1, 7, 6, 6, 1, 0, 0, 12, 9,
        9, 1, 1, 1, 1, 0, 0,
    ],
    [
        7, 9, 7, 1, 1, 5, 7, 8, 10, 12, 6, 8, 2, 7, 9, 35, 7, 9, 1, 0, 0, 2, 14, 16, 14, 0, 2, 0,
        49, 63, 49, 1, 1, 1, 0, 2, 0,
    ],
    [
        100, 200, 300, 9, 8, 7, 100, 109, 208, 307, 91, 192, 293, 900, 1600, 2100, 11, 25, 42, 1, 0,
        6, 200, 300, 400, 0, 100, 200, 10000, 20000, 30000, 1, 2, 3, 0, 0, 0,
    ],
    [
        65535, 5, 1, 65535, 3, 1, 1, 131070, 8, 2, 0, 2, 0, 4294836225, 15, 1, 1, 1, 1, 0, 2, 0,
        65536, 6, 2, 65534, 4, 0, 65535, 5, 1, 65535, 5, 1, 0, 0, 0,
    ],
];

#[test]
fn test_ops() {
    for row in OPS.span() {
        let r = row.span();
        assert_eq!(vc(r, 0) + vc(r, 3), vc(r, 7));
        assert_eq!(vc(r, 0) - vc(r, 3), vc(r, 10));
        assert_eq!(vc(r, 0) * vc(r, 3), vc(r, 13));
        assert_eq!(vc(r, 0) / vc(r, 3), vc(r, 16));
        assert_eq!(vc(r, 0) % vc(r, 3), vc(r, 19));
        assert_eq!(vc(r, 0).add_scalar(sc(r, 6)), vc(r, 22));
        assert_eq!(vc(r, 0).sub_scalar(sc(r, 6)), vc(r, 25));
        assert_eq!(vc(r, 0).mul_scalar(sc(r, 6)), vc(r, 28));
        assert_eq!(vc(r, 0).div_scalar(sc(r, 6)), vc(r, 31));
        assert_eq!(vc(r, 0).rem_scalar(sc(r, 6)), vc(r, 34));
    }
}

const ASSIGN_OPS: [[i64; 36]; 2] = [
    [
        20, 40, 80, 2, 3, 7, 22, 43, 87, 18, 37, 73, 40, 120, 560, 10, 13, 11, 0, 1, 3, 23, 43, 83,
        17, 37, 77, 60, 120, 240, 6, 13, 26, 2, 1, 2,
    ],
    [
        1000, 7, 65535, 10, 7, 3, 1010, 14, 65538, 990, 0, 65532, 10000, 49, 196605, 100, 1, 21845,
        0, 0, 0, 1003, 10, 65538, 997, 4, 65532, 3000, 21, 196605, 333, 2, 21845, 1, 1, 0,
    ],
];

#[test]
fn test_assign_ops() {
    for row in ASSIGN_OPS.span() {
        let r = row.span();
        let mut a = vc(r, 0);
        a += vc(r, 3);
        assert_eq!(a, vc(r, 6));
        let mut a = vc(r, 0);
        a += 3;
        assert_eq!(a, vc(r, 21));
        let mut a = vc(r, 0);
        a -= vc(r, 3);
        assert_eq!(a, vc(r, 9));
        let mut a = vc(r, 0);
        a -= 3;
        assert_eq!(a, vc(r, 24));
        let mut a = vc(r, 0);
        a *= vc(r, 3);
        assert_eq!(a, vc(r, 12));
        let mut a = vc(r, 0);
        a *= 3;
        assert_eq!(a, vc(r, 27));
        let mut a = vc(r, 0);
        a /= vc(r, 3);
        assert_eq!(a, vc(r, 15));
        let mut a = vc(r, 0);
        a /= 3;
        assert_eq!(a, vc(r, 30));
        let mut a = vc(r, 0);
        a %= vc(r, 3);
        assert_eq!(a, vc(r, 18));
        let mut a = vc(r, 0);
        a %= 3;
        assert_eq!(a, vc(r, 33));
    }
}

const MIN_MAX: [[i64; 12]; 8] = [
    [0, 1, 2, 4294967295, 4294967294, 2147483648, 0, 1, 2, 4294967295, 4294967294, 2147483648],
    [
        4294967295, 4294967294, 2147483648, 4294967295, 1, 2, 4294967295, 1, 2, 4294967295,
        4294967294, 2147483648,
    ],
    [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
    [65535, 65536, 7, 65536, 65535, 3, 65535, 65535, 3, 65536, 65536, 7],
    [4294967295, 2147483648, 65536, 1, 2, 65536, 1, 2, 65536, 4294967295, 2147483648, 65536],
    [0, 0, 0, 4294967295, 2147483648, 65536, 0, 0, 0, 4294967295, 2147483648, 65536],
    [
        2147483649, 2147483648, 2147483647, 2147483648, 2147483649, 65535, 2147483648, 2147483648,
        65535, 2147483649, 2147483649, 2147483647,
    ],
    [3, 5, 7, 13, 2, 1, 3, 2, 1, 13, 5, 7],
];

#[test]
fn test_min_max() {
    for row in MIN_MAX.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).min(vc(r, 3)), vc(r, 6));
        assert_eq!(vc(r, 3).min(vc(r, 0)), vc(r, 6));
        assert_eq!(vc(r, 0).max(vc(r, 3)), vc(r, 9));
        assert_eq!(vc(r, 3).max(vc(r, 0)), vc(r, 9));
    }
}

const MIN_MAX_POSITION_ELEMENT: [[i64; 7]; 8] = [
    [1, 2, 3, 0, 2, 1, 3], [1, 1, 1, 0, 0, 1, 1], [3, 2, 1, 2, 0, 1, 3], [1, 2, 1, 0, 1, 1, 2],
    [1, 0, 1, 1, 0, 0, 1], [0, 1, 2, 0, 2, 0, 2],
    [4294967295, 4294967294, 2147483648, 2, 0, 2147483648, 4294967295], [0, 1, 2, 0, 2, 0, 2],
];

#[test]
fn test_min_max_position_element() {
    for row in MIN_MAX_POSITION_ELEMENT.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).min_position(), us(r, 3));
        assert_eq!(vc(r, 0).max_position(), us(r, 4));
        assert_eq!(vc(r, 0).min_element(), sc(r, 5));
        assert_eq!(vc(r, 0).max_element(), sc(r, 6));
    }
}

const CLAMP: [[i64; 12]; 7] = [
    [0, 0, 0, 1, 3, 3, 6, 8, 8, 1, 3, 3], [5, 5, 5, 1, 3, 3, 6, 8, 8, 5, 5, 5],
    [9, 9, 9, 1, 3, 3, 6, 8, 8, 6, 8, 8], [0, 4, 7, 1, 3, 3, 6, 8, 8, 1, 4, 7],
    [0, 0, 0, 1, 3, 3, 6, 8, 8, 1, 3, 3],
    [4294967295, 4294967295, 4294967295, 1, 3, 3, 6, 8, 8, 6, 8, 8],
    [1, 3, 3, 0, 0, 0, 4294967295, 4294967295, 4294967295, 1, 3, 3],
];

#[test]
fn test_clamp() {
    for row in CLAMP.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).clamp(vc(r, 3), vc(r, 6)), vc(r, 9));
    }
}

const SUM_PRODUCT: [[i64; 5]; 6] = [
    [1, 2, 3, 6, 6], [30, 7, 110, 147, 23100], [1, 2, 3, 6, 6], [0, 1, 5, 6, 0],
    [100, 200, 300, 600, 6000000], [2, 2, 2, 6, 8],
];

#[test]
fn test_sum_product() {
    for row in SUM_PRODUCT.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).element_sum(), sc(r, 3));
        assert_eq!(vc(r, 0).element_product(), sc(r, 4));
    }
}

const CMP: [[i64; 24]; 8] = [
    [
        0, 1, 2, 4294967295, 4294967294, 2147483648, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1,
    ],
    [
        4294967295, 4294967294, 2147483648, 4294967295, 1, 2, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        0, 0, 0, 0, 0,
    ],
    [0, 1, 2, 0, 1, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0],
    [65535, 65536, 7, 65536, 65535, 3, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0],
    [
        4294967295, 2147483648, 65536, 1, 2, 65536, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
        0, 0,
    ],
    [0, 0, 0, 4294967295, 2147483648, 65536, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
    [
        2147483649, 2147483648, 2147483647, 2147483648, 2147483649, 65535, 0, 0, 0, 1, 1, 1, 1, 0,
        1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
    ],
    [3, 5, 7, 13, 2, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0],
];

#[test]
fn test_cmp() {
    for row in CMP.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).cmpeq(vc(r, 3)), bv(r, 6));
        assert_eq!(vc(r, 0).cmpne(vc(r, 3)), bv(r, 9));
        assert_eq!(vc(r, 0).cmpge(vc(r, 3)), bv(r, 12));
        assert_eq!(vc(r, 0).cmpgt(vc(r, 3)), bv(r, 15));
        assert_eq!(vc(r, 0).cmple(vc(r, 3)), bv(r, 18));
        assert_eq!(vc(r, 0).cmplt(vc(r, 3)), bv(r, 21));
    }
}

#[test]
fn test_cmp_all_any() {
    let a = uvec3(1, 1, 1);
    let b = uvec3(2, 2, 2);
    assert!(a.cmplt(b).all() && a.cmple(b).all() && b.cmpgt(a).all() && b.cmpge(a).all());
    assert!(a.cmpne(b).all() && a.cmpeq(a).all() && !a.cmpeq(b).any() && !a.cmplt(a).any());
    assert!(a == a && a != b);
}

const DIV_REM: [[i64; 12]; 8] = [
    [0, 1, 2, 4294967295, 4294967294, 2147483648, 0, 0, 0, 0, 1, 2],
    [4294967295, 4294967294, 2147483648, 4294967295, 1, 2, 1, 4294967294, 1073741824, 0, 0, 0],
    [0, 1, 2, 3, 1, 2, 0, 1, 1, 0, 0, 0], [65535, 65536, 7, 65536, 65535, 3, 0, 1, 2, 65535, 1, 1],
    [4294967295, 2147483648, 65536, 1, 2, 65536, 4294967295, 1073741824, 1, 0, 0, 0],
    [0, 0, 0, 4294967295, 2147483648, 65536, 0, 0, 0, 0, 0, 0],
    [4294967295, 4294967295, 0, 4294967295, 1, 4294967295, 1, 4294967295, 0, 0, 0, 0],
    [4294967295, 2147483648, 5, 2, 3, 7, 2147483647, 715827882, 0, 1, 2, 5],
];

#[test]
fn test_div_rem() {
    for row in DIV_REM.span() {
        let r = row.span();
        assert_eq!(vc(r, 0) / vc(r, 3), vc(r, 6));
        assert_eq!(vc(r, 0) % vc(r, 3), vc(r, 9));
        assert_eq!(vc(r, 0).wrapping_div(vc(r, 3)), vc(r, 6));
        assert_eq!(vc(r, 0).saturating_div(vc(r, 3)), vc(r, 6));
        assert_eq!(vc(r, 0).checked_div(vc(r, 3)), Some(vc(r, 6)));
    }
}

const CHECKED_DIV: [[i64; 10]; 8] = [
    [0, 1, 2, 4294967295, 4294967294, 2147483648, 1, 0, 0, 0],
    [4294967295, 4294967294, 2147483648, 4294967295, 0, 2, 0, 0, 0, 0],
    [0, 1, 2, 0, 1, 2, 0, 0, 0, 0], [65535, 65536, 7, 65536, 65535, 3, 1, 0, 1, 2],
    [4294967295, 2147483648, 65536, 1, 2, 65536, 1, 4294967295, 1073741824, 1],
    [0, 0, 0, 4294967295, 2147483648, 65536, 1, 0, 0, 0],
    [2147483649, 2147483648, 2147483647, 0, 2147483649, 65535, 0, 0, 0, 0],
    [3, 5, 7, 13, 2, 1, 1, 0, 2, 7],
];

#[test]
fn test_checked_div() {
    for row in CHECKED_DIV.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).checked_div(vc(r, 3)), opt(r, 6));
    }
}

const WRAPPING_SATURATING_CHECKED: [[i64; 36]; 8] = [
    [
        0, 1, 2, 4294967295, 4294967294, 2147483648, 4294967295, 4294967295, 2147483650, 4294967295,
        4294967295, 2147483650, 1, 4294967295, 4294967295, 2147483650, 1, 3, 2147483650, 0, 0, 0, 0,
        0, 0, 0, 0, 4294967294, 0, 0, 4294967294, 4294967295, 0, 0, 0, 0,
    ],
    [
        4294967295, 4294967294, 2147483648, 4294967295, 1, 2, 4294967294, 4294967295, 2147483650,
        4294967295, 4294967295, 2147483650, 0, 0, 0, 0, 0, 4294967293, 2147483646, 0, 4294967293,
        2147483646, 1, 0, 4294967293, 2147483646, 1, 4294967294, 0, 4294967295, 4294967294,
        4294967295, 0, 0, 0, 0,
    ],
    [
        0, 1, 2, 0, 1, 2, 0, 2, 4, 0, 2, 4, 1, 0, 2, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 4, 0, 1,
        4, 1, 0, 1, 4,
    ],
    [
        65535, 65536, 7, 65536, 65535, 3, 131071, 131071, 10, 131071, 131071, 10, 1, 131071, 131071,
        10, 4294967295, 1, 4, 0, 1, 4, 0, 0, 0, 0, 4294901760, 4294901760, 21, 4294901760,
        4294901760, 21, 1, 4294901760, 4294901760, 21,
    ],
    [
        4294967295, 2147483648, 65536, 1, 2, 65536, 0, 2147483650, 131072, 4294967295, 2147483650,
        131072, 0, 0, 0, 0, 4294967294, 2147483646, 0, 4294967294, 2147483646, 0, 1, 4294967294,
        2147483646, 0, 4294967295, 0, 0, 4294967295, 4294967295, 4294967295, 0, 0, 0, 0,
    ],
    [
        0, 0, 0, 4294967295, 2147483648, 65536, 4294967295, 2147483648, 65536, 4294967295,
        2147483648, 65536, 1, 4294967295, 2147483648, 65536, 1, 2147483648, 4294901760, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
    ],
    [
        2147483649, 2147483648, 2147483647, 2147483648, 2147483649, 65535, 1, 1, 2147549182,
        4294967295, 4294967295, 2147549182, 0, 0, 0, 0, 1, 4294967295, 2147418112, 1, 0, 2147418112,
        0, 0, 0, 0, 2147483648, 2147483648, 2147418113, 4294967295, 4294967295, 4294967295, 0, 0, 0,
        0,
    ],
    [
        3, 5, 7, 13, 2, 1, 16, 7, 8, 16, 7, 8, 1, 16, 7, 8, 4294967286, 3, 6, 0, 3, 6, 0, 0, 0, 0,
        39, 10, 7, 39, 10, 7, 1, 39, 10, 7,
    ],
];

#[test]
fn test_wrapping_saturating_checked() {
    for row in WRAPPING_SATURATING_CHECKED.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).wrapping_add(vc(r, 3)), vc(r, 6));
        assert_eq!(vc(r, 0).saturating_add(vc(r, 3)), vc(r, 9));
        assert_eq!(vc(r, 0).checked_add(vc(r, 3)), opt(r, 12));
        assert_eq!(vc(r, 0).wrapping_sub(vc(r, 3)), vc(r, 16));
        assert_eq!(vc(r, 0).saturating_sub(vc(r, 3)), vc(r, 19));
        assert_eq!(vc(r, 0).checked_sub(vc(r, 3)), opt(r, 22));
        assert_eq!(vc(r, 0).wrapping_mul(vc(r, 3)), vc(r, 26));
        assert_eq!(vc(r, 0).saturating_mul(vc(r, 3)), vc(r, 29));
        assert_eq!(vc(r, 0).checked_mul(vc(r, 3)), opt(r, 32));
    }
}

const SIGNED_OPS: [[i64; 16]; 8] = [
    [0, 1, 2, 3, -2, -46341, 3, 4294967295, 4294920957, 3, 0, 0, 0, 0, 0, 0],
    [
        4294967295, 4294967294, 2147483648, -1, -1, 1, 4294967294, 4294967293, 2147483649,
        4294967294, 4294967293, 2147483649, 1, 4294967294, 4294967293, 2147483649,
    ],
    [
        0, 1, 2, -2147483648, 2147483647, 65536, 2147483648, 2147483648, 65538, 0, 2147483648,
        65538, 0, 0, 0, 0,
    ],
    [
        65535, 65536, 7, 65536, 65536, -65536, 131071, 131072, 4294901767, 131071, 131072, 0, 0, 0,
        0, 0,
    ],
    [
        4294967295, 2147483648, 65536, -5, 7, -2147483648, 4294967290, 2147483655, 2147549184,
        4294967290, 2147483655, 0, 0, 0, 0, 0,
    ],
    [
        0, 0, 0, 2147483647, 2147483646, 65536, 2147483647, 2147483646, 65536, 2147483647,
        2147483646, 65536, 1, 2147483647, 2147483646, 65536,
    ],
    [
        2147483649, 2147483648, 2147483647, 2147483647, 1, 2, 0, 2147483649, 2147483649, 4294967295,
        2147483649, 2147483649, 0, 0, 0, 0,
    ],
    [4294967295, 0, 0, 1, -1, -1, 0, 4294967295, 4294967295, 4294967295, 0, 0, 0, 0, 0, 0],
];

#[test]
fn test_signed_ops() {
    for row in SIGNED_OPS.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).wrapping_add_signed(vo(r, 3)), vc(r, 6));
        assert_eq!(vc(r, 0).saturating_add_signed(vo(r, 3)), vc(r, 9));
        assert_eq!(vc(r, 0).checked_add_signed(vo(r, 3)), opt(r, 12));
    }
}

const DISTANCES: [[i64; 9]; 9] = [
    [0, 1, 2, 4294967295, 4294967294, 2147483648, 0, 0, 4294967295],
    [4294967295, 4294967294, 2147483648, 4294967295, 1, 2, 0, 0, 4294967293],
    [0, 1, 2, 0, 1, 2, 1, 0, 0], [65535, 65536, 7, 65536, 65535, 3, 1, 6, 4],
    [4294967295, 2147483648, 65536, 1, 2, 65536, 0, 0, 4294967294],
    [0, 0, 0, 4294967295, 2147483648, 65536, 0, 0, 4294967295],
    [2147483649, 2147483648, 2147483647, 2147483648, 2147483649, 65535, 1, 2147418114, 2147418112],
    [3, 5, 7, 13, 2, 1, 1, 19, 10], [3, 27, 98, 20, 65, 97, 1, 56, 38],
];

#[test]
fn test_distances() {
    for row in DISTANCES.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).checked_manhattan_distance(vc(r, 3)), optu(r, 6));
        if let Some(d) = optu(r, 6) {
            assert_eq!(vc(r, 0).manhattan_distance(vc(r, 3)), d);
        }
        assert_eq!(vc(r, 0).chebyshev_distance(vc(r, 3)), su(r, 8));
    }
}

const CASTS: [[i64; 10]; 8] = [
    [0, 1, 2, 0, 1, 2, 1, 0, 1, 2],
    [4294967295, 4294967294, 2147483648, -1, -2, -2147483648, 0, 0, 0, 0],
    [0, 1, 2, 0, 1, 2, 1, 0, 1, 2], [65535, 65536, 7, 65535, 65536, 7, 1, 65535, 65536, 7],
    [4294967295, 2147483648, 65536, -1, -2147483648, 65536, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    [2147483649, 2147483648, 2147483647, -2147483647, -2147483648, 2147483647, 0, 0, 0, 0],
    [3, 5, 7, 3, 5, 7, 1, 3, 5, 7],
];

#[test]
fn test_casts() {
    for row in CASTS.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).as_ivec3(), vo(r, 3));
        assert_eq!(vo(r, 3).as_uvec3(), vc(r, 0));
        let res: Option<IVec3> = vc(r, 0).try_into();
        assert_eq!(res, opto(r, 6));
    }
}

const BIT_OPS: [[i64; 18]; 8] = [
    [
        0, 1, 2, 4294967295, 4294967294, 2147483648, 0, 0, 0, 4294967295, 4294967295, 2147483650,
        4294967295, 4294967295, 2147483650, 4294967295, 4294967294, 4294967293,
    ],
    [
        4294967295, 4294967294, 2147483648, 4294967295, 1, 2, 4294967295, 0, 0, 4294967295,
        4294967295, 2147483650, 0, 4294967295, 2147483650, 0, 1, 2147483647,
    ],
    [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0, 0, 4294967295, 4294967294, 4294967293],
    [
        65535, 65536, 7, 65536, 65535, 3, 0, 0, 3, 131071, 131071, 7, 131071, 131071, 4, 4294901760,
        4294901759, 4294967288,
    ],
    [
        4294967295, 2147483648, 65536, 1, 2, 65536, 1, 0, 65536, 4294967295, 2147483650, 65536,
        4294967294, 2147483650, 0, 0, 2147483647, 4294901759,
    ],
    [
        0, 0, 0, 4294967295, 2147483648, 65536, 0, 0, 0, 4294967295, 2147483648, 65536, 4294967295,
        2147483648, 65536, 4294967295, 4294967295, 4294967295,
    ],
    [
        2147483649, 2147483648, 2147483647, 2147483648, 2147483649, 65535, 2147483648, 2147483648,
        65535, 2147483649, 2147483649, 2147483647, 1, 1, 2147418112, 2147483646, 2147483647,
        2147483648,
    ],
    [3, 5, 7, 13, 2, 1, 1, 0, 1, 15, 7, 7, 14, 7, 6, 4294967292, 4294967290, 4294967288],
];

#[test]
fn test_bit_ops() {
    for row in BIT_OPS.span() {
        let r = row.span();
        assert_eq!(vc(r, 0) & vc(r, 3), vc(r, 6));
        assert_eq!(vc(r, 0) | vc(r, 3), vc(r, 9));
        assert_eq!(vc(r, 0) ^ vc(r, 3), vc(r, 12));
        assert_eq!(~vc(r, 0), vc(r, 15));
    }
}

const SHIFTS: [[i64; 10]; 8] = [
    [0, 1, 2, 0, 0, 1, 2, 0, 1, 2],
    [
        4294967295, 4294967294, 2147483648, 1, 4294967294, 4294967292, 0, 2147483647, 2147483647,
        1073741824,
    ],
    [0, 1, 2, 2, 0, 4, 8, 0, 0, 0], [65535, 65536, 7, 5, 2097120, 2097152, 224, 2047, 2048, 0],
    [4294967295, 2147483648, 65536, 15, 4294934528, 0, 2147483648, 131071, 65536, 2],
    [0, 0, 0, 16, 0, 0, 0, 0, 0, 0],
    [2147483649, 2147483648, 2147483647, 30, 1073741824, 0, 3221225472, 2, 2, 1],
    [3, 5, 7, 31, 2147483648, 2147483648, 2147483648, 0, 0, 0],
];

#[test]
fn test_shifts() {
    for row in SHIFTS.span() {
        let r = row.span();
        assert_eq!(vc(r, 0).shl(su(r, 3)), vc(r, 4));
        assert_eq!(vc(r, 0).shr(su(r, 3)), vc(r, 7));
    }
}

#[test]
fn test_hash_serde() {
    let a = uvec3(1, 2, 3);
    let b = uvec3(3, 2, 1);
    assert_eq!(hash(a), hash(a));
    assert!(hash(a) != hash(b));
    let mut out = array![];
    a.serialize(ref out);
    assert_eq!(out.len(), 3);
    let mut span = out.span();
    assert_eq!(Serde::<UVec3>::deserialize(ref span), Some(a));
}

#[test]
#[should_panic(expected: 'u32_add Overflow')]
fn test_add_overflow() {
    let _ = UVec3Trait::MAX + UVec3Trait::X;
}

#[test]
#[should_panic(expected: 'u32_add Overflow')]
fn test_add_scalar_overflow() {
    let _ = UVec3Trait::MAX.add_scalar(1);
}

#[test]
#[should_panic(expected: 'u32_sub Overflow')]
fn test_sub_overflow() {
    let _ = UVec3Trait::ZERO - UVec3Trait::X;
}

#[test]
#[should_panic(expected: 'u32_sub Overflow')]
fn test_sub_scalar_overflow() {
    let _ = UVec3Trait::ZERO.sub_scalar(1);
}

#[test]
#[should_panic(expected: 'u32_mul Overflow')]
fn test_mul_overflow() {
    let _ = UVec3Trait::MAX * uvec3(2, 2, 2);
}

#[test]
#[should_panic(expected: 'u32_mul Overflow')]
fn test_mul_scalar_overflow() {
    let _ = UVec3Trait::MAX.mul_scalar(2);
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_div_by_zero() {
    let _ = UVec3Trait::ONE / UVec3Trait::X;
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_rem_by_zero() {
    let _ = UVec3Trait::ONE % UVec3Trait::X;
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_div_scalar_by_zero() {
    let _ = UVec3Trait::ONE.div_scalar(0);
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_rem_scalar_by_zero() {
    let _ = UVec3Trait::ONE.rem_scalar(0);
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_wrapping_div_by_zero() {
    let _ = UVec3Trait::ONE.wrapping_div(UVec3Trait::X);
}

#[test]
#[should_panic(expected: 'Division by 0')]
fn test_saturating_div_by_zero() {
    let _ = UVec3Trait::ONE.saturating_div(UVec3Trait::X);
}

#[test]
#[should_panic(expected: 'UVec3: overflow')]
fn test_dot_overflow() {
    let _ = UVec3Trait::MAX.dot(UVec3Trait::MAX);
}

#[test]
#[should_panic(expected: 'UVec3: overflow')]
fn test_dot_into_vec_overflow() {
    let _ = UVec3Trait::MAX.dot_into_vec(UVec3Trait::MAX);
}

#[test]
#[should_panic(expected: 'UVec3: overflow')]
fn test_length_squared_overflow() {
    let _ = UVec3Trait::MAX.length_squared();
}

#[test]
#[should_panic(expected: 'UVec3: overflow')]
fn test_element_sum_overflow() {
    let _ = UVec3Trait::MAX.element_sum();
}

#[test]
#[should_panic(expected: 'UVec3: overflow')]
fn test_element_product_overflow() {
    let _ = UVec3Trait::MAX.element_product();
}

#[test]
#[should_panic(expected: 'UVec3: overflow')]
fn test_manhattan_distance_overflow() {
    let _ = UVec3Trait::MIN.manhattan_distance(UVec3Trait::MAX);
}

#[test]
#[should_panic(expected: 'UVec3: overflow')]
fn test_cross_overflow() {
    let _ = uvec3(65536, 0, 0).cross(uvec3(0, 65536, 0));
}

#[test]
#[should_panic(expected: 'UVec3: overflow')]
fn test_cross_negative() {
    let _ = UVec3Trait::Y.cross(UVec3Trait::X);
}

#[test]
#[should_panic(expected: 'UVec3: shift overflow')]
fn test_shl_overflow() {
    let _ = UVec3Trait::ONE.shl(32);
}

#[test]
#[should_panic(expected: 'UVec3: shift overflow')]
fn test_shr_overflow() {
    let _ = UVec3Trait::ONE.shr(32);
}

#[test]
fn test_fused_kernels_check_the_result_only() {
    assert_eq!(uvec3(4294967295, 2, 0).element_product(), 0);
}

#[test]
#[fuzzer(runs: 256, seed: 3501)]
fn fuzz_wrapping_checked_saturating(a: u32, b: u32, c: u32, d: u32) {
    let va = uvec3(a, b, a);
    let vb = uvec3(c, d, a);
    let exact = [wide(a) + wide(c), wide(b) + wide(d), wide(a) + wide(a)];
    assert_eq!(va.wrapping_add(vb).to_array(), map_wrap(exact));
    assert_eq!(va.saturating_add(vb).to_array(), map_sat(exact));
    assert_eq!(va.checked_add(vb), map_checked(exact));
    let exact = [wide(a) - wide(c), wide(b) - wide(d), wide(a) - wide(a)];
    assert_eq!(va.wrapping_sub(vb).to_array(), map_wrap(exact));
    assert_eq!(va.saturating_sub(vb).to_array(), map_sat(exact));
    assert_eq!(va.checked_sub(vb), map_checked(exact));
    let exact = [wide(a) * wide(c), wide(b) * wide(d), wide(a) * wide(a)];
    assert_eq!(va.wrapping_mul(vb).to_array(), map_wrap(exact));
    assert_eq!(va.saturating_mul(vb).to_array(), map_sat(exact));
    assert_eq!(va.checked_mul(vb), map_checked(exact));
    // mixed signedness: the other-signedness operand is `vb` reinterpreted
    let ub = vb.as_ivec3();
    let [ux, uy, uz] = ub.to_array();
    let exact = [wide(a) + wide_o(ux), wide(b) + wide_o(uy), wide(a) + wide_o(uz)];
    assert_eq!(va.wrapping_add_signed(ub).to_array(), map_wrap(exact));
    assert_eq!(va.saturating_add_signed(ub).to_array(), map_sat(exact));
    assert_eq!(va.checked_add_signed(ub), map_checked(exact));
}

#[test]
#[fuzzer(runs: 256, seed: 3502)]
fn fuzz_min_max_clamp_select_cmp_distances(a: u32, b: u32, c: u32, d: u32) {
    let va = uvec3(a, b, a);
    let vb = uvec3(c, d, a);
    let lo = va.min(vb);
    let hi = va.max(vb);
    assert!(lo.cmple(hi).all());
    assert!(lo.cmple(va).all() && lo.cmple(vb).all());
    assert!(hi.cmpge(va).all() && hi.cmpge(vb).all());
    assert_eq!(UVec3Trait::select(va.cmplt(vb), va, vb), lo);
    assert_eq!(UVec3Trait::select(va.cmpgt(vb), va, vb), hi);
    assert_eq!(va.cmpeq(vb), !va.cmpne(vb));
    assert_eq!(va.cmpge(vb), !va.cmplt(vb));
    assert_eq!(va.cmple(vb), !va.cmpgt(vb));
    let vc = uvec3(d, a, c);
    assert_eq!(vc.clamp(lo, hi), vc.max(lo).min(hi));
    assert!(lo.min_element() <= lo.max_element());
    assert_eq!(va[va.min_position()], va.min_element());
    assert_eq!(va[va.max_position()], va.max_element());
    let d = [abs_wide(wide(a) - wide(c)), abs_wide(wide(b) - wide(d)), abs_wide(wide(a) - wide(a))];
    let [dx, dy, dz] = d;
    let sum = dx + dy + dz;
    let expected: Option<u32> = sum.try_into();
    assert_eq!(va.checked_manhattan_distance(vb), expected);
    assert_eq!(vb.checked_manhattan_distance(va), expected);
    let mut m = dx;
    if dy > m {
        m = dy;
    }
    if dz > m {
        m = dz;
    }
    assert_eq!(wide_u(va.chebyshev_distance(vb)), m);
}

#[test]
#[fuzzer(runs: 256, seed: 3504)]
fn fuzz_dot_casts_bits_shifts(a: u32, b: u32, c: u32, d: u32, k: u32) {
    // 14-bit operands: nothing overflows
    let va = uvec3(a / 0x40000, b / 0x40000, a / 0x40000);
    let vb = uvec3(c / 0x40000, d / 0x40000, a / 0x40000);
    let expected = wide(a / 0x40000) * wide(c / 0x40000)
        + wide(b / 0x40000) * wide(d / 0x40000)
        + wide(a / 0x40000) * wide(a / 0x40000);
    assert_eq!(wide(va.dot(vb)), expected);
    assert_eq!(va.dot(vb), vb.dot(va));
    assert_eq!(va.length_squared(), va.dot(va));
    assert_eq!(wide(va.element_sum()), wide(a / 0x40000) + wide(b / 0x40000) + wide(a / 0x40000));
    let tiny = uvec3(a / 0x1000000, b / 0x1000000, a / 0x1000000);
    assert_eq!(
        wide(tiny.element_product()),
        wide(a / 0x1000000) * wide(b / 0x1000000) * wide(a / 0x1000000),
    );
    let va = uvec3(a, b, a);
    let vb = uvec3(b, a, a);
    assert_eq!(va.as_ivec3().as_uvec3(), va);
    assert_eq!(wide_o(va.as_ivec3().x), wrap_o(wide(a)));
    // (a & b) + (a | b) == a + b and (a ^ b) + 2 * (a & b) == a + b
    assert_eq!(wide((va & vb).x) + wide((va | vb).x), wide(a) + wide(b));
    assert_eq!(wide((va ^ vb).x) + 2 * wide((va & vb).x), wide(a) + wide(b));
    assert_eq!((va ^ vb) ^ vb, va);
    assert_eq!(~(va & vb), ~va | ~vb);
    assert_eq!(wide((~va).x), -1 - wide(a) + 0x100000000);
    let k = k % 32;
    let p = pow2(k);
    assert_eq!(wide(va.shl(k).x), wrap(wide(a) * p));
    assert_eq!(wide(va.shr(k).x), floor_div(wide(a), p));
}

#[test]
#[fuzzer(runs: 256, seed: 3506)]
fn fuzz_div_rem(a: u32, b: u32, c: u32, d: u32) {
    let va = uvec3(a, b, a);
    let vb = uvec3(nz(c), nz(d), nz(a));
    let q = va / vb;
    let r = va % vb;
    assert!(r.cmplt(vb).all());
    for i in 0..3_usize {
        assert_eq!(wide(q[i]) * wide(vb[i]) + wide(r[i]), wide(va[i]));
    }
    assert_eq!(va.wrapping_div(vb), q);
    assert_eq!(va.saturating_div(vb), q);
    assert_eq!(va.checked_div(vb), Some(q));
}
