//! Tests of `glam::camera`: the view constructors against `glam::mat4` (bit-identical), the
//! projection constructors on exactly representable geometry (`fov = PI / 2`, dyadic near / far /
//! boxes: every expected element is an exact Q32.32 value derived by hand, tables in quarter units
//! of one), the projection of the corners of the frustum / box to the NDC cube, the lh / rh and
//! API relations, the usable range, seeded fuzz properties and one test per panic path.
//!
//! The glam-rs results on arbitrary parameters are checked by `golden_camera.cairo` (generated by
//! `tools/refgen` with `glam::dcamera` as the oracle).

use fixed::fixed::{FRAC_PI_2, Fixed, FixedTrait, MAX, MIN, ONE, PI};
use glam::affine3::Affine3Trait;
use glam::camera::lh::proj::{directx as lh_directx, opengl as lh_opengl, vulkan as lh_vulkan};
use glam::camera::lh::view as lh_view;
use glam::camera::rh::proj::{directx as rh_directx, opengl as rh_opengl, vulkan as rh_vulkan};
use glam::camera::rh::view as rh_view;
use glam::mat3::Mat3;
use glam::mat4::{Mat4, Mat4Trait};
use glam::quat::QuatTrait;
use glam::vec3::Vec3;
use glam::vec4::Vec4;

/// A `Fixed` from its raw Q32.32 value.
fn f(raw: i64) -> Fixed {
    FixedTrait::from_raw(raw)
}

/// A `Fixed` from quarters: `q(6) = 1.5`.
fn q(n: i64) -> Fixed {
    f(n * 0x40000000)
}

/// The table cell `i` of a row, in quarters.
fn c(r: Span<i64>, i: u32) -> Fixed {
    q(*r[i])
}

fn v3(x: Fixed, y: Fixed, z: Fixed) -> Vec3 {
    Vec3 { x, y, z }
}

fn z4() -> Vec4 {
    Vec4 { x: q(0), y: q(0), z: q(0), w: q(0) }
}

/// The perspective layout.
fn pm(xx: Fixed, yy: Fixed, zz: Fixed, zw: Fixed, tz: Fixed) -> Mat4 {
    Mat4 {
        x_axis: Vec4 { x: xx, ..z4() },
        y_axis: Vec4 { y: yy, ..z4() },
        z_axis: Vec4 { z: zz, w: zw, ..z4() },
        w_axis: Vec4 { z: tz, ..z4() },
    }
}

/// The frustum layout.
fn fm(xx: Fixed, yy: Fixed, zx: Fixed, zy: Fixed, zz: Fixed, zw: Fixed, tz: Fixed) -> Mat4 {
    Mat4 {
        x_axis: Vec4 { x: xx, ..z4() },
        y_axis: Vec4 { y: yy, ..z4() },
        z_axis: Vec4 { x: zx, y: zy, z: zz, w: zw },
        w_axis: Vec4 { z: tz, ..z4() },
    }
}

/// The orthographic layout.
fn om(xx: Fixed, yy: Fixed, zz: Fixed, tx: Fixed, ty: Fixed, tz: Fixed) -> Mat4 {
    Mat4 {
        x_axis: Vec4 { x: xx, ..z4() },
        y_axis: Vec4 { y: yy, ..z4() },
        z_axis: Vec4 { z: zz, ..z4() },
        w_axis: Vec4 { x: tx, y: ty, z: tz, w: ONE },
    }
}

/// `|a - b| <= tol` raw ULP.
fn near_raw(a: Fixed, b: Fixed, tol: i64) -> bool {
    let d = a.raw - b.raw;
    d <= tol && d >= -tol
}

// Exact perspective. Row: aspect, xx, near, far, then the left-handed depth terms: zz and tz of
// the [0, 1] range (`q`, `-near * q`), zz and tz of the [-1, 1] range (`2 q - 1`, `-2 near q`),
// with `q = far / (far - near)`; `fov = PI / 2` (`cot = 1` exactly).
const PERSP: [[i64; 8]; 6] = [
    [8, 2, 4, 12, 6, -6, 8, -12], [4, 4, 8, 24, 6, -12, 8, -24], [2, 8, 4, 8, 8, -8, 12, -16],
    [16, 1, 8, 12, 12, -24, 20, -48], [8, 2, 2, 6, 6, -3, 8, -6], [4, 4, 4, 12, 6, -6, 8, -12],
];

#[test]
fn test_perspective_exact() {
    for row in PERSP.span() {
        let r = row.span();
        let (a, xx, n, z) = (c(r, 0), c(r, 1), c(r, 2), c(r, 3));
        let (zz_zo, tz_zo, zz_gl, tz_gl) = (c(r, 4), c(r, 5), c(r, 6), c(r, 7));
        let (yy, nyy, one, none) = (ONE, -ONE, ONE, -ONE);
        assert_eq!(lh_opengl::perspective(FRAC_PI_2, a, n, z), pm(xx, yy, zz_gl, one, tz_gl));
        assert_eq!(lh_directx::perspective(FRAC_PI_2, a, n, z), pm(xx, yy, zz_zo, one, tz_zo));
        assert_eq!(lh_vulkan::perspective(FRAC_PI_2, a, n, z), pm(xx, nyy, zz_zo, one, tz_zo));
        assert_eq!(rh_opengl::perspective(FRAC_PI_2, a, n, z), pm(xx, yy, -zz_gl, none, tz_gl));
        assert_eq!(rh_directx::perspective(FRAC_PI_2, a, n, z), pm(xx, yy, -zz_zo, none, tz_zo));
        assert_eq!(rh_vulkan::perspective(FRAC_PI_2, a, n, z), pm(xx, nyy, -zz_zo, none, tz_zo));
    }
}

#[test]
fn test_perspective_infinite_exact() {
    for row in PERSP.span() {
        let r = row.span();
        let (a, xx, n) = (c(r, 0), c(r, 1), c(r, 2));
        let (o, no, z) = (ONE, -ONE, q(0));
        assert_eq!(lh_directx::perspective_infinite(FRAC_PI_2, a, n), pm(xx, o, o, o, -n));
        assert_eq!(lh_vulkan::perspective_infinite(FRAC_PI_2, a, n), pm(xx, no, o, o, -n));
        assert_eq!(rh_directx::perspective_infinite(FRAC_PI_2, a, n), pm(xx, o, no, no, -n));
        assert_eq!(rh_vulkan::perspective_infinite(FRAC_PI_2, a, n), pm(xx, no, no, no, -n));
        assert_eq!(lh_directx::perspective_infinite_reverse(FRAC_PI_2, a, n), pm(xx, o, z, o, n));
        assert_eq!(lh_vulkan::perspective_infinite_reverse(FRAC_PI_2, a, n), pm(xx, no, z, o, n));
        assert_eq!(rh_directx::perspective_infinite_reverse(FRAC_PI_2, a, n), pm(xx, o, z, no, n));
        assert_eq!(rh_vulkan::perspective_infinite_reverse(FRAC_PI_2, a, n), pm(xx, no, z, no, n));
    }
}

// Exact orthographic. Row: left, right, bottom, top, near, far, then xx, yy, tx, ty and the
// left-handed depth terms of the [0, 1] range (zz = 1 / d, tz = -near / d) and of the [-1, 1]
// range (zz = 2 / d, tz = -(far + near) / d).
const ORTHO: [[i64; 14]; 4] = [
    [-16, 16, -8, 8, 4, 12, 1, 2, 0, 0, 2, -2, 4, -8],
    [-8, 24, -4, 12, 4, 20, 1, 2, -2, -2, 1, -1, 2, -6],
    [0, 4, 0, 4, 0, 4, 8, 8, -4, -4, 4, 0, 8, -4],
    [-4, 12, 8, 40, 4, 20, 2, 1, -2, -6, 1, -1, 2, -6],
];

#[test]
fn test_orthographic_exact() {
    for row in ORTHO.span() {
        let r = row.span();
        let (l, rt, b, t, n, z) = (c(r, 0), c(r, 1), c(r, 2), c(r, 3), c(r, 4), c(r, 5));
        let (xx, yy, tx, ty) = (c(r, 6), c(r, 7), c(r, 8), c(r, 9));
        let (zz_zo, tz_zo, zz_gl, tz_gl) = (c(r, 10), c(r, 11), c(r, 12), c(r, 13));
        assert_eq!(lh_opengl::orthographic(l, rt, b, t, n, z), om(xx, yy, zz_gl, tx, ty, tz_gl));
        assert_eq!(lh_directx::orthographic(l, rt, b, t, n, z), om(xx, yy, zz_zo, tx, ty, tz_zo));
        // glam-rs negates `yy` only: the Y translation is not flipped
        assert_eq!(lh_vulkan::orthographic(l, rt, b, t, n, z), om(xx, -yy, zz_zo, tx, ty, tz_zo));
        assert_eq!(rh_opengl::orthographic(l, rt, b, t, n, z), om(xx, yy, -zz_gl, tx, ty, tz_gl));
        assert_eq!(rh_directx::orthographic(l, rt, b, t, n, z), om(xx, yy, -zz_zo, tx, ty, tz_zo));
        assert_eq!(rh_vulkan::orthographic(l, rt, b, t, n, z), om(xx, -yy, -zz_zo, tx, ty, tz_zo));
    }
}

// Exact frustum. Row: left, right, bottom, top, near, far, then xx, yy, zx, zy and the
// left-handed depth terms as in `PERSP` (zz, tz of the [0, 1] range, zz, tz of the [-1, 1] range).
const FRUSTUM: [[i64; 14]; 3] = [
    [-8, 8, -4, 4, 4, 12, 2, 4, 0, 0, 6, -6, 8, -12],
    [-4, 12, 0, 8, 4, 8, 2, 4, 2, 4, 8, -8, 12, -16],
    [-16, 0, -8, 0, 8, 12, 4, 8, -4, -4, 12, -24, 20, -48],
];

#[test]
fn test_frustum_exact() {
    for row in FRUSTUM.span() {
        let r = row.span();
        let (l, rt, b, t, n, z) = (c(r, 0), c(r, 1), c(r, 2), c(r, 3), c(r, 4), c(r, 5));
        let (xx, yy, zx, zy) = (c(r, 6), c(r, 7), c(r, 8), c(r, 9));
        let (zz_zo, tz_zo, zz_gl, tz_gl) = (c(r, 10), c(r, 11), c(r, 12), c(r, 13));
        let (one, none) = (ONE, -ONE);
        assert_eq!(lh_opengl::frustum(l, rt, b, t, n, z), fm(xx, yy, zx, zy, zz_gl, one, tz_gl));
        assert_eq!(lh_directx::frustum(l, rt, b, t, n, z), fm(xx, yy, zx, zy, zz_zo, one, tz_zo));
        assert_eq!(lh_vulkan::frustum(l, rt, b, t, n, z), fm(xx, -yy, zx, -zy, zz_zo, one, tz_zo));
        assert_eq!(rh_opengl::frustum(l, rt, b, t, n, z), fm(xx, yy, zx, zy, -zz_gl, none, tz_gl));
        assert_eq!(rh_directx::frustum(l, rt, b, t, n, z), fm(xx, yy, zx, zy, -zz_zo, none, tz_zo));
        assert_eq!(
            rh_vulkan::frustum(l, rt, b, t, n, z), fm(xx, -yy, zx, -zy, -zz_zo, none, tz_zo),
        );
    }
}

/// Projects the view space point `(x, y, -+dist)` (`-` for right-handed) and compares the NDC
/// point with `(ex, ey, ez)` exactly.
fn check_ndc(m: Mat4, rh: bool, x: Fixed, y: Fixed, dist: Fixed, ex: Fixed, ey: Fixed, ez: Fixed) {
    let z = if rh {
        -dist
    } else {
        dist
    };
    let p = m.project_point3(v3(x, y, z));
    assert_eq!(p, v3(ex, ey, ez), "ndc of ({:?}, {:?}, {:?})", x, y, dist);
}

// Corners of the frustum of `fov = PI / 2`, aspect 2, near 1, far 3: the near plane corners are
// (+-2, +-1) at distance 1 and the far plane ones (+-6, +-3) at distance 3.
#[test]
fn test_perspective_corners_to_ndc() {
    let (a, n, z) = (q(8), q(4), q(12));
    let (m1, m2, m3) = (q(-4), q(0), q(4));
    for sx in array![m1, m3].span() {
        for sy in array![m1, m3].span() {
            let (sx, sy) = (*sx, *sy);
            // near plane at distance 1, far plane at distance 3
            let mats = [
                (lh_opengl::perspective(FRAC_PI_2, a, n, z), false, m1, sy),
                (lh_directx::perspective(FRAC_PI_2, a, n, z), false, m2, sy),
                (lh_vulkan::perspective(FRAC_PI_2, a, n, z), false, m2, -sy),
                (rh_opengl::perspective(FRAC_PI_2, a, n, z), true, m1, sy),
                (rh_directx::perspective(FRAC_PI_2, a, n, z), true, m2, sy),
                (rh_vulkan::perspective(FRAC_PI_2, a, n, z), true, m2, -sy),
            ];
            for e in mats.span() {
                let (m, rh, ez_near, ey) = *e;
                check_ndc(m, rh, q(8) * sx, q(4) * sy, q(4), sx, ey, ez_near);
                check_ndc(m, rh, q(24) * sx, q(12) * sy, q(12), sx, ey, m3);
            }
        }
    }
}

#[test]
fn test_infinite_corners_to_ndc() {
    // near 1, aspect 2: the near corners are (+-2, +-1) at distance 1, the ones at distance 4
    // (+-8, +-4)
    let (a, n, m1, p1) = (q(8), q(4), q(-4), q(4));
    for sx in array![m1, p1].span() {
        for sy in array![m1, p1].span() {
            let (sx, sy) = (*sx, *sy);
            let (ld, lv) = (
                lh_directx::perspective_infinite(FRAC_PI_2, a, n),
                lh_vulkan::perspective_infinite(FRAC_PI_2, a, n),
            );
            let (rd, rv) = (
                rh_directx::perspective_infinite(FRAC_PI_2, a, n),
                rh_vulkan::perspective_infinite(FRAC_PI_2, a, n),
            );
            let z0 = q(0);
            // depth 0 at `near`, 3 / 4 at distance 4
            check_ndc(ld, false, q(8) * sx, q(4) * sy, q(4), sx, sy, z0);
            check_ndc(lv, false, q(8) * sx, q(4) * sy, q(4), sx, -sy, z0);
            check_ndc(rd, true, q(8) * sx, q(4) * sy, q(4), sx, sy, z0);
            check_ndc(rv, true, q(8) * sx, q(4) * sy, q(4), sx, -sy, z0);
            check_ndc(ld, false, q(32) * sx, q(16) * sy, q(16), sx, sy, q(3));
            check_ndc(rv, true, q(32) * sx, q(16) * sy, q(16), sx, -sy, q(3));
            // reverse: depth 1 at `near`, 1 / 4 at distance 4
            let (ld, lv) = (
                lh_directx::perspective_infinite_reverse(FRAC_PI_2, a, n),
                lh_vulkan::perspective_infinite_reverse(FRAC_PI_2, a, n),
            );
            let (rd, rv) = (
                rh_directx::perspective_infinite_reverse(FRAC_PI_2, a, n),
                rh_vulkan::perspective_infinite_reverse(FRAC_PI_2, a, n),
            );
            check_ndc(ld, false, q(8) * sx, q(4) * sy, q(4), sx, sy, q(4));
            check_ndc(lv, false, q(8) * sx, q(4) * sy, q(4), sx, -sy, q(4));
            check_ndc(rd, true, q(8) * sx, q(4) * sy, q(4), sx, sy, q(4));
            check_ndc(rv, true, q(8) * sx, q(4) * sy, q(4), sx, -sy, q(4));
            check_ndc(ld, false, q(32) * sx, q(16) * sy, q(16), sx, sy, q(1));
            check_ndc(rv, true, q(32) * sx, q(16) * sy, q(16), sx, -sy, q(1));
        }
    }
}

/// The projection of the box `[left, right] x [bottom, top] x [near, far]` (rows of `ORTHO`) to
/// the NDC cube.
#[test]
fn test_orthographic_box_to_cube() {
    let (m1, p1, z0) = (q(-4), q(4), q(0));
    for row in ORTHO.span() {
        let r = row.span();
        let (l, rt, b, t, n, z) = (c(r, 0), c(r, 1), c(r, 2), c(r, 3), c(r, 4), c(r, 5));
        // the Y translation is not flipped by glam-rs: Vulkan maps the cube only for `bottom =
        // -top`
        let sym = b + t == z0;
        for cx in array![(l, m1), (rt, p1)].span() {
            for cy in array![(b, m1), (t, p1)].span() {
                for cz in array![(n, m1, z0), (z, p1, p1)].span() {
                    let ((x, ex), (y, ey), (d, ez_gl, ez_zo)) = (*cx, *cy, *cz);
                    check_ndc(
                        lh_opengl::orthographic(l, rt, b, t, n, z), false, x, y, d, ex, ey, ez_gl,
                    );
                    check_ndc(
                        rh_opengl::orthographic(l, rt, b, t, n, z), true, x, y, d, ex, ey, ez_gl,
                    );
                    check_ndc(
                        lh_directx::orthographic(l, rt, b, t, n, z), false, x, y, d, ex, ey, ez_zo,
                    );
                    check_ndc(
                        rh_directx::orthographic(l, rt, b, t, n, z), true, x, y, d, ex, ey, ez_zo,
                    );
                    if sym {
                        check_ndc(
                            lh_vulkan::orthographic(l, rt, b, t, n, z),
                            false,
                            x,
                            y,
                            d,
                            ex,
                            -ey,
                            ez_zo,
                        );
                        check_ndc(
                            rh_vulkan::orthographic(l, rt, b, t, n, z),
                            true,
                            x,
                            y,
                            d,
                            ex,
                            -ey,
                            ez_zo,
                        );
                    }
                }
            }
        }
    }
}

/// The projection of the corners of the frustum (rows of `FRUSTUM`) to the NDC cube, on the near
/// and on the far plane (the box scaled by `far / near`).
#[test]
fn test_frustum_corners_to_ndc() {
    let (m1, p1, z0) = (q(-4), q(4), q(0));
    for row in FRUSTUM.span() {
        let r = row.span();
        let (l, rt, b, t, n, z) = (c(r, 0), c(r, 1), c(r, 2), c(r, 3), c(r, 4), c(r, 5));
        // glam-rs keeps the sign of `zx`, `zy` in the left-handed matrices: an off-center
        // left-handed frustum is mirrored, only the centered box maps to the cube there
        let sym = l + rt == z0 && b + t == z0;
        for cx in array![(l, m1), (rt, p1)].span() {
            for cy in array![(b, m1), (t, p1)].span() {
                let ((x, ex), (y, ey)) = (*cx, *cy);
                let (fx, fy) = ((x * z) / n, (y * z) / n);
                let gl = (
                    lh_opengl::frustum(l, rt, b, t, n, z), rh_opengl::frustum(l, rt, b, t, n, z),
                );
                let dx = (
                    lh_directx::frustum(l, rt, b, t, n, z), rh_directx::frustum(l, rt, b, t, n, z),
                );
                let vk = (
                    lh_vulkan::frustum(l, rt, b, t, n, z), rh_vulkan::frustum(l, rt, b, t, n, z),
                );
                let (gl_l, gl_r) = gl;
                let (dx_l, dx_r) = dx;
                let (vk_l, vk_r) = vk;
                if sym {
                    check_ndc(gl_l, false, x, y, n, ex, ey, m1);
                    check_ndc(dx_l, false, x, y, n, ex, ey, z0);
                    check_ndc(vk_l, false, x, y, n, ex, -ey, z0);
                    check_ndc(gl_l, false, fx, fy, z, ex, ey, p1);
                    check_ndc(dx_l, false, fx, fy, z, ex, ey, p1);
                    check_ndc(vk_l, false, fx, fy, z, ex, -ey, p1);
                }
                check_ndc(gl_r, true, x, y, n, ex, ey, m1);
                check_ndc(dx_r, true, x, y, n, ex, ey, z0);
                check_ndc(vk_r, true, x, y, n, ex, -ey, z0);
                check_ndc(gl_r, true, fx, fy, z, ex, ey, p1);
                check_ndc(dx_r, true, fx, fy, z, ex, ey, p1);
                check_ndc(vk_r, true, fx, fy, z, ex, -ey, p1);
            }
        }
    }
}

// Parameters of the relations below. Row: vertical fov, aspect, near, far, left, right, bottom,
// top (raw).
const PARAMS: [[i64; 8]; 3] = [
    [
        4497679235, 0x180000000, 429496730, 0x6400000000, -0x800000000, 0x800000000, -0x480000000,
        0x480000000,
    ],
    [
        4294967296, 3221225472, 2147483648, 30064771072, -14173392077, 7301444403, -2576980378,
        9019431322,
    ],
    [
        10737418240, 17179869184, 12884901888, 15032385536, -429496729600, 214748364800,
        -322122547200, 107374182400,
    ],
];

/// `m` with the sign of the depth terms `z_axis.z` and `z_axis.w` flipped: right-handed from
/// left-handed.
fn flip_z(m: Mat4) -> Mat4 {
    Mat4 { z_axis: Vec4 { z: -m.z_axis.z, w: -m.z_axis.w, ..m.z_axis }, ..m }
}

/// `m` with the sign of `yy` flipped, and of `zy` when `zy`: Vulkan from DirectX.
fn flip_y(m: Mat4, zy: bool) -> Mat4 {
    let z = if zy {
        Vec4 { y: -m.z_axis.y, ..m.z_axis }
    } else {
        m.z_axis
    };
    Mat4 { y_axis: Vec4 { y: -m.y_axis.y, ..m.y_axis }, z_axis: z, ..m }
}

#[test]
fn test_lh_rh_and_vulkan_relations() {
    for row in PARAMS.span() {
        let r = row.span();
        let (fov, a, n, z) = (f(*r[0]), f(*r[1]), f(*r[2]), f(*r[3]));
        let (l, rt, b, t) = (f(*r[4]), f(*r[5]), f(*r[6]), f(*r[7]));
        // right-handed = left-handed with `zz` and `zw` negated
        assert_eq!(
            rh_opengl::perspective(fov, a, n, z), flip_z(lh_opengl::perspective(fov, a, n, z)),
        );
        assert_eq!(
            rh_directx::perspective(fov, a, n, z), flip_z(lh_directx::perspective(fov, a, n, z)),
        );
        assert_eq!(
            rh_vulkan::perspective(fov, a, n, z), flip_z(lh_vulkan::perspective(fov, a, n, z)),
        );
        assert_eq!(
            rh_directx::perspective_infinite(fov, a, n),
            flip_z(lh_directx::perspective_infinite(fov, a, n)),
        );
        assert_eq!(
            rh_vulkan::perspective_infinite(fov, a, n),
            flip_z(lh_vulkan::perspective_infinite(fov, a, n)),
        );
        assert_eq!(
            rh_directx::perspective_infinite_reverse(fov, a, n),
            flip_z(lh_directx::perspective_infinite_reverse(fov, a, n)),
        );
        assert_eq!(
            rh_vulkan::perspective_infinite_reverse(fov, a, n),
            flip_z(lh_vulkan::perspective_infinite_reverse(fov, a, n)),
        );
        assert_eq!(
            rh_opengl::frustum(l, rt, b, t, n, z), flip_z(lh_opengl::frustum(l, rt, b, t, n, z)),
        );
        assert_eq!(
            rh_directx::frustum(l, rt, b, t, n, z), flip_z(lh_directx::frustum(l, rt, b, t, n, z)),
        );
        assert_eq!(
            rh_vulkan::frustum(l, rt, b, t, n, z), flip_z(lh_vulkan::frustum(l, rt, b, t, n, z)),
        );
        // Vulkan = DirectX with the Y axis flipped
        assert_eq!(
            lh_vulkan::perspective(fov, a, n, z),
            flip_y(lh_directx::perspective(fov, a, n, z), false),
        );
        assert_eq!(
            rh_vulkan::perspective(fov, a, n, z),
            flip_y(rh_directx::perspective(fov, a, n, z), false),
        );
        assert_eq!(
            lh_vulkan::perspective_infinite(fov, a, n),
            flip_y(lh_directx::perspective_infinite(fov, a, n), false),
        );
        assert_eq!(
            rh_vulkan::perspective_infinite_reverse(fov, a, n),
            flip_y(rh_directx::perspective_infinite_reverse(fov, a, n), false),
        );
        assert_eq!(
            lh_vulkan::frustum(l, rt, b, t, n, z),
            flip_y(lh_directx::frustum(l, rt, b, t, n, z), true),
        );
        assert_eq!(
            rh_vulkan::frustum(l, rt, b, t, n, z),
            flip_y(rh_directx::frustum(l, rt, b, t, n, z), true),
        );
        // orthographic: the two signs of a round to nearest quotient differ by at most a tie
        let (lo, ro) = (
            lh_opengl::orthographic(l, rt, b, t, n, z), rh_opengl::orthographic(l, rt, b, t, n, z),
        );
        assert_eq!((ro.x_axis, ro.y_axis, ro.w_axis), (lo.x_axis, lo.y_axis, lo.w_axis));
        assert!(near_raw(ro.z_axis.z, -lo.z_axis.z, 1), "rh ortho zz");
        let (ld, rd) = (
            lh_directx::orthographic(l, rt, b, t, n, z),
            rh_directx::orthographic(l, rt, b, t, n, z),
        );
        assert!(near_raw(rd.z_axis.z, -ld.z_axis.z, 1), "rh ortho zz");
        let lv = lh_vulkan::orthographic(l, rt, b, t, n, z);
        assert!(near_raw(lv.y_axis.y, -ld.y_axis.y, 1), "vulkan ortho yy");
        // glam-rs does not flip the Y translation
        assert_eq!(lv.w_axis, ld.w_axis);
        assert_eq!(lv.x_axis, ld.x_axis);
        assert_eq!(lv.z_axis, ld.z_axis);
    }
}

/// The `[-1, 1]` depth range is the `[0, 1]` one mapped by `2 z - 1`.
#[test]
fn test_opengl_vs_directx_depth() {
    for row in PARAMS.span() {
        let r = row.span();
        let (fov, a, n, z) = (f(*r[0]), f(*r[1]), f(*r[2]), f(*r[3]));
        let (l, rt, b, t) = (f(*r[4]), f(*r[5]), f(*r[6]), f(*r[7]));
        let (g, d) = (lh_opengl::perspective(fov, a, n, z), lh_directx::perspective(fov, a, n, z));
        assert_eq!((g.x_axis, g.y_axis, g.z_axis.w), (d.x_axis, d.y_axis, d.z_axis.w));
        // `2 q - 1` exactly; `-2 near q` is one floor of the doubled product: 0 or 1 ULP above
        // twice the floor of `-near q`
        assert_eq!(g.z_axis.z, d.z_axis.z + d.z_axis.z - ONE);
        assert!(near_raw(g.w_axis.z, d.w_axis.z + d.w_axis.z, 1), "perspective tz");
        let (g, d) = (
            lh_opengl::frustum(l, rt, b, t, n, z), lh_directx::frustum(l, rt, b, t, n, z),
        );
        assert_eq!(
            (g.x_axis, g.y_axis, g.z_axis.x, g.z_axis.y),
            (d.x_axis, d.y_axis, d.z_axis.x, d.z_axis.y),
        );
        assert_eq!(g.z_axis.z, d.z_axis.z + d.z_axis.z - ONE);
        assert!(near_raw(g.w_axis.z, d.w_axis.z + d.w_axis.z, 1), "frustum tz");
        // the depth terms of a frustum are the ones of the perspective of the same near / far
        let p = lh_directx::perspective(fov, a, n, z);
        assert_eq!((d.z_axis.z, d.z_axis.w, d.w_axis.z), (p.z_axis.z, p.z_axis.w, p.w_axis.z));
        // orthographic: two quotients per term, each within 1 ULP of the exact one
        let (g, d) = (
            lh_opengl::orthographic(l, rt, b, t, n, z), lh_directx::orthographic(l, rt, b, t, n, z),
        );
        assert_eq!((g.x_axis, g.y_axis), (d.x_axis, d.y_axis));
        assert!(near_raw(g.z_axis.z, d.z_axis.z + d.z_axis.z, 1), "ortho zz");
        // -(far + near) / d = 2 (-near / d) - 1: three roundings to nearest
        assert!(near_raw(g.w_axis.z, d.w_axis.z + d.w_axis.z - ONE, 2), "ortho tz");
    }
}

// The view constructors. Row: eye, direction / center, up (raw).
const VIEWS: [[i64; 9]; 4] = [
    [0x100000000, 0x200000000, 0x300000000, 0x6db6db6d, 0xdb6db6db, 0x49249249, 0, 0x100000000, 0],
    [-0x500000000, 0, 0x700000000, 0, 0, -0x100000000, 0, 0x100000000, 0],
    [0x30000000, -0x20000000, 0x500000000, 0x100000000, 0, 0, 0, 0, 0x100000000],
    [0, 0, 0, -0x49249249, 0x6db6db6d, 0xdb6db6db, 0x100000000, 0, 0],
];

fn rot(m: Mat4) -> Mat3 {
    Mat3 {
        x_axis: v3(m.x_axis.x, m.x_axis.y, m.x_axis.z),
        y_axis: v3(m.y_axis.x, m.y_axis.y, m.y_axis.z),
        z_axis: v3(m.z_axis.x, m.z_axis.y, m.z_axis.z),
    }
}

/// The view constructors are `Mat4::look_*` bit for bit (inlined), and the `Mat3` ones are the
/// rotation block of the `Mat4` ones.
#[test]
fn test_view_matches_mat4() {
    for row in VIEWS.span() {
        let r = row.span();
        let e = v3(f(*r[0]), f(*r[1]), f(*r[2]));
        let d = v3(f(*r[3]), f(*r[4]), f(*r[5]));
        let u = v3(f(*r[6]), f(*r[7]), f(*r[8]));
        assert_eq!(rh_view::look_to_mat4(e, d, u), Mat4Trait::look_to_rh(e, d, u));
        assert_eq!(lh_view::look_to_mat4(e, d, u), Mat4Trait::look_to_lh(e, d, u));
        assert_eq!(rh_view::look_at_mat4(e, d, u), Mat4Trait::look_at_rh(e, d, u));
        assert_eq!(lh_view::look_at_mat4(e, d, u), Mat4Trait::look_at_lh(e, d, u));
        assert_eq!(rh_view::look_to_mat3(d, u), rot(Mat4Trait::look_to_rh(e, d, u)));
        assert_eq!(lh_view::look_to_mat3(d, u), rot(Mat4Trait::look_to_lh(e, d, u)));
        assert_eq!(rh_view::look_at_mat3(e, d, u), rot(Mat4Trait::look_at_rh(e, d, u)));
        assert_eq!(lh_view::look_at_mat3(e, d, u), rot(Mat4Trait::look_at_lh(e, d, u)));
        assert_eq!(
            rh_view::look_to_affine3(e, d, u),
            Affine3Trait::from_mat4(rh_view::look_to_mat4(e, d, u)),
        );
        assert_eq!(
            lh_view::look_to_affine3(e, d, u),
            Affine3Trait::from_mat4(lh_view::look_to_mat4(e, d, u)),
        );
        assert_eq!(
            rh_view::look_at_affine3(e, d, u),
            Affine3Trait::from_mat4(rh_view::look_at_mat4(e, d, u)),
        );
        assert_eq!(
            lh_view::look_at_affine3(e, d, u),
            Affine3Trait::from_mat4(lh_view::look_at_mat4(e, d, u)),
        );
        assert_eq!(rh_view::look_to_quat(d, u), QuatTrait::from_mat3(rh_view::look_to_mat3(d, u)));
        assert_eq!(lh_view::look_to_quat(d, u), QuatTrait::from_mat3(lh_view::look_to_mat3(d, u)));
        assert_eq!(
            rh_view::look_at_quat(e, d, u), QuatTrait::from_mat3(rh_view::look_at_mat3(e, d, u)),
        );
        assert_eq!(
            lh_view::look_at_quat(e, d, u), QuatTrait::from_mat3(lh_view::look_at_mat3(e, d, u)),
        );
    }
}

/// Exact view matrices: looking down -Z (identity rotation), looking down +X.
#[test]
fn test_view_exact() {
    let (o, z, e) = (ONE, q(0), v3(q(4), q(8), q(12)));
    let up = v3(z, o, z);
    let ident = Mat3 { x_axis: v3(o, z, z), y_axis: v3(z, o, z), z_axis: v3(z, z, o) };
    let neg = Vec4 { x: -o, y: -o - o, z: -o - o - o, w: o };
    let m = Mat4 {
        x_axis: Vec4 { x: o, ..z4() },
        y_axis: Vec4 { y: o, ..z4() },
        z_axis: Vec4 { z: o, ..z4() },
        w_axis: neg,
    };
    // right-handed: forward is -Z
    assert_eq!(rh_view::look_to_mat4(e, v3(z, z, -o), up), m);
    assert_eq!(rh_view::look_at_mat4(e, v3(q(4), q(8), q(-4)), up), m);
    assert_eq!(rh_view::look_to_mat3(v3(z, z, -o), up), ident);
    assert_eq!(rh_view::look_at_mat3(e, v3(q(4), q(8), q(-4)), up), ident);
    // left-handed: forward is +Z
    assert_eq!(lh_view::look_to_mat4(e, v3(z, z, o), up), m);
    assert_eq!(lh_view::look_at_mat4(e, v3(q(4), q(8), q(28)), up), m);
    assert_eq!(lh_view::look_to_mat3(v3(z, z, o), up), ident);
    assert_eq!(lh_view::look_at_mat3(e, v3(q(4), q(8), q(28)), up), ident);
    // looking along +X: s = +Z, u = +Y; the eye maps to the origin, `eye + 5 dir` to (0, 0, -5)
    let yaw = Mat3 { x_axis: v3(z, z, -o), y_axis: v3(z, o, z), z_axis: v3(o, z, z) };
    let m = rh_view::look_to_mat4(e, v3(o, z, z), up);
    assert_eq!(rot(m), yaw);
    assert_eq!(m.w_axis, Vec4 { x: -q(12), y: -q(8), z: q(4), w: o });
    assert_eq!(m.transform_point3(e), v3(z, z, z));
    assert_eq!(m.transform_point3(v3(q(24), q(8), q(12))), v3(z, z, -q(20)));
    let m = lh_view::look_to_mat4(e, v3(o, z, z), up);
    assert_eq!(m.transform_point3(v3(q(24), q(8), q(12))), v3(z, z, q(20)));
}

/// The usable range: `far` up to the top of the scalar range, a reversed depth range.
#[test]
fn test_perspective_range() {
    // far = MAX: q = far / (far - 1) = 1 + 2^-31 (raw 2^32 + 2), the depth terms of the [0, 1]
    // range
    let m = lh_directx::perspective(FRAC_PI_2, ONE, ONE, MAX);
    assert!(near_raw(m.z_axis.z, ONE, 3) && m.z_axis.z.raw > ONE.raw, "zz at far = MAX");
    assert_eq!(m.w_axis.z, -m.z_axis.z);
    let g = lh_opengl::perspective(FRAC_PI_2, ONE, ONE, MAX);
    assert_eq!(g.z_axis.z, m.z_axis.z + m.z_axis.z - ONE);
    assert_eq!(g.w_axis.z, -(m.z_axis.z + m.z_axis.z));
    // reversed depth (near > far) is accepted, as in glam-rs: near maps to 0 and far to 1
    let m = lh_directx::perspective(FRAC_PI_2, ONE, q(400), ONE);
    assert!(m.z_axis.z.raw < 0 && m.w_axis.z.raw > 0, "reversed depth signs");
    // a field of view of 6 raw ULP is the narrowest one: cot(3 raw) = 2^64 / 3 raw
    let m = lh_directx::perspective_infinite(f(6), ONE, ONE);
    assert_eq!(m.y_axis.y.raw, 6148914691236517205);
    assert_eq!(m.x_axis.x, m.y_axis.y);
    // the widest one, PI - 1 raw ULP: cot is (nearly) zero
    let m = lh_directx::perspective_infinite(f(13493037704), ONE, ONE);
    assert!(m.y_axis.y.raw >= 0 && m.y_axis.y.raw <= 2, "cot at PI - 1 ULP");
}

/// A value in `[lo, hi]` (raw) from a `u32`, for the fuzz properties.
fn pick(a: u32, lo: i64, hi: i64) -> Fixed {
    let k: i64 = (a % 1048576).into();
    f(lo + k * ((hi - lo) / 1048576))
}

/// Projects the point at `dist` on the axis (`-dist` for right-handed) and returns the NDC depth.
fn depth_of(m: Mat4, rh: bool, dist: Fixed) -> Fixed {
    let z = if rh {
        -dist
    } else {
        dist
    };
    m.project_point3(v3(q(0), q(0), z)).z
}

// The depth mapping of the perspective and frustum constructors: `near` maps to -1 / 0 and `far`
// to 1 within 13 ULP, for `near` in [0.25, 8] and `far` in `near * [1.5, 50]`. The clip depth is
// off by `1` (the floored dot) plus `zz` (2 ULP at most, 1 for the [0, 1] range) times the distance
// plus `tz` (`2 near + 1` at most): over `w = near` that is `4 + 2 / near <= 12` and over `w = far`
// `2 + (2 near + 2) / far <= 10` ULP, plus 1 for the rounded division.
#[test]
#[fuzzer(runs: 128, seed: 901)]
fn fuzz_perspective_depth_maps_near_far(a: u32, b: u32, c: u32, d: u32) {
    let (fov, asp) = (pick(a, 3435973837, 11166914970), pick(b, 2147483648, 17179869184));
    let n = pick(c, 1073741824, 34359738368);
    let z = n * pick(d, 6442450944, 214748364800);
    let (m1, tol) = (q(-4), 13);
    let (one, zero) = (ONE, q(0));
    let (lg, ld) = (
        lh_opengl::perspective(fov, asp, n, z), lh_directx::perspective(fov, asp, n, z),
    );
    let (rg, rd) = (rh_opengl::perspective(fov, asp, n, z), rh_vulkan::perspective(fov, asp, n, z));
    assert!(near_raw(depth_of(lg, false, n), m1, tol), "lh gl near");
    assert!(near_raw(depth_of(rg, true, n), m1, tol), "rh gl near");
    assert!(near_raw(depth_of(ld, false, n), zero, tol), "lh dx near");
    assert!(near_raw(depth_of(rd, true, n), zero, tol), "rh vk near");
    assert!(near_raw(depth_of(lg, false, z), one, tol), "lh gl far");
    assert!(near_raw(depth_of(rg, true, z), one, tol), "rh gl far");
    assert!(near_raw(depth_of(ld, false, z), one, tol), "lh dx far");
    assert!(near_raw(depth_of(rd, true, z), one, tol), "rh vk far");
    // a frustum has the same depth terms
    let (l, r) = (-n, n);
    let (fl, fr) = (lh_opengl::frustum(l, r, l, r, n, z), rh_directx::frustum(l, r, l, r, n, z));
    assert!(near_raw(depth_of(fl, false, n), m1, tol), "frustum gl near");
    assert!(near_raw(depth_of(fr, true, z), one, tol), "frustum dx far");
}

// The relations between the variants on random parameters (exact, see
// `test_lh_rh_and_vulkan_relations`).
#[test]
#[fuzzer(runs: 128, seed: 902)]
fn fuzz_relations(a: u32, b: u32, c: u32, d: u32, e: u32, g: u32) {
    let (fov, asp) = (pick(a, 3435973837, 11166914970), pick(b, 2147483648, 17179869184));
    let n = pick(c, 1073741824, 34359738368);
    let z = n * pick(d, 6442450944, 214748364800);
    let (l, r) = (pick(e, -214748364800, -2147483648), pick(g, 2147483648, 214748364800));
    let (bt, t) = (
        pick(a / 2 + e / 2, -214748364800, -2147483648),
        pick(b / 2 + g / 2, 2147483648, 214748364800),
    );
    assert_eq!(
        rh_opengl::perspective(fov, asp, n, z), flip_z(lh_opengl::perspective(fov, asp, n, z)),
    );
    assert_eq!(
        rh_vulkan::frustum(l, r, bt, t, n, z), flip_z(lh_vulkan::frustum(l, r, bt, t, n, z)),
    );
    assert_eq!(
        lh_vulkan::perspective(fov, asp, n, z),
        flip_y(lh_directx::perspective(fov, asp, n, z), false),
    );
    assert_eq!(
        rh_vulkan::frustum(l, r, bt, t, n, z), flip_y(rh_directx::frustum(l, r, bt, t, n, z), true),
    );
    let (g, d) = (lh_opengl::perspective(fov, asp, n, z), lh_directx::perspective(fov, asp, n, z));
    assert_eq!(g.z_axis.z, d.z_axis.z + d.z_axis.z - ONE);
    assert!(near_raw(g.w_axis.z, d.w_axis.z + d.w_axis.z, 1), "perspective tz");
}

// The box of an orthographic maps to the NDC cube. Coordinates are at most 64, and each of
// `xx`, `yy`, `zz` is a quotient rounded to nearest (within 1 ULP), so `xx * x` is within 64 ULP,
// plus 1 for the translation and 1 for the floored dot: 66 ULP.
#[test]
#[fuzzer(runs: 128, seed: 903)]
fn fuzz_orthographic_box_to_cube(a: u32, b: u32, c: u32, d: u32, e: u32, g: u32) {
    let (l, r) = (pick(a, -68719476736, -2147483648), pick(b, 2147483648, 68719476736));
    let (bt, t) = (pick(c, -68719476736, -2147483648), pick(d, 2147483648, 68719476736));
    let n = pick(e, 1073741824, 34359738368);
    let z = n * pick(g, 6442450944, 32212254720);
    let (m1, p1, z0, tol) = (q(-4), q(4), q(0), 66);
    let m = lh_opengl::orthographic(l, r, bt, t, n, z);
    let k = rh_directx::orthographic(l, r, bt, t, n, z);
    let p = m.project_point3(v3(l, bt, n));
    assert!(near_raw(p.x, m1, tol) && near_raw(p.y, m1, tol) && near_raw(p.z, m1, tol), "gl min");
    let p = m.project_point3(v3(r, t, z));
    assert!(near_raw(p.x, p1, tol) && near_raw(p.y, p1, tol) && near_raw(p.z, p1, tol), "gl max");
    let p = k.project_point3(v3(l, bt, -n));
    assert!(near_raw(p.x, m1, tol) && near_raw(p.y, m1, tol) && near_raw(p.z, z0, tol), "dx min");
    let p = k.project_point3(v3(r, t, -z));
    assert!(near_raw(p.x, p1, tol) && near_raw(p.y, p1, tol) && near_raw(p.z, p1, tol), "dx max");
}

// Panic paths.

// panics: camera::rh::proj::opengl::perspective
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_perspective_fov_zero() {
    let _ = rh_opengl::perspective(q(0), ONE, ONE, q(8));
}

// panics: camera::lh::proj::vulkan::perspective
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_perspective_fov_pi() {
    let _ = lh_vulkan::perspective(PI, ONE, ONE, q(8));
}

// panics: camera::rh::proj::directx::perspective_infinite
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_perspective_infinite_fov_negative() {
    let _ = rh_directx::perspective_infinite(-ONE, ONE, ONE);
}

// panics: camera::lh::proj::directx::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_perspective_infinite_reverse_fov_too_wide() {
    let _ = lh_directx::perspective_infinite_reverse(q(16), ONE, ONE);
}

// panics: camera::rh::proj::opengl::perspective
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_perspective_aspect_zero() {
    let _ = rh_opengl::perspective(FRAC_PI_2, q(0), ONE, q(8));
}

// panics: camera::lh::proj::vulkan::perspective_infinite
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_perspective_infinite_aspect_zero() {
    let _ = lh_vulkan::perspective_infinite(FRAC_PI_2, q(0), ONE);
}

// panics: camera::lh::proj::opengl::perspective
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_perspective_near_zero() {
    let _ = lh_opengl::perspective(FRAC_PI_2, ONE, q(0), q(8));
}

// panics: camera::rh::proj::vulkan::perspective_infinite
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_perspective_infinite_near_negative() {
    let _ = rh_vulkan::perspective_infinite(FRAC_PI_2, ONE, -ONE);
}

// panics: camera::rh::proj::directx::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_perspective_infinite_reverse_near_zero() {
    let _ = rh_directx::perspective_infinite_reverse(FRAC_PI_2, ONE, q(0));
}

// panics: camera::lh::proj::directx::frustum
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_frustum_near_zero() {
    let _ = lh_directx::frustum(q(-4), q(4), q(-4), q(4), q(0), q(8));
}

// panics: camera::rh::proj::directx::perspective
#[test]
#[should_panic(expected: 'camera: far not positive')]
fn test_perspective_far_zero() {
    let _ = rh_directx::perspective(FRAC_PI_2, ONE, ONE, q(0));
}

// panics: camera::rh::proj::vulkan::frustum
#[test]
#[should_panic(expected: 'camera: far not positive')]
fn test_frustum_far_negative() {
    let _ = rh_vulkan::frustum(q(-4), q(4), q(-4), q(4), ONE, -ONE);
}

// panics: camera::lh::proj::opengl::perspective
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_perspective_near_equals_far() {
    let _ = lh_opengl::perspective(FRAC_PI_2, ONE, ONE, ONE);
}

// panics: camera::rh::proj::opengl::frustum
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_frustum_near_equals_far() {
    let _ = rh_opengl::frustum(q(-4), q(4), q(-4), q(4), ONE, ONE);
}

// panics: camera::rh::proj::vulkan::orthographic
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_orthographic_near_equals_far() {
    let _ = rh_vulkan::orthographic(q(-4), q(4), q(-4), q(4), ONE, ONE);
}

// panics: camera::lh::proj::opengl::orthographic
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_orthographic_left_equals_right() {
    let _ = lh_opengl::orthographic(ONE, ONE, q(-4), q(4), ONE, q(8));
}

// panics: camera::lh::proj::directx::perspective_infinite
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_perspective_infinite_fov_one_ulp() {
    let _ = lh_directx::perspective_infinite(f(1), ONE, ONE);
}

// panics: camera::lh::proj::directx::perspective_infinite
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_perspective_infinite_fov_four_ulp() {
    let _ = lh_directx::perspective_infinite(f(4), ONE, ONE);
}

// panics: camera::lh::proj::opengl::perspective
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_perspective_depth_overflow() {
    // tz = 2 * near * far / (far - near) ~ 2^32
    let _ = lh_opengl::perspective(FRAC_PI_2, ONE, f(0x4000000000000000), MAX);
}

// panics: camera::rh::proj::directx::perspective
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_perspective_depth_quotient_overflow() {
    // far / (far - near) = 100 * 2^32
    let _ = rh_directx::perspective(FRAC_PI_2, ONE, q(400), q(400) + f(1));
}

// panics: camera::rh::view::look_at_mat4
#[test]
#[should_panic(expected: 'Vec3: normalize zero')]
fn test_look_at_center_is_eye() {
    let e = v3(ONE, ONE, ONE);
    let _ = rh_view::look_at_mat4(e, e, v3(q(0), ONE, q(0)));
}

// panics: camera::lh::view::look_to_mat3
#[test]
#[should_panic(expected: 'Vec3: normalize zero')]
fn test_look_to_parallel_up() {
    let _ = lh_view::look_to_mat3(v3(q(0), ONE, q(0)), v3(q(0), ONE, q(0)));
}

// panics: camera::rh::view::look_at_affine3
#[test]
#[should_panic(expected: 'Vec3: normalize zero')]
fn test_look_at_affine3_center_is_eye() {
    let e = v3(ONE, ONE, ONE);
    let _ = rh_view::look_at_affine3(e, e, v3(q(0), ONE, q(0)));
}

// panics: camera::lh::view::look_to_quat
#[test]
#[should_panic(expected: 'Vec3: normalize zero')]
fn test_look_to_quat_parallel_up() {
    let y = v3(q(0), ONE, q(0));
    let _ = lh_view::look_to_quat(y, y);
}


// panics: camera::lh::proj::opengl::perspective
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_lh_opengl_perspective_fov_zero() {
    let _ = lh_opengl::perspective(q(0), ONE, ONE, q(8));
}

// panics: camera::lh::proj::opengl::perspective
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_lh_opengl_perspective_aspect_zero() {
    let _ = lh_opengl::perspective(FRAC_PI_2, q(0), ONE, q(8));
}

// panics: camera::lh::proj::opengl::perspective
#[test]
#[should_panic(expected: 'camera: far not positive')]
fn test_lh_opengl_perspective_far_zero() {
    let _ = lh_opengl::perspective(FRAC_PI_2, ONE, ONE, q(0));
}

// panics: camera::lh::proj::opengl::orthographic
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_opengl_orthographic_width_one_ulp() {
    let _ = lh_opengl::orthographic(q(0), f(1), q(-4), q(4), ONE, q(8));
}

// panics: camera::lh::proj::opengl::frustum
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_lh_opengl_frustum_near_zero() {
    let _ = lh_opengl::frustum(q(-4), q(4), q(-4), q(4), q(0), q(8));
}

// panics: camera::lh::proj::opengl::frustum
#[test]
#[should_panic(expected: 'camera: far not positive')]
fn test_lh_opengl_frustum_far_zero() {
    let _ = lh_opengl::frustum(q(-4), q(4), q(-4), q(4), ONE, q(0));
}

// panics: camera::lh::proj::opengl::frustum
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_lh_opengl_frustum_near_equals_far() {
    let _ = lh_opengl::frustum(q(-4), q(4), q(-4), q(4), ONE, ONE);
}

// panics: camera::lh::proj::opengl::frustum
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_opengl_frustum_depth_overflow() {
    let _ = lh_opengl::frustum(q(-4), q(4), q(-4), q(4), q(400), q(400) + f(1));
}

// panics: camera::lh::proj::vulkan::perspective
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_lh_vulkan_perspective_aspect_zero() {
    let _ = lh_vulkan::perspective(FRAC_PI_2, q(0), ONE, q(8));
}

// panics: camera::lh::proj::vulkan::perspective
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_lh_vulkan_perspective_near_zero() {
    let _ = lh_vulkan::perspective(FRAC_PI_2, ONE, q(0), q(8));
}

// panics: camera::lh::proj::vulkan::perspective
#[test]
#[should_panic(expected: 'camera: far not positive')]
fn test_lh_vulkan_perspective_far_zero() {
    let _ = lh_vulkan::perspective(FRAC_PI_2, ONE, ONE, q(0));
}

// panics: camera::lh::proj::vulkan::perspective
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_lh_vulkan_perspective_near_equals_far() {
    let _ = lh_vulkan::perspective(FRAC_PI_2, ONE, ONE, ONE);
}

// panics: camera::lh::proj::vulkan::perspective
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_vulkan_perspective_fov_four_ulp() {
    let _ = lh_vulkan::perspective(f(4), ONE, ONE, q(8));
}

// panics: camera::lh::proj::vulkan::perspective_infinite
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_lh_vulkan_perspective_infinite_fov_pi() {
    let _ = lh_vulkan::perspective_infinite(PI, ONE, ONE);
}

// panics: camera::lh::proj::vulkan::perspective_infinite
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_lh_vulkan_perspective_infinite_near_zero() {
    let _ = lh_vulkan::perspective_infinite(FRAC_PI_2, ONE, q(0));
}

// panics: camera::lh::proj::vulkan::perspective_infinite
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_lh_vulkan_perspective_infinite_fov_one_ulp() {
    let _ = lh_vulkan::perspective_infinite(f(1), ONE, ONE);
}

// panics: camera::lh::proj::vulkan::perspective_infinite
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_vulkan_perspective_infinite_fov_four_ulp() {
    let _ = lh_vulkan::perspective_infinite(f(4), ONE, ONE);
}

// panics: camera::lh::proj::vulkan::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_lh_vulkan_perspective_infinite_reverse_fov_pi() {
    let _ = lh_vulkan::perspective_infinite_reverse(PI, ONE, ONE);
}

// panics: camera::lh::proj::vulkan::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_lh_vulkan_perspective_infinite_reverse_aspect_zero() {
    let _ = lh_vulkan::perspective_infinite_reverse(FRAC_PI_2, q(0), ONE);
}

// panics: camera::lh::proj::vulkan::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_lh_vulkan_perspective_infinite_reverse_near_zero() {
    let _ = lh_vulkan::perspective_infinite_reverse(FRAC_PI_2, ONE, q(0));
}

// panics: camera::lh::proj::vulkan::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_lh_vulkan_perspective_infinite_reverse_fov_one_ulp() {
    let _ = lh_vulkan::perspective_infinite_reverse(f(1), ONE, ONE);
}

// panics: camera::lh::proj::vulkan::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_vulkan_perspective_infinite_reverse_fov_four_ulp() {
    let _ = lh_vulkan::perspective_infinite_reverse(f(4), ONE, ONE);
}

// panics: camera::lh::proj::vulkan::orthographic
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_lh_vulkan_orthographic_left_equals_right() {
    let _ = lh_vulkan::orthographic(ONE, ONE, q(-4), q(4), ONE, q(8));
}

// panics: camera::lh::proj::vulkan::orthographic
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_vulkan_orthographic_width_one_ulp() {
    let _ = lh_vulkan::orthographic(q(0), f(1), q(-4), q(4), ONE, q(8));
}

// panics: camera::lh::proj::vulkan::frustum
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_lh_vulkan_frustum_near_zero() {
    let _ = lh_vulkan::frustum(q(-4), q(4), q(-4), q(4), q(0), q(8));
}

// panics: camera::lh::proj::vulkan::frustum
#[test]
#[should_panic(expected: 'camera: far not positive')]
fn test_lh_vulkan_frustum_far_zero() {
    let _ = lh_vulkan::frustum(q(-4), q(4), q(-4), q(4), ONE, q(0));
}

// panics: camera::lh::proj::vulkan::frustum
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_lh_vulkan_frustum_near_equals_far() {
    let _ = lh_vulkan::frustum(q(-4), q(4), q(-4), q(4), ONE, ONE);
}

// panics: camera::lh::proj::vulkan::frustum
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_vulkan_frustum_depth_overflow() {
    let _ = lh_vulkan::frustum(q(-4), q(4), q(-4), q(4), q(400), q(400) + f(1));
}

// panics: camera::lh::proj::directx::perspective
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_lh_directx_perspective_fov_zero() {
    let _ = lh_directx::perspective(q(0), ONE, ONE, q(8));
}

// panics: camera::lh::proj::directx::perspective
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_lh_directx_perspective_aspect_zero() {
    let _ = lh_directx::perspective(FRAC_PI_2, q(0), ONE, q(8));
}

// panics: camera::lh::proj::directx::perspective
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_lh_directx_perspective_near_zero() {
    let _ = lh_directx::perspective(FRAC_PI_2, ONE, q(0), q(8));
}

// panics: camera::lh::proj::directx::perspective
#[test]
#[should_panic(expected: 'camera: far not positive')]
fn test_lh_directx_perspective_far_zero() {
    let _ = lh_directx::perspective(FRAC_PI_2, ONE, ONE, q(0));
}

// panics: camera::lh::proj::directx::perspective
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_lh_directx_perspective_near_equals_far() {
    let _ = lh_directx::perspective(FRAC_PI_2, ONE, ONE, ONE);
}

// panics: camera::lh::proj::directx::perspective
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_directx_perspective_fov_four_ulp() {
    let _ = lh_directx::perspective(f(4), ONE, ONE, q(8));
}

// panics: camera::lh::proj::directx::perspective_infinite
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_lh_directx_perspective_infinite_fov_pi() {
    let _ = lh_directx::perspective_infinite(PI, ONE, ONE);
}

// panics: camera::lh::proj::directx::perspective_infinite
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_lh_directx_perspective_infinite_aspect_zero() {
    let _ = lh_directx::perspective_infinite(FRAC_PI_2, q(0), ONE);
}

// panics: camera::lh::proj::directx::perspective_infinite
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_lh_directx_perspective_infinite_near_zero() {
    let _ = lh_directx::perspective_infinite(FRAC_PI_2, ONE, q(0));
}

// panics: camera::lh::proj::directx::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_lh_directx_perspective_infinite_reverse_aspect_zero() {
    let _ = lh_directx::perspective_infinite_reverse(FRAC_PI_2, q(0), ONE);
}

// panics: camera::lh::proj::directx::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_lh_directx_perspective_infinite_reverse_near_zero() {
    let _ = lh_directx::perspective_infinite_reverse(FRAC_PI_2, ONE, q(0));
}

// panics: camera::lh::proj::directx::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_lh_directx_perspective_infinite_reverse_fov_one_ulp() {
    let _ = lh_directx::perspective_infinite_reverse(f(1), ONE, ONE);
}

// panics: camera::lh::proj::directx::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_directx_perspective_infinite_reverse_fov_four_ulp() {
    let _ = lh_directx::perspective_infinite_reverse(f(4), ONE, ONE);
}

// panics: camera::lh::proj::directx::orthographic
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_lh_directx_orthographic_left_equals_right() {
    let _ = lh_directx::orthographic(ONE, ONE, q(-4), q(4), ONE, q(8));
}

// panics: camera::lh::proj::directx::orthographic
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_directx_orthographic_width_one_ulp() {
    let _ = lh_directx::orthographic(q(0), f(1), q(-4), q(4), ONE, q(8));
}

// panics: camera::lh::proj::directx::frustum
#[test]
#[should_panic(expected: 'camera: far not positive')]
fn test_lh_directx_frustum_far_zero() {
    let _ = lh_directx::frustum(q(-4), q(4), q(-4), q(4), ONE, q(0));
}

// panics: camera::lh::proj::directx::frustum
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_lh_directx_frustum_near_equals_far() {
    let _ = lh_directx::frustum(q(-4), q(4), q(-4), q(4), ONE, ONE);
}

// panics: camera::lh::proj::directx::frustum
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_directx_frustum_depth_overflow() {
    let _ = lh_directx::frustum(q(-4), q(4), q(-4), q(4), q(400), q(400) + f(1));
}

// panics: camera::lh::view::look_at_mat4
#[test]
#[should_panic(expected: 'Vec3: normalize zero')]
fn test_lh_look_at_mat4_center_is_eye() {
    let _ = lh_view::look_at_mat4(v3(q(0), ONE, q(0)), v3(q(0), ONE, q(0)), v3(q(0), ONE, q(0)));
}

// panics: camera::lh::view::look_at_mat4
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_look_at_mat4_cross_overflow() {
    let _ = lh_view::look_at_mat4(v3(q(0), q(0), q(0)), v3(ONE, ONE, q(0)), v3(-MAX, MAX, q(0)));
}

// panics: camera::lh::view::look_at_mat4
#[test]
#[should_panic(expected: 'i64_neg Underflow')]
fn test_lh_look_at_mat4_eye_min() {
    let _ = lh_view::look_at_mat4(v3(MIN, q(0), q(0)), v3(MIN, q(0), ONE), v3(q(0), ONE, q(0)));
}

// panics: camera::lh::view::look_at_mat4
#[test]
#[should_panic(expected: 'i64_sub Underflow')]
fn test_lh_look_at_mat4_center_minus_eye() {
    let _ = lh_view::look_at_mat4(v3(ONE, q(0), q(0)), v3(MIN, q(0), q(0)), v3(q(0), ONE, q(0)));
}

// panics: camera::lh::view::look_to_mat4
#[test]
#[should_panic(expected: 'Vec3: normalize zero')]
fn test_lh_look_to_mat4_parallel_up() {
    let _ = lh_view::look_to_mat4(v3(q(0), q(0), q(0)), v3(q(0), ONE, q(0)), v3(q(0), ONE, q(0)));
}

// panics: camera::lh::view::look_to_mat4
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_look_to_mat4_cross_overflow() {
    let _ = lh_view::look_to_mat4(v3(q(0), q(0), q(0)), v3(MAX, q(0), q(0)), v3(q(0), q(8), q(0)));
}

// panics: camera::lh::view::look_to_mat4
#[test]
#[should_panic(expected: 'i64_neg Underflow')]
fn test_lh_look_to_mat4_dir_min() {
    let _ = lh_view::look_to_mat4(v3(q(0), q(0), q(0)), v3(MIN, q(0), q(0)), v3(q(0), -f(1), q(0)));
}

// panics: camera::lh::view::look_at_mat3
#[test]
#[should_panic(expected: 'Vec3: normalize zero')]
fn test_lh_look_at_mat3_center_is_eye() {
    let _ = lh_view::look_at_mat3(v3(q(0), ONE, q(0)), v3(q(0), ONE, q(0)), v3(q(0), ONE, q(0)));
}

// panics: camera::lh::view::look_at_mat3
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_look_at_mat3_cross_overflow() {
    let _ = lh_view::look_at_mat3(v3(q(0), q(0), q(0)), v3(ONE, ONE, q(0)), v3(-MAX, MAX, q(0)));
}

// panics: camera::lh::view::look_at_mat3
#[test]
#[should_panic(expected: 'i64_sub Underflow')]
fn test_lh_look_at_mat3_center_minus_eye() {
    let _ = lh_view::look_at_mat3(v3(ONE, q(0), q(0)), v3(MIN, q(0), q(0)), v3(q(0), ONE, q(0)));
}

// panics: camera::lh::view::look_to_mat3
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_lh_look_to_mat3_cross_overflow() {
    let _ = lh_view::look_to_mat3(v3(MAX, q(0), q(0)), v3(q(0), q(8), q(0)));
}

// panics: camera::lh::view::look_to_mat3
#[test]
#[should_panic(expected: 'i64_neg Underflow')]
fn test_lh_look_to_mat3_dir_min() {
    let _ = lh_view::look_to_mat3(v3(MIN, q(0), q(0)), v3(q(0), -f(1), q(0)));
}

// panics: camera::rh::proj::opengl::perspective
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_rh_opengl_perspective_near_zero() {
    let _ = rh_opengl::perspective(FRAC_PI_2, ONE, q(0), q(8));
}

// panics: camera::rh::proj::opengl::perspective
#[test]
#[should_panic(expected: 'camera: far not positive')]
fn test_rh_opengl_perspective_far_zero() {
    let _ = rh_opengl::perspective(FRAC_PI_2, ONE, ONE, q(0));
}

// panics: camera::rh::proj::opengl::perspective
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_rh_opengl_perspective_near_equals_far() {
    let _ = rh_opengl::perspective(FRAC_PI_2, ONE, ONE, ONE);
}

// panics: camera::rh::proj::opengl::perspective
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_opengl_perspective_fov_four_ulp() {
    let _ = rh_opengl::perspective(f(4), ONE, ONE, q(8));
}

// panics: camera::rh::proj::opengl::orthographic
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_rh_opengl_orthographic_left_equals_right() {
    let _ = rh_opengl::orthographic(ONE, ONE, q(-4), q(4), ONE, q(8));
}

// panics: camera::rh::proj::opengl::orthographic
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_opengl_orthographic_width_one_ulp() {
    let _ = rh_opengl::orthographic(q(0), f(1), q(-4), q(4), ONE, q(8));
}

// panics: camera::rh::proj::opengl::frustum
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_rh_opengl_frustum_near_zero() {
    let _ = rh_opengl::frustum(q(-4), q(4), q(-4), q(4), q(0), q(8));
}

// panics: camera::rh::proj::opengl::frustum
#[test]
#[should_panic(expected: 'camera: far not positive')]
fn test_rh_opengl_frustum_far_zero() {
    let _ = rh_opengl::frustum(q(-4), q(4), q(-4), q(4), ONE, q(0));
}

// panics: camera::rh::proj::opengl::frustum
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_opengl_frustum_depth_overflow() {
    let _ = rh_opengl::frustum(q(-4), q(4), q(-4), q(4), q(400), q(400) + f(1));
}

// panics: camera::rh::proj::vulkan::perspective
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_rh_vulkan_perspective_fov_zero() {
    let _ = rh_vulkan::perspective(q(0), ONE, ONE, q(8));
}

// panics: camera::rh::proj::vulkan::perspective
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_rh_vulkan_perspective_aspect_zero() {
    let _ = rh_vulkan::perspective(FRAC_PI_2, q(0), ONE, q(8));
}

// panics: camera::rh::proj::vulkan::perspective
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_rh_vulkan_perspective_near_zero() {
    let _ = rh_vulkan::perspective(FRAC_PI_2, ONE, q(0), q(8));
}

// panics: camera::rh::proj::vulkan::perspective
#[test]
#[should_panic(expected: 'camera: far not positive')]
fn test_rh_vulkan_perspective_far_zero() {
    let _ = rh_vulkan::perspective(FRAC_PI_2, ONE, ONE, q(0));
}

// panics: camera::rh::proj::vulkan::perspective
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_rh_vulkan_perspective_near_equals_far() {
    let _ = rh_vulkan::perspective(FRAC_PI_2, ONE, ONE, ONE);
}

// panics: camera::rh::proj::vulkan::perspective
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_vulkan_perspective_fov_four_ulp() {
    let _ = rh_vulkan::perspective(f(4), ONE, ONE, q(8));
}

// panics: camera::rh::proj::vulkan::perspective_infinite
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_rh_vulkan_perspective_infinite_fov_pi() {
    let _ = rh_vulkan::perspective_infinite(PI, ONE, ONE);
}

// panics: camera::rh::proj::vulkan::perspective_infinite
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_rh_vulkan_perspective_infinite_aspect_zero() {
    let _ = rh_vulkan::perspective_infinite(FRAC_PI_2, q(0), ONE);
}

// panics: camera::rh::proj::vulkan::perspective_infinite
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_rh_vulkan_perspective_infinite_fov_one_ulp() {
    let _ = rh_vulkan::perspective_infinite(f(1), ONE, ONE);
}

// panics: camera::rh::proj::vulkan::perspective_infinite
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_vulkan_perspective_infinite_fov_four_ulp() {
    let _ = rh_vulkan::perspective_infinite(f(4), ONE, ONE);
}

// panics: camera::rh::proj::vulkan::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_rh_vulkan_perspective_infinite_reverse_fov_pi() {
    let _ = rh_vulkan::perspective_infinite_reverse(PI, ONE, ONE);
}

// panics: camera::rh::proj::vulkan::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_rh_vulkan_perspective_infinite_reverse_aspect_zero() {
    let _ = rh_vulkan::perspective_infinite_reverse(FRAC_PI_2, q(0), ONE);
}

// panics: camera::rh::proj::vulkan::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_rh_vulkan_perspective_infinite_reverse_near_zero() {
    let _ = rh_vulkan::perspective_infinite_reverse(FRAC_PI_2, ONE, q(0));
}

// panics: camera::rh::proj::vulkan::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_rh_vulkan_perspective_infinite_reverse_fov_one_ulp() {
    let _ = rh_vulkan::perspective_infinite_reverse(f(1), ONE, ONE);
}

// panics: camera::rh::proj::vulkan::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_vulkan_perspective_infinite_reverse_fov_four_ulp() {
    let _ = rh_vulkan::perspective_infinite_reverse(f(4), ONE, ONE);
}

// panics: camera::rh::proj::vulkan::orthographic
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_vulkan_orthographic_width_one_ulp() {
    let _ = rh_vulkan::orthographic(q(0), f(1), q(-4), q(4), ONE, q(8));
}

// panics: camera::rh::proj::vulkan::frustum
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_rh_vulkan_frustum_near_zero() {
    let _ = rh_vulkan::frustum(q(-4), q(4), q(-4), q(4), q(0), q(8));
}

// panics: camera::rh::proj::vulkan::frustum
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_rh_vulkan_frustum_near_equals_far() {
    let _ = rh_vulkan::frustum(q(-4), q(4), q(-4), q(4), ONE, ONE);
}

// panics: camera::rh::proj::vulkan::frustum
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_vulkan_frustum_depth_overflow() {
    let _ = rh_vulkan::frustum(q(-4), q(4), q(-4), q(4), q(400), q(400) + f(1));
}

// panics: camera::rh::proj::directx::perspective
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_rh_directx_perspective_fov_zero() {
    let _ = rh_directx::perspective(q(0), ONE, ONE, q(8));
}

// panics: camera::rh::proj::directx::perspective
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_rh_directx_perspective_aspect_zero() {
    let _ = rh_directx::perspective(FRAC_PI_2, q(0), ONE, q(8));
}

// panics: camera::rh::proj::directx::perspective
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_rh_directx_perspective_near_zero() {
    let _ = rh_directx::perspective(FRAC_PI_2, ONE, q(0), q(8));
}

// panics: camera::rh::proj::directx::perspective
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_rh_directx_perspective_near_equals_far() {
    let _ = rh_directx::perspective(FRAC_PI_2, ONE, ONE, ONE);
}

// panics: camera::rh::proj::directx::perspective_infinite
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_rh_directx_perspective_infinite_aspect_zero() {
    let _ = rh_directx::perspective_infinite(FRAC_PI_2, q(0), ONE);
}

// panics: camera::rh::proj::directx::perspective_infinite
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_rh_directx_perspective_infinite_near_zero() {
    let _ = rh_directx::perspective_infinite(FRAC_PI_2, ONE, q(0));
}

// panics: camera::rh::proj::directx::perspective_infinite
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_rh_directx_perspective_infinite_fov_one_ulp() {
    let _ = rh_directx::perspective_infinite(f(1), ONE, ONE);
}

// panics: camera::rh::proj::directx::perspective_infinite
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_directx_perspective_infinite_fov_four_ulp() {
    let _ = rh_directx::perspective_infinite(f(4), ONE, ONE);
}

// panics: camera::rh::proj::directx::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'camera: fov out of range')]
fn test_rh_directx_perspective_infinite_reverse_fov_pi() {
    let _ = rh_directx::perspective_infinite_reverse(PI, ONE, ONE);
}

// panics: camera::rh::proj::directx::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'camera: aspect zero')]
fn test_rh_directx_perspective_infinite_reverse_aspect_zero() {
    let _ = rh_directx::perspective_infinite_reverse(FRAC_PI_2, q(0), ONE);
}

// panics: camera::rh::proj::directx::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_rh_directx_perspective_infinite_reverse_fov_one_ulp() {
    let _ = rh_directx::perspective_infinite_reverse(f(1), ONE, ONE);
}

// panics: camera::rh::proj::directx::perspective_infinite_reverse
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_directx_perspective_infinite_reverse_fov_four_ulp() {
    let _ = rh_directx::perspective_infinite_reverse(f(4), ONE, ONE);
}

// panics: camera::rh::proj::directx::orthographic
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_rh_directx_orthographic_left_equals_right() {
    let _ = rh_directx::orthographic(ONE, ONE, q(-4), q(4), ONE, q(8));
}

// panics: camera::rh::proj::directx::orthographic
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_directx_orthographic_width_one_ulp() {
    let _ = rh_directx::orthographic(q(0), f(1), q(-4), q(4), ONE, q(8));
}

// panics: camera::rh::proj::directx::frustum
#[test]
#[should_panic(expected: 'camera: near not positive')]
fn test_rh_directx_frustum_near_zero() {
    let _ = rh_directx::frustum(q(-4), q(4), q(-4), q(4), q(0), q(8));
}

// panics: camera::rh::proj::directx::frustum
#[test]
#[should_panic(expected: 'camera: far not positive')]
fn test_rh_directx_frustum_far_zero() {
    let _ = rh_directx::frustum(q(-4), q(4), q(-4), q(4), ONE, q(0));
}

// panics: camera::rh::proj::directx::frustum
#[test]
#[should_panic(expected: 'Fixed: division by zero')]
fn test_rh_directx_frustum_near_equals_far() {
    let _ = rh_directx::frustum(q(-4), q(4), q(-4), q(4), ONE, ONE);
}

// panics: camera::rh::proj::directx::frustum
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_directx_frustum_depth_overflow() {
    let _ = rh_directx::frustum(q(-4), q(4), q(-4), q(4), q(400), q(400) + f(1));
}

// panics: camera::rh::view::look_at_mat4
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_look_at_mat4_cross_overflow() {
    let _ = rh_view::look_at_mat4(v3(q(0), q(0), q(0)), v3(ONE, ONE, q(0)), v3(-MAX, MAX, q(0)));
}

// panics: camera::rh::view::look_at_mat4
#[test]
#[should_panic(expected: 'i64_neg Underflow')]
fn test_rh_look_at_mat4_eye_min() {
    let _ = rh_view::look_at_mat4(v3(MIN, q(0), q(0)), v3(MIN, q(0), -ONE), v3(q(0), ONE, q(0)));
}

// panics: camera::rh::view::look_at_mat4
#[test]
#[should_panic(expected: 'i64_sub Underflow')]
fn test_rh_look_at_mat4_center_minus_eye() {
    let _ = rh_view::look_at_mat4(v3(ONE, q(0), q(0)), v3(MIN, q(0), q(0)), v3(q(0), ONE, q(0)));
}

// panics: camera::rh::view::look_to_mat4
#[test]
#[should_panic(expected: 'Vec3: normalize zero')]
fn test_rh_look_to_mat4_parallel_up() {
    let _ = rh_view::look_to_mat4(v3(q(0), q(0), q(0)), v3(q(0), ONE, q(0)), v3(q(0), ONE, q(0)));
}

// panics: camera::rh::view::look_to_mat4
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_look_to_mat4_cross_overflow() {
    let _ = rh_view::look_to_mat4(v3(q(0), q(0), q(0)), v3(MAX, q(0), q(0)), v3(q(0), q(8), q(0)));
}

// panics: camera::rh::view::look_to_mat4
#[test]
#[should_panic(expected: 'i64_neg Underflow')]
fn test_rh_look_to_mat4_dir_min() {
    let _ = rh_view::look_to_mat4(v3(q(0), q(0), q(0)), v3(MIN, q(0), q(0)), v3(q(0), -f(1), q(0)));
}

// panics: camera::rh::view::look_at_mat3
#[test]
#[should_panic(expected: 'Vec3: normalize zero')]
fn test_rh_look_at_mat3_center_is_eye() {
    let _ = rh_view::look_at_mat3(v3(q(0), ONE, q(0)), v3(q(0), ONE, q(0)), v3(q(0), ONE, q(0)));
}

// panics: camera::rh::view::look_at_mat3
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_look_at_mat3_cross_overflow() {
    let _ = rh_view::look_at_mat3(v3(q(0), q(0), q(0)), v3(ONE, ONE, q(0)), v3(-MAX, MAX, q(0)));
}

// panics: camera::rh::view::look_at_mat3
#[test]
#[should_panic(expected: 'i64_sub Underflow')]
fn test_rh_look_at_mat3_center_minus_eye() {
    let _ = rh_view::look_at_mat3(v3(ONE, q(0), q(0)), v3(MIN, q(0), q(0)), v3(q(0), ONE, q(0)));
}

// panics: camera::rh::view::look_to_mat3
#[test]
#[should_panic(expected: 'Vec3: normalize zero')]
fn test_rh_look_to_mat3_parallel_up() {
    let _ = rh_view::look_to_mat3(v3(q(0), ONE, q(0)), v3(q(0), ONE, q(0)));
}

// panics: camera::rh::view::look_to_mat3
#[test]
#[should_panic(expected: 'Fixed: overflow')]
fn test_rh_look_to_mat3_cross_overflow() {
    let _ = rh_view::look_to_mat3(v3(MAX, q(0), q(0)), v3(q(0), q(8), q(0)));
}

// panics: camera::rh::view::look_to_mat3
#[test]
#[should_panic(expected: 'i64_neg Underflow')]
fn test_rh_look_to_mat3_dir_min() {
    let _ = rh_view::look_to_mat3(v3(MIN, q(0), q(0)), v3(q(0), -f(1), q(0)));
}
