//! Oracle registry: one [`Registry`] per module, filled by `src/oracles/<module>.rs::register`.

use std::collections::BTreeMap;

use crate::rng::Rng;
use crate::value::{Out, Value};

pub type Oracle = Box<dyn Fn(&[Value]) -> Out>;
pub type Generator = Box<dyn Fn(&mut Rng) -> Value>;

#[derive(Default)]
pub struct Registry {
    pub oracles: BTreeMap<String, Oracle>,
    pub generators: BTreeMap<String, Generator>,
}

impl Registry {
    /// Registers the oracle of one function: a closure from the (already quantized) arguments
    /// to the reference result.
    pub fn add<O, F>(&mut self, name: &str, f: F)
    where
        O: Into<Out>,
        F: Fn(&[Value]) -> O + 'static,
    {
        let previous = self
            .oracles
            .insert(name.to_owned(), Box::new(move |args| f(args).into()));
        assert!(previous.is_none(), "oracle {name:?} registered twice");
    }

    /// Registers a custom input generator, referenced from a spec with `custom = "<name>"`.
    pub fn generator<F>(&mut self, name: &str, f: F)
    where
        F: Fn(&mut Rng) -> Value + 'static,
    {
        let previous = self.generators.insert(name.to_owned(), Box::new(f));
        assert!(previous.is_none(), "generator {name:?} registered twice");
    }
}

#[derive(Default)]
pub struct Registries {
    modules: BTreeMap<String, Registry>,
}

impl Registries {
    /// Called by the code generated by `build.rs`, once per file of `src/oracles/`.
    pub fn module(&mut self, name: &str, register: fn(&mut Registry)) {
        let mut registry = Registry::default();
        register(&mut registry);
        self.modules.insert(name.to_owned(), registry);
    }

    pub fn get(&self, module: &str) -> Option<&Registry> {
        self.modules.get(module)
    }
}
